Repository DataDog/dd-trace-js, pull requests merged in 2018-12, with the labels that each got.

#392 Fix graphql wrapping types
  src/plugins/graphql.js
  test/plugins/graphql.spec.js
Labels: bug, community, integrations

#393 fix koa integration returning 404 with legacy middleware
  package.json
  src/plugins/koa.js
  test/plugins/koa.spec.js
Labels: bug, integrations

#397 prefix span context properties with an underscore
  src/format.js
  src/opentracing/propagation/text_map.js
  src/opentracing/span.js
  src/opentracing/span_context.js
  src/opentracing/tracer.js
  src/plugins/util/redis.js
  src/plugins/util/web.js
  src/priority_sampler.js
  src/writer.js
  test/dd-trace.spec.js
  test/format.spec.js
  test/opentracing/span.spec.js
  test/opentracing/span_context.spec.js
  test/opentracing/tracer.spec.js
  test/plugins/graphql.spec.js
  test/plugins/util/redis.spec.js
  test/plugins/util/tx.spec.js
  test/plugins/util/web.spec.js
  test/priority_sampler.spec.js
  test/tracer.spec.js
  test/writer.spec.js
Labels: core, enhancement

#396 add a log propagator to allow correlation of a trace with logs
  ext/formats.js
  ext/index.js
  src/opentracing/propagation/log.js
  src/opentracing/propagation/text_map.js
  src/opentracing/span_context.js
  src/opentracing/tracer.js
  test/opentracing/propagation/log.spec.js
  test/opentracing/span_context.spec.js
Labels: core, enhancement

#398 fix baggage items at the span level instead of trace level
  src/opentracing/span.js
  test/opentracing/span.spec.js
Labels: bug, core

#399 add middleware and stack trace support for express
  src/plugins/router.js
  src/plugins/util/web.js
  test/.eslintrc.json
  test/plugins/express.spec.js
  test/plugins/router.spec.js
  test/plugins/util/web.spec.js
Labels: enhancement, integrations
