Repository DataDog/dd-trace-js, pull requests merged in 2018-09, with the labels that each got.

#245 [GraphQL] Instrument document parsing & validation and include variables in metadata
  docs/API.md
  src/plugins/graphql.js
  test/plugins/graphql.spec.js
Labels: community, enhancement, integrations

#275 add an environment variable to disable context propagation
  src/noop.js
  src/plugins/amqp10.js
  src/plugins/amqplib.js
  src/scope/noop/scope.js
  src/scope/noop/scope_manager.js
  src/tracer.js
  test/plugins/amqp10.spec.js
  test/plugins/amqplib.spec.js
  test/plugins/elasticsearch.spec.js
  test/plugins/express.spec.js
  test/plugins/graphql.spec.js
  test/plugins/http.spec.js
  test/plugins/mongodb-core.spec.js
  test/plugins/mysql.spec.js
  test/plugins/mysql2.spec.js
  test/plugins/pg.spec.js
  test/plugins/redis.spec.js
Labels: core, enhancement

#277 fix already flushed traces being reused by new child spans
  src/opentracing/span.js
  test/opentracing/span.spec.js
Labels: bug, core

#217 Respect and propagate X-Datadog-Sampling-Priority.
  benchmark/platform/node.js
  benchmark/stubs/span.js
  ext/index.js
  ext/priority.js
  ext/tags.js
  src/constants.js
  src/format.js
  src/opentracing/propagation/text_map.js
  src/opentracing/span.js
  src/opentracing/span_context.js
  src/opentracing/tracer.js
  src/plugins/http.js
  src/priority_sampler.js
  src/recorder.js
  src/writer.js
  test/dd-trace.spec.js
  test/format.spec.js
  test/opentracing/propagation/text_map.spec.js
  test/opentracing/span.spec.js
  test/opentracing/span_context.spec.js
  test/opentracing/tracer.spec.js
  test/plugins/agent.js
  test/priority_sampler.spec.js
  test/recorder.spec.js
  test/tracer.spec.js
  test/writer.spec.js
Labels: community, core, enhancement

#268 [http] Fix repeated traces on Node < v9 when tracing `https` requests.
  LICENSE-3rdparty.csv
  package.json
  src/plugins/http.js
  test/plugins/http.spec.js
Labels: bug, community, integrations

#281 fix node-memwatch being included in user dependencies
  .eslintignore
  LICENSE-3rdparty.csv
  package.json
  scripts/check_licenses.js
  test/leak/package.json
Labels: dev/testing, dev/tooling

#283 improve benchmark execution speed
  benchmark/benchmark.js
  benchmark/core.js
  benchmark/platform/node.js
Labels: dev/testing, dev/tooling

#284 add yarn dependencies caching to the build
  .circleci/config.yml
Labels: dev/tooling

#285 update elasticsearch container to be more efficient
  .circleci/config.yml
  docker-compose.yml
Labels: dev/tooling

#282 add hapi integration
  docs/API.md
  ext/kinds.js
  ext/tags.js
  ext/types.js
  src/plugins/express.js
  src/plugins/hapi.js
  src/plugins/index.js
  src/plugins/util/web.js
  test/plugins/hapi.spec.js
  test/plugins/util/web.spec.js
  test/setup.js
Labels: enhancement, integrations

#286 update tests to wipe the require cache only once per suite
  test/plugins/agent.js
  test/plugins/amqplib.spec.js
  test/plugins/elasticsearch.spec.js
  test/plugins/express.spec.js
  test/plugins/graphql.spec.js
  test/plugins/mongodb-core.spec.js
  test/plugins/mysql.spec.js
  test/plugins/mysql2.spec.js
  test/plugins/pg.spec.js
  test/plugins/redis.spec.js
  test/setup.js
Labels: dev/testing, dev/tooling

#291 add ioredis integration
  docs/API.md
  src/plugins/index.js
  src/plugins/ioredis.js
  test/plugins/ioredis.spec.js
Labels: enhancement, integrations

#288 add koa integration
  docs/API.md
  scripts/install_plugin_modules.js
  src/plugins/index.js
  src/plugins/koa.js
  src/plugins/util/web.js
  test/plugins/externals.json
  test/plugins/koa.spec.js
  test/plugins/util/web.spec.js
  test/setup.js
Labels: enhancement, integrations

#289 add restify integration
  docs/API.md
  src/plugins/index.js
  src/plugins/restify.js
  test/plugins/restify.spec.js
  test/setup.js
Labels: enhancement, integrations

#295 fix typos causing some tests to fail
  test/plugins/util/web.spec.js
Labels: dev/testing
