Repository DataDog/dd-trace-js, pull requests merged in 2018-07, with the labels that each got.

#167 fix graphql stability and only instrument custom resolvers
  src/opentracing/span.js
  src/plugins/graphql.js
  test/plugins/graphql.spec.js
Labels: bug, integrations

#171 Deeper GraphQL and Recursively nested schemas
  src/plugins/graphql.js
  test/plugins/graphql.spec.js
Labels: bug, community, integrations

#177 fix Noop.bind not returning a function
  src/noop.js
  test/noop.spec.js
Labels: bug, core

#178 fix mysql span getting the wrong parent in some cases
  src/plugins/mysql.js
  test/plugins/mysql.spec.js
Labels: bug, integrations

#180 fix graphql unsupported operation errors and fix support for mutations
  src/plugins/graphql.js
  test/plugins/graphql.spec.js
Labels: bug, integrations

#181 remove incorrect module order warning
  src/instrumenter.js
Labels: bug, core

#185 fix sample rate config not being used
  src/opentracing/tracer.js
  test/opentracing/tracer.spec.js
Labels: bug, core

#184 replace CLS with a new scope manager for context propagation
  LICENSE-3rdparty.csv
  benchmark/core.js
  benchmark/dd-trace.js
  benchmark/index.js
  benchmark/platform/node.js
  benchmark/scope.js
  docs/API.md
  package.json
  src/config.js
  src/noop.js
  src/opentracing/tracer.js
  src/platform/node/context/cls.js
  src/platform/node/context/cls_bluebird.js
  src/platform/node/context/cls_hooked.js
  src/platform/node/context/index.js
  src/platform/node/index.js
  src/platform/node/load.js
  src/plugins/amqplib.js
  src/plugins/elasticsearch.js
  src/plugins/express.js
  src/plugins/graphql.js
  src/plugins/http.js
  src/plugins/mongodb-core.js
  src/plugins/mysql.js
  src/plugins/mysql2.js
  src/plugins/pg.js
  src/plugins/redis.js
  src/proxy.js
  src/scope/async_hooks/async_hooks.js
  src/scope/async_hooks/async_wrap.js
  src/scope/async_hooks/index.js
  src/scope/context.js
  src/scope/context_execution.js
  src/scope/scope.js
  src/scope/scope_manager.js
  src/tracer.js
  test/noop.spec.js
  test/opentracing/tracer.spec.js
  test/platform/node/index.spec.js
  test/plugins/agent.js
  test/plugins/amqplib.spec.js
  test/plugins/elasticsearch.spec.js
  test/plugins/express.spec.js
  test/plugins/graphql.spec.js
  test/plugins/http.spec.js
  test/plugins/mongodb-core.spec.js
  test/plugins/mysql.spec.js
  test/plugins/mysql2.spec.js
  test/plugins/pg.spec.js
  test/plugins/redis.spec.js
  test/proxy.spec.js
  test/scope/context.spec.js
  test/scope/context_execution.spec.js
  test/scope/scope.spec.js
  test/scope/scope_manager.spec.js
  test/setup.js
  test/tracer.spec.js
Labels: breaking-change, core, enhancement, integrations

#189 cleanup unused code in ScopeManager and ContextExecution
  src/scope/context_execution.js
  src/scope/scope_manager.js
Labels: core

#190 fix pg parent scope not available in query callbacks
  src/plugins/pg.js
  test/plugins/pg.spec.js
Labels: bug, integrations

#191 Making parentPath defensively fall back to callerPath
  src/platform/node/load.js
Labels: bug, community, core

#192 update service names and span types to match the specification
  docs/API.md
  src/config.js
  src/plugins/amqplib.js
  src/plugins/elasticsearch.js
  src/plugins/express.js
  src/plugins/http.js
  src/plugins/https.js
  src/plugins/mongodb-core.js
  src/plugins/mysql.js
  src/plugins/mysql2.js
  src/plugins/pg.js
  src/plugins/redis.js
  test/config.spec.js
  test/plugins/amqplib.spec.js
  test/plugins/elasticsearch.spec.js
  test/plugins/express.spec.js
  test/plugins/http.spec.js
  test/plugins/mongodb-core.spec.js
  test/plugins/mysql.spec.js
  test/plugins/mysql2.spec.js
  test/plugins/pg.spec.js
  test/plugins/redis.spec.js
Labels: breaking-change, enhancement, integrations

#193 fix express path being lost when changing scope
  src/plugins/express.js
  test/plugins/express.spec.js
Labels: bug, integrations

#194 fix span recorded multiple times if finish() is called more than once
  src/opentracing/span.js
  test/opentracing/span.spec.js
Labels: bug, core

#195 remove mentions of beta as the module is now stable
  CONTRIBUTING.md
  README.md
  package.json
Labels: docs

#199 fix reference to https plugin that no longer exists
  src/plugins/index.js
Labels: bug, core

#203 fix memory leak when destroy is called before after on context
  src/scope/scope_manager.js
Labels: bug, core

#205 fix 403 error from AWS when sending a signed request
  src/plugins/http.js
  test/plugins/http.spec.js
Labels: bug, integrations

#207 flush pending traces when the process exits gracefully
  LICENSE-3rdparty.csv
  package.json
  src/platform/node/index.js
  src/scheduler.js
  test/scheduler.spec.js
Labels: core, enhancement
