Repository DataDog/dd-trace-js, pull requests merged in 2019-05, with the labels that each got.

#545 Add typings for ext submodules
  docs/test.ts
  ext/formats.d.ts
  ext/index.d.ts
  ext/index.js
  ext/kinds.d.ts
  ext/priority.d.ts
  ext/tags.d.ts
  ext/types.d.ts
Labels: community, dev/tooling

#544 fix sampling priority being locked too early
  benchmark/core.js
  src/opentracing/span.js
  src/writer.js
  test/opentracing/span.spec.js
  test/writer.spec.js
Labels: bug, core

#551 update benchmarks to disable real http calls
  benchmark/benchmark.js
Labels: dev/tooling

#552 update supported engines to be less strict
  package.json
  src/platform/node/validate.js
Labels: core, enhancement

#554 add support for node 12
  .circleci/config.yml
  package.json
  src/native/metrics/SpanTracker.cpp
  src/native/metrics/utils.cpp
  src/native/metrics/utils.hpp
Labels: bug, core, enhancement

#555 fix incompatibility with express-async-errors
  src/plugins/router.js
Labels: bug, integrations

#550 fix client sampling not reducing the tracer overhead
  benchmark/stubs/span.js
  src/constants.js
  src/noop/span.js
  src/noop/span_context.js
  src/noop/tracer.js
  src/opentracing/span.js
  src/opentracing/span_context.js
  src/opentracing/tracer.js
  src/plugins/http/client.js
  src/plugins/net.js
  src/plugins/util/web.js
  src/sampler.js
  test/opentracing/span.spec.js
  test/opentracing/span_context.spec.js
  test/opentracing/tracer.spec.js
  test/proxy.spec.js
Labels: core, enhancement

#561 Initial addition of koa-route plugin
  src/plugins/koa.js
  src/plugins/util/web.js
  test/plugins/externals.json
  test/plugins/koa.spec.js
  test/plugins/util/web.spec.js
Labels: enhancement, integrations

#562 Add option to add hostname tag to every trace
  docs/API.md
  src/config.js
  src/constants.js
  src/format.js
  src/opentracing/span.js
  src/opentracing/tracer.js
  src/platform/node/hostname.js
  src/platform/node/index.js
  test/config.spec.js
  test/format.spec.js
  test/opentracing/tracer.spec.js
Labels: core, enhancement

#563 fix split traces when using knex
  docs/test.ts
  index.d.ts
  src/plugins/index.js
  src/plugins/knex.js
  test/plugins/agent.js
  test/plugins/externals.json
  test/plugins/knex.spec.js
Labels: bug, integrations

#567 API doc - fix links
  docs/API.md
Labels: docs

#564 fix(EventEmitter): use listener ddId when registering
  src/scope/new/base.js
  test/scope/scope.spec.js
Labels: bug, community, core

#566 fix event listeners in net plugin
  src/plugins/dns.js
  src/plugins/net.js
  test/plugins/dns.spec.js
  test/plugins/net.spec.js
Labels: bug, integrations

#568 fix support for new elasticsearch version as a new module
  scripts/install_plugin_modules.js
  src/instrumenter.js
  src/plugins/elasticsearch.js
  test/instrumenter.spec.js
  test/plugins/elasticsearch.spec.js
  test/setup/core.js
Labels: bug, integrations

#569 update test services to only wait 1 minute for the server to start
  test/setup/operation.js
Labels: dev/testing, dev/tooling

#570 add support for promise
  .circleci/config.yml
  docs/test.ts
  index.d.ts
  src/plugins/index.js
  src/plugins/promise.js
  test/plugins/promise.spec.js
Labels: enhancement, integrations

#572 add support for promise-js
  .circleci/config.yml
  docs/test.ts
  index.d.ts
  src/plugins/index.js
  src/plugins/promise-js.js
  test/plugins/promise-js.spec.js
Labels: enhancement, integrations

#574 refactor promise tests to reuse the same test suite
  test/plugins/bluebird.spec.js
  test/plugins/promise-js.spec.js
  test/plugins/promise.js
  test/plugins/promise.spec.js
  test/plugins/q.spec.js
  test/plugins/when.spec.js
Labels: dev/testing

#575 fix dns plugin not working in node 4
  src/plugins/dns.js
Labels: bug, integrations

#573 update analytics config with a simpler API that also fixes plugin config
  src/analytics_sampler.js
  src/format.js
  src/instrumenter.js
  src/plugins/graphql.js
  src/plugins/util/web.js
  src/proxy.js
  test/analytics_sampler.spec.js
  test/format.spec.js
  test/instrumenter.spec.js
  test/proxy.spec.js
Labels: bug, core, enhancement, integrations

#579 add an alternative scope manager in pure JS for older versions of Node
  LICENSE-3rdparty.csv
  benchmark/index.js
  benchmark/scope/async-listener.js
  benchmark/scope/async_hooks.js
  docs/test.ts
  ext/scopes.d.ts
  ext/scopes.js
  index.d.ts
  package.json
  src/config.js
  src/noop/tracer.js
  src/scope/async-listener.js
  src/scope/async_hooks.js
  src/scope/base.js
  src/tracer.js
  test/config.spec.js
  test/scope/async-listener.spec.js
  test/scope/async_hooks.spec.js
  test/scope/test.js
  test/setup/core.js
Labels: bug, core, enhancement
