Repository DataDog/dd-trace-js, pull requests merged in 2019-06, with the labels that each got.

#581 fix memory leak caused by a bug in node with http keep-alive
  src/scope/async_hooks.js
  src/scope/async_hooks/async_wrap.js
  test/leak/scope/async_hooks.js
  test/scope/async_hooks.spec.js
Labels: bug, core

#582 Add paperplane integration
  .circleci/config.yml
  docs/API.md
  docs/test.ts
  index.d.ts
  src/plugins/index.js
  src/plugins/paperplane.js
  test/plugins/paperplane.spec.js
Labels: community, enhancement, integrations

#584 mysql pooled queries have the wrong parent
  src/plugins/mysql.js
  test/plugins/mysql.spec.js
  test/plugins/mysql2.spec.js
Labels: bug, community, integrations

#576 Add support for http2
  .circleci/config.yml
  docs/test.ts
  index.d.ts
  package.json
  src/plugins/http2/client.js
  src/plugins/http2/index.js
  src/plugins/http2/server.js
  src/plugins/index.js
  src/plugins/util/web.js
  test/plugins/http2/client.spec.js
  test/plugins/http2/server.spec.js
  test/plugins/http2/ssl/test.crt
  test/plugins/http2/ssl/test.key
Labels: enhancement, integrations

#586 remove replica set in mongo build due to bug in circleci
  .circleci/config.yml
  docker-compose.yml
  test/plugins/mongodb-core.spec.js
  test/setup/services/mongo.js
Labels: dev/tooling

#589 add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: dev/tooling

#591 add pull request template
  .github/pull_request_template.md
Labels: dev/tooling

#593 update plugin checklist to hint removal if unneeded
  .github/pull_request_template.md
Labels: dev/tooling

#590 Adds an option to skip downloading binaries
  scripts/post_install.js
Labels: community, dev/tooling, enhancement

#592 add timeout to prebuilt addons download to avoid idle sockets
  scripts/post_install.js
Labels: bug, dev/tooling

#594 replace custom env var with standard flag to skip prebuilt download
  scripts/post_install.js
Labels: dev/tooling

#587 fix auto instrumentation of loaded modules without an entrypoint defined
  packages/dd-trace/src/instrumenter.js
  packages/dd-trace/test/instrumenter.spec.js
  packages/dd-trace/test/node_modules/other/package.json
Labels: community

#595 fix http client holding onto async resources in some cases
  packages/dd-trace/src/platform/node/request.js
  packages/dd-trace/src/writer.js
  packages/dd-trace/test/platform/node/index.spec.js
  packages/dd-trace/test/writer.spec.js
Labels: bug, core

#601 fix jest tests breaking because of unsupported require syntax
  benchmark/scope/async_hooks.js
  packages/dd-trace/src/scope/async_hooks.js
Labels: bug, core

#598 add memory leak protection when async resources are not destroyed
  benchmark/scope/async_hooks.js
  benchmark/stubs/span.js
  packages/datadog-plugin-memcached/test/index.spec.js
  packages/dd-trace/src/scope/async_hooks.js
  packages/dd-trace/src/scope/base.js
  packages/dd-trace/src/writer.js
  packages/dd-trace/test/scope/async_hooks.spec.js
  packages/dd-trace/test/writer.spec.js
Labels: breaking-change, core, enhancement

#602 update build config to generate prebuilds for tags
  .circleci/config.yml
Labels: dev/tooling

#604 fix incorrect metrics for async resources
  packages/dd-trace/src/scope/async_hooks.js
  packages/dd-trace/src/scope/async_hooks/async_wrap.js
  packages/dd-trace/test/scope/async_hooks.spec.js
Labels: bug, core
