Repository DataDog/dd-trace-js, pull requests merged in 2019-10, with the labels that each got.

#700 fix support for mongodb after mongodb-core merge
  packages/datadog-plugin-mongodb-core/src/index.js
  packages/datadog-plugin-mongodb-core/test/index.spec.js
Labels: bug, integrations

#701 remove flaky memory leak tests and optimize benchmarks
  .circleci/config.yml
  benchmark/benchmark.js
Labels: dev/tooling

#705 add firefox to circle browser tests
  LICENSE-3rdparty.csv
  karma.conf.js
  package.json
Labels: dev/testing

#707 fix missing stack trace when logging non-errors as errors
  packages/dd-trace/src/log.js
  packages/dd-trace/test/log.spec.js
Labels: bug, core

#716 fixed agent-writer-error-message-bug
  packages/dd-trace/src/exporters/agent/writer.js
Labels: bug, community, core

#722 fix priority sampling not updating the rates from the agent
  packages/dd-trace/src/exporters/agent/index.js
  packages/dd-trace/src/exporters/agent/writer.js
  packages/dd-trace/src/opentracing/tracer.js
  packages/dd-trace/test/exporters/agent/exporter.spec.js
  packages/dd-trace/test/exporters/agent/writer.spec.js
  packages/dd-trace/test/opentracing/tracer.spec.js
Labels: bug, core

#720 fix native addon for Node 13 and older versions of glibc
  .circleci/config.yml
  LICENSE-3rdparty.csv
  package.json
  scripts/prebuild.js
Labels: bug, core

#721 fix missing configuration options in typescript definitions
  docs/test.ts
  index.d.ts
Labels: dev/tooling

#724 fix service name when tracer is imported by a dependency
  .gitignore
  packages/dd-trace/src/platform/node/service.js
  packages/dd-trace/test/platform/node/index.spec.js
  packages/dd-trace/test/platform/node/load/node_modules/dep/index.js
  packages/dd-trace/test/platform/node/load/node_modules/dep/load/index.js
  packages/dd-trace/test/platform/node/load/node_modules/dep/package.json
Labels: bug, core

#728 add browserstack and improve browser compatibility
  .babelrc
  LICENSE-3rdparty.csv
  README.md
  karma.conf.js
  package.json
  packages/dd-trace/browser.js
  packages/dd-trace/src/platform/browser/tags.js
  packages/dd-trace/src/scope/zone.js
  packages/dd-trace/test/browser.test.js
  webpack.config.js
Labels: core, dev/testing, dev/tooling

#726 fix tedious support now that exported classes are read-only
  packages/datadog-plugin-tedious/src/index.js
Labels: bug, integrations
