Repository DataDog/dd-trace-js, pull requests merged in 2019-12, with the labels that each got.

#765 fix error in graphql plugin with unpatched context values
  packages/datadog-plugin-graphql/src/index.js
Labels: bug, integrations

#767 update build scripts to use a single prebuilds artifact
  .circleci/config.yml
  .gitignore
  .npmignore
  LICENSE-3rdparty.csv
  package.json
  scripts/prebuilds.js
  scripts/prepublish.js
Labels: dev/tooling

#771 fix log injection removing inherited properties on log records
  packages/dd-trace/src/plugins/util/log.js
  packages/dd-trace/test/plugins/util/log.spec.js
Labels: bug, core

#772 fix async scope tracking not resolving awaited promises
  packages/dd-trace/src/scope/async_hooks.js
Labels: bug, core

#773 update async scope tracking to not track itself
  packages/dd-trace/src/scope/async_hooks.js
Labels: core, enhancement

#774 fix missing/wrong native extensions in scripts
  scripts/post_install.js
  scripts/prepublish.js
Labels: dev/tooling

#777 add safety nets for type errors in amqplib plugin
  packages/datadog-plugin-amqplib/src/index.js
Labels: integrations

#778 add safety nets for type errors in cassandra-driver plugin
  packages/datadog-plugin-cassandra-driver/src/index.js
Labels: integrations

#779 add safety nets for type errors in connect plugin
  packages/datadog-plugin-connect/src/index.js
Labels: integrations

#782 add safety nets for type errors in couchbase plugin
  packages/datadog-plugin-couchbase/src/index.js
Labels: integrations

#783 add safety nets for type errors in dns plugin
  packages/datadog-plugin-dns/src/index.js
Labels: integrations

#784 add safety nets for type errors in elasticsearch plugin
  packages/datadog-plugin-elasticsearch/src/index.js
Labels: integrations

#786 add safety nets for type errors in generic-pool plugin
  packages/datadog-plugin-generic-pool/src/index.js
Labels: integrations

#785 add safety nets for type errors in fastify plugin
  packages/datadog-plugin-fastify/src/fastify.js
  packages/datadog-plugin-fastify/src/find-my-way.js
Labels: integrations

#776 add safety nets for type errors in amqp10 plugin
  packages/datadog-plugin-amqp10/src/index.js
Labels: integrations

#781 fix log injection not working when logger is required before dd-trace
  packages/dd-trace/src/instrumenter.js
  packages/dd-trace/test/instrumenter.spec.js
Labels: bug, core

#733 Add support for disabling plugins by environment variable
  docs/API.md
  packages/dd-trace/src/instrumenter.js
  packages/dd-trace/test/instrumenter.spec.js
Labels: core, enhancement

#787 add safety nets for type errors in graphql plugin
  packages/datadog-plugin-graphql/src/index.js
Labels: integrations

#788 add safety nets for type errors in grpc plugin
  packages/datadog-plugin-grpc/src/client.js
  packages/datadog-plugin-grpc/src/server.js
  packages/datadog-plugin-grpc/src/util.js
Labels: integrations

#789 add safety nets for type errors in hapi plugin
  packages/datadog-plugin-hapi/src/route.js
  packages/datadog-plugin-hapi/src/server.js
Labels: integrations

#791 fix base scope missing the _activate protected method
  packages/dd-trace/src/scope/base.js
  packages/dd-trace/test/scope/base.spec.js
Labels: bug, core

#796 remove default rate limit in priority sampler
  packages/dd-trace/src/priority_sampler.js
Labels: core, enhancement

#800 add safety net for uri errors in http plugin
  packages/datadog-plugin-http/src/client.js
Labels: integrations

#802 add safety nets for type errors in http2 plugin
  packages/datadog-plugin-http2/src/client.js
  packages/datadog-plugin-http2/src/server.js
Labels: integrations

#805 add benchmarks for node platform metrics
  benchmark/core.js
  benchmark/platform/node.js
  benchmark/stubs/span.js
Labels: dev/testing

#808 add safety nets for type errors in ioredis plugin
  packages/datadog-plugin-ioredis/src/index.js
Labels: integrations

#809 add safety nets for type errors in koa plugin
  packages/datadog-plugin-koa/src/index.js
Labels: integrations

#810 add safety nets for type errors in limitd-client plugin
  packages/datadog-plugin-limitd-client/src/index.js
Labels: integrations

#801 add support for rhea
  .circleci/config.yml
  docs/test.ts
  index.d.ts
  packages/datadog-plugin-rhea/src/index.js
  packages/datadog-plugin-rhea/test/index.spec.js
  packages/dd-trace/src/plugins/index.js
  packages/dd-trace/test/setup/core.js
Labels: enhancement, integrations
