Repository DataDog/dd-trace-js, pull requests merged in 2019-04, with the labels that each got.

#514 update runtime metrics for beta release
  benchmark/core.js
  docs/API.md
  docs/test.ts
  index.d.ts
  src/config.js
  src/format.js
  src/platform/node/index.js
  src/platform/node/metrics.js
  src/proxy.js
  src/scope/new/scope.js
  test/config.spec.js
  test/format.spec.js
  test/platform/node/index.spec.js
  test/proxy.spec.js
  test/scope/scope.spec.js
  test/tracer.spec.js
Labels: bug, core, enhancement

#519 collect heap space metrics by default + fix gc stats
  src/native/metrics/GarbageCollection.cpp
  src/platform/node/metrics.js
  test/platform/node/index.spec.js
Labels: bug, core, enhancement

#525 fix client.batch() promise support in cassandra-driver plugin
  src/plugins/cassandra-driver.js
  src/plugins/util/tx.js
  test/plugins/cassandra-driver.spec.js
Labels: bug, integrations

#526 fix error in pg plugin when using pg without pg-native
  src/plugins/pg.js
Labels: bug, integrations

#528 fix trace analytics env var inconsistent with other tracers
  src/config.js
Labels: core, enhancement

#527 fix log injection causing side effects on the provided object
  src/plugins/bunyan.js
  src/plugins/pino.js
  src/plugins/util/log.js
  src/plugins/winston.js
  test/plugins/util/log.spec.js
Labels: bug, core, integrations

#531 fix query string being included in the http.url tag
  src/plugins/util/web.js
  test/plugins/http/client.spec.js
  test/plugins/util/web.spec.js
Labels: bug, integrations

#532 add docs folder to npmignore except typescript definitions
  .npmignore
Labels: dev/tooling

#521 add percentiles to histograms and enable all metrics
  LICENSE-3rdparty.csv
  binding.gyp
  package.json
  scripts/check_licenses.js
  scripts/post_install.js
  scripts/prebuild.js
  src/native/metrics/Histogram.cpp
  src/native/metrics/Histogram.hpp
  src/native/metrics/Object.cpp
  src/native/metrics/SpanTracker.cpp
  src/native/metrics/SpanTracker.hpp
  src/native/metrics/main.cpp
  src/native/tdigest/LICENSE-2.0.txt
  src/native/tdigest/NOTICES
  src/native/tdigest/TDigest.h
  src/platform/node/metrics.js
  test/platform/node/index.spec.js
Labels: core, enhancement

#529 add request hook for http client request spans
  docs/test.ts
  index.d.ts
  src/plugins/http/client.js
  test/plugins/http/client.spec.js
Labels: breaking-change, enhancement, integrations

#534 enable all async resource metrics without debug mode
  src/scope/new/scope.js
  src/tracer.js
  test/scope/scope.spec.js
Labels: core, enhancement

#535 fix alpine test for prebuilt native addon
  LICENSE-3rdparty.csv
  package.json
  scripts/prebuild.js
Labels: dev/testing, dev/tooling

#536 update runtime metrics to no longer be experimental
  docs/API.md
  docs/test.ts
  index.d.ts
  src/config.js
  src/platform/node/metrics.js
  src/proxy.js
  test/config.spec.js
  test/proxy.spec.js
Labels: core, enhancement

#530 add support for forced tracing
  ext/tags.js
  src/priority_sampler.js
  test/priority_sampler.spec.js
Labels: core, enhancement

#538 fix incorrect percentiles when count is 0
  src/native/metrics/Histogram.cpp
Labels: bug, core

#498 add support to split object tags as a tag for each property
  src/format.js
  src/plugins/graphql.js
  test/format.spec.js
Labels: breaking-change, core, enhancement

#539 replace hot-shots with internal dogstatsd implementation
  LICENSE-3rdparty.csv
  package.json
  src/platform/node/dogstatsd.js
  src/platform/node/metrics.js
  test/platform/node/dogstatsd.spec.js
  test/platform/node/index.spec.js
Labels: core, enhancement

#479 feat: support unix sockets for requests
  src/writer.js
  test/writer.spec.js
Labels: community, core, enhancement

#541 fix mongodb build failing because of new image release
  .circleci/config.yml
Labels: dev/testing, dev/tooling

#540 fix dogstatsd sockets not handling errors and preventing process exit
  src/platform/node/dogstatsd.js
  test/platform/node/dogstatsd.spec.js
Labels: bug, core
