Repository DataDog/dd-trace-js, pull requests merged in 2019-07, with the labels that each got.

#606 fix undefined type resulting in wrong async resource metrics
  packages/dd-trace/src/scope/async_hooks.js
  packages/dd-trace/test/scope/async_hooks.spec.js
Labels: bug, core

#605 add support for connect
  .circleci/config.yml
  docs/API.md
  docs/test.ts
  index.d.ts
  packages/datadog-plugin-connect/src/index.js
  packages/datadog-plugin-connect/test/index.spec.js
  packages/dd-trace/src/instrumenter.js
  packages/dd-trace/src/plugins/index.js
  packages/dd-trace/test/instrumenter.spec.js
Labels: enhancement, integrations

#611 remove flaky memory leak tests
  .circleci/config.yml
Labels: dev/testing

#610 fix missing TS type for passing variables as an array to graphql
  docs/test.ts
  index.d.ts
Labels: dev/tooling

#607 add support for B3 propagation
  benchmark/core.js
  benchmark/stubs/span.js
  benchmark/stubs/trace.js
  docs/API.md
  docs/test.ts
  index.d.ts
  packages/datadog-plugin-http2/src/server.js
  packages/datadog-plugin-koa/test/index.spec.js
  packages/dd-trace/index.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/format.js
  packages/dd-trace/src/noop/span.js
  packages/dd-trace/src/noop/span_context.js
  packages/dd-trace/src/opentracing/propagation/log.js
  packages/dd-trace/src/opentracing/propagation/text_map.js
  packages/dd-trace/src/opentracing/span_context.js
  packages/dd-trace/src/opentracing/tracer.js
  packages/dd-trace/src/platform/node/id.js
  packages/dd-trace/src/plugins/util/web.js
  packages/dd-trace/src/writer.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/dd-trace.spec.js
  packages/dd-trace/test/format.spec.js
  packages/dd-trace/test/noop.spec.js
  packages/dd-trace/test/opentracing/propagation/binary.spec.js
  packages/dd-trace/test/opentracing/propagation/log.spec.js
  packages/dd-trace/test/opentracing/propagation/text_map.spec.js
  packages/dd-trace/test/opentracing/span.spec.js
  packages/dd-trace/test/opentracing/span_context.spec.js
  packages/dd-trace/test/opentracing/tracer.spec.js
  packages/dd-trace/test/platform/node/index.spec.js
  packages/dd-trace/test/plugins/util/web.spec.js
  packages/dd-trace/test/tracer.spec.js
  packages/dd-trace/test/writer.spec.js
  scripts/tdd.js
Labels: core, enhancement

#599 Add tedious integration
  .circleci/config.yml
  docker-compose.yml
  docs/API.md
  docs/test.ts
  index.d.ts
  packages/datadog-plugin-tedious/src/index.js
  packages/datadog-plugin-tedious/test/index.spec.js
  packages/dd-trace/src/plugins/index.js
  packages/dd-trace/test/setup/services/mssql.js
Labels: enhancement, integrations

#609 replace memory leak detection mechanism with erasing finished traces
  benchmark/scope/async_hooks.js
  packages/dd-trace/src/opentracing/span.js
  packages/dd-trace/src/scope/async_hooks.js
  packages/dd-trace/src/writer.js
  packages/dd-trace/test/opentracing/span.spec.js
  packages/dd-trace/test/plugins/util/tx.spec.js
  packages/dd-trace/test/plugins/util/web.spec.js
  packages/dd-trace/test/scope/async_hooks.spec.js
  packages/dd-trace/test/tracer.spec.js
  packages/dd-trace/test/writer.spec.js
Labels: core, enhancement

#613 remove runtime-id tag from runtime metrics and traces
  packages/dd-trace/src/format.js
  packages/dd-trace/src/platform/node/metrics.js
  packages/dd-trace/test/format.spec.js
  packages/dd-trace/test/platform/node/index.spec.js
Labels: core

#615 fix mongodb-core plugin swallowing missing callback errors
  packages/datadog-plugin-mongodb-core/src/index.js
  packages/datadog-plugin-mongodb-core/test/index.spec.js
Labels: bug, integrations

#616 fix api docs config table and make it more readable
  docs/API.md
  docs/package.json
Labels: docs

#617 fix machine size for darwin prebuilds in circleci
  .circleci/config.yml
Labels: dev/tooling

#614 add support for fastify
  .circleci/config.yml
  docs/API.md
  docs/test.ts
  index.d.ts
  packages/datadog-plugin-fastify/src/fastify.js
  packages/datadog-plugin-fastify/src/find-my-way.js
  packages/datadog-plugin-fastify/src/index.js
  packages/datadog-plugin-fastify/test/index.spec.js
  packages/dd-trace/src/plugins/index.js
  packages/dd-trace/src/plugins/util/web.js
  packages/dd-trace/test/plugins/util/web.spec.js
  scripts/tdd.js
Labels: enhancement, integrations

#622 remove code related to old versions of Node
  .circleci/config.yml
  .eslintignore
  LICENSE-3rdparty.csv
  README.md
  benchmark/index.js
  benchmark/scope/async-listener.js
  benchmark/scope/async_hooks.js
  ext/scopes.d.ts
  ext/scopes.js
  index.d.ts
  package.json
  packages/datadog-plugin-mongodb-core/src/index.js
  packages/datadog-plugin-mongodb-core/test/index.spec.js
  packages/dd-trace/src/platform/node/dogstatsd.js
  packages/dd-trace/src/platform/node/id.js
  packages/dd-trace/src/platform/node/msgpack.js
  packages/dd-trace/src/platform/node/validate.js
  packages/dd-trace/src/scope/async-listener.js
  packages/dd-trace/src/scope/async_hooks.js
  packages/dd-trace/src/scope/async_hooks/async_hooks.js
  packages/dd-trace/src/scope/async_hooks/async_wrap.js
  packages/dd-trace/src/scope/async_hooks/index.js
  packages/dd-trace/src/tracer.js
  packages/dd-trace/test/platform/node/index.spec.js
  packages/dd-trace/test/scope/async-listener.spec.js
  packages/dd-trace/test/setup/core.js
  scripts/prebuild.js
Labels: core, enhancement

#623 add code coverage using codecov
  .circleci/config.yml
  .codecov.yml
  LICENSE-3rdparty.csv
  README.md
  package.json
Labels: dev/tooling

#612 add a header to the agent request with the container ID
  LICENSE-3rdparty.csv
  package.json
  packages/dd-trace/src/platform/node/request.js
  packages/dd-trace/test/platform/node/index.spec.js
Labels: core, enhancement

#625 fix incorrect middleware name when wrapped using express-async-errors
  packages/datadog-plugin-router/src/index.js
Labels: bug, integrations

#626 fix support for passing tags as types other than object
  packages/dd-trace/src/opentracing/span.js
  packages/dd-trace/src/opentracing/tracer.js
  packages/dd-trace/test/opentracing/span.spec.js
  packages/dd-trace/test/opentracing/tracer.spec.js
Labels: bug, core

#627 fix missing spans for express built-in middleware
  packages/datadog-plugin-express/src/index.js
  packages/datadog-plugin-express/test/index.spec.js
Labels: bug, integrations

#628 update the koa plugin to capture the entire framework duration
  packages/datadog-plugin-koa/src/index.js
Labels: integrations

#631 Update bluebird github link
  index.d.ts
Labels: community, docs

#630 fix fastify plugin not validating the status code for errors
  packages/dd-trace/src/plugins/util/web.js
  packages/dd-trace/test/plugins/util/web.spec.js
Labels: bug, integrations

#624 Add debug launch commands and forward arguments to tdd
  .gitignore
  .vscode/launch.json
  .vscode/settings.json
  scripts/tdd.js
Labels: dev/testing

#634 fix hapi plugin for hapi namespace change
  packages/datadog-plugin-hapi/src/index.js
  packages/datadog-plugin-hapi/test/index.spec.js
Labels: bug, community, integrations

#638 fix error when addTags is called with an empty parameter
  packages/dd-trace/src/opentracing/span.js
Labels: bug, core

#639 handle null/undefined references gracefully without an error
  packages/dd-trace/src/opentracing/tracer.js
Labels: core, enhancement

#633 Inject trace ids into paperplane logs
  packages/datadog-plugin-paperplane/src/index.js
  packages/datadog-plugin-paperplane/test/index.spec.js
Labels: community, enhancement
