Repository DataDog/dd-trace-js, pull requests merged in 2019-11, with the labels that each got.

#734 fix older versions of node 8 image not supported by the native addons
  .circleci/config.yml
Labels: bug, core

#736 fix prepared statement support for mysql2
  packages/datadog-plugin-mysql2/src/index.js
  packages/datadog-plugin-mysql2/test/index.spec.js
Labels: bug, integrations

#732 add experimental priority sampling config as sampling rules
  LICENSE-3rdparty.csv
  docs/test.ts
  index.d.ts
  package.json
  packages/dd-trace/src/config.js
  packages/dd-trace/src/constants.js
  packages/dd-trace/src/opentracing/tracer.js
  packages/dd-trace/src/priority_sampler.js
  packages/dd-trace/src/rate_limiter.js
  packages/dd-trace/test/priority_sampler.spec.js
  packages/dd-trace/test/rate_limiter.spec.js
Labels: core, enhancement

#737 make log exporter the default only in beta versions for lambda
  packages/dd-trace/src/platform/node/exporter.js
  packages/dd-trace/test/platform/node/index.spec.js
Labels: core

#727 Add experimental support for customizing tracer log levels
  docs/API.md
  docs/test.ts
  index.d.ts
  packages/dd-trace/src/config.js
  packages/dd-trace/src/log.js
  packages/dd-trace/src/opentracing/tracer.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/log.spec.js
Labels: core, enhancement

#740 update release scripts with new workflow
  package.json
  scripts/helpers/exec.js
  scripts/postpublish.js
  scripts/prepublish.js
  scripts/release.js
  scripts/version.js
Labels: dev/tooling

#739 add support for global tags in runtime metrics
  docs/API.md
  packages/dd-trace/src/config.js
  packages/dd-trace/src/opentracing/span.js
  packages/dd-trace/src/platform/node/metrics.js
  packages/dd-trace/src/tagger.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/opentracing/span.spec.js
  packages/dd-trace/test/platform/node/index.spec.js
  packages/dd-trace/test/tagger.spec.js
Labels: core, enhancement

#743 update linux prebuilds to use ubuntu 14.04 to get an older glibcxx
  .circleci/config.yml
  LICENSE-3rdparty.csv
  package.json
  scripts/prebuild.js
  scripts/prepublish.js
Labels: core, enhancement

#746 remove tagging in version script
  scripts/version.js
Labels: dev/tooling

#745 fix runtime metrics in node 8 for windows and mac
  scripts/prebuild.js
Labels: bug, core

#749 add environment variables to configure the priority sampler
  packages/dd-trace/src/config.js
  packages/dd-trace/test/config.spec.js
Labels: core, enhancement

#748 add tracer metrics for the agent exporter
  LICENSE-3rdparty.csv
  benchmark/core.js
  package.json
  packages/dd-trace/src/exporters/agent/writer.js
  packages/dd-trace/src/histogram.js
  packages/dd-trace/src/platform/browser/metrics.js
  packages/dd-trace/src/platform/node/metrics.js
  packages/dd-trace/src/platform/node/request.js
  packages/dd-trace/src/scope/async_hooks.js
  packages/dd-trace/test/exporters/agent/writer.spec.js
  packages/dd-trace/test/histogram.spec.js
  packages/dd-trace/test/platform/node/index.spec.js
  packages/dd-trace/test/scope/async_hooks.spec.js
Labels: core, enhancement

#753 add more tracer metrics and fix counters
  packages/dd-trace/src/exporters/agent/writer.js
  packages/dd-trace/src/instrumenter.js
  packages/dd-trace/src/opentracing/tracer.js
  packages/dd-trace/src/platform/node/metrics.js
  packages/dd-trace/test/platform/node/index.spec.js
Labels: core, enhancement

#754 fix release script with new endpoint and add retries
  scripts/prepublish.js
Labels: dev/tooling

#755 fix wrong artifact used for node 8 on linux when releasing
  .circleci/config.yml
  scripts/prebuild.js
Labels: bug, dev/tooling

#756 update prepublish script to use last workflow run instead of first
  scripts/prepublish.js
Labels: dev/tooling

#757 update prepublish script to use the new workflow api
  scripts/prepublish.js
Labels: dev/tooling

#763 add tests and checksum validation for prebuilt native addons
  .circleci/config.yml
  .npmignore
  LICENSE-3rdparty.csv
  package.json
  packages/dd-trace/src/platform/node/metrics.js
  scripts/post_install.js
  scripts/prebuild.js
  scripts/prepublish.js
Labels: bug, core, dev/tooling
