Repository DataDog/dd-trace-js, pull requests merged in 2019-01, with the labels that each got.

#404 fix error in redis plugin for commands without a callback
  src/plugins/redis.js
  test/plugins/redis.spec.js
Labels: bug, integrations

#405 add dns integration
  src/plugins/dns.js
  src/plugins/index.js
  test/plugins/dns.spec.js
Labels: enhancement, integrations

#406 add net integration
  src/plugins/index.js
  src/plugins/net.js
  test/plugins/net.spec.js
Labels: enhancement, integrations

#407 add trace search sampling configuration
  ext/tags.js
  src/constants.js
  src/event_sampler.js
  src/format.js
  src/plugins/util/web.js
  test/event_sampler.spec.js
  test/format.spec.js
  test/plugins/util/web.spec.js
Labels: core, enhancement, integrations

#409 add more metadata to net.connect and update operation name
  src/plugins/net.js
  test/plugins/net.spec.js
Labels: enhancement, integrations

#408 add automatic log correlation of tracer identifiers for winston
  src/instrumenter.js
  src/plugins/index.js
  src/plugins/util/log.js
  src/plugins/winston.js
  test/plugins/util/log.spec.js
  test/plugins/winston.spec.js
Labels: enhancement, integrations

#410 add automatic log correlation of trace identifiers for bunyan
  src/plugins/bunyan.js
  src/plugins/index.js
  test/plugins/bunyan.spec.js
Labels: enhancement, integrations

#413 fix calling public methods on the no-op span context
  src/noop/span.js
  src/noop/span_context.js
  src/noop/tracer.js
  src/proxy.js
  test/noop.spec.js
  test/proxy.spec.js
Labels: bug, core

#414 add automatic log correlation of tracer identifiers for pino
  .circleci/config.yml
  src/instrumenter.js
  src/plugins/index.js
  src/plugins/pino.js
  test/plugins/pino.spec.js
Labels: enhancement, integrations

#416 Add protocol as a configuration option for the dd-trace-agent URL
  docs/API.md
  src/config.js
  src/platform/node/request.js
  src/proxy.js
  test/config.spec.js
Labels: community, core, enhancement

#380 fix CircleCI job names in README
  README.md
Labels: docs

#417 add support for latest module versions in all plugins
  src/plugins/amqp10.js
  src/plugins/amqplib.js
  src/plugins/bluebird.js
  src/plugins/bunyan.js
  src/plugins/elasticsearch.js
  src/plugins/express.js
  src/plugins/graphql.js
  src/plugins/hapi.js
  src/plugins/ioredis.js
  src/plugins/koa.js
  src/plugins/memcached.js
  src/plugins/mongodb-core.js
  src/plugins/mysql.js
  src/plugins/mysql2.js
  src/plugins/pg.js
  src/plugins/pino.js
  src/plugins/q.js
  src/plugins/redis.js
  src/plugins/restify.js
  src/plugins/router.js
  src/plugins/when.js
  src/plugins/winston.js
Labels: enhancement, integrations
