Repository DataDog/dd-trace-js, pull requests merged in 2019-08, with the labels that each got.

#643 Add workaround for loopback
  packages/datadog-plugin-express/test/index.spec.js
  packages/datadog-plugin-router/src/index.js
  packages/dd-trace/test/plugins/externals.json
Labels: enhancement, integrations

#648 Fix "Plugin is exported" link in PR template
  .github/pull_request_template.md
Labels: docs

#644 fix net.Socket listeners scope and allow to bind prototypes
  packages/datadog-plugin-net/src/index.js
  packages/datadog-plugin-net/test/index.spec.js
  packages/dd-trace/src/instrumenter.js
  packages/dd-trace/src/scope/base.js
  packages/dd-trace/test/instrumenter.spec.js
  packages/dd-trace/test/scope/test.js
Labels: bug, core, enhancement, integrations

#646 add limitd-client plugin to fix scope propagation
  .circleci/config.yml
  docker-compose.yml
  docs/API.md
  docs/test.ts
  index.d.ts
  package.json
  packages/datadog-plugin-limitd-client/src/index.js
  packages/datadog-plugin-limitd-client/test/index.spec.js
  packages/dd-trace/src/plugins/index.js
  packages/dd-trace/test/setup/services/limitd.js
Labels: bug, integrations

#647 update post install script to use published prebuilds
  .npmignore
  scripts/post_install.js
Labels: dev/tooling

#650 switch from azure to circle for windows builds
  .circleci/config.yml
  azure-pipelines.prebuild.yml
  azure-pipelines.yml
Labels: dev/tooling

#645 Darcy.rayner/add log writer
  benchmark/core.js
  ext/exporters.d.ts
  ext/exporters.js
  ext/index.d.ts
  ext/index.js
  index.d.ts
  packages/dd-trace/src/config.js
  packages/dd-trace/src/exporters/agent/index.js
  packages/dd-trace/src/exporters/agent/scheduler.js
  packages/dd-trace/src/exporters/agent/writer.js
  packages/dd-trace/src/exporters/log/index.js
  packages/dd-trace/src/opentracing/span.js
  packages/dd-trace/src/opentracing/tracer.js
  packages/dd-trace/src/span_processor.js
  packages/dd-trace/test/exporters/agent/exporter.spec.js
  packages/dd-trace/test/exporters/agent/scheduler.spec.js
  packages/dd-trace/test/exporters/agent/writer.spec.js
  packages/dd-trace/test/exporters/log/exporter.spec.js
  packages/dd-trace/test/opentracing/span.spec.js
  packages/dd-trace/test/opentracing/tracer.spec.js
  packages/dd-trace/test/recorder.spec.js
  packages/dd-trace/test/span_processor.spec.js
Labels: core, enhancement

#649 add experimental support for thenables in the scope manager
  .eslintrc.json
  benchmark/scope/async_hooks.js
  docs/test.ts
  index.d.ts
  packages/dd-trace/src/config.js
  packages/dd-trace/src/noop/tracer.js
  packages/dd-trace/src/scope/async_hooks.js
  packages/dd-trace/src/tracer.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/scope/async_hooks.spec.js
  packages/dd-trace/test/setup/core.js
Labels: core, enhancement

#653 update post install script to not run locally
  scripts/post_install.js
Labels: dev/tooling

#651 Fix connection options for older versions of redis
  packages/datadog-plugin-redis/src/index.js
Labels: bug, integrations

#658 fix graphql exception because of utility exported from a different file
  packages/datadog-plugin-graphql/src/index.js
Labels: bug, integrations

#547 Add grpc client and server plugin
  .circleci/config.yml
  LICENSE-3rdparty.csv
  docs/API.md
  docs/test.ts
  index.d.ts
  package.json
  packages/datadog-plugin-grpc/src/client.js
  packages/datadog-plugin-grpc/src/index.js
  packages/datadog-plugin-grpc/src/kinds.js
  packages/datadog-plugin-grpc/src/server.js
  packages/datadog-plugin-grpc/src/util.js
  packages/datadog-plugin-grpc/test/client.spec.js
  packages/datadog-plugin-grpc/test/server.spec.js
  packages/datadog-plugin-grpc/test/test.proto
  packages/datadog-plugin-http2/src/client.js
  packages/datadog-plugin-http2/src/server.js
  packages/datadog-plugin-http2/test/client.spec.js
  packages/datadog-plugin-http2/test/server.spec.js
  packages/dd-trace/src/plugins/index.js
  packages/dd-trace/test/plugins/agent.js
  packages/dd-trace/test/plugins/externals.json
  scripts/install_plugin_modules.js
Labels: community, enhancement, integrations

#632 Add couchbase plugin
  .circleci/config.yml
  docker-compose.yml
  docs/API.md
  docs/test.ts
  index.d.ts
  packages/datadog-plugin-couchbase/src/index.js
  packages/datadog-plugin-couchbase/test/index.spec.js
  packages/dd-trace/src/plugins/index.js
  packages/dd-trace/test/plugins/agent.js
  packages/dd-trace/test/setup/services/couchbase.js
  scripts/install_plugin_modules.js
Labels: enhancement, integrations

#659 Support circular references in tags and better array formatting
  packages/dd-trace/src/format.js
  packages/dd-trace/test/format.spec.js
Labels: core, enhancement
