Repository DataDog/dd-trace-js, pull requests merged in 2019-02, with the labels that each got.

#421 disable net and dns plugins
  src/plugins/dns.js
  src/plugins/net.js
  test/plugins/dns.spec.js
  test/plugins/net.spec.js
Labels: integrations

#422 fix http server response handlers not running in the request scope
  src/plugins/util/web.js
  test/plugins/util/web.spec.js
  test/setup/core.js
Labels: bug, integrations

#423 fix log injection with a null active span and update injection keys
  src/plugins/util/log.js
  test/plugins/bunyan.spec.js
  test/plugins/pino.spec.js
  test/plugins/util/log.spec.js
  test/plugins/winston.spec.js
Labels: bug, enhancement, integrations

#424 fix redis/ioredis plugins not binding their callbacks to the parent scope
  src/plugins/util/tx.js
  test/plugins/util/tx.spec.js
Labels: bug, integrations

#425 Revert "add trace search sampling configuration"
  ext/tags.js
  src/constants.js
  src/event_sampler.js
  src/format.js
  src/plugins/util/web.js
  test/event_sampler.spec.js
  test/format.spec.js
  test/plugins/util/web.spec.js
Labels: core

#427 add documentation about enabling log correlation
  docs/API.md
Labels: docs

#426 fix references to the old trace IDs
  src/opentracing/propagation/log.js
  test/opentracing/propagation/log.spec.js
  test/plugins/winston.spec.js
Labels: bug, core

#428 fix wrong image used for windows build
  azure-pipelines.yml
Labels: dev/tooling

#429 fix noop span context trace IDs to match the backend expectation
  src/noop/span_context.js
  test/noop.spec.js
Labels: bug, core

#436 fix tests not running for plugin utils
  package.json
Labels: dev/testing

#435 fix benchmarks using a span stub with an invalid context
  benchmark/stubs/span.js
Labels: dev/testing, dev/tooling

#434 fix serializing tag values with no toString method
  src/format.js
  test/format.spec.js
Labels: bug, core

#433 add header tags and separate client/server config in http plugin
  ext/tags.js
  src/plugins/http/client.js
  src/plugins/http/server.js
  src/plugins/util/web.js
  test/plugins/express.spec.js
  test/plugins/http/client.spec.js
  test/plugins/util/web.spec.js
Labels: breaking-change, enhancement, integrations

#438 Add whitelist/blacklist settings to express plugin
  docs/API.md
  src/plugins/http/client.js
  src/plugins/util/urlfilter.js
  src/plugins/util/web.js
  src/writer.js
  test/plugins/util/web.spec.js
  test/writer.spec.js
Labels: community, enhancement, integrations

#432 add note about where to find code examples
  examples/README.md
Labels: docs

#442 enable net and dns plugins
  src/plugins/dns.js
  src/plugins/net.js
  test/plugins/dns.spec.js
  test/plugins/net.spec.js
Labels: integrations

#443 add support for generic-pool
  .circleci/config.yml
  src/plugins/generic-pool.js
  src/plugins/index.js
  test/plugins/externals.json
  test/plugins/generic-pool.spec.js
Labels: enhancement, integrations

#441 update documentation for the new scope manager
  docs/API.md
Labels: docs

#446 Fix traceId/parentId printing in debug JSON output
  src/platform/node/id.js
  src/platform/node/uint64be.js
Labels: community, core

#445 fix graphql error with multiple execution of the same document
  src/plugins/graphql.js
  test/plugins/graphql.spec.js
Labels: bug, integrations

#439 fix plugin test externals not loaded if not instrumented
  test/setup/core.js
Labels: dev/testing

#447 Move two more places to uint64be json-compatible class
  src/opentracing/propagation/log.js
  src/opentracing/propagation/text_map.js
  src/platform/node/index.js
  test/opentracing/propagation/log.spec.js
  test/opentracing/propagation/text_map.spec.js
Labels: community, core, enhancement

#448 fix http aborted request support and flushing stream too early
  src/plugins/http/client.js
  test/plugins/http/client.spec.js
Labels: bug, integrations

#449 fix restify crashing with array middleware
  src/plugins/restify.js
  test/plugins/restify.spec.js
Labels: bug, integrations

#450 [http] fix suppressed error event and span never finishing
  src/plugins/http/client.js
  test/plugins/http/client.spec.js
Labels: bug, integrations

#451 [graphql] rewrite according to apollo engine reporting format
  .circleci/config.yml
  LICENSE-3rdparty.csv
  package.json
  src/plugins/graphql.js
  src/plugins/graphql/tools/index.js
  src/plugins/graphql/tools/signature.js
  src/plugins/graphql/tools/transforms.js
  test/leak/plugins/graphql.js
  test/plugins/graphql.spec.js
Labels: bug, enhancement, integrations

#403 add typescript definitions and replace jsdoc with typedoc
  .circleci/config.yml
  LICENSE-3rdparty.csv
  docs/API.md
  docs/gulpfile.js
  docs/index.d.ts
  docs/jsdoc.json
  docs/package.json
  docs/test.ts
  docs/tsconfig.json
  docs/typedoc.js
  package.json
  scripts/publish_docs.js
  src/globals.js
  src/opentracing/externals.js
  src/proxy.js
  src/scope/new/base.js
Labels: docs

#453 fix script to work with typedoc
  scripts/publish_docs.js
Labels: dev/tooling

#454 fix importing the library with typescript
  .gitignore
  docs/package.json
  docs/test.ts
  index.js
Labels: bug

#456 fix missing remote for git push command of docs publish script
  scripts/publish_docs.js
Labels: dev/tooling

#459 fix ts definitions files excluded with npmignore
  .npmignore
Labels: bug, dev/tooling

#461 add synthetics integration
  src/constants.js
  src/format.js
  src/opentracing/propagation/text_map.js
  src/opentracing/span.js
  test/format.spec.js
  test/opentracing/propagation/text_map.spec.js
  test/opentracing/span.spec.js
Labels: core, enhancement

#465 fix typescript breaking with different opentracing versions
  docs/test.ts
  package.json
Labels: bug, dev/tooling

#468 fix error in express plugin with capturing groups in routes
  package.json
  src/plugins/router.js
  test/plugins/express.spec.js
Labels: bug, integrations

#463 add automatic instrumentation for koa middleware
  src/plugins/koa.js
  src/plugins/util/web.js
  test/plugins/koa.spec.js
  test/plugins/util/web.spec.js
Labels: enhancement, integrations

#457 add tracer.trace() and tracer.wrap() as high level APIs
  docs/index.d.ts
  docs/test.ts
  src/noop/tracer.js
  src/proxy.js
  src/tracer.js
  test/noop.spec.js
  test/proxy.spec.js
  test/tracer.spec.js
Labels: core, enhancement

#470 fix span types for http servers and clients
  ext/types.js
  src/plugins/http/client.js
  src/plugins/util/web.js
  test/plugins/express.spec.js
  test/plugins/hapi.spec.js
  test/plugins/http/client.spec.js
  test/plugins/http/server.spec.js
  test/plugins/koa.spec.js
  test/plugins/restify.spec.js
  test/plugins/util/web.spec.js
Labels: bug, integrations
