Repository DataDog/dd-trace-js, pull requests merged in 2020-06, with the labels that each got.

#973 fix ERR_INVALID_ARG_TYPE exception for webpack
  packages/dd-trace/src/platform/node/pkg.js
Labels: bug, core

#976 truncate IDs in encoder
  packages/dd-trace/src/encode/index.js
  packages/dd-trace/test/encode.spec.js
Labels: core

#980 fix prepublish failing when workflows are unexpectedly ordered
  scripts/prepublish.js
Labels: dev/tooling

#963 support SQS propagation
  packages/datadog-plugin-aws-sdk/src/helpers.js
  packages/datadog-plugin-aws-sdk/src/index.js
  packages/datadog-plugin-aws-sdk/src/services/sqs.js
  packages/datadog-plugin-aws-sdk/test/fixtures/sqs.js
  packages/datadog-plugin-aws-sdk/test/index.spec.js
Labels: enhancement, integrations

#982 add distributed tracing support to amqplib
  packages/datadog-plugin-amqplib/src/index.js
  packages/datadog-plugin-amqplib/test/index.spec.js
Labels: enhancement, integrations

#985 fix global tags missing from logs after span is finished
  packages/dd-trace/src/opentracing/propagation/log.js
  packages/dd-trace/src/opentracing/tracer.js
  packages/dd-trace/test/opentracing/propagation/log.spec.js
Labels: bug, core

#987 update log injection to include global tags outside of a trace
  packages/dd-trace/src/opentracing/propagation/log.js
  packages/dd-trace/test/opentracing/propagation/log.spec.js
Labels: core, enhancement

#986 fix fs errors when using promisified methods
  packages/datadog-plugin-fs/src/index.js
  packages/datadog-plugin-fs/test/index.spec.js
Labels: bug, integrations

#997 Fix for #992
  packages/datadog-plugin-aws-sdk/src/helpers.js
  packages/datadog-plugin-aws-sdk/test/index.spec.js
Labels: bug, integrations

#990 fix fs tests randomly failing in build
  packages/datadog-plugin-fs/test/index.spec.js
Labels: dev/testing

#1001 fix error in amqplib plugin when the message is null
  packages/datadog-plugin-amqplib/src/index.js
  packages/datadog-plugin-amqplib/test/index.spec.js
Labels: bug, integrations

#1002 fix primary tags being overridden with empty default values
  packages/dd-trace/src/config.js
  packages/dd-trace/test/config.spec.js
Labels: bug, core

#984 add profiling support
  .circleci/config.yml
  .eslintignore
  .gitignore
  .npmignore
  LICENSE-3rdparty.csv
  benchmark/profiler/index.js
  benchmark/profiler/server.js
  docs/API.md
  index.d.ts
  package.json
  packages/dd-trace/src/config.js
  packages/dd-trace/src/opentracing/tracer.js
  packages/dd-trace/src/platform/browser/index.js
  packages/dd-trace/src/platform/node/index.js
  packages/dd-trace/src/platform/node/profiler.js
  packages/dd-trace/src/profiling/config.js
  packages/dd-trace/src/profiling/encoders/pprof.js
  packages/dd-trace/src/profiling/exporters/agent.js
  packages/dd-trace/src/profiling/exporters/file.js
  packages/dd-trace/src/profiling/index.js
  packages/dd-trace/src/profiling/loggers/console.js
  packages/dd-trace/src/profiling/mapper.js
  packages/dd-trace/src/profiling/profile.js
  packages/dd-trace/src/profiling/profiler.js
  packages/dd-trace/src/profiling/profilers/inspector/cpu.js
  packages/dd-trace/src/profiling/profilers/inspector/heap.js
  packages/dd-trace/src/profiling/profilers/native/cpu.js
  packages/dd-trace/src/profiling/profilers/native/heap.js
  packages/dd-trace/src/profiling/tagger.js
  packages/dd-trace/src/profiling/util.js
  packages/dd-trace/src/proxy.js
  packages/dd-trace/test/asserts/profile.js
  packages/dd-trace/test/opentracing/tracer.spec.js
  packages/dd-trace/test/profiling/.eslintrc.json
  packages/dd-trace/test/profiling/config.spec.js
  packages/dd-trace/test/profiling/exporters/agent.spec.js
  packages/dd-trace/test/profiling/exporters/file.spec.js
  packages/dd-trace/test/profiling/loggers/console.spec.js
  packages/dd-trace/test/profiling/mapper.spec.js
  packages/dd-trace/test/profiling/mapper/sourcemaps/dist/external.js
  packages/dd-trace/test/profiling/mapper/sourcemaps/dist/external.js.map
  packages/dd-trace/test/profiling/mapper/sourcemaps/dist/inline.js
  packages/dd-trace/test/profiling/mapper/sourcemaps/dist/missing.js
  packages/dd-trace/test/profiling/mapper/sourcemaps/dist/url.js
  packages/dd-trace/test/profiling/mapper/sourcemaps/dist/url.js.map
  packages/dd-trace/test/profiling/mapper/sourcemaps/src/greeter.ts
  packages/dd-trace/test/profiling/mapper/sourcemaps/src/index.ts
  packages/dd-trace/test/profiling/profiler.spec.js
  packages/dd-trace/test/profiling/profilers/inspector/cpu.spec.js
  packages/dd-trace/test/profiling/profilers/inspector/heap.spec.js
  packages/dd-trace/test/profiling/profilers/native/cpu.spec.js
  packages/dd-trace/test/profiling/profilers/native/heap.spec.js
  packages/dd-trace/test/profiling/tagger.spec.js
  packages/dd-trace/test/profiling/util.spec.js
  packages/dd-trace/test/proxy.spec.js
  packages/dd-trace/test/setup/core.js
  protobuf/profile.d.ts
  protobuf/profile.js
  protobuf/profile.proto
Labels: enhancement, profiling

#995 docs,packages/dd-trace: add dogstatsd.hostname option
  docs/API.md
  docs/test.ts
  index.d.ts
  packages/dd-trace/src/config.js
  packages/dd-trace/src/platform/node/metrics.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/platform/node/index.spec.js
Labels: community, core, enhancement
