Repository DataDog/dd-trace-js, pull requests merged in 2020-10, with the labels that each got.

#1098 update profiler to not use any promises
  packages/dd-trace/src/config.js
  packages/dd-trace/src/platform/browser/index.js
  packages/dd-trace/src/platform/node/client.js
  packages/dd-trace/src/platform/node/index.js
  packages/dd-trace/src/profiling/encoders/pprof.js
  packages/dd-trace/src/profiling/exporters/agent.js
  packages/dd-trace/src/profiling/exporters/file.js
  packages/dd-trace/src/profiling/profiler.js
  packages/dd-trace/src/profiling/profilers/inspector/cpu.js
  packages/dd-trace/src/profiling/profilers/inspector/heap.js
  packages/dd-trace/src/profiling/util.js
  packages/dd-trace/test/profiling/exporters/agent.spec.js
  packages/dd-trace/test/profiling/exporters/file.spec.js
  packages/dd-trace/test/profiling/profiler.spec.js
  packages/dd-trace/test/profiling/profilers/inspector/cpu.spec.js
  packages/dd-trace/test/profiling/profilers/inspector/heap.spec.js
  packages/dd-trace/test/profiling/util.spec.js
Labels: enhancement, profiling

#1105 fix logging of dropped traces not including the trace
  packages/dd-trace/src/span_processor.js
Labels: bug, core

#1107 update agent exporter to always use 0.4 endpoint by default
  benchmark/core.js
  benchmark/index.js
  docs/API.md
  docs/package.json
  index.d.ts
  packages/dd-trace/src/config.js
  packages/dd-trace/src/exporters/agent/index.js
  packages/dd-trace/src/exporters/agent/writer.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/exporters/agent/writer.spec.js
  packages/dd-trace/test/setup/core.js
Labels: breaking-change, bug, core, enhancement

#1109 fix graphql resolve span duration not accounting for wall time
  packages/datadog-plugin-graphql/src/index.js
  packages/datadog-plugin-graphql/test/index.spec.js
Labels: bug, integrations

#1104 disable debug metrics by default
  packages/dd-trace/src/opentracing/span.js
  packages/dd-trace/src/opentracing/tracer.js
  packages/dd-trace/src/scope/async_hooks.js
  packages/dd-trace/test/opentracing/span.spec.js
  packages/dd-trace/test/opentracing/tracer.spec.js
  packages/dd-trace/test/setup/core.js
Labels: core, enhancement

#1108 Span Creation Optimizations
  packages/dd-trace/src/opentracing/tracer.js
Labels: core, enhancement

#1086 default to AsyncLocalStorage on versions of node that support it
  packages/dd-trace/src/platform/node/index.js
  packages/dd-trace/src/scope/async_hooks.js
  packages/dd-trace/test/platform/node/index.spec.js
  packages/dd-trace/test/scope/async_hooks.spec.js
  packages/dd-trace/test/setup/core.js
Labels: core, enhancement

#1110 add support for changing the pg service name based on connection params
  docs/test.ts
  index.d.ts
  packages/datadog-plugin-pg/src/index.js
  packages/datadog-plugin-pg/test/index.spec.js
Labels: enhancement, integrations

#1119 fix performance regression in the agent exporter
  LICENSE-3rdparty.csv
  benchmark/core.js
  benchmark/stubs/span.js
  package.json
  packages/datadog-plugin-graphql/test/index.spec.js
  packages/dd-trace/src/encode/0.4.js
  packages/dd-trace/src/encode/0.5.js
  packages/dd-trace/src/encode/encoder-state.js
  packages/dd-trace/src/encode/notepack.js
  packages/dd-trace/src/encode/tokens.js
  packages/dd-trace/src/encode/util.js
  packages/dd-trace/src/exporters/agent/writer.js
  packages/dd-trace/src/id.js
  packages/dd-trace/src/platform/node/index.js
  packages/dd-trace/src/platform/node/msgpack.js
  packages/dd-trace/test/dd-trace.spec.js
  packages/dd-trace/test/encode/0.4.spec.js
  packages/dd-trace/test/encode/0.5.spec.js
  packages/dd-trace/test/exporters/agent/writer.spec.js
  packages/dd-trace/test/platform/node/index.spec.js
Labels: core, enhancement

#1121 Fix get rum data
  packages/dd-trace/src/noop/tracer.js
  packages/dd-trace/src/opentracing/tracer.js
  packages/dd-trace/src/proxy.js
  packages/dd-trace/src/tracer.js
  packages/dd-trace/test/proxy.spec.js
  packages/dd-trace/test/tracer.spec.js
Labels: bug, community, core

#1127 wrap end on prototype instead of instances
  packages/dd-trace/src/plugins/util/web.js
  packages/dd-trace/test/plugins/util/web.spec.js
Labels: core, enhancement, integrations

#1123 add official support for tracing without limits
  docs/API.md
  docs/test.ts
  index.d.ts
  packages/dd-trace/src/config.js
  packages/dd-trace/test/config.spec.js
Labels: core, enhancement

#1125 fix old versions of mongoose losing the asynchronous context
  .circleci/config.yml
  docs/test.ts
  index.d.ts
  packages/datadog-plugin-mongoose/src/index.js
  packages/datadog-plugin-mongoose/test/index.spec.js
  packages/dd-trace/src/plugins/index.js
  packages/dd-trace/test/plugins/externals.json
Labels: enhancement, integrations

#1124 add native addons support for node 15
  .circleci/config.yml
  scripts/prebuild.js
Labels: core, enhancement

#1128 fix instrumented functions missing symbols from the original
  packages/datadog-plugin-dns/test/index.spec.js
  packages/dd-trace/src/instrumenter.js
  packages/dd-trace/test/instrumenter.spec.js
Labels: bug, core, integrations

#1126 wrap emitter prototypes instead of instances where possible
  benchmark/scope/async_hooks.js
  packages/datadog-plugin-http/src/server.js
  packages/dd-trace/src/scope/base.js
Labels: core, enhancement

#1088 add scope manager that uses the execution async resource for propagation
  benchmark/index.js
  benchmark/scope/async_resource.js
  ext/scopes.d.ts
  ext/scopes.js
  packages/dd-trace/src/platform/node/index.js
  packages/dd-trace/src/scope/async_resource.js
  packages/dd-trace/test/scope/async_resource.spec.js
  packages/dd-trace/test/setup/core.js
Labels: core, enhancement

#1134 fix memory leak in the async_local_storage scope manager
  packages/dd-trace/src/scope/async_local_storage.js
Labels: bug, core

#1131 allow setting agent url after initialization
  index.d.ts
  packages/dd-trace/src/exporters/agent/index.js
  packages/dd-trace/src/exporters/agent/writer.js
  packages/dd-trace/src/exporters/browser/index.js
  packages/dd-trace/src/noop/tracer.js
  packages/dd-trace/src/proxy.js
  packages/dd-trace/src/tracer.js
  packages/dd-trace/test/browser.test.js
  packages/dd-trace/test/exporters/agent/exporter.spec.js
  packages/dd-trace/test/exporters/agent/writer.spec.js
  packages/dd-trace/test/proxy.spec.js
  packages/dd-trace/test/tracer.spec.js
Labels: core, enhancement

#1132 fix ingestion rate limiter drifting on interval change
  packages/dd-trace/src/rate_limiter.js
  packages/dd-trace/test/rate_limiter.spec.js
Labels: bug, core

#1139 Fix GraphQL span finishTime calculation
  packages/datadog-plugin-graphql/src/index.js
Labels: bug, community, integrations

#1138 add a fast path in toArray for length-8 IDs
  packages/dd-trace/src/id.js
Labels: core, enhancement

#1142 fix socket connect callback not running in parent scope
  packages/datadog-plugin-net/src/index.js
  packages/datadog-plugin-net/test/index.spec.js
Labels: bug, integrations

#1143 remove idle call frame samples from profiles
  packages/dd-trace/src/profiling/profilers/inspector/cpu.js
  packages/dd-trace/test/profiling/profilers/inspector/cpu.spec.js
Labels: enhancement, profiling
