Repository DataDog/dd-trace-js, pull requests merged in 2020-09, with the labels that each got.

#1052 Trace Agent Protocol v0.5
  benchmark/core.js
  benchmark/e2e/fake-agent.js
  benchmark/index.js
  docs/package.json
  packages/datadog-plugin-net/test/index.spec.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/encode/0.4.js
  packages/dd-trace/src/encode/0.5.js
  packages/dd-trace/src/encode/cache.js
  packages/dd-trace/src/encode/encoder-state.js
  packages/dd-trace/src/encode/index.js
  packages/dd-trace/src/encode/tokens.js
  packages/dd-trace/src/encode/util.js
  packages/dd-trace/src/exporters/agent/writer.js
  packages/dd-trace/test/dd-trace.spec.js
  packages/dd-trace/test/encode/0.4.spec.js
  packages/dd-trace/test/encode/0.5.spec.js
  packages/dd-trace/test/exporters/agent/writer.spec.js
  packages/dd-trace/test/plugins/agent.js
  packages/dd-trace/test/plugins/helpers.js
  packages/dd-trace/test/setup/core.js
Labels: core, enhancement

#1074 stop using LRU in 0.4 protocol
  LICENSE-3rdparty.csv
  package.json
  packages/dd-trace/src/encode/0.4.js
  packages/dd-trace/src/encode/0.5.js
  packages/dd-trace/src/encode/cache.js
  packages/dd-trace/src/encode/tokens.js
Labels: core, enhancement

#1077 add option to disable splitting aws-sdk service names by aws service
  docs/test.ts
  index.d.ts
  packages/datadog-plugin-aws-sdk/src/index.js
Labels: enhancement, integrations

#1070 enable manually triggering reliablity environment deploy
  .gitlab-ci.yml
Labels: dev/tooling

#1051 fix: missing startupLogsEnabled in typescript definition
  docs/API.md
  docs/test.ts
  index.d.ts
  packages/dd-trace/src/config.js
  packages/dd-trace/src/platform/node/startup-log.js
  packages/dd-trace/test/platform/node/startup-log.spec.js
Labels: community, core, enhancement

#1084 Allow benchmarking arbitrary e2e apps
  benchmark/e2e/benchmark-run.js
  benchmark/e2e/express-helloworld-manyroutes/app.js
Labels: dev/tooling

#1085 Fix span hooks example
  docs/API.md
Labels: community, docs

#1096 fix sqs message attributes quota reached when propagating
  packages/datadog-plugin-aws-sdk/src/index.js
  packages/datadog-plugin-aws-sdk/src/services/sqs.js
Labels: bug, integrations

#1089 Add async_local_storage to available scopes
  index.d.ts
Labels: community, dev/tooling
