Repository DataDog/dd-trace-js, pull requests merged in 2021-11, with the labels that each got.

#1668 add caching to random id generation
  packages/dd-trace/src/id.js
  packages/dd-trace/test/id.spec.js
Labels: core

#1667 fix tedious tests using deprecated api for v14
  packages/datadog-plugin-tedious/test/index.spec.js
Labels: dev/testing

#1665 Fix typo in comment.
  packages/dd-trace/src/proxy.js
Labels: community, docs

#1660 fix grpc client instrumentation when service prop exists
  packages/datadog-plugin-grpc/src/client.js
  packages/datadog-plugin-grpc/test/client.spec.js
  packages/datadog-plugin-grpc/test/hasservice.proto
Labels: bug, integrations

#1673 Fix CPU profiler latency
  package.json
  packages/dd-trace/src/profiling/profilers/cpu.js
  packages/dd-trace/test/profiling/profilers/cpu.spec.js
Labels: profiling

#1681 Update Typescript types to allow disabling of client or server in http plugins
  index.d.ts
Labels: dev/tooling, docs

#1683 update integration tests to use a real install from npm
  integration-tests/esm.spec.js
  integration-tests/esm/express.mjs
  integration-tests/esm/http.mjs
  integration-tests/helpers.js
  integration-tests/startup.spec.js
  integration-tests/startup/index.js
Labels: dev/testing

#1686 [ci-visibility] Update CI Visibility Spec
  packages/dd-trace/src/plugins/util/ci.js
  packages/dd-trace/src/plugins/util/user-provided-git.js
  packages/dd-trace/test/plugins/util/ci-env/buildkite.json
  packages/dd-trace/test/plugins/util/ci-env/github.json
  packages/dd-trace/test/plugins/util/ci-env/usersupplied.json
Labels: ci-app

#1687 Appsec response reporting
  packages/dd-trace/src/appsec/addresses.js
  packages/dd-trace/src/appsec/callbacks/ddwaf.js
  packages/dd-trace/src/appsec/index.js
  packages/dd-trace/src/appsec/reporter.js
  packages/dd-trace/test/appsec/callbacks/ddwaf.spec.js
  packages/dd-trace/test/appsec/index.spec.js
  packages/dd-trace/test/appsec/reporter.spec.js
Labels: appsec

#1696 Make Node.js typings consistent with engines and allow newer versions
  package.json
Labels: dev/tooling
