Repository DataDog/dd-trace-js, pull requests merged in 2021-03, with the labels that each got.

#1256 re-enable codecov
  .circleci/config.yml
  package.json
Labels: dev/testing

#1260 fix bound emitters leaking when trying to remove all listeners
  packages/dd-trace/src/scope/base.js
  packages/dd-trace/test/scope/test.js
Labels: bug, core

#1265 [serverless] add support for datadog extension
  packages/dd-trace/src/config.js
  packages/dd-trace/src/constants.js
  packages/dd-trace/src/exporter.js
  packages/dd-trace/test/exporter.spec.js
Labels: core, enhancement

#1271 update tedious ci tests to run on node 10
  .circleci/config.yml
Labels: dev/testing

#1266 fix sampling priority applied incorrectly
  packages/dd-trace/src/format.js
  packages/dd-trace/src/opentracing/span.js
  packages/dd-trace/src/priority_sampler.js
  packages/dd-trace/test/format.spec.js
  packages/dd-trace/test/opentracing/span.spec.js
  packages/dd-trace/test/priority_sampler.spec.js
Labels: bug, core

#1275 fix elasticsearch tests failing because of node requirement bump
  .circleci/config.yml
Labels: dev/testing

#1274 fix requests to the agent being traced
  packages/dd-trace/src/opentracing/tracer.js
  packages/dd-trace/src/scope/async_resource.js
  packages/dd-trace/test/opentracing/tracer.spec.js
  packages/dd-trace/test/plugins/util/redis.spec.js
  packages/dd-trace/test/scope/async_resource.spec.js
Labels: bug, core

#1284 Add async_hooks component benchmark
  .circleci/config.yml
  benchmark/sirun/async_hooks/index.js
  benchmark/sirun/async_hooks/meta.json
  benchmark/sirun/event_loop.js
  benchmark/sirun/gc.js
  benchmark/sirun/monitor.js
  benchmark/sirun/statsd.js
Labels: dev/testing, dev/tooling
