Repository DataDog/dd-trace-js, pull requests merged in 2021-07, with the labels that each got.

#1461 Prevent agent 502 errors
  packages/dd-trace/src/profiling/config.js
  packages/dd-trace/src/profiling/exporters/agent.js
  packages/dd-trace/test/profiling/config.spec.js
  packages/dd-trace/test/profiling/profiler.spec.js
Labels: profiling

#1452 Appsec entrypoint
  packages/dd-trace/src/appsec/index.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/proxy.js
  packages/dd-trace/test/proxy.spec.js
Labels: appsec

#1469 add upstream tests for axios
  .circleci/config.yml
  packages/datadog-plugin-axios/test/suite.js
  packages/dd-trace/test/plugins/suite.js
Labels: dev/testing, dev/tooling

#1478 [backport] enable prebuilds on release branches
  .circleci/config.yml
Labels: backport

#1482 fix abruptly closed http client requests not tagged as error
  packages/datadog-plugin-http/src/client.js
  packages/datadog-plugin-http/test/client.spec.js
Labels: bug, integrations

#1485 fix suffix incorrectly added to configured service name
  packages/datadog-plugin-aws-sdk/src/index.js
  packages/datadog-plugin-aws-sdk/test/aws-sdk.spec.js
Labels: bug, integrations

#1444 preinstall script to check version ranges
  package.json
  scripts/preinstall.js
Labels: semver-major

#1489 [ci-app] Update CI App Spec
  packages/dd-trace/src/plugins/util/ci.js
  packages/dd-trace/test/plugins/util/ci-env/appveyor.json
  packages/dd-trace/test/plugins/util/ci-env/azurepipelines.json
  packages/dd-trace/test/plugins/util/ci-env/bitbucket.json
  packages/dd-trace/test/plugins/util/ci-env/bitrise.json
  packages/dd-trace/test/plugins/util/ci-env/circleci.json
  packages/dd-trace/test/plugins/util/ci-env/github.json
  packages/dd-trace/test/plugins/util/ci-env/gitlab.json
  packages/dd-trace/test/plugins/util/ci-env/jenkins.json
  packages/dd-trace/test/plugins/util/ci-env/travisci.json
Labels: ci-app

#1493 update version script to support new release flow and major versions
  scripts/version.js
Labels: dev/tooling

#1497 add legacy dist tags and fix prerelease detection for docs
  scripts/postpublish.js
Labels: dev/tooling

#1500 fix version script not using the correct branches and suffixes
  scripts/version.js
Labels: dev/tooling

#1496 [ci-app] Fix `cucumber` Test Suite Extraction
  LICENSE-3rdparty.csv
  package.json
  packages/datadog-plugin-cucumber/src/index.js
  packages/datadog-plugin-cucumber/test/index.spec.js
Labels: ci-app

#1502 fix support for mongodb 4.x
  packages/datadog-plugin-mongodb-core/src/unified.js
  packages/datadog-plugin-mongodb-core/test/core.spec.js
  packages/datadog-plugin-mongodb-core/test/mongodb.spec.js
Labels: bug, integrations

#1507 Fix express api docs with invalid syntax
  docs/API.md
Labels: docs

#1508 fix tedious invalid stored procedure tag
  packages/datadog-plugin-tedious/src/index.js
  packages/datadog-plugin-tedious/test/index.spec.js
Labels: bug, dev/testing, integrations, semver-patch

#1504 [ci-app] Fix Exception in Hooks Outside of Tests
  packages/datadog-plugin-jest/src/index.js
  packages/datadog-plugin-jest/test/index.spec.js
Labels: ci-app

#1495 Add parse and validate hooks for graphql plugin:
  docs/test.ts
  index.d.ts
  packages/datadog-plugin-graphql/src/index.js
  packages/datadog-plugin-graphql/test/index.spec.js
Labels: community, enhancement, integrations, semver-minor

#1513 Make pprof required to satisfy check_licenses
  package.json
Labels: profiling

#1518 remove legacy tags from post-publish script
  scripts/postpublish.js
Labels: dev/tooling

#1520 update post-publish script to not publish docs on legacy branches
  scripts/postpublish.js
Labels: dev/tooling

#1523 Prevent next failures on profiler branch
  .circleci/config.yml
  packages/datadog-plugin-next/test/index.spec.js
  packages/datadog-plugin-next/test/next.config.js
  packages/dd-trace/test/plugins/externals.json
Labels: profiling

#1526 Fix checksum in prebuilds script
  scripts/prebuilds.js
Labels: dev/tooling

#1529 Use forked pprof module with prebuilds
  .eslintignore
  .npmignore
  LICENSE-3rdparty.csv
  package.json
  packages/dd-trace/src/profiling/profilers/cpu.js
  packages/dd-trace/src/profiling/profilers/heap.js
  packages/dd-trace/test/profiling/exporters/agent.spec.js
  packages/dd-trace/test/profiling/profilers/cpu.spec.js
  packages/dd-trace/test/profiling/profilers/heap.spec.js
Labels: profiling

#1530 Add additional profiler tests
  packages/dd-trace/test/profiling/profiler.spec.js
Labels: profiling

#1532 fix tests for pino 7
  packages/datadog-plugin-pino/test/index.spec.js
Labels: dev/testing, integrations
