Repository DataDog/dd-trace-js, pull requests merged in 2021-04, with the labels that each got.

#1295 move benchmark jobs to their own workflow
  .circleci/config.yml
Labels: dev/tooling

#1299 fix requests to the agent being traced
  packages/datadog-plugin-http/src/client.js
  packages/datadog-plugin-http/test/client.spec.js
  packages/dd-trace/test/plugins/agent.js
Labels: bug, integrations

#1302 add support for couchbase storage queries
  packages/datadog-plugin-couchbase/src/index.js
  packages/datadog-plugin-couchbase/test/index.spec.js
Labels: enhancement, integrations

#1305 fix unintended minimum version bump for couchbase support
  packages/datadog-plugin-couchbase/src/index.js
Labels: integrations

#1291 update profiler to default to pprof module
  LICENSE-3rdparty.csv
  package.json
  packages/dd-trace/src/profiling/config.js
  packages/dd-trace/src/profiling/encoders/pprof.js
  packages/dd-trace/src/profiling/exporters/agent.js
  packages/dd-trace/src/profiling/exporters/file.js
  packages/dd-trace/src/profiling/index.js
  packages/dd-trace/src/profiling/profile.js
  packages/dd-trace/src/profiling/profiler.js
  packages/dd-trace/src/profiling/profilers/cpu.js
  packages/dd-trace/src/profiling/profilers/heap.js
  packages/dd-trace/src/profiling/profilers/inspector/cpu.js
  packages/dd-trace/src/profiling/profilers/inspector/heap.js
  packages/dd-trace/src/profiling/profilers/native/cpu.js
  packages/dd-trace/src/profiling/profilers/native/heap.js
  packages/dd-trace/src/profiling/util.js
  packages/dd-trace/test/asserts/profile.js
  packages/dd-trace/test/profiling/config.spec.js
  packages/dd-trace/test/profiling/exporters/agent.spec.js
  packages/dd-trace/test/profiling/exporters/file.spec.js
  packages/dd-trace/test/profiling/profiler.spec.js
  packages/dd-trace/test/profiling/profilers/cpu.spec.js
  packages/dd-trace/test/profiling/profilers/heap.spec.js
  packages/dd-trace/test/profiling/profilers/inspector/cpu.spec.js
  packages/dd-trace/test/profiling/profilers/inspector/heap.spec.js
  packages/dd-trace/test/profiling/util.spec.js
  protobuf/profile.d.ts
  protobuf/profile.js
  protobuf/profile.proto
Labels: profiling

#1308 make circle token optional for prepublish script
  scripts/prepublish.js
Labels: dev/tooling

#1314 fix container id not reporting properly in kubernetes
  packages/dd-trace/src/exporters/agent/docker.js
  packages/dd-trace/test/exporters/agent/docker.spec.js
Labels: bug, core

#1315 fix sampling priority using the wrong service name
  packages/dd-trace/src/priority_sampler.js
  packages/dd-trace/test/priority_sampler.spec.js
Labels: bug, core

#1317 update prepublish script to only block for prebuilds
  scripts/prepublish.js
Labels: dev/tooling

#1323 remove dependency on read-pkg-up
  LICENSE-3rdparty.csv
  package.json
  packages/dd-trace/src/pkg.js
Labels: bug, core

#1324 remove dependency on axios and parent-module that were unused
  LICENSE-3rdparty.csv
  package.json
Labels: core

#1335 add native addon prebuilds for node 16
  .circleci/config.yml
  scripts/prebuild.js
Labels: core, enhancement
