Repository DataDog/dd-trace-js, pull requests merged in 2021-02, with the labels that each got.

#1223 [ci-app] Fix Mocha Instrumentation
  packages/datadog-plugin-mocha/src/index.js
  packages/datadog-plugin-mocha/test/index.spec.js
  packages/datadog-plugin-mocha/test/mocha-test-timeout-fail.js
  packages/datadog-plugin-mocha/test/mocha-test-timeout-pass.js
Labels: bug, integrations

#1232 fix tedious test
  packages/datadog-plugin-tedious/test/index.spec.js
  packages/dd-trace/test/setup/services/mssql.js
Labels: dev/testing

#1233 fix possible app crash in latest when used with meteor 2.0
  index.d.ts
  packages/dd-trace/src/platform/node/index.js
  packages/dd-trace/test/platform/node/index.spec.js
  packages/dd-trace/test/setup/core.js
Labels: bug, core

#1237 fix aws-sdk tests not waiting for localstack to be ready
  .circleci/config.yml
  packages/dd-trace/test/setup/services/localstack.js
Labels: dev/testing

#1241 Fixes #1240 properly spread callback args
  packages/datadog-plugin-mysql2/src/index.js
  packages/datadog-plugin-mysql2/test/index.spec.js
Labels: bug, community, integrations

#1246 [ci-app] Add CI App Feature Tracking
  packages/dd-trace/src/plugins/util/ci-app-spec.json
Labels: enhancement, integrations
