Repository DataDog/dd-trace-js, pull requests merged in 2021-09, with the labels that each got.

#1602 Feat: conditionally inject headers (#1601)
  docs/test.ts
  index.d.ts
  packages/datadog-plugin-http/src/client.js
  packages/datadog-plugin-http/test/client.spec.js
Labels: enhancement, community, integrations, semver-minor

#1605 [ci-app] Fix Skipped Cucumber Steps Being Marked as Errors
  packages/datadog-plugin-cucumber/src/index.js
  packages/datadog-plugin-cucumber/test/features/simple.feature
  packages/datadog-plugin-cucumber/test/index.spec.js
  packages/dd-trace/src/plugins/util/ci-app-spec.json
  packages/dd-trace/src/plugins/util/test.js
Labels: ci-app

#1606 Add additional metadata to profiler export
  package.json
  packages/dd-trace/src/profiling/exporters/agent.js
  packages/dd-trace/test/profiling/exporters/agent.spec.js
  packages/dd-trace/test/profiling/profiler.spec.js
Labels: profiling

#1562 [ci-app] Cypress Plugin Instrumentation
  .circleci/config.yml
  .npmignore
  cypress/plugin.js
  cypress/support.js
  docs/test.ts
  index.d.ts
  packages/datadog-plugin-cypress/src/index.js
  packages/datadog-plugin-cypress/src/plugin.js
  packages/datadog-plugin-cypress/src/support.js
  packages/datadog-plugin-cypress/test/app/app-server.js
  packages/datadog-plugin-cypress/test/app/cypress.json
  packages/datadog-plugin-cypress/test/app/cypress/integration/integration-test.js
  packages/datadog-plugin-cypress/test/app/cypress/plugins/index.js
  packages/datadog-plugin-cypress/test/app/cypress/support/index.js
  packages/datadog-plugin-cypress/test/index.spec.js
  packages/datadog-plugin-jest/src/util.js
  packages/datadog-plugin-mocha/src/index.js
  packages/dd-trace/src/plugins/index.js
  packages/dd-trace/src/plugins/util/test.js
  packages/dd-trace/test/plugins/agent.js
  packages/dd-trace/test/plugins/externals.json
Labels: ci-app

#1617 fix support for mongoose 6
  packages/datadog-plugin-mongoose/src/index.js
Labels: bug, integrations

#1618 fix aws-sdk tests calling done with non-errors
  packages/datadog-plugin-cypress/test/index.spec.js
  packages/dd-trace/test/plugins/agent.js
Labels: dev/testing, integrations

#1619 fix mongoose context propagation for aggregations
  packages/datadog-plugin-mongodb-core/src/unified.js
  packages/datadog-plugin-mongodb-core/test/mongodb.spec.js
Labels: bug, integrations

#1624 fix missing retry dependency for profiling
  LICENSE-3rdparty.csv
  package.json
Labels: bug, profiling
