Repository DataDog/dd-trace-js, pull requests merged in 2021-08, with the labels that each got.

#1539 [ci-app] Fix Possible Missing `getVmContext`
  packages/datadog-plugin-jest/src/index.js
  packages/datadog-plugin-jest/test/index.spec.js
Labels: bug, ci-app

#1542 [ci-app] Update CI App spec
  packages/dd-trace/src/plugins/util/ci.js
  packages/dd-trace/test/plugins/util/ci-env/gitlab.json
Labels: ci-app

#1533 fix missing error tags for hook exceptions
  packages/datadog-plugin-fastify/src/fastify.js
  packages/datadog-plugin-fastify/test/index.spec.js
  packages/dd-trace/test/plugins/externals.json
Labels: bug, integrations

#1528 add log benchmarks
  .circleci/config.yml
  benchmark/core.js
  benchmark/sirun/log/README.md
  benchmark/sirun/log/index.js
  benchmark/sirun/log/meta.json
Labels: dev/testing

#1538 fix next request error when rendering directly
  packages/datadog-plugin-next/src/index.js
Labels: bug, integrations

#1544 update version script to not conflict branch with tag
  scripts/version.js
Labels: dev/tooling

#1552 fix fastify error when hooks have only a single parameter
  packages/datadog-plugin-fastify/src/fastify.js
  packages/datadog-plugin-fastify/test/index.spec.js
  packages/dd-trace/test/plugins/externals.json
Labels: bug, integrations

#1553 bump sketches-js to avoid security warning and add audit
  .circleci/config.yml
  package.json
Labels: bug, core

#1550 [ci-app] Fix `this.skip` in Mocha
  packages/datadog-plugin-mocha/src/index.js
  packages/datadog-plugin-mocha/test/index.spec.js
  packages/datadog-plugin-mocha/test/mocha-test-skip.js
Labels: ci-app

#1543 Ensure fresh start time is used for each profiler capture
  package.json
  packages/dd-trace/src/profiling/profiler.js
  packages/dd-trace/test/profiling/profiler.spec.js
Labels: profiling

#1422 Profiler tracking PR
  .circleci/config.yml
  .eslintignore
  .npmignore
  LICENSE-3rdparty.csv
  benchmark/sirun/profiler/index.js
  benchmark/sirun/profiler/meta.json
  package.json
  packages/datadog-plugin-next/test/index.spec.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/profiling/config.js
  packages/dd-trace/src/profiling/encoders/pprof.js
  packages/dd-trace/src/profiling/exporters/agent.js
  packages/dd-trace/src/profiling/exporters/file.js
  packages/dd-trace/src/profiling/index.js
  packages/dd-trace/src/profiling/profile.js
  packages/dd-trace/src/profiling/profiler.js
  packages/dd-trace/src/profiling/profilers/cpu.js
  packages/dd-trace/src/profiling/profilers/heap.js
  packages/dd-trace/src/profiling/profilers/inspector/cpu.js
  packages/dd-trace/src/profiling/profilers/inspector/heap.js
  packages/dd-trace/src/profiling/profilers/native/cpu.js
  packages/dd-trace/src/profiling/util.js
  packages/dd-trace/src/startup-log.js
  packages/dd-trace/test/asserts/profile.js
  packages/dd-trace/test/profiling/config.spec.js
  packages/dd-trace/test/profiling/exporters/agent.spec.js
  packages/dd-trace/test/profiling/exporters/file.spec.js
  packages/dd-trace/test/profiling/profiler.spec.js
  packages/dd-trace/test/profiling/profilers/cpu.spec.js
  packages/dd-trace/test/profiling/profilers/heap.spec.js
  packages/dd-trace/test/profiling/profilers/inspector/cpu.spec.js
  packages/dd-trace/test/profiling/profilers/inspector/heap.spec.js
  packages/dd-trace/test/profiling/util.spec.js
  protobuf/profile.d.ts
  protobuf/profile.js
  protobuf/profile.proto
Labels: profiling

#1558 Add runtime-id tag to profiler
  LICENSE-3rdparty.csv
  index.d.ts
  package.json
  packages/dd-trace/src/config.js
  packages/dd-trace/src/metrics.js
  packages/dd-trace/src/profiler.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/profiling/exporters/agent.spec.js
Labels: profiling

#1569 [ci-app] Calculate `ci.workspace_path` from `git` too
  packages/dd-trace/src/plugins/util/ci.js
  packages/dd-trace/src/plugins/util/git.js
  packages/dd-trace/src/plugins/util/tags.js
  packages/dd-trace/src/plugins/util/test.js
  packages/dd-trace/test/plugins/util/git.spec.js
Labels: ci-app

#1567 [ci-app] Allow User Defined Git Tags
  packages/dd-trace/src/plugins/util/git.js
  packages/dd-trace/test/plugins/util/git.spec.js
Labels: ci-app

#1570 fix missing origin allowed header for cors
  packages/dd-trace/src/plugins/util/web.js
  packages/dd-trace/test/plugins/util/web.spec.js
Labels: bug, semver-patch

#1571 fix graphql query source exposed by default
  index.d.ts
  packages/datadog-plugin-graphql/src/index.js
  packages/datadog-plugin-graphql/test/index.spec.js
Labels: bug, integrations

#1568 Revert "remove profiling documentation while the feature is disabled (#1064)"
  docs/API.md
  index.d.ts
Labels: profiling

#1572 Allow specifying list of profilers to use
  packages/dd-trace/src/profiling/config.js
  packages/dd-trace/test/profiling/config.spec.js
Labels: profiling

#1573 fix elasticsearch tests and make instrumentation safer
  .circleci/config.yml
  docker-compose.yml
  packages/datadog-plugin-elasticsearch/src/index.js
  packages/datadog-plugin-elasticsearch/test/index.spec.js
Labels: dev/testing

#1574 fix support for next 11.1
  packages/datadog-plugin-next/src/index.js
  packages/datadog-plugin-next/test/index.spec.js
Labels: bug, integrations

#1559 Move native metrics to a separate repository
  .circleci/config.yml
  .npmignore
  LICENSE-3rdparty.csv
  benchmark/core.js
  binding.gyp
  package.json
  packages/dd-trace/src/metrics.js
  packages/dd-trace/src/native/metrics/Collector.cpp
  packages/dd-trace/src/native/metrics/Collector.hpp
  packages/dd-trace/src/native/metrics/EventLoop.cpp
  packages/dd-trace/src/native/metrics/EventLoop.hpp
  packages/dd-trace/src/native/metrics/GarbageCollection.cpp
  packages/dd-trace/src/native/metrics/GarbageCollection.hpp
  packages/dd-trace/src/native/metrics/Heap.cpp
  packages/dd-trace/src/native/metrics/Heap.hpp
  packages/dd-trace/src/native/metrics/Histogram.cpp
  packages/dd-trace/src/native/metrics/Histogram.hpp
  packages/dd-trace/src/native/metrics/Object.cpp
  packages/dd-trace/src/native/metrics/Object.hpp
  packages/dd-trace/src/native/metrics/Process.cpp
  packages/dd-trace/src/native/metrics/Process.hpp
  packages/dd-trace/src/native/metrics/SpanTracker.cpp
  packages/dd-trace/src/native/metrics/SpanTracker.hpp
  packages/dd-trace/src/native/metrics/main.cpp
  packages/dd-trace/src/native/metrics/utils.cpp
  packages/dd-trace/src/native/metrics/utils.hpp
  packages/dd-trace/src/native/tdigest/LICENSE-2.0.txt
  packages/dd-trace/src/native/tdigest/NOTICES
  packages/dd-trace/src/native/tdigest/TDigest.h
  packages/dd-trace/src/opentracing/span.js
  packages/dd-trace/test/opentracing/span.spec.js
  scripts/prebuild.js
  scripts/prebuilds.js
  scripts/prepublish.js
  scripts/should_rebuild.js
Labels: core

#1579 make measuredByDefault actually do something
  packages/dd-trace/src/analytics_sampler.js
  packages/dd-trace/test/analytics_sampler.spec.js
Labels: semver-patch

#1514 avoid DNS lookups when dogstatsd host is an IP address
  packages/dd-trace/src/dogstatsd.js
  packages/dd-trace/test/dogstatsd.spec.js
Labels: community, integrations

#1599 [ci-app] Fix `jest` Test Suite
  packages/datadog-plugin-jest/test/circus.spec.js
Labels: ci-app
