Repository DataDog/dd-trace-js, pull requests merged in 2021-06, with the labels that each got.

#1398 [ci-app] JUnit XML Upload – Fix `DD_ENV` to `CI`
  scripts/junit_report.js
Labels: ci-app

#1396 [ci-app] Remove `ci.job.id` from CircleCI Env Var Extraction
  packages/dd-trace/src/plugins/util/ci.js
  packages/dd-trace/test/plugins/util/ci-env/circleci.json
Labels: ci-app

#1385 [ci-app] Add origin Tag Propagation for Testing Integrations
  packages/datadog-plugin-cucumber/src/index.js
  packages/datadog-plugin-cucumber/test/index.spec.js
  packages/datadog-plugin-jest/src/index.js
  packages/datadog-plugin-jest/test/index.spec.js
  packages/datadog-plugin-mocha/src/index.js
  packages/datadog-plugin-mocha/test/index.spec.js
  packages/datadog-plugin-mocha/test/mocha-test-integration.js
  packages/dd-trace/src/plugins/util/test.js
Labels: ci-app

#1401 [ci-app] Fix `DD_ENV` in JUnit XML Upload
  scripts/junit_report.js
Labels: ci-app

#1397 [ci-app] Update Git Metadata Extraction
  LICENSE-3rdparty.csv
  packages/dd-trace/src/plugins/util/git.js
  packages/dd-trace/test/plugins/util/git.spec.js
  vendor/git-repo-info.js
Labels: ci-app

#1400 [ci-app] Add `_dd.origin` to CI App Spec
  packages/dd-trace/src/plugins/util/ci-app-spec.json
Labels: ci-app

#1399 [ci-app] Fix Typo in `ci.pipeline.url` in CircleCI
  packages/dd-trace/src/plugins/util/ci.js
  packages/dd-trace/test/plugins/util/ci-env/circleci.json
Labels: ci-app

#1389 fix support for grpc custom client instances
  packages/datadog-plugin-grpc/src/client.js
  packages/datadog-plugin-grpc/src/util.js
  packages/datadog-plugin-grpc/test/client.spec.js
  packages/datadog-plugin-grpc/test/invalid.proto
  packages/datadog-plugin-grpc/test/server.spec.js
  packages/datadog-plugin-grpc/test/service.js
  packages/datadog-plugin-grpc/test/test.proto
Labels: enhancement, integrations

#1412 allow subclasses of router
  packages/datadog-plugin-router/src/index.js
  packages/datadog-plugin-router/test/index.spec.js
Labels: bug, integrations

#1414 Improve compatibility with ESBuild
  packages/datadog-plugin-aws-sdk/src/helpers.js
Labels: community, dev/tooling

#1406 [ci-app] Add HTTP Integrations Tests to Testing Frameworks Instrumentations
  packages/datadog-plugin-cucumber/src/index.js
  packages/datadog-plugin-cucumber/test/features/simple.feature
  packages/datadog-plugin-cucumber/test/features/simple.js
  packages/datadog-plugin-cucumber/test/index.spec.js
  packages/datadog-plugin-jest/src/index.js
  packages/datadog-plugin-jest/test/index.spec.js
  packages/datadog-plugin-mocha/src/index.js
  packages/datadog-plugin-mocha/test/index.spec.js
  packages/datadog-plugin-mocha/test/mocha-test-integration-http.js
  packages/dd-trace/src/plugins/util/test.js
Labels: ci-app

#1403 Fix profiler config propagation
  packages/dd-trace/src/profiler.js
  packages/dd-trace/src/profiling/config.js
  packages/dd-trace/src/profiling/exporters/agent.js
  packages/dd-trace/test/profiling/config.spec.js
  packages/dd-trace/test/profiling/profiler.spec.js
Labels: profiling

#1404 [ci-app] Jest – Fix Instrumentation Snapshot Errors
  packages/datadog-plugin-jest/src/index.js
  packages/datadog-plugin-jest/test/index.spec.js
  packages/datadog-plugin-mocha/src/index.js
  packages/dd-trace/src/format.js
  packages/dd-trace/src/plugins/util/test.js
  packages/dd-trace/src/tracer.js
  packages/dd-trace/src/util.js
Labels: ci-app

#1423 fix missing bulkBody info
  packages/datadog-plugin-elasticsearch/src/index.js
  packages/datadog-plugin-elasticsearch/test/index.spec.js
Labels: community, enhancement, integrations

#1426 fix intermittent google cloud pubsub test timeout
  packages/datadog-plugin-google-cloud-pubsub/test/index.spec.js
Labels: dev/testing

#1427 fix kafkajs test setup timeout
  packages/dd-trace/test/setup/services/kafka.js
Labels: dev/testing

#1432 fix possible race condition in mongoose tests
  .circleci/config.yml
  docker-compose.yml
  packages/datadog-plugin-mongoose/test/index.spec.js
Labels: dev/testing

#1425 fix stale module returned when require cache is overridden
  package.json
  packages/dd-trace/src/ritm.js
Labels: bug, core

#1433 temporarily disable node upstream tests
  .circleci/config.yml
Labels: dev/testing

#1424 fix tests for next 11
  packages/datadog-plugin-next/test/index.spec.js
  packages/datadog-plugin-next/test/next.config.js
Labels: dev/testing, integrations

#1437 Make profiler use normal enable option
  packages/dd-trace/src/config.js
Labels: profiling

#1439 Edit Tagger.js to support whitespace
  packages/dd-trace/src/profiling/tagger.js
  packages/dd-trace/src/tagger.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/profiling/tagger.spec.js
Labels: bug, core, profiling

#1438 [ci-app] Support Cucumber >=7.3.0
  packages/datadog-plugin-cucumber/src/index.js
  packages/datadog-plugin-cucumber/test/index.spec.js
Labels: bug, ci-app, integrations

#1430 [ci-app] Add JUnit XML Upload to Plugins Tests
  .circleci/config.yml
  .gitignore
  mocha-reporter-config.json
  package.json
  scripts/junit_report.js
Labels: ci-app

#1429 [ci-app] Add Error Handling for `beforeEach`/`afterEach` Hooks in Testing Frameworks
  packages/datadog-plugin-cucumber/test/features/simple.feature
  packages/datadog-plugin-cucumber/test/features/simple.js
  packages/datadog-plugin-cucumber/test/index.spec.js
  packages/datadog-plugin-jest/src/index.js
  packages/datadog-plugin-jest/test/index.spec.js
  packages/datadog-plugin-mocha/src/index.js
  packages/datadog-plugin-mocha/test/index.spec.js
  packages/datadog-plugin-mocha/test/mocha-fail-hook-async.js
  packages/datadog-plugin-mocha/test/mocha-fail-hook-sync.js
  packages/dd-trace/src/util.js
Labels: ci-app

#1443 fix pino-pretty test check for invalid string on the record
  packages/datadog-plugin-pino/test/index.spec.js
Labels: dev/testing

#1440 fix random next test errors because of slow webpack
  packages/datadog-plugin-next/test/index.spec.js
Labels: dev/testing

#1442 fix errors in web frameworks when using fake requests
  packages/dd-trace/src/plugins/util/web.js
  packages/dd-trace/test/plugins/util/web.spec.js
Labels: bug, core, integrations

#1449 add lint rule 'import/no-extraneous-dependencies'
  .eslintrc.json
  LICENSE-3rdparty.csv
  package.json
  packages/datadog-plugin-next/test/index.spec.js
  packages/dd-trace/test/instrumenter.spec.js
Labels: semver-patch

#1454 Remove DD_PROFILING_INTERVAL env var
  packages/dd-trace/src/profiling/config.js
Labels: profiling

#1445 remove internal services and replace analytics with measured
  docker-compose.yml
  docs/test.ts
  index.d.ts
  packages/datadog-plugin-amqp10/src/index.js
  packages/datadog-plugin-amqplib/src/index.js
  packages/datadog-plugin-aws-sdk/src/index.js
  packages/datadog-plugin-cassandra-driver/src/index.js
  packages/datadog-plugin-couchbase/src/index.js
  packages/datadog-plugin-dns/src/index.js
  packages/datadog-plugin-dns/test/index.spec.js
  packages/datadog-plugin-elasticsearch/src/index.js
  packages/datadog-plugin-fs/src/index.js
  packages/datadog-plugin-fs/test/index.spec.js
  packages/datadog-plugin-google-cloud-pubsub/src/index.js
  packages/datadog-plugin-graphql/src/index.js
  packages/datadog-plugin-graphql/test/index.spec.js
  packages/datadog-plugin-grpc/src/client.js
  packages/datadog-plugin-grpc/src/server.js
  packages/datadog-plugin-http/src/client.js
  packages/datadog-plugin-http2/src/client.js
  packages/datadog-plugin-http2/src/server.js
  packages/datadog-plugin-kafkajs/src/index.js
  packages/datadog-plugin-memcached/src/index.js
  packages/datadog-plugin-mongodb-core/src/util.js
  packages/datadog-plugin-mysql/src/index.js
  packages/datadog-plugin-mysql2/src/index.js
  packages/datadog-plugin-net/src/index.js
  packages/datadog-plugin-net/test/index.spec.js
  packages/datadog-plugin-next/src/index.js
  packages/datadog-plugin-next/test/index.spec.js
  packages/datadog-plugin-oracledb/src/index.js
  packages/datadog-plugin-pg/src/index.js
  packages/datadog-plugin-rhea/src/index.js
  packages/datadog-plugin-tedious/src/index.js
  packages/dd-trace/src/analytics_sampler.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/format.js
  packages/dd-trace/src/instrumenter.js
  packages/dd-trace/src/opentracing/tracer.js
  packages/dd-trace/src/plugins/util/redis.js
  packages/dd-trace/src/plugins/util/web.js
  packages/dd-trace/src/proxy.js
  packages/dd-trace/src/startup-log.js
  packages/dd-trace/src/tracer.js
  packages/dd-trace/test/analytics_sampler.spec.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/format.spec.js
  packages/dd-trace/test/instrumenter.spec.js
  packages/dd-trace/test/proxy.spec.js
  packages/dd-trace/test/startup-log.spec.js
  packages/dd-trace/test/tracer.spec.js
Labels: breaking-change, core, enhancement, integrations, semver-major

#1447 Drop Node 8 and Node 10 support.
  .circleci/config.yml
  package.json
  packages/datadog-plugin-couchbase/src/index.js
  packages/datadog-plugin-dns/test/index.spec.js
  packages/datadog-plugin-fs/test/index.spec.js
  packages/datadog-plugin-grpc/src/client.js
  packages/datadog-plugin-grpc/src/server.js
  packages/datadog-plugin-http/src/client.js
  packages/datadog-plugin-http/test/client.spec.js
  packages/datadog-plugin-http2/test/client.spec.js
  packages/datadog-plugin-restify/test/index.spec.js
  packages/dd-trace/src/loader.js
  packages/dd-trace/src/profiling/profiler.js
  packages/dd-trace/src/require-package-json.js
  packages/dd-trace/src/scope/async_hooks.js
  packages/dd-trace/src/startup-log.js
  packages/dd-trace/test/plugins/suite.js
  packages/dd-trace/test/profiling/mapper.spec.js
  packages/dd-trace/test/profiling/profiler.spec.js
  packages/dd-trace/test/profiling/profilers/inspector/heap.spec.js
  packages/dd-trace/test/scope/async_hooks.spec.js
  scripts/install_plugin_modules.js
  scripts/junit_report.js
Labels: breaking-change, core, semver-major

#1457 fix incorrect 3rd-party licenses and improve license validation
  LICENSE-3rdparty.csv
  scripts/check_licenses.js
Labels: dev/tooling

#1453 [ci-app] Handle Uncaught Async Errors in Mocha
  packages/datadog-plugin-mocha/src/index.js
  packages/datadog-plugin-mocha/test/index.spec.js
  packages/datadog-plugin-mocha/test/mocha-test-done-fail-badly.js
Labels: ci-app
