Repository DataDog/dd-trace-js, pull requests merged in 2021-01, with the labels that each got.

#1183 fix fs tests breaking in node 15
  packages/datadog-plugin-fs/test/index.spec.js
Labels: dev/testing

#1179 fix aws-sdk tests
  .circleci/config.yml
  docker-compose.yml
  packages/datadog-plugin-aws-sdk/test/aws-sdk.spec.js
  packages/datadog-plugin-aws-sdk/test/fixtures/dynamodb.js
  packages/datadog-plugin-aws-sdk/test/index.spec.js
  packages/datadog-plugin-aws-sdk/test/spec_helpers.js
  packages/datadog-plugin-aws-sdk/test/sqs.spec.js
  packages/dd-trace/test/setup/services/localstack.js
Labels: dev/testing, integrations

#1184 Update axios to 0.21.1 to address CVE
  package.json
Labels: community, core

#1188 [ci-app] Fix Jest Flaky Test Setup and Use More Supported Branch Extraction
  packages/datadog-plugin-jest/test/index.spec.js
  packages/dd-trace/src/plugins/util/git.js
Labels: dev/testing

#1178 fix missing span types in some web and worker plugins
  packages/datadog-plugin-amqp10/src/index.js
  packages/datadog-plugin-amqp10/test/index.spec.js
  packages/datadog-plugin-amqplib/src/index.js
  packages/datadog-plugin-amqplib/test/index.spec.js
  packages/datadog-plugin-aws-sdk/src/services/sqs.js
  packages/datadog-plugin-google-cloud-pubsub/src/index.js
  packages/datadog-plugin-google-cloud-pubsub/test/index.spec.js
  packages/datadog-plugin-grpc/src/client.js
  packages/datadog-plugin-grpc/src/server.js
  packages/datadog-plugin-grpc/test/client.spec.js
  packages/datadog-plugin-grpc/test/server.spec.js
  packages/datadog-plugin-rhea/src/index.js
  packages/datadog-plugin-rhea/test/index.spec.js
Labels: bug, integrations

#1189 Revert "wrap end on prototype instead of instances"
  packages/dd-trace/src/plugins/util/web.js
  packages/dd-trace/test/plugins/util/web.spec.js
Labels: bug, core, integrations

#1146 Add KafkaJS support
  .circleci/config.yml
  docker-compose.yml
  docs/API.md
  docs/test.ts
  index.d.ts
  packages/datadog-plugin-kafkajs/src/index.js
  packages/datadog-plugin-kafkajs/test/index.spec.js
  packages/dd-trace/src/plugins/index.js
  packages/dd-trace/test/setup/services/kafka.js
Labels: community, enhancement, integrations

#1161 fix double-routing in restify
  packages/datadog-plugin-fastify/src/find-my-way.js
  packages/datadog-plugin-fastify/src/index.js
  packages/datadog-plugin-restify/src/index.js
  packages/datadog-plugin-restify/test/index.spec.js
Labels: bug, integrations

#1192 export the tracer from implicit init file
  init.js
Labels: core, enhancement

#1191 Call options fn on each invocation in tracer.wrap
  packages/dd-trace/src/tracer.js
  packages/dd-trace/test/tracer.spec.js
Labels: bug, core

#1194 add option to split ioredis service name by instance
  docs/test.ts
  index.d.ts
  packages/datadog-plugin-ioredis/src/index.js
  packages/datadog-plugin-ioredis/test/index.spec.js
Labels: enhancement, integrations

#1176 fix container tagging support for ecs and fargate
  LICENSE-3rdparty.csv
  package.json
  packages/dd-trace/src/platform/node/docker.js
  packages/dd-trace/src/platform/node/request.js
  packages/dd-trace/test/platform/node/index.spec.js
Labels: bug, core

#1196 replace blacklist and whitelist with blocklist and allowlist
  docs/test.ts
  index.d.ts
  packages/datadog-plugin-http/src/client.js
  packages/datadog-plugin-http2/src/client.js
  packages/datadog-plugin-ioredis/test/index.spec.js
  packages/datadog-plugin-redis/test/index.spec.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/plugins/util/urlfilter.js
  packages/dd-trace/test/plugins/util/web.spec.js
Labels: core, docs, enhancement

#1193 add option to enable/disable tracing of individual aws services
  packages/datadog-plugin-aws-sdk/src/helpers.js
  packages/datadog-plugin-aws-sdk/src/index.js
  packages/datadog-plugin-aws-sdk/src/services/sqs.js
  packages/datadog-plugin-aws-sdk/test/aws-sdk.spec.js
  packages/datadog-plugin-aws-sdk/test/sqs.spec.js
Labels: enhancement, integrations

#1197 add type definitions for aws-sdk service configuration
  docs/test.ts
  index.d.ts
Labels: dev/tooling, docs

#1201 fix ts for aws split-by-service change
  docs/package.json
  docs/tsconfig.json
  index.d.ts
Labels: dev/tooling, docs

#1166 AWS SDK: Inject trace data to sync lambda invoke
  .circleci/config.yml
  LICENSE-3rdparty.csv
  docker-compose.yml
  package.json
  packages/datadog-plugin-aws-sdk/src/helpers.js
  packages/datadog-plugin-aws-sdk/src/services/lambda.js
  packages/datadog-plugin-aws-sdk/test/fixtures/base.js
  packages/datadog-plugin-aws-sdk/test/lambda.spec.js
Labels: enhancement, integrations

#1213 fix invalid errors causing incorrect encoding
  packages/dd-trace/src/format.js
  packages/dd-trace/test/format.spec.js
Labels: bug, core

#1205 [ci-app] Add Support for Additional CIs
  packages/dd-trace/src/plugins/util/ci.js
  packages/dd-trace/test/plugins/util/ci-env/appveyor.json
  packages/dd-trace/test/plugins/util/ci-env/azurepipelines.json
  packages/dd-trace/test/plugins/util/ci-env/bitbucket.json
  packages/dd-trace/test/plugins/util/ci-env/bitrise.json
  packages/dd-trace/test/plugins/util/ci-env/buildkite.json
  packages/dd-trace/test/plugins/util/ci-env/circleci.json
  packages/dd-trace/test/plugins/util/ci-env/github.json
  packages/dd-trace/test/plugins/util/ci-env/gitlab.json
  packages/dd-trace/test/plugins/util/ci-env/jenkins.json
  packages/dd-trace/test/plugins/util/ci-env/travisci.json
  packages/dd-trace/test/plugins/util/ci.spec.js
Labels: enhancement, integrations

#1211 Invoke run when eachMessage is absent
  packages/datadog-plugin-kafkajs/src/index.js
  packages/datadog-plugin-kafkajs/test/index.spec.js
Labels: bug, community, integrations

#1215 [ci-app] Improve Test Environment Metadata Extraction
  packages/datadog-plugin-jest/src/index.js
  packages/datadog-plugin-mocha/src/index.js
  packages/dd-trace/src/plugins/util/test.js
Labels: integrations

#1218 fix fastify error when handler is passed in the options
  packages/datadog-plugin-fastify/src/fastify.js
  packages/datadog-plugin-fastify/test/index.spec.js
Labels: bug, integrations
