Repository DataDog/dd-trace-js, pull requests merged in 2022-04, with the labels that each got.

#1963 Bump `@datadog/native-appsec` to `1.0.0`
  package.json
Labels: appsec

#1960 Update AppSec rules file to 1.3.0
  packages/dd-trace/src/appsec/recommended.json
Labels: appsec

#1968 test that amqplib commands run normally
  packages/datadog-plugin-amqplib/test/index.spec.js
Labels: dev/testing

#1955 normalize http plugin config only when needed
  packages/datadog-plugin-http/src/client.js
  packages/datadog-plugin-http/src/server.js
Labels: integrations

#1956 fix http client integration always setting the error flag
  packages/datadog-instrumentations/src/http/client.js
  packages/datadog-plugin-http/test/client.spec.js
Labels: bug, integrations

#1964 [ci-visibility] Update agentless payload format
  packages/dd-trace/src/encode/agentless-ci-visibility.js
  packages/dd-trace/test/encode/agentless-ci-visibility.spec.js
Labels: ci-app

#1975 Update AppSec rules file to v1.3.1
  packages/dd-trace/src/appsec/recommended.json
Labels: appsec

#1976 [ci-visibility] Fix Cucumber Tests
  packages/datadog-plugin-cucumber/test/index.spec.js
Labels: bug, ci-app

#1853 dispose of the wafContext after each use
  packages/dd-trace/src/appsec/callbacks/ddwaf.js
  packages/dd-trace/test/appsec/callbacks/ddwaf.spec.js
Labels: appsec

#1981 Bump `@datadog/native-appsec` to `1.0.1`
  package.json
Labels: appsec

#1978 [ci-visibility] Code Owners for `cypress`
  packages/datadog-plugin-cypress/src/plugin.js
  packages/datadog-plugin-cypress/test/app/CODEOWNERS
  packages/datadog-plugin-cypress/test/index.spec.js
Labels: ci-app

#1977 [ci-visibility] Code Owners for `cucumber`
  packages/datadog-plugin-cucumber/src/index.js
  packages/dd-trace/src/plugins/util/test.js
Labels: ci-app

#1987 [ci-visibility] Rewrite Cypress Plugin
  packages/datadog-instrumentations/src/cypress.js
  packages/datadog-plugin-cypress/src/index.js
  packages/datadog-plugin-cypress/test/index.spec.js
Labels: ci-app

#2004 fix fs spans never finishing when a stream is not consumed
  packages/datadog-plugin-fs/src/index.js
  packages/datadog-plugin-fs/test/index.spec.js
Labels: bug, integrations

#2013 fix fs plugin adding error tags
  packages/datadog-plugin-fs/test/index.spec.js
  packages/dd-trace/src/format.js
Labels: bug, integrations

#2012 fix web requests in blocklist reaching the agent
  packages/datadog-plugin-http/src/server.js
  packages/datadog-plugin-http/test/server.spec.js
  packages/dd-trace/src/plugins/util/web.js
  packages/dd-trace/src/span_processor.js
Labels: bug, integrations

#2005 Support Appsec Metrics, Obfuscator and WAF Timeout
  docs/API.md
  docs/test.ts
  index.d.ts
  package.json
  packages/dd-trace/src/appsec/callbacks/ddwaf.js
  packages/dd-trace/src/appsec/index.js
  packages/dd-trace/src/appsec/reporter.js
  packages/dd-trace/src/appsec/rule_manager.js
  packages/dd-trace/src/config.js
  packages/dd-trace/test/appsec/callbacks/ddwaf.spec.js
  packages/dd-trace/test/appsec/index.spec.js
  packages/dd-trace/test/appsec/reporter.spec.js
  packages/dd-trace/test/appsec/rule_manager.spec.js
  packages/dd-trace/test/config.spec.js
Labels: appsec

#2011 [ci-visibility] Fix `jest` instrumentation after latest major release
  packages/datadog-instrumentations/src/jest.js
  packages/datadog-plugin-jest/test/circus.spec.js
  packages/datadog-plugin-jest/test/env.js
Labels: ci-app
