Repository DataDog/dd-trace-js, pull requests merged in 2022-03, with the labels that each got.

#1889 feat: Use base64 encoded JSON and Binary type to avoid message being …
  packages/datadog-plugin-aws-sdk/src/services/sns.js
  packages/datadog-plugin-aws-sdk/test/sns.spec.js
Labels: bug, integrations

#1911 bump `@datadog/native-appsec` to `^0.8.2`
  package.json
Labels: appsec

#1918 [ci-visibility] Fix mocha when run in parallel mode: new plugin.
  packages/datadog-instrumentations/src/mocha.js
  packages/datadog-plugin-mocha/src/index.js
Labels: ci-app

#1927 fix require performance regression in require hook
  packages/datadog-instrumentations/src/helpers/instrument.js
  packages/datadog-plugin-mocha/test/index.spec.js
  packages/datadog-plugin-mocha/test/mocha-test-integration-http.js
  packages/datadog-plugin-mocha/test/mocha-test-integration.js
  packages/dd-trace/src/loader.js
  packages/dd-trace/src/ritm.js
Labels: bug, core

#1929 fix error on catch-all routes for next
  .gitignore
  packages/datadog-plugin-next/src/index.js
  packages/datadog-plugin-next/test/build.js
  packages/datadog-plugin-next/test/index.spec.js
  packages/datadog-plugin-next/test/next.config.js
  packages/datadog-plugin-next/test/package.json
  packages/datadog-plugin-next/test/pages/api/invalid/[...catchAll].js
  packages/datadog-plugin-next/test/server.js
Labels: bug, integrations

#1930 fix http connect/upgrade spans never finishing
  packages/datadog-instrumentations/src/http/client.js
  packages/datadog-plugin-http/test/client.spec.js
Labels: bug, integrations

#1880 [ci-visibility] CI Visibility's agentless intake
  CODEOWNERS
  ci/init.js
  ci/jest/env.js
  ext/exporters.d.ts
  ext/exporters.js
  packages/dd-trace/src/ci-visibility/exporters/agentless/index.js
  packages/dd-trace/src/ci-visibility/exporters/agentless/writer.js
  packages/dd-trace/src/encode/0.4.js
  packages/dd-trace/src/encode/agentless-ci-visibility.js
  packages/dd-trace/src/encode/tags-processors.js
  packages/dd-trace/src/exporter.js
  packages/dd-trace/src/exporters/agent/index.js
  packages/dd-trace/src/exporters/agent/request.js
  packages/dd-trace/src/exporters/agent/writer.js
  packages/dd-trace/src/exporters/common/docker.js
  packages/dd-trace/src/exporters/common/request.js
  packages/dd-trace/src/exporters/common/writer.js
  packages/dd-trace/src/exporters/scheduler.js
  packages/dd-trace/src/profiling/exporters/agent.js
  packages/dd-trace/test/ci-visibility/exporters/agentless/exporter.spec.js
  packages/dd-trace/test/ci-visibility/exporters/agentless/writer.spec.js
  packages/dd-trace/test/encode/agentless-ci-visibility.spec.js
  packages/dd-trace/test/exporters/agent/exporter.spec.js
  packages/dd-trace/test/exporters/agent/request.spec.js
  packages/dd-trace/test/exporters/agent/writer.spec.js
  packages/dd-trace/test/exporters/common/docker.spec.js
  packages/dd-trace/test/exporters/common/request.spec.js
  packages/dd-trace/test/exporters/scheduler.spec.js
  packages/dd-trace/test/profiling/exporters/agent.spec.js
Labels: ci-app

#1936 fix require hooks iterating over object prototype when instrumenting
  packages/dd-trace/src/ritm.js
Labels: bug, core

#1896 add metrics to track span lifecycle in debug mode
  packages/dd-trace/src/opentracing/span.js
Labels: enhancement, core

#1942 fix `AsyncResource.bind()` binding `this` to itself by default
  packages/datadog-instrumentations/src/helpers/instrument.js
  packages/datadog-plugin-net/test/index.spec.js
Labels: bug, core, integrations

#1934 fix mixing esm and commonjs modules and add error handling
  packages/datadog-instrumentations/src/helpers/hook.js
  packages/datadog-instrumentations/src/helpers/instrument.js
  packages/dd-trace/src/iitm.js
  packages/dd-trace/src/loader.js
  packages/dd-trace/src/ritm.js
  packages/dd-trace/test/iitm.spec.js
Labels: bug, core

#1947 fix experimental warning in next test
  packages/datadog-plugin-next/test/index.spec.js
Labels: dev/testing

#1948 fix support for loading the tracer with `mocha --require`
  ci/init.js
  packages/datadog-instrumentations/src/cucumber.js
  packages/datadog-instrumentations/src/mocha.js
Labels: bug, integrations

#1952 Update AppSec rules to v1.2.7
  packages/dd-trace/src/appsec/recommended.json
Labels: appsec
