Repository DataDog/dd-trace-js, pull requests merged in 2022-09, with the labels that each got.

#2333 Disable CI Vis Performance Test
  .circleci/config.yml
Labels: ci-app, semver-patch

#2258 Send all dependencies
  packages/dd-trace/src/iitm.js
  packages/dd-trace/src/ritm.js
  packages/dd-trace/src/telemetry/dependencies.js
  packages/dd-trace/src/telemetry/index.js
  packages/dd-trace/src/telemetry/send-data.js
  packages/dd-trace/test/iitm.spec.js
  packages/dd-trace/test/require-package-json.spec.js
  packages/dd-trace/test/telemetry/dependencies.spec.js
  packages/dd-trace/test/telemetry/index.spec.js
  packages/dd-trace/test/telemetry/send-data.spec.js
Labels: semver-patch

#2331 fix agent exporter tracing itself on retries
  packages/dd-trace/src/exporters/common/request.js
Labels: bug, semver-patch

#2166 Add client ip parsing and reporting
  LICENSE-3rdparty.csv
  docs/API.md
  docs/test.ts
  ext/tags.d.ts
  ext/tags.js
  package.json
  packages/dd-trace/src/config.js
  packages/dd-trace/src/plugin_manager.js
  packages/dd-trace/src/plugins/util/ip_blocklist.js
  packages/dd-trace/src/plugins/util/web.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/plugin_manager.spec.js
  packages/dd-trace/test/plugins/util/web.spec.js
  yarn.lock
Labels: core, semver-minor

#2273 [IAST] Detect and report weak hashing vulnerabilities
  docs/test.ts
  index.d.ts
  packages/datadog-instrumentations/src/crypto.js
  packages/datadog-instrumentations/src/helpers/hooks.js
  packages/datadog-instrumentations/src/http/server.js
  packages/datadog-plugin-http/test/server.spec.js
  packages/dd-trace/src/appsec/iast/analyzers/analyzers.js
  packages/dd-trace/src/appsec/iast/analyzers/index.js
  packages/dd-trace/src/appsec/iast/analyzers/vulnerability-analyzer.js
  packages/dd-trace/src/appsec/iast/analyzers/weak-hash-analyzer.js
  packages/dd-trace/src/appsec/iast/iast-context.js
  packages/dd-trace/src/appsec/iast/index.js
  packages/dd-trace/src/appsec/iast/overhead-controller.js
  packages/dd-trace/src/appsec/iast/path-line.js
  packages/dd-trace/src/appsec/iast/vulnerability-reporter.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/proxy.js
  packages/dd-trace/test/appsec/iast/analyzers/index.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/vulnerability-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/weak-hash-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/iast-context.spec.js
  packages/dd-trace/test/appsec/iast/index.spec.js
  packages/dd-trace/test/appsec/iast/overhead-controller.spec.js
  packages/dd-trace/test/appsec/iast/path-line.spec.js
  packages/dd-trace/test/appsec/iast/vulnerability-reporter.spec.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/proxy.spec.js
Labels: semver-patch, appsec, iast

#2332 fix mongodb error with any bson that is not an object id
  packages/datadog-plugin-mongodb-core/src/index.js
  packages/datadog-plugin-mongodb-core/test/mongodb.spec.js
Labels: bug, integrations, semver-patch

#2335 fix log injection with existing properties or non-extensible objects
  packages/datadog-plugin-winston/test/index.spec.js
  packages/dd-trace/src/plugins/log_plugin.js
Labels: bug, integrations, semver-patch

#2283 Implement trace stats
  benchmark/sirun/exporting-pipeline/index.js
  benchmark/sirun/exporting-pipeline/meta.json
  package.json
  packages/dd-trace/src/config.js
  packages/dd-trace/src/constants.js
  packages/dd-trace/src/encode/span-stats.js
  packages/dd-trace/src/exporters/agent/index.js
  packages/dd-trace/src/exporters/agent/writer.js
  packages/dd-trace/src/exporters/span-stats/index.js
  packages/dd-trace/src/exporters/span-stats/writer.js
  packages/dd-trace/src/format.js
  packages/dd-trace/src/span_processor.js
  packages/dd-trace/src/span_stats.js
  packages/dd-trace/test/encode/span-stats.spec.js
  packages/dd-trace/test/exporters/agent/exporter.spec.js
  packages/dd-trace/test/exporters/agent/writer.spec.js
  packages/dd-trace/test/exporters/span-stats/exporter.spec.js
  packages/dd-trace/test/exporters/span-stats/writer.spec.js
  packages/dd-trace/test/span_processor.spec.js
  packages/dd-trace/test/span_stats.spec.js
Labels: semver-minor

#2202 Add Support for DD_TRACE_SAMPLING_RULES
  docs/API.md
  docs/test.ts
  index.d.ts
  packages/dd-trace/src/config.js
  packages/dd-trace/src/opentracing/tracer.js
  packages/dd-trace/src/priority_sampler.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/priority_sampler.spec.js
Labels: docs, semver-patch

#2339 fix actual grpc status code being overridden by auto-cancellation
  packages/datadog-instrumentations/src/grpc/server.js
  packages/datadog-plugin-grpc/test/server.spec.js
Labels: bug, integrations, semver-patch

#2338 Update library injection system tests
  .github/workflows/system-tests.yml
Labels: semver-patch

#2340 fix k8s image publish
  .github/workflows/release-latest.yml
  .gitlab-ci.yml
  k8s/auto-inst/Dockerfile
Labels: semver-patch

#2344 Update import-in-the-middle
  package.json
  yarn.lock
Labels: bug, semver-patch

#2349 Remap sample_rate to sampleRate in DD_TRACE_SAMPLING_RULES
  packages/dd-trace/src/config.js
  packages/dd-trace/test/config.spec.js
Labels: bug, semver-patch

#2341 [ci-visibility] Improve coverage writer
  packages/datadog-plugin-jest/test/circus.spec.js
  packages/dd-trace/src/ci-visibility/exporters/agentless/coverage-writer.js
  packages/dd-trace/src/encode/coverage-ci-visibility.js
Labels: ci-app, semver-patch

#2342 Report weak cipher vulnerability
  packages/datadog-instrumentations/src/crypto.js
  packages/dd-trace/src/appsec/iast/analyzers/analyzers.js
  packages/dd-trace/src/appsec/iast/analyzers/weak-cipher-analyzer.js
  packages/dd-trace/test/appsec/iast/analyzers/weak-cipher-analyzers.spec.js
Labels: semver-patch, appsec, iast

#2350 add security email to readme
  README.md
Labels: semver-patch

#2347 Update lib injection system test branch
  .github/workflows/system-tests.yml
Labels: semver-patch

#2351 Swap IP parser library from `cidr-matcher` to `ipaddr.js`
  LICENSE-3rdparty.csv
  package.json
  packages/dd-trace/src/plugins/util/ip_blocklist.js
  yarn.lock
Labels: semver-patch

#2352 fix hash detection failure after last merge
  packages/datadog-instrumentations/src/crypto.js
  packages/dd-trace/src/appsec/iast/analyzers/weak-cipher-analyzer.js
  packages/dd-trace/test/appsec/iast/analyzers/weak-cipher-analyzers.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/weak-hash-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/utils.js
  packages/dd-trace/test/dd-trace.spec.js
Labels: semver-patch, iast

#2357 run system tests on commits to master
  .github/workflows/system-tests.yml
Labels: dev/testing, semver-patch

#2343 [ci-visibility] Update how mocha test suites are reported
  packages/datadog-instrumentations/src/mocha.js
  packages/datadog-plugin-mocha/src/index.js
  packages/datadog-plugin-mocha/test/index.spec.js
  packages/datadog-plugin-mocha/test/mocha-test-suite-level-fail-after-each.js
  packages/datadog-plugin-mocha/test/mocha-test-suite-level-fail-skip-describe.js
  packages/datadog-plugin-mocha/test/mocha-test-suite-level-fail-test.js
  packages/datadog-plugin-mocha/test/mocha-test-suite-level-pass.js
Labels: ci-app, semver-patch

#2359 Update AppSec rules to v1.4.0
  packages/dd-trace/src/appsec/recommended.json
Labels: semver-patch

#2122 [ci-visibility] Test suite visibility: support `jest`
  packages/datadog-instrumentations/src/helpers/hooks.js
  packages/datadog-instrumentations/src/jest.js
  packages/datadog-plugin-jest/src/index.js
  packages/datadog-plugin-jest/test/circus.spec.js
  packages/datadog-plugin-jest/test/jasmine2.spec.js
  packages/datadog-plugin-jest/test/jest-test-suite.js
  packages/datadog-plugin-jest/test/jest-test.js
  packages/datadog-plugin-mocha/src/index.js
  packages/dd-trace/src/encode/agentless-ci-visibility.js
  packages/dd-trace/src/plugins/index.js
Labels: ci-app, semver-minor

#2360 Set `maxSockets` instead of `maxTotalSockets`
  packages/dd-trace/src/exporters/common/request.js
  packages/dd-trace/test/exporters/common/request.spec.js
Labels: semver-patch

#2363 [ci-visibility] Fix skipping of whole `describe` clauses
  packages/datadog-instrumentations/src/mocha.js
  packages/datadog-plugin-mocha/test/index.spec.js
  packages/datadog-plugin-mocha/test/mocha-test-skip-describe.js
Labels: ci-app, semver-patch

#2345 improve vulnerabilities deduplication
  LICENSE-3rdparty.csv
  package.json
  packages/dd-trace/src/appsec/iast/vulnerability-reporter.js
  packages/dd-trace/test/appsec/iast/vulnerability-reporter.spec.js
  yarn.lock
Labels: semver-patch, iast

#2368 Remove dead code
  packages/dd-trace/src/plugins/util/redis.js
  packages/dd-trace/src/plugins/util/tx.js
  packages/dd-trace/test/plugins/util/redis.spec.js
  packages/dd-trace/test/plugins/util/tx.spec.js
Labels: semver-patch

#2369 Fix next.js page pathname
  packages/datadog-instrumentations/src/next.js
  packages/datadog-plugin-next/test/index.spec.js
Labels: bug, semver-patch

#2374 [ci-visibility] Do not reset coverage counters and report suite coverage
  packages/datadog-instrumentations/src/jest.js
  packages/datadog-plugin-jest/src/index.js
  packages/datadog-plugin-jest/test/circus.spec.js
  packages/dd-trace/src/ci-visibility/exporters/agentless/index.js
  packages/dd-trace/test/ci-visibility/exporters/agentless/exporter.spec.js
Labels: ci-app, semver-patch

#2375 update iitm
  package.json
  yarn.lock
Labels: semver-patch

#2361 Ensure spans are truncated when encoded
  benchmark/sirun/exporting-pipeline/index.js
  packages/dd-trace/src/encode/0.4.js
  packages/dd-trace/src/encode/0.5.js
  packages/dd-trace/test/encode/0.4.spec.js
  packages/dd-trace/test/encode/0.5.spec.js
Labels: semver-minor, performance

#2376 Fix IP blocklist polyfill
  packages/dd-trace/src/plugins/util/ip_blocklist.js
Labels: semver-patch

#2379 Bump native-metrics version
  package.json
  yarn.lock
Labels: bug, semver-patch

#2383 Update querystring obfuscation regex
  packages/dd-trace/src/config.js
  packages/dd-trace/test/config.spec.js
Labels: semver-patch

#2378 Remove proxyquire references to not iast modules from iast test
  packages/dd-trace/src/appsec/iast/analyzers/vulnerability-analyzer.js
  packages/dd-trace/src/appsec/iast/index.js
  packages/dd-trace/src/appsec/iast/path-line.js
  packages/dd-trace/test/appsec/iast/analyzers/vulnerability-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/index.spec.js
  packages/dd-trace/test/appsec/iast/overhead-controller.spec.js
  packages/dd-trace/test/appsec/iast/utils.js
  packages/dd-trace/test/plugins/agent.js
Labels: semver-patch, iast

#2386 tracking open spans
  packages/dd-trace/src/opentracing/span.js
Labels: semver-patch

#2364 Revert "Disable CI Vis Performance Test (#2333)"
  .circleci/config.yml
Labels: ci-app, semver-patch

#2389 update import-in-the-middle 1.3.3 -> 1.3.4
  package.json
  yarn.lock
Labels: semver-patch

#2402 support custom heartbeat rate
  packages/dd-trace/src/telemetry/index.js
  packages/dd-trace/test/telemetry/index.spec.js
Labels: semver-patch

#2377 [ci-visibility] Test skipping for `jest`
  packages/datadog-instrumentations/src/jest.js
  packages/datadog-plugin-jest/src/index.js
  packages/datadog-plugin-jest/test/circus.spec.js
  packages/datadog-plugin-jest/test/jest-itr-pass.js
  packages/datadog-plugin-jest/test/jest-itr-skip.js
  packages/dd-trace/src/ci-visibility/intelligent-test-runner/get-skippable-suites.js
  packages/dd-trace/src/encode/coverage-ci-visibility.js
  packages/dd-trace/src/plugin_manager.js
  packages/dd-trace/src/plugins/util/test.js
  packages/dd-trace/src/proxy.js
Labels: do-not-merge/WIP, ci-app, semver-minor

#2406 fix possible race condition in redis error test
  packages/datadog-plugin-redis/test/legacy.spec.js
Labels: dev/testing, semver-patch

#2393 Fix flaky test in iast overhead controller
  packages/dd-trace/test/appsec/iast/overhead-controller.spec.js
Labels: semver-patch, iast

#2396 fix distributed tracing for rhea externally encoded messages
  packages/datadog-instrumentations/src/rhea.js
  packages/datadog-plugin-rhea/src/index.js
  packages/datadog-plugin-rhea/test/index.spec.js
Labels: bug, integrations, semver-patch

#2373 add tracing base plugins and refactor database plugins
  benchmark/stubs/span.js
  package.json
  packages/datadog-instrumentations/src/cassandra-driver.js
  packages/datadog-instrumentations/src/memcached.js
  packages/datadog-instrumentations/src/oracledb.js
  packages/datadog-plugin-cassandra-driver/src/index.js
  packages/datadog-plugin-elasticsearch/src/index.js
  packages/datadog-plugin-memcached/src/index.js
  packages/datadog-plugin-mongodb-core/src/index.js
  packages/datadog-plugin-mysql/src/index.js
  packages/datadog-plugin-mysql2/src/index.js
  packages/datadog-plugin-oracledb/src/index.js
  packages/datadog-plugin-pg/src/index.js
  packages/datadog-plugin-redis/src/index.js
  packages/datadog-plugin-tedious/src/index.js
  packages/dd-trace/src/plugins/cache.js
  packages/dd-trace/src/plugins/client.js
  packages/dd-trace/src/plugins/database.js
  packages/dd-trace/src/plugins/outgoing.js
  packages/dd-trace/src/plugins/plugin.js
  packages/dd-trace/src/plugins/storage.js
  packages/dd-trace/src/plugins/tracing.js
  packages/dd-trace/test/.eslintrc.json
  yarn.lock
Labels: semver-patch

#2408 [ci-visibility] Do not fail process when packfile generation fails or git is missing
  packages/dd-trace/src/ci-visibility/exporters/git/git_metadata.js
  packages/dd-trace/src/plugins/util/git.js
  packages/dd-trace/test/ci-visibility/exporters/git/git_metadata.spec.js
Labels: ci-app, semver-patch

#2407 [ci-visibility] Add query to configuration API for intelligent test runner
  packages/datadog-instrumentations/src/jest.js
  packages/datadog-plugin-jest/src/index.js
  packages/datadog-plugin-jest/test/circus.spec.js
  packages/dd-trace/src/ci-visibility/intelligent-test-runner/get-itr-configuration.js
Labels: ci-app, semver-minor

#2419 [ci-visibility] Fix bug when creating git pack files
  packages/dd-trace/src/plugins/util/git.js
  packages/dd-trace/test/plugins/util/git.spec.js
Labels: bug, ci-app, semver-patch
