Repository DataDog/dd-trace-js, pull requests merged in 2022-07, with the labels that each got.

#2158 feat: specs for disabling DD_TELEMETRY_ENABLED if AWS_LAMBDA_FUNCTION…
  packages/dd-trace/test/config.spec.js
Labels: semver-patch, serverless

#2165 bump native appsec to 1.2.1
  package.json
Labels: semver-patch

#2142 rewrite next integration with the new plugin system
  packages/datadog-instrumentations/index.js
  packages/datadog-instrumentations/src/next.js
  packages/datadog-plugin-next/src/index.js
  packages/datadog-plugin-next/test/index.spec.js
Labels: integrations, semver-patch

#2168 Disable telemetry if agentless is being used
  packages/dd-trace/src/config.js
Labels: ci-app, semver-patch

#2130 Report querystring by default and add query string obfuscator
  benchmark/sirun/plugin-http/client.js
  benchmark/sirun/plugin-http/meta.json
  docs/API.md
  packages/datadog-plugin-http2/src/server.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/plugin_manager.js
  packages/dd-trace/src/plugins/util/web.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/plugin_manager.spec.js
  packages/dd-trace/test/plugins/util/web.spec.js
Labels: core, semver-major, appsec

#2140 remove deprecated methods for the next major
  packages/dd-trace/src/noop/tracer.js
  packages/dd-trace/src/proxy.js
  packages/dd-trace/src/tracer.js
  packages/dd-trace/test/noop.spec.js
  packages/dd-trace/test/plugins/agent.js
  packages/dd-trace/test/proxy.spec.js
Labels: breaking-change, core, semver-major

#2171 fix koa plugin repeating route with multiple middleware
  packages/datadog-instrumentations/src/connect.js
  packages/datadog-instrumentations/src/koa.js
  packages/datadog-instrumentations/src/router.js
  packages/datadog-plugin-koa/test/index.spec.js
  packages/datadog-plugin-router/src/index.js
  yarn.lock
Labels: bug, integrations, semver-patch

#2176 rewrite grpc integration with the new plugin system
  packages/datadog-instrumentations/index.js
  packages/datadog-instrumentations/src/grpc.js
  packages/datadog-instrumentations/src/grpc/client.js
  packages/datadog-instrumentations/src/grpc/server.js
  packages/datadog-instrumentations/src/grpc/types.js
  packages/datadog-plugin-grpc/src/client.js
  packages/datadog-plugin-grpc/src/index.js
  packages/datadog-plugin-grpc/src/server.js
  packages/datadog-plugin-grpc/test/client.spec.js
  packages/datadog-plugin-grpc/test/server.spec.js
Labels: integrations, semver-patch

#2177 rewrite http2 integration with new plugin system
  packages/datadog-instrumentations/index.js
  packages/datadog-instrumentations/src/fastify.js
  packages/datadog-instrumentations/src/http2.js
  packages/datadog-instrumentations/src/http2/client.js
  packages/datadog-instrumentations/src/http2/server.js
  packages/datadog-plugin-http2/src/client.js
  packages/datadog-plugin-http2/src/index.js
  packages/datadog-plugin-http2/src/server.js
  packages/datadog-plugin-http2/test/client.spec.js
  packages/datadog-plugin-http2/test/server.spec.js
  packages/dd-trace/src/plugins/plugin.js
  packages/dd-trace/src/plugins/util/web.js
Labels: integrations, semver-patch

#2184 remove grpc client service suffix and rename spans
  packages/datadog-plugin-grpc/src/client.js
  packages/datadog-plugin-grpc/src/server.js
  packages/datadog-plugin-grpc/test/client.spec.js
  packages/datadog-plugin-grpc/test/server.spec.js
Labels: breaking-change, integrations, semver-major

#2136 remove http client service name suffix and rename server service
  integration-tests/esm.spec.js
  integration-tests/startup.spec.js
  packages/datadog-plugin-http/src/client.js
  packages/datadog-plugin-http/src/server.js
  packages/datadog-plugin-http/test/client.spec.js
  packages/datadog-plugin-http/test/server.spec.js
  packages/datadog-plugin-http2/src/client.js
  packages/datadog-plugin-http2/test/client.spec.js
  packages/datadog-plugin-router/test/index.spec.js
Labels: integrations, semver-major

#2139 remove event emitter binding from scope manager
  packages/dd-trace/src/scope.js
  packages/dd-trace/test/scope.spec.js
Labels: breaking-change, core, semver-major

#2169 [GraphQL] Path Checking Performance Fix
  benchmark/sirun/plugin-graphql/index.js
  benchmark/sirun/plugin-graphql/meta.json
  packages/datadog-instrumentations/src/graphql.js
  packages/datadog-plugin-graphql/src/resolve.js
Labels: semver-patch, performance

#2172 [ci-visibility] Support `mocha` test suites
  packages/datadog-instrumentations/src/mocha.js
  packages/datadog-plugin-mocha/src/index.js
  packages/datadog-plugin-mocha/test/index.spec.js
  packages/datadog-plugin-mocha/test/mocha-test-suite-level-2.js
  packages/datadog-plugin-mocha/test/mocha-test-suite-level.js
  packages/dd-trace/src/encode/agentless-ci-visibility.js
  packages/dd-trace/src/plugin_manager.js
  packages/dd-trace/src/plugins/util/test.js
Labels: ci-app, semver-minor

#2180 Update typescript definition to prevent experimental:true property
  index.d.ts
Labels: semver-patch

#2044 add cpu profiler support
  packages/datadog-core/src/storage/async_hooks.js
  packages/datadog-core/src/storage/async_resource.js
  packages/dd-trace/src/profiling/config.js
  packages/dd-trace/src/profiling/index.js
  packages/dd-trace/src/profiling/profiler.js
  packages/dd-trace/src/profiling/profilers/cpu.js
  packages/dd-trace/test/profiling/config.spec.js
  packages/dd-trace/test/profiling/profiler.spec.js
  packages/dd-trace/test/profiling/profilers/cpu.spec.js
Labels: profiling, semver-minor

#2197 fix http plugins calling res.end multiple times
  packages/datadog-plugin-http/src/server.js
  packages/datadog-plugin-http/test/server.spec.js
  packages/dd-trace/src/plugins/util/web.js
Labels: bug, integrations, semver-patch

#2200 Put profile endpoint collection behind a config option
  package.json
  packages/dd-trace/src/profiling/config.js
  packages/dd-trace/src/profiling/profilers/cpu.js
  packages/dd-trace/test/profiling/profilers/cpu.spec.js
  yarn.lock
Labels: profiling, semver-minor

#2199 fix tedious 15 tests failing because node 12 is no longer supported
  .github/workflows/plugins.yml
Labels: dev/testing, semver-patch

#2185 Couchbase NodeJS SDK v3 and v4 Support
  .github/workflows/plugins.yml
  docker-compose.yml
  packages/datadog-instrumentations/src/couchbase.js
  packages/datadog-plugin-couchbase/src/index.js
  packages/datadog-plugin-couchbase/test/index.spec.js
Labels: integrations, semver-patch

#2210 docs: fix reference to mysql2 upstream
  index.d.ts
Labels: docs, semver-patch

#2212 fix ci visibility tests for codeowners using the wrong team for the project
  packages/datadog-plugin-jest/test/circus.spec.js
  packages/datadog-plugin-jest/test/jasmine2.spec.js
  packages/datadog-plugin-mocha/test/index.spec.js
  packages/dd-trace/test/plugins/util/__test__/CODEOWNERS
  packages/dd-trace/test/plugins/util/test.spec.js
Labels: dev/testing, ci-app, semver-patch

#2207 [ci-visibility] Remove require.cache hack in `ci/init`
  ci/init.js
  ci/jest/env.js
Labels: ci-app, semver-major

#2217 remove form-data dependency
  LICENSE-3rdparty.csv
  package.json
  packages/dd-trace/src/profiling/exporters/agent.js
  packages/dd-trace/src/profiling/exporters/form-data.js
  packages/dd-trace/test/profiling/profiler.spec.js
  yarn.lock
Labels: profiling, semver-patch

#2219 Add tests for form-data encoder
  packages/dd-trace/src/profiling/exporters/form-data.js
  packages/dd-trace/test/profiling/exporters/form-data.spec.js
Labels: profiling, semver-patch

#2194 fix integration tests not erroring when the child process exits
  integration-tests/esm.spec.js
  integration-tests/helpers.js
Labels: dev/testing, semver-patch

#2209 fix calling use before init enabling plugins when tracer is disabled
  packages/dd-trace/src/plugin_manager.js
  packages/dd-trace/test/plugin_manager.spec.js
Labels: bug, core, integrations, semver-patch

#2211 fix graphql execute and resolve spans always flagged as errors
  packages/datadog-instrumentations/src/graphql.js
  packages/datadog-plugin-graphql/src/resolve.js
  packages/datadog-plugin-graphql/test/index.spec.js
Labels: bug, integrations, semver-patch

#2214 fix possible disconnected middleware spans for web frameworks
  packages/datadog-plugin-express/test/index.spec.js
  packages/datadog-plugin-router/src/index.js
Labels: bug, integrations, semver-patch

#2216 fix middleware errors not being also set on the request
  packages/datadog-plugin-connect/test/index.spec.js
  packages/datadog-plugin-express/test/index.spec.js
  packages/datadog-plugin-http/src/server.js
  packages/datadog-plugin-router/src/index.js
  packages/dd-trace/src/plugins/util/web.js
  packages/dd-trace/test/plugins/util/web.spec.js
Labels: bug, integrations, semver-patch

#2193 update import-in-the-middle to 1.2.3
  package.json
  yarn.lock
Labels: semver-patch

#2220 fix all express spans nested under first middleware span
  packages/datadog-plugin-express/test/index.spec.js
  packages/datadog-plugin-router/src/index.js
Labels: bug, integrations, semver-patch

#2173 Method to get first non Datadog file and line
  packages/dd-trace/src/appsec/iast/path-line.js
  packages/dd-trace/test/appsec/iast/path-line.spec.js
Labels: semver-patch, appsec

#2227 [ci-visibility] Fix `mocha` wrong status calculation
  packages/datadog-instrumentations/src/mocha.js
  packages/datadog-plugin-mocha/test/index.spec.js
  packages/datadog-plugin-mocha/test/mocha-fail-hook-async.js
Labels: ci-app, semver-patch

#2205 Report vulnerabilities
  packages/dd-trace/src/appsec/iast/index.js
  packages/dd-trace/src/appsec/iast/vulnerability-reporter.js
  packages/dd-trace/test/appsec/iast/index.spec.js
  packages/dd-trace/test/appsec/iast/vulnerability-reporter.spec.js
Labels: semver-patch, appsec

#2228 fix next default resource being static value instead of http method
  packages/datadog-plugin-next/src/index.js
  packages/datadog-plugin-next/test/index.spec.js
  packages/datadog-plugin-next/test/public/test.txt
Labels: bug, integrations, semver-patch, next

#2230 upgrade iitm and native metrics dependencies
  package.json
  yarn.lock
Labels: semver-patch, dependencies

#2232 fix metrics init test timing out on windows
  packages/dd-trace/test/metrics.spec.js
Labels: dev/testing, semver-patch

#2240 fix middleware error causing exception without an active http span
  packages/datadog-instrumentations/src/connect.js
  packages/datadog-instrumentations/src/fastify.js
  packages/datadog-instrumentations/src/koa.js
  packages/datadog-instrumentations/src/router.js
  packages/datadog-plugin-express/test/index.spec.js
  packages/datadog-plugin-fastify/test/index.spec.js
  packages/datadog-plugin-koa/test/index.spec.js
  packages/datadog-plugin-router/src/index.js
  packages/datadog-plugin-router/test/index.spec.js
  packages/dd-trace/src/plugins/util/web.js
Labels: bug, integrations, semver-patch
