Repository DataDog/dd-trace-js, pull requests merged in 2022-01, with the labels that each got.

#1706 [ci-visibility] Link CI Visibility and RUM
  packages/datadog-plugin-cypress/src/plugin.js
  packages/datadog-plugin-cypress/src/support.js
  packages/datadog-plugin-cypress/test/app/app-server.js
  packages/datadog-plugin-cypress/test/index.spec.js
  packages/dd-trace/src/plugins/util/test.js
Labels: ci-app

#1744 Fix empty retries from profile exporter
  packages/dd-trace/src/profiling/exporters/agent.js
  packages/dd-trace/test/profiling/exporters/agent.spec.js
Labels: profiling

#1725 [ci-visibility] Add Performance Overhead Check
  .circleci/config.yml
  benchmark/e2e-ci/benchmark-run.js
  package.json
Labels: ci-app

#1745 fix loopback tests unable to install the module
  packages/dd-trace/test/plugins/externals.json
Labels: dev/testing

#1746 increase cypress test timeout
  packages/datadog-plugin-cypress/test/index.spec.js
Labels: dev/testing

#1730 [ci-visibility] Use `config` to get Service Name for Testing Instrumentations
  docs/test.ts
  index.d.ts
  packages/datadog-plugin-cucumber/src/index.js
  packages/datadog-plugin-jest/src/jest-environment.js
  packages/datadog-plugin-jest/src/jest-jasmine2.js
  packages/datadog-plugin-jest/test/circus.spec.js
  packages/datadog-plugin-jest/test/jasmine2.spec.js
  packages/datadog-plugin-mocha/src/index.js
  packages/dd-trace/src/plugins/util/test.js
  packages/dd-trace/test/plugins/util/test-environment.spec.js
Labels: ci-app

#1753 codeql ignore test directories
  .github/codeql_config.yml
  .github/workflows/codeql-analysis.yml
Labels: dev/testing

#1751 Migrate mysql to new plugin system
  packages/datadog-instrumentations/index.js
  packages/datadog-instrumentations/src/mysql.js
  packages/datadog-plugin-mysql/src/index.js
  packages/datadog-plugin-mysql/test/index.spec.js
Labels: integrations

#1757 [ci-visibility] Fix mocha when run in `parallel` mode
  packages/datadog-plugin-mocha/src/index.js
Labels: ci-app

#1759 add cypress 'dd:addTags' command
  packages/datadog-plugin-cypress/src/plugin.js
  packages/datadog-plugin-cypress/test/app/cypress/integration/integration-test.js
  packages/datadog-plugin-cypress/test/index.spec.js
Labels: ci-app

#1462 AppSec Beta
  .circleci/config.yml
  LICENSE-3rdparty.csv
  benchmark/sirun/appsec/README.md
  benchmark/sirun/appsec/client.js
  benchmark/sirun/appsec/common.js
  benchmark/sirun/appsec/meta.json
  benchmark/sirun/appsec/server.js
  package.json
  packages/datadog-plugin-http/src/server.js
  packages/datadog-plugin-http/test/server.spec.js
  packages/dd-trace/src/appsec/addresses.js
  packages/dd-trace/src/appsec/callbacks/ddwaf.js
  packages/dd-trace/src/appsec/callbacks/index.js
  packages/dd-trace/src/appsec/gateway/als.js
  packages/dd-trace/src/appsec/gateway/channels.js
  packages/dd-trace/src/appsec/gateway/engine/engine.js
  packages/dd-trace/src/appsec/gateway/engine/index.js
  packages/dd-trace/src/appsec/gateway/engine/runner.js
  packages/dd-trace/src/appsec/index.js
  packages/dd-trace/src/appsec/recommended.json
  packages/dd-trace/src/appsec/reporter.js
  packages/dd-trace/src/appsec/rule_manager.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/plugins/util/web.js
  packages/dd-trace/src/startup-log.js
  packages/dd-trace/test/appsec/callbacks/ddwaf.spec.js
  packages/dd-trace/test/appsec/gateway/engine/engine.spec.js
  packages/dd-trace/test/appsec/gateway/engine/index.spec.js
  packages/dd-trace/test/appsec/gateway/engine/runner.spec.js
  packages/dd-trace/test/appsec/index.spec.js
  packages/dd-trace/test/appsec/reporter.spec.js
  packages/dd-trace/test/appsec/rule_manager.spec.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/plugins/util/web.spec.js
  packages/dd-trace/test/startup-log.spec.js
Labels: appsec

#1767 fix express integration losing the route when handled in a middlware
  packages/datadog-plugin-express/test/index.spec.js
  packages/datadog-plugin-router/src/index.js
Labels: bug, integrations

#1773 Appsec config cleanup
  docs/API.md
  packages/dd-trace/src/config.js
  packages/dd-trace/test/config.spec.js
Labels: appsec

#1770 update codeql config to ignore folders only used in dev
  .github/codeql_config.yml
Labels: dev/tooling

#1777 remove support for enabling internal errors
  docs/test.ts
  index.d.ts
  packages/dd-trace/src/config.js
  packages/dd-trace/src/format.js
  packages/dd-trace/src/opentracing/tracer.js
  packages/dd-trace/test/config.spec.js
Labels: breaking-change, core, semver-major

#1754 add test for calling res.end and next for express
  packages/datadog-plugin-express/test/index.spec.js
Labels: dev/testing, integrations

#1598 add support for moleculer
  .circleci/config.yml
  docs/API.md
  docs/test.ts
  index.d.ts
  packages/datadog-plugin-moleculer/src/client.js
  packages/datadog-plugin-moleculer/src/index.js
  packages/datadog-plugin-moleculer/src/server.js
  packages/datadog-plugin-moleculer/src/util.js
  packages/datadog-plugin-moleculer/test/index.spec.js
  packages/dd-trace/src/plugins/index.js
  packages/dd-trace/test/plugins/externals.json
Labels: enhancement, integrations, semver-minor

#1755 remove client sampling
  benchmark/sirun/exporting-pipeline/index.js
  benchmark/stubs/span.js
  docs/API.md
  index.d.ts
  node-upstream-tests/node/run_tests.js
  packages/datadog-plugin-dns/test/index.spec.js
  packages/datadog-plugin-fs/src/index.js
  packages/datadog-plugin-http/src/client.js
  packages/datadog-plugin-http/test/client.spec.js
  packages/datadog-plugin-http2/src/client.js
  packages/datadog-plugin-http2/src/server.js
  packages/datadog-plugin-http2/test/server.spec.js
  packages/datadog-plugin-net/src/index.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/constants.js
  packages/dd-trace/src/exporters/agent/request.js
  packages/dd-trace/src/log.js
  packages/dd-trace/src/noop/span_context.js
  packages/dd-trace/src/opentracing/propagation/text_map.js
  packages/dd-trace/src/opentracing/span.js
  packages/dd-trace/src/opentracing/span_context.js
  packages/dd-trace/src/opentracing/tracer.js
  packages/dd-trace/src/plugins/plugin.js
  packages/dd-trace/src/plugins/util/test.js
  packages/dd-trace/src/plugins/util/web.js
  packages/dd-trace/src/span_processor.js
  packages/dd-trace/src/tracer.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/log.spec.js
  packages/dd-trace/test/opentracing/propagation/text_map.spec.js
  packages/dd-trace/test/opentracing/span.spec.js
  packages/dd-trace/test/opentracing/span_context.spec.js
  packages/dd-trace/test/opentracing/tracer.spec.js
  packages/dd-trace/test/plugins/util/web.spec.js
  packages/dd-trace/test/span_processor.spec.js
  packages/dd-trace/test/tracer.spec.js
Labels: core

#1778 remove support for nested object tags
  packages/datadog-plugin-cypress/src/plugin.js
  packages/dd-trace/src/format.js
  packages/dd-trace/test/format.spec.js
Labels: breaking-change, core

#1779 remove deprecated options and apis
  docs/API.md
  packages/dd-trace/src/config.js
  packages/dd-trace/src/noop/tracer.js
  packages/dd-trace/src/proxy.js
  packages/dd-trace/src/scope/noop/scope_manager.js
  packages/dd-trace/src/tracer.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/leak/scope_manager.js
  packages/dd-trace/test/proxy.spec.js
  packages/dd-trace/test/scope/scope_manager.spec.js
Labels: breaking-change, core

#1780 add option to enable or disable only tracing
  docs/API.md
  packages/dd-trace/src/config.js
  packages/dd-trace/src/proxy.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/proxy.spec.js
Labels: breaking-change, core

#1781 update @datadog/native-appsec to 0.8.0
  package.json
Labels: appsec

#1775 Appsec express support
  packages/dd-trace/src/appsec/addresses.js
  packages/dd-trace/src/appsec/index.js
  packages/dd-trace/src/appsec/reporter.js
  packages/dd-trace/test/appsec/index.spec.js
  packages/dd-trace/test/appsec/reporter.spec.js
Labels: appsec

#1783 Appsec waf optimization
  packages/dd-trace/src/appsec/index.js
  packages/dd-trace/src/appsec/reporter.js
  packages/dd-trace/test/appsec/index.spec.js
  packages/dd-trace/test/appsec/reporter.spec.js
Labels: appsec

#1733 fix(pino): support module exports for pino version >= 6.8.0
  packages/datadog-plugin-pino/src/index.js
  packages/datadog-plugin-pino/test/index.spec.js
Labels: bug, integrations

#1786 AppSec Rate Limit
  packages/dd-trace/src/appsec/index.js
  packages/dd-trace/src/appsec/reporter.js
  packages/dd-trace/src/config.js
  packages/dd-trace/test/appsec/index.spec.js
  packages/dd-trace/test/appsec/reporter.spec.js
  packages/dd-trace/test/config.spec.js
Labels: appsec

#1792 Setup system tests in CI
  .github/workflows/system-tests.yml
Labels: dev/testing, dev/tooling

#1791 update rules file to v1.2.5
  packages/dd-trace/src/appsec/recommended.json
Labels: appsec

#1787 add migration guide for 1.0 to 2.0
  .npmignore
  MIGRATING.md
Labels: docs
