Repository DataDog/dd-trace-js, pull requests merged in 2022-06, with the labels that each got.

#2097 [ci-visibility] Increase expectation callback's timeout for `jest` tests
  packages/datadog-plugin-jest/test/circus.spec.js
Labels: ci-app, semver-patch

#2098 fix amqplib upstream tests failing due to missing tag for release
  packages/datadog-plugin-amqplib/test/suite.js
Labels: dev/testing, integrations, semver-patch

#2099 fix aws-sdk complete event running in wrong async context
  docker-compose.yml
  packages/datadog-instrumentations/src/aws-sdk.js
  packages/datadog-plugin-aws-sdk/test/aws-sdk.spec.js
  packages/datadog-plugin-aws-sdk/test/lambda.spec.js
  packages/datadog-plugin-aws-sdk/test/sqs.spec.js
  packages/dd-trace/test/setup/services/localstack.js
Labels: bug, integrations, semver-patch

#2100 fix pino tests failing with version 8
  .github/workflows/plugins.yml
  packages/datadog-plugin-pino/test/index.spec.js
  packages/dd-trace/test/plugins/externals.json
  scripts/install_plugin_modules.js
Labels: dev/testing, integrations, semver-patch

#2101 [ci-visibility] Fix initialization of agentless via `DD_CIVISIBILITY_AGENTLESS_ENABLED`
  ci/init.js
  ci/jest/env.js
Labels: ci-app, semver-patch

#2102 [ci-visibility] Fix Cypress tests
  packages/datadog-plugin-cypress/test/app-10/CODEOWNERS
  packages/datadog-plugin-cypress/test/app-10/app-server.js
  packages/datadog-plugin-cypress/test/app-10/cypress.config.js
  packages/datadog-plugin-cypress/test/app-10/cypress/integration/integration-test.js
  packages/datadog-plugin-cypress/test/app-10/cypress/plugins/index.js
  packages/datadog-plugin-cypress/test/app-10/cypress/support/index.js
  packages/datadog-plugin-cypress/test/index.spec.js
Labels: ci-app, semver-patch

#2110 fix error when the execution async resource is undefined
  packages/datadog-core/src/storage/async_resource.js
Labels: semver-patch

#2107 fix fastify plugin breaking user-defined async stores
  packages/datadog-instrumentations/src/fastify.js
  packages/datadog-plugin-fastify/test/index.spec.js
Labels: bug, integrations, semver-patch

#2114 fix support for fastify 4
  .github/workflows/plugins.yml
  packages/datadog-instrumentations/src/fastify.js
  packages/datadog-plugin-fastify/test/index.spec.js
Labels: bug, integrations, semver-patch

#2104 [ci-visibility] Remove old `cypress` folder
  cypress/plugin.js
  cypress/support.js
Labels: breaking-change, ci-app, semver-major

#2128 bump pprof to 0.5.0
  package.json
  yarn.lock
Labels: semver-patch

#2121 Rewrite GraphQL with the new plugin system
  packages/datadog-instrumentations/index.js
  packages/datadog-instrumentations/src/graphql.js
  packages/datadog-plugin-graphql/src/index.js
  packages/datadog-plugin-graphql/test/index.spec.js
Labels: integrations, semver-patch

#2133 [GraphQL] Separating resolve subscribers in plugin
  packages/datadog-instrumentations/src/graphql.js
  packages/datadog-plugin-graphql/src/index.js
  packages/datadog-plugin-graphql/src/resolve.js
Labels: integrations, semver-patch

#2126 [ci-visibility] Add `test.source.file` as the path where the test is defined
  packages/datadog-plugin-cucumber/test/index.spec.js
  packages/datadog-plugin-cypress/test/index.spec.js
  packages/datadog-plugin-jest/test/circus.spec.js
  packages/datadog-plugin-jest/test/jasmine2.spec.js
  packages/datadog-plugin-mocha/test/index.spec.js
  packages/dd-trace/src/plugins/util/test.js
Labels: ci-app, semver-minor

#2132 fix http client spans marked as errors for requests without a response
  packages/datadog-instrumentations/src/http/client.js
  packages/datadog-plugin-http/src/client.js
  packages/datadog-plugin-http/test/client.spec.js
Labels: bug, integrations, semver-patch

#2138 remove version file and use package.json directly instead
  packages/dd-trace/lib/version.js
  packages/dd-trace/src/exporters/agent/writer.js
  packages/dd-trace/src/profiling/exporters/agent.js
  packages/dd-trace/src/startup-log.js
  packages/dd-trace/src/telemetry.js
  packages/dd-trace/test/exporters/agent/writer.spec.js
  packages/dd-trace/test/profiling/exporters/agent.spec.js
  packages/dd-trace/test/startup-log.spec.js
Labels: core, semver-patch

#2146 bump sketches to 1.0.5
  package.json
  yarn.lock
Labels: semver-patch

#2147 bump multer dev dependency to 1.4.5
  package.json
  yarn.lock
Labels: semver-patch

#2150 increase profile export test timeout
  packages/dd-trace/test/profiling/exporters/agent.spec.js
Labels: dev/testing, profiling, semver-patch

#2152 feat: Don't enable DD_TRACE_TELEMETRY API in Lambda, unless env is set
  packages/dd-trace/src/config.js
Labels: bug, semver-patch

#2153 bump native addons to support linux arm32
  package.json
  yarn.lock
Labels: semver-patch
