Repository DataDog/dd-trace-js, pull requests merged in 2022-05, with the labels that each got.

#1974 Move `build` workflow from CircleCI to GitHub Actions
  .circleci/config.yml
  .github/actions/node/12/action.yml
  .github/actions/node/14/action.yml
  .github/actions/node/16/action.yml
  .github/actions/node/17/action.yml
  .github/actions/node/latest/action.yml
  .github/actions/node/oldest/action.yml
  .github/actions/node/setup/action.yml
  .github/workflows/core.yml
  .github/workflows/plugins.yml
  .github/workflows/profiling.yml
  .github/workflows/project.yml
  .github/workflows/tracing.yml
  .gitignore
  .nycrc
  LICENSE-3rdparty.csv
  docs/yarn.lock
  mocha-reporter-config.json
  package.json
  packages/datadog-instrumentations/src/pg.js
  packages/datadog-plugin-amqplib/test/suite.js
  packages/datadog-plugin-knex/test/index.spec.js
  packages/datadog-plugin-net/test/index.spec.js
  packages/datadog-plugin-oracledb/test/index.spec.js
  packages/dd-trace/test/plugins/externals.json
  packages/dd-trace/test/plugins/suite.js
  packages/dd-trace/test/setup/services/oracledb.js
  yarn.lock
Labels: dev/tooling

#2025 require semver labels
  .github/workflows/pr-labels.yml
Labels: semver-patch

#2019 Add duration_ext metric
  packages/dd-trace/src/appsec/callbacks/ddwaf.js
  packages/dd-trace/src/appsec/reporter.js
  packages/dd-trace/test/appsec/callbacks/ddwaf.spec.js
  packages/dd-trace/test/appsec/reporter.spec.js
Labels: appsec, semver-minor

#2024 migrate oracledb to new plugin system
  packages/datadog-instrumentations/index.js
  packages/datadog-instrumentations/src/oracledb.js
  packages/datadog-plugin-oracledb/src/index.js
  packages/datadog-plugin-oracledb/test/index.spec.js
Labels: semver-patch

#2021 remove postpublish script
  package.json
  scripts/postpublish.js
Labels: semver-patch

#2018 metrics are supposed to be microseconds
  packages/dd-trace/src/appsec/callbacks/ddwaf.js
  packages/dd-trace/test/appsec/callbacks/ddwaf.spec.js
Labels: semver-patch, appsec

#1995 rewrite express and router plugins with new plugin system
  packages/datadog-instrumentations/index.js
  packages/datadog-instrumentations/src/express.js
  packages/datadog-instrumentations/src/http/server.js
  packages/datadog-instrumentations/src/router.js
  packages/datadog-plugin-express/src/index.js
  packages/datadog-plugin-express/test/index.spec.js
  packages/datadog-plugin-http/src/server.js
  packages/datadog-plugin-redis/test/legacy.spec.js
  packages/datadog-plugin-router/src/index.js
  packages/datadog-plugin-router/test/index.spec.js
  packages/datadog-plugin-web/src/index.js
  packages/dd-trace/src/plugins/plugin.js
  packages/dd-trace/src/plugins/util/web.js
  packages/dd-trace/test/plugins/agent.js
  packages/dd-trace/test/plugins/util/web.spec.js
Labels: integrations

#1926 convert google-cloud-pubsub plugin to new system
  packages/datadog-instrumentations/index.js
  packages/datadog-instrumentations/src/google-cloud-pubsub.js
  packages/datadog-plugin-google-cloud-pubsub/src/index.js
  packages/datadog-plugin-google-cloud-pubsub/test/index.spec.js
Labels: semver-patch

#1921 migrate kafkajs to new plugin system
  packages/datadog-instrumentations/index.js
  packages/datadog-instrumentations/src/kafkajs.js
  packages/datadog-plugin-kafkajs/src/index.js
  packages/datadog-plugin-kafkajs/test/index.spec.js
Labels: semver-patch

#2029 fix express recording urls in blocklist
  packages/datadog-plugin-express/test/index.spec.js
  packages/datadog-plugin-kafkajs/test/index.spec.js
  packages/dd-trace/src/plugins/util/web.js
Labels: bug, integrations, semver-patch

#2020 Fix http server async-end when context doesn't have response
  packages/datadog-plugin-http/src/server.js
Labels: bug, community, integrations, semver-patch

#2027 Correct profiler naming
  benchmark/sirun/goal.json
  benchmark/sirun/profiler/index.js
  benchmark/sirun/profiler/meta.json
  packages/dd-trace/src/profiling/config.js
  packages/dd-trace/src/profiling/index.js
  packages/dd-trace/src/profiling/profilers/space.js
  packages/dd-trace/src/profiling/profilers/wall.js
  packages/dd-trace/test/profiling/config.spec.js
  packages/dd-trace/test/profiling/exporters/agent.spec.js
  packages/dd-trace/test/profiling/profiler.spec.js
  packages/dd-trace/test/profiling/profilers/space.spec.js
  packages/dd-trace/test/profiling/profilers/wall.spec.js
Labels: profiling, semver-patch

#2031 fix address tag for dns lookups with `all` option
  packages/datadog-plugin-dns/src/index.js
  packages/datadog-plugin-dns/test/index.spec.js
Labels: bug, integrations, semver-patch

#2032 rewrite connect plugin with new plugin system
  packages/datadog-instrumentations/index.js
  packages/datadog-instrumentations/src/connect.js
  packages/datadog-plugin-connect/src/index.js
  packages/datadog-plugin-connect/test/index.spec.js
Labels: integrations, semver-patch

#2035 update log plugins to receive log injection config directly
  packages/datadog-plugin-bunyan/test/index.spec.js
  packages/datadog-plugin-pino/test/index.spec.js
  packages/datadog-plugin-winston/test/index.spec.js
  packages/dd-trace/src/plugin_manager.js
  packages/dd-trace/src/plugins/log_plugin.js
  packages/dd-trace/test/plugin_manager.spec.js
Labels: integrations, semver-patch

#2033 rewrite koa plugin with new plugin system
  packages/datadog-instrumentations/index.js
  packages/datadog-instrumentations/src/koa.js
  packages/datadog-plugin-koa/src/index.js
  packages/datadog-plugin-koa/test/index.spec.js
Labels: integrations, semver-patch

#2037 rewrite paperplane plugin for the new plugin system
  .github/workflows/plugins.yml
  packages/datadog-instrumentations/index.js
  packages/datadog-instrumentations/src/paperplane.js
  packages/datadog-plugin-paperplane/src/index.js
  packages/datadog-plugin-paperplane/src/logger.js
  packages/datadog-plugin-paperplane/src/server.js
  packages/datadog-plugin-paperplane/test/index.spec.js
  packages/dd-trace/src/plugins/util/web.js
Labels: integrations, semver-patch

#2038 add all dns addresses as a new tag when option is set
  packages/datadog-plugin-dns/src/index.js
  packages/datadog-plugin-dns/test/index.spec.js
Labels: enhancement, integrations, semver-patch

#2034 rewrite restify and fastify plugins with the new plugin system
  packages/datadog-instrumentations/index.js
  packages/datadog-instrumentations/src/fastify.js
  packages/datadog-instrumentations/src/find-my-way.js
  packages/datadog-instrumentations/src/restify.js
  packages/datadog-plugin-fastify/src/fastify.js
  packages/datadog-plugin-fastify/src/find-my-way.js
  packages/datadog-plugin-fastify/src/index.js
  packages/datadog-plugin-fastify/test/index.spec.js
  packages/datadog-plugin-find-my-way/src/index.js
  packages/datadog-plugin-find-my-way/test/index.spec.js
  packages/datadog-plugin-restify/src/index.js
  packages/datadog-plugin-restify/test/index.spec.js
  packages/dd-trace/src/plugins/index.js
Labels: integrations, semver-patch

#2040 restrict pr labels check to master
  .github/workflows/pr-labels.yml
Labels: semver-patch

#2028 convert aws-sdk to new plugin system
  packages/datadog-instrumentations/index.js
  packages/datadog-instrumentations/src/aws-sdk.js
  packages/datadog-plugin-aws-sdk/src/base.js
  packages/datadog-plugin-aws-sdk/src/helpers.js
  packages/datadog-plugin-aws-sdk/src/index.js
  packages/datadog-plugin-aws-sdk/src/services/cloudwatchlogs.js
  packages/datadog-plugin-aws-sdk/src/services/default.js
  packages/datadog-plugin-aws-sdk/src/services/dynamodb.js
  packages/datadog-plugin-aws-sdk/src/services/eventbridge.js
  packages/datadog-plugin-aws-sdk/src/services/index.js
  packages/datadog-plugin-aws-sdk/src/services/kinesis.js
  packages/datadog-plugin-aws-sdk/src/services/lambda.js
  packages/datadog-plugin-aws-sdk/src/services/redshift.js
  packages/datadog-plugin-aws-sdk/src/services/s3.js
  packages/datadog-plugin-aws-sdk/src/services/sns.js
  packages/datadog-plugin-aws-sdk/src/services/sqs.js
  packages/datadog-plugin-aws-sdk/test/aws-sdk.spec.js
  packages/datadog-plugin-aws-sdk/test/eventbridge.spec.js
  packages/datadog-plugin-aws-sdk/test/kinesis.spec.js
  packages/datadog-plugin-aws-sdk/test/lambda.spec.js
  packages/datadog-plugin-aws-sdk/test/sns.spec.js
  packages/datadog-plugin-aws-sdk/test/sqs.spec.js
Labels: semver-patch

#2049 fix unreturned promise in fastify hooks
  packages/datadog-instrumentations/src/fastify.js
  packages/datadog-plugin-fastify/test/index.spec.js
Labels: semver-patch

#2052 [ci-visibility] Add `library_version` to agentless and agent based intake
  packages/datadog-plugin-cucumber/test/index.spec.js
  packages/datadog-plugin-cypress/test/index.spec.js
  packages/datadog-plugin-jest/test/circus.spec.js
  packages/datadog-plugin-jest/test/jasmine2.spec.js
  packages/datadog-plugin-mocha/test/index.spec.js
  packages/dd-trace/src/encode/agentless-ci-visibility.js
  packages/dd-trace/src/plugins/util/test.js
  packages/dd-trace/test/encode/agentless-ci-visibility.spec.js
Labels: semver-minor

#2064 AppSec error list metric
  package.json
  packages/dd-trace/src/appsec/callbacks/ddwaf.js
  packages/dd-trace/test/appsec/callbacks/ddwaf.spec.js
  yarn.lock
Labels: appsec, semver-minor

#2069 rewrite moleculer plugins with the new plugin system
  packages/datadog-instrumentations/index.js
  packages/datadog-instrumentations/src/moleculer.js
  packages/datadog-instrumentations/src/moleculer/client.js
  packages/datadog-instrumentations/src/moleculer/server.js
  packages/datadog-plugin-moleculer/src/client.js
  packages/datadog-plugin-moleculer/src/index.js
  packages/datadog-plugin-moleculer/src/server.js
  packages/datadog-plugin-moleculer/test/index.spec.js
  packages/dd-trace/test/setup/core.js
  scripts/install_plugin_modules.js
Labels: integrations, semver-patch

#2070 rewrite hapi integration with the new plugin system
  packages/datadog-instrumentations/index.js
  packages/datadog-instrumentations/src/hapi.js
  packages/datadog-plugin-hapi/src/index.js
  packages/datadog-plugin-hapi/src/route.js
  packages/datadog-plugin-hapi/src/server.js
  packages/datadog-plugin-hapi/test/index.spec.js
Labels: integrations, semver-patch

#2080 remove legacy release action that is not needed on this branch
  .github/actions/publish/action.yml
  .github/workflows/release.yml
Labels: dev/tooling, semver-patch

#2079 add release script for legacy version
  .circleci/config.yml
  .github/workflows/release.yml
Labels: dev/tooling

#2078 fix store leak in plugin storage management
  packages/datadog-instrumentations/src/amqp10.js
  packages/datadog-instrumentations/src/amqplib.js
  packages/datadog-instrumentations/src/cassandra-driver.js
  packages/datadog-instrumentations/src/connect.js
  packages/datadog-instrumentations/src/couchbase.js
  packages/datadog-instrumentations/src/cucumber.js
  packages/datadog-instrumentations/src/dns.js
  packages/datadog-instrumentations/src/elasticsearch.js
  packages/datadog-instrumentations/src/http/client.js
  packages/datadog-instrumentations/src/http/server.js
  packages/datadog-instrumentations/src/ioredis.js
  packages/datadog-instrumentations/src/jest.js
  packages/datadog-instrumentations/src/koa.js
  packages/datadog-instrumentations/src/memcached.js
  packages/datadog-instrumentations/src/mocha.js
  packages/datadog-instrumentations/src/mongodb-core.js
  packages/datadog-instrumentations/src/mysql.js
  packages/datadog-instrumentations/src/mysql2.js
  packages/datadog-instrumentations/src/net.js
  packages/datadog-instrumentations/src/pg.js
  packages/datadog-instrumentations/src/redis.js
  packages/datadog-instrumentations/src/rhea.js
  packages/datadog-instrumentations/src/router.js
  packages/datadog-instrumentations/src/sharedb.js
  packages/datadog-instrumentations/src/tedious.js
  packages/datadog-plugin-amqp10/src/index.js
  packages/datadog-plugin-amqplib/src/index.js
  packages/datadog-plugin-cassandra-driver/src/index.js
  packages/datadog-plugin-connect/test/index.spec.js
  packages/datadog-plugin-couchbase/src/index.js
  packages/datadog-plugin-cucumber/src/index.js
  packages/datadog-plugin-dns/src/index.js
  packages/datadog-plugin-elasticsearch/src/index.js
  packages/datadog-plugin-express/test/index.spec.js
  packages/datadog-plugin-http/src/client.js
  packages/datadog-plugin-http/src/server.js
  packages/datadog-plugin-jest/src/index.js
  packages/datadog-plugin-kafkajs/src/index.js
  packages/datadog-plugin-koa/test/index.spec.js
  packages/datadog-plugin-memcached/src/index.js
  packages/datadog-plugin-mocha/src/index.js
  packages/datadog-plugin-mongodb-core/src/index.js
  packages/datadog-plugin-mysql/src/index.js
  packages/datadog-plugin-net/src/index.js
  packages/datadog-plugin-pg/src/index.js
  packages/datadog-plugin-redis/src/index.js
  packages/datadog-plugin-rhea/src/index.js
  packages/datadog-plugin-router/src/index.js
  packages/datadog-plugin-sharedb/src/index.js
  packages/datadog-plugin-tedious/src/index.js
  packages/dd-trace/src/plugins/plugin.js
Labels: bug, integrations, semver-patch

#2085 fix type error in hapi
  packages/datadog-instrumentations/src/hapi.js
  packages/datadog-plugin-hapi/src/index.js
Labels: bug, integrations, semver-patch

#2074 Report user agent in traces
  docs/test.ts
  ext/tags.d.ts
  ext/tags.js
  packages/datadog-plugin-http2/src/server.js
  packages/dd-trace/src/plugins/util/web.js
  packages/dd-trace/test/plugins/util/web.spec.js
Labels: semver-minor

#2066 Support passing in a function to determine service name for mysql
  docs/test.ts
  index.d.ts
  packages/datadog-plugin-mysql/src/index.js
  packages/datadog-plugin-mysql/test/index.spec.js
  packages/datadog-plugin-mysql2/test/index.spec.js
Labels: enhancement, community, integrations, semver-minor
