Repository DataDog/dd-trace-js, pull requests merged in 2022-08, with the labels that each got.

#2243 update tracer to not extend from opentracing
  ext/formats.js
  packages/datadog-plugin-aws-sdk/src/base.js
  packages/datadog-plugin-aws-sdk/src/services/sqs.js
  packages/dd-trace/src/noop/span.js
  packages/dd-trace/src/noop/tracer.js
  packages/dd-trace/src/opentracing/span.js
  packages/dd-trace/src/opentracing/span_context.js
  packages/dd-trace/src/opentracing/tracer.js
  packages/dd-trace/src/plugins/util/web.js
  packages/dd-trace/src/profiling/profilers/cpu.js
  packages/dd-trace/src/proxy.js
  packages/dd-trace/test/noop.spec.js
  packages/dd-trace/test/opentracing/tracer.spec.js
  packages/dd-trace/test/tracer.spec.js
Labels: core, semver-patch

#2250 update github workflows to run on pull requests
  .github/workflows/core.yml
  .github/workflows/plugins.yml
  .github/workflows/profiling.yml
  .github/workflows/project.yml
  .github/workflows/tracing.yml
Labels: dev/testing, semver-patch

#2246 Remove `performance-now` and make sure the reference is fetched at the beginning
  LICENSE-3rdparty.csv
  package.json
  packages/dd-trace/src/opentracing/span.js
  packages/dd-trace/test/opentracing/span.spec.js
  yarn.lock
Labels: semver-patch

#2229 Creating a K8s Injection Image
  .github/workflows/test-k8s-lib-injection.yaml
  k8s/README.md
  k8s/auto-inst/Dockerfile
  k8s/auto-inst/copy-lib.sh
  k8s/auto-inst/package.json
  k8s/dd-apm-test-agent-config.yaml
  k8s/kind-config.yaml
  k8s/pod.yml
  k8s/sample-app/Dockerfile
  k8s/sample-app/index.js
  k8s/test-pod.yaml
Labels: semver-patch

#2253 [ci-visibility] Fix `before` hooks errors stopping execution in `mocha`
  packages/datadog-instrumentations/src/mocha.js
  packages/datadog-plugin-mocha/test/mocha-fail-hook-async.js
Labels: ci-app, semver-patch

#2247 Add package size reporting to CI
  .github/workflows/package-size.yml
Labels: semver-patch, dependencies

#2249 fix restify disconnected trace when middleware breaks async context
  packages/datadog-instrumentations/src/connect.js
  packages/datadog-instrumentations/src/koa.js
  packages/datadog-instrumentations/src/restify.js
  packages/datadog-instrumentations/src/router.js
  packages/datadog-plugin-restify/src/index.js
  packages/datadog-plugin-restify/test/index.spec.js
Labels: bug, integrations, semver-patch

#2254 fix excessive requests queueing when the agent is overloaded
  packages/dd-trace/src/encode/0.4.js
  packages/dd-trace/src/exporters/common/request.js
  packages/dd-trace/src/exporters/common/writer.js
  packages/dd-trace/test/exporters/common/request.spec.js
Labels: enhancement, core, semver-patch

#2256 update native-metrics to 1.4.2 and pprof to 1.0.2
  package.json
  yarn.lock
Labels: bug, semver-patch

#2261 [ci-visibility] Remove `fs` configuration in ci visibility
  ci/init.js
  ci/jest/env.js
Labels: ci-app, semver-major

#2242 load instrumentation hooks only when the corresponding module is imported
  packages/datadog-instrumentations/index.js
  packages/datadog-instrumentations/src/helpers/hooks.js
  packages/datadog-instrumentations/src/helpers/instrument.js
  packages/datadog-instrumentations/src/helpers/instrumentations.js
  packages/datadog-instrumentations/src/helpers/register.js
Labels: enhancement, core, integrations, semver-patch

#2262 Fix querystring obfuscation benchmark
  benchmark/sirun/plugin-http/client.js
Labels: semver-patch

#2263 [ci-visibility] Update extraction of CI metadata
  packages/dd-trace/src/plugins/util/ci.js
  packages/dd-trace/src/plugins/util/tags.js
  packages/dd-trace/test/plugins/util/ci-env/buildkite.json
  packages/dd-trace/test/plugins/util/ci-env/circleci.json
  packages/dd-trace/test/plugins/util/ci-env/github.json
  packages/dd-trace/test/plugins/util/ci-env/gitlab.json
  packages/dd-trace/test/plugins/util/ci-env/jenkins.json
Labels: ci-app, semver-patch

#2224 IAST Overhead control engine
  docs/test.ts
  index.d.ts
  packages/dd-trace/src/appsec/iast/index.js
  packages/dd-trace/src/appsec/iast/overhead-controller.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/proxy.js
  packages/dd-trace/test/appsec/iast/index.spec.js
  packages/dd-trace/test/appsec/iast/overhead-controller.spec.js
  packages/dd-trace/test/config.spec.js
Labels: semver-patch, appsec

#2265 update sketches-js to 2.0.0
  package.json
  yarn.lock
Labels: semver-patch

#2267 Crypto instrumentation, Analyzer and WeakHashAnalyzer
  packages/datadog-instrumentations/index.js
  packages/datadog-instrumentations/src/crypto.js
  packages/dd-trace/src/appsec/iast/analyzers/analyzers.js
  packages/dd-trace/src/appsec/iast/analyzers/index.js
  packages/dd-trace/src/appsec/iast/analyzers/vulnerability-analyzer.js
  packages/dd-trace/src/appsec/iast/analyzers/weak-hash-analyzer.js
  packages/dd-trace/src/appsec/iast/iast-context.js
  packages/dd-trace/src/appsec/iast/index.js
  packages/dd-trace/src/appsec/iast/overhead-controller.js
  packages/dd-trace/src/appsec/iast/vulnerability-reporter.js
  packages/dd-trace/test/appsec/iast/analyzers/index.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/vulnerability-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/weak-hash-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/iast-context.spec.js
  packages/dd-trace/test/appsec/iast/index.spec.js
  packages/dd-trace/test/appsec/iast/overhead-controller.spec.js
  packages/dd-trace/test/appsec/iast/vulnerability-reporter.spec.js
Labels: appsec

#2245 [ci-visibility] Upload git metadata
  packages/dd-trace/src/ci-visibility/exporters/git/git_metadata.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/plugins/util/git.js
  packages/dd-trace/src/proxy.js
  packages/dd-trace/test/ci-visibility/exporters/git/git_metadata.spec.js
Labels: do-not-merge/WIP, ci-app, semver-minor

#2278 Move `form-data` to common folder
  packages/dd-trace/src/ci-visibility/exporters/git/git_metadata.js
  packages/dd-trace/src/exporters/common/form-data.js
  packages/dd-trace/src/profiling/exporters/agent.js
  packages/dd-trace/test/exporters/common/form-data.spec.js
Labels: semver-patch

#2233 update release workflow to support 3.x and 2.x releases
  .github/workflows/release.yml
Labels: dev/tooling, semver-patch

#2281 [ci-visibility] Remove `jest/env`
  ci/jest/env.js
  packages/datadog-plugin-jest/test/env.js
Labels: ci-app, semver-major

#2279 increase profiler agent test timeout
  packages/dd-trace/test/profiling/exporters/agent.spec.js
Labels: dev/testing, profiling, semver-patch

#2275 fix w3c trace context inject/extract not propagating IDs properly
  packages/datadog-plugin-mocha/src/index.js
  packages/dd-trace/src/id.js
  packages/dd-trace/src/opentracing/propagation/text_map.js
  packages/dd-trace/test/id.spec.js
  packages/dd-trace/test/opentracing/propagation/text_map.spec.js
Labels: bug, semver-patch

#2234 load plugins only when the corresponding instrumentation is loaded
  packages/datadog-instrumentations/src/helpers/instrument.js
  packages/datadog-instrumentations/test/helpers/promise.js
  packages/datadog-plugin-amqp10/test/index.spec.js
  packages/datadog-plugin-aws-sdk/test/aws-sdk.spec.js
  packages/datadog-plugin-jest/test/circus.spec.js
  packages/datadog-plugin-jest/test/jasmine2.spec.js
  packages/datadog-plugin-limitd-client/test/index.spec.js
  packages/datadog-plugin-rhea/test/index.spec.js
  packages/datadog-plugin-winston/test/index.spec.js
  packages/dd-trace/src/plugin_manager.js
  packages/dd-trace/src/plugins/index.js
  packages/dd-trace/src/proxy.js
  packages/dd-trace/src/startup-log.js
  packages/dd-trace/src/telemetry.js
  packages/dd-trace/test/plugin_manager.spec.js
  packages/dd-trace/test/plugins/agent.js
  packages/dd-trace/test/proxy.spec.js
  packages/dd-trace/test/startup-log.spec.js
  packages/dd-trace/test/telemetry.spec.js
  scripts/install_plugin_modules.js
Labels: enhancement, core, integrations, semver-patch

#2259 remove documentation about event emitter scope binding
  docs/API.md
  docs/test.ts
  index.d.ts
Labels: docs, semver-major

#2260 drop support for node 12 and move `@types/node` to dev dependencies
  .circleci/config.yml
  .github/actions/node/17/action.yml
  .github/actions/node/18/action.yml
  .github/actions/node/latest/action.yml
  .github/actions/node/oldest/action.yml
  .github/actions/node/setup/action.yml
  .github/workflows/plugins.yml
  .github/workflows/profiling.yml
  .github/workflows/project.yml
  .github/workflows/tracing.yml
  .nvmrc
  LICENSE-3rdparty.csv
  benchmark/sirun/plugin-graphql/index.js
  benchmark/sirun/startup/startup-test.js
  package.json
  packages/datadog-core/src/storage/index.js
  packages/datadog-core/test/storage/async_resource.spec.js
  packages/datadog-instrumentations/src/grpc/client.js
  packages/datadog-instrumentations/src/grpc/server.js
  packages/datadog-instrumentations/src/hapi.js
  packages/datadog-instrumentations/src/pg.js
  packages/dd-trace/src/iitm.js
  packages/dd-trace/test/iitm.spec.js
  yarn.lock
Labels: breaking-change, semver-major

#2285 disable k8s library injection test
  .github/workflows/test-k8s-lib-injection.yaml
Labels: semver-patch

#2286 disable couchbase test
  .github/workflows/plugins.yml
Labels: semver-patch

#2287 remove promise binding from scope manager
  docs/test.ts
  packages/dd-trace/src/noop/scope.js
  packages/dd-trace/src/scope.js
  packages/dd-trace/test/scope.spec.js
Labels: breaking-change, semver-major

#2288 fix moleculer test timing out in latest version
  packages/datadog-plugin-moleculer/test/index.spec.js
Labels: semver-patch

#2280 add guide for migrating from 2.x to 3.0
  MIGRATING.md
Labels: docs, semver-major

#2291 v4.0.0-pre
  package.json
Labels: semver-patch

#2294 [ci-visibility] Improve phrasing in migrating guide
  MIGRATING.md
Labels: ci-app, semver-patch

#2274 Publishing init images for k8s
  .github/actions/injection/action.yml
  .github/workflows/release-latest.yml
  .github/workflows/test-k8s-lib-injection.yaml
  .gitlab-ci.yml
  k8s/auto-inst/Dockerfile
  k8s/auto-inst/package.json
  k8s/test-pod.yaml
Labels: semver-minor

#2300 fix path for shared gh action for k8s injection
  .github/actions/injection/action.yml
  .github/workflows/release-latest.yml
  .github/workflows/test-k8s-lib-injection.yaml
Labels: semver-patch

#2298 Fix msgpack encoding when there is a buffer resize
  packages/dd-trace/src/encode/0.4.js
  packages/dd-trace/src/encode/agentless-ci-visibility.js
  packages/dd-trace/test/encode/0.4.spec.js
Labels: semver-patch

#2299 Use private symbol for ddResourceStore
  packages/datadog-core/src/storage/async_resource.js
  packages/datadog-core/test/storage/test.js
Labels: semver-patch

#2295 Remove mongodb sanitization
  packages/datadog-plugin-mongodb-core/src/index.js
  packages/datadog-plugin-mongodb-core/test/core.spec.js
  packages/datadog-plugin-mongodb-core/test/mongodb.spec.js
Labels: integrations, semver-minor

#2308 fix error when using stealthy-require
  integration-tests/startup.spec.js
  integration-tests/startup/index.js
  packages/datadog-instrumentations/src/helpers/instrumentations.js
Labels: bug, semver-patch

#2301 stop loading the entire library when disabled
  packages/dd-trace/index.js
  packages/dd-trace/src/index.js
  packages/dd-trace/src/noop/proxy.js
  packages/dd-trace/src/proxy.js
  packages/dd-trace/test/proxy.spec.js
Labels: semver-patch

#2302 Use lib injection system tests
  .github/workflows/system-tests.yml
Labels: semver-patch

#2306 Fix oracle connect descriptors
  packages/datadog-plugin-oracledb/src/index.js
  packages/datadog-plugin-oracledb/test/index.spec.js
Labels: bug, semver-patch

#2296 [ci-visibility] Change how data is flushed
  packages/datadog-instrumentations/src/cucumber.js
  packages/datadog-instrumentations/src/jest.js
  packages/datadog-plugin-cucumber/src/index.js
  packages/datadog-plugin-jest/src/index.js
  packages/dd-trace/src/ci-visibility/exporters/agentless/index.js
  packages/dd-trace/src/ci-visibility/exporters/agentless/writer.js
  packages/dd-trace/src/encode/0.4.js
  packages/dd-trace/src/encode/agentless-ci-visibility.js
  packages/dd-trace/src/exporters/agent/index.js
  packages/dd-trace/src/exporters/agent/writer.js
  packages/dd-trace/src/exporters/common/request.js
  packages/dd-trace/src/exporters/common/writer.js
  packages/dd-trace/src/telemetry.js
  packages/dd-trace/test/ci-visibility/exporters/agentless/exporter.spec.js
  packages/dd-trace/test/encode/agentless-ci-visibility.spec.js
  packages/dd-trace/test/exporters/agent/exporter.spec.js
  packages/dd-trace/test/exporters/common/request.spec.js
Labels: semver-patch

#2315 [ci-visibility] Allow setting url for coverage intake
  packages/dd-trace/src/ci-visibility/exporters/agentless/index.js
  packages/dd-trace/test/ci-visibility/exporters/agentless/exporter.spec.js
Labels: ci-app, semver-patch

#2316 disable dd-trace in jest workers
  packages/dd-trace/src/index.js
Labels: bug, integrations, semver-patch

#2320 fix event context propagation in net
  packages/datadog-instrumentations/src/net.js
  packages/datadog-plugin-net/test/index.spec.js
Labels: semver-patch

#2309 add trace tags propagation and decision maker tag
  packages/dd-trace/src/config.js
  packages/dd-trace/src/constants.js
  packages/dd-trace/src/opentracing/propagation/text_map.js
  packages/dd-trace/src/plugins/util/web.js
  packages/dd-trace/src/priority_sampler.js
  packages/dd-trace/test/dd-trace.spec.js
  packages/dd-trace/test/opentracing/propagation/text_map.spec.js
  packages/dd-trace/test/plugins/util/web.spec.js
  packages/dd-trace/test/priority_sampler.spec.js
Labels: semver-minor

#2323 fix image publish
  .github/workflows/release-latest.yml
Labels: semver-patch

#2329 Update import-in-the-middle
  package.json
  yarn.lock
Labels: bug, semver-patch

#2328 fix race condition in redis error handling test
  packages/datadog-plugin-redis/test/legacy.spec.js
Labels: dev/testing, semver-patch

#2327 increase encode test timeout to 30 seconds
  packages/dd-trace/test/encode/0.4.spec.js
Labels: semver-patch

#2326 remove codecov status checks
  .codecov.yml
Labels: dev/testing, semver-patch
