Repository DataDog/dd-trace-js, pull requests merged in 2022-12, with the labels that each got.

#2581 web spans should not inherit active context unless it's a lambda span
  packages/dd-trace/src/plugins/util/web.js
  packages/dd-trace/test/plugins/util/web.spec.js
Labels: bug, semver-patch

#2564 remove AsyncResource usage from http server and web frameworks
  packages/datadog-instrumentations/src/connect.js
  packages/datadog-instrumentations/src/http/server.js
  packages/datadog-instrumentations/src/koa.js
  packages/datadog-instrumentations/src/restify.js
  packages/datadog-instrumentations/src/router.js
  packages/datadog-plugin-http/src/server.js
  packages/datadog-plugin-router/src/index.js
Labels: integrations, semver-patch

#2585 Format ts files correctly
  docs/test.ts
  index.d.ts
Labels: semver-patch

#2576 Span resource match for test agent
  packages/datadog-plugin-jest/test/circus.spec.js
  packages/datadog-plugin-jest/test/jasmine2.spec.js
  packages/datadog-plugin-mocha/test/index.spec.js
  packages/dd-trace/test/plugins/agent.js
Labels: dev/testing, dev/tooling, semver-patch

#2596 Revert "web spans should not inherit active context unless it's a lambda wrapper span (#2581)
  packages/dd-trace/src/plugins/util/web.js
  packages/dd-trace/test/plugins/util/web.spec.js
Labels: semver-patch

#2599 [ci-visibility] Fix mocha and jest not running tests when dd-trace is not init
  integration-tests/ci-visibility.spec.js
  integration-tests/ci-visibility/run-jest.js
  integration-tests/ci-visibility/run-mocha.js
  integration-tests/ci-visibility/test/ci-visibility-test.js
  packages/datadog-instrumentations/src/jest.js
  packages/datadog-instrumentations/src/mocha.js
Labels: ci-app, semver-patch

#2606 [ci-visibility] Pin version in ci visibility integration tests
  integration-tests/ci-visibility.spec.js
Labels: ci-app, semver-patch

#2603 [ci-visibility] Improve reliability of ci visibility tests
  packages/datadog-plugin-cypress/test/index.spec.js
  packages/datadog-plugin-jest/test/circus.spec.js
  packages/datadog-plugin-jest/test/jasmine2.spec.js
Labels: semver-patch

#2566 [ci-visibility] Support CI Visibility encoding via the agent through EVP proxy
  ci/init.js
  ext/exporters.d.ts
  ext/exporters.js
  packages/datadog-plugin-cucumber/src/index.js
  packages/datadog-plugin-jest/src/index.js
  packages/datadog-plugin-jest/test/circus.spec.js
  packages/datadog-plugin-mocha/src/index.js
  packages/datadog-plugin-mocha/test/index.spec.js
  packages/dd-trace/src/ci-visibility/exporters/agent-proxy/index.js
  packages/dd-trace/src/ci-visibility/exporters/agentless/coverage-writer.js
  packages/dd-trace/src/ci-visibility/exporters/agentless/index.js
  packages/dd-trace/src/ci-visibility/exporters/agentless/writer.js
  packages/dd-trace/src/exporter.js
  packages/dd-trace/src/exporters/agent/index.js
  packages/dd-trace/src/exporters/common/agent-info-exporter.js
  packages/dd-trace/src/plugin_manager.js
  packages/dd-trace/src/plugins/ci_plugin.js
  packages/dd-trace/test/ci-visibility/exporters/agent-proxy/agent-proxy.spec.js
  packages/dd-trace/test/exporters/common/agent-info-exporter.spec.js
  packages/dd-trace/test/plugins/agent.js
Labels: ci-app, semver-minor

#2600 don't trace profiler export
  packages/dd-trace/src/profiling/exporters/agent.js
  packages/dd-trace/test/profiling/exporters/agent.spec.js
Labels: semver-patch

#2602 README overhaul for dec 2022
  README.md
Labels: semver-patch

#2543 feat: Add moduleLoadEndChannel, publish after load. Move moduleLoadSt…
  packages/dd-trace/src/ritm.js
  packages/dd-trace/test/ritm-tests/module-a.js
  packages/dd-trace/test/ritm-tests/module-b.js
  packages/dd-trace/test/ritm.spec.js
Labels: semver-minor

#2586 rename localhost to 127.0.0.1 for tests
  packages/datadog-plugin-pg/test/index.spec.js
Labels: semver-patch

#2611 [ci-visibility] Fix integration test sandbox setup
  integration-tests/helpers.js
Labels: ci-app, semver-patch

#2609 helpful documentation changes
  .github/ISSUE_TEMPLATE/bug_report.md
  README.md
  docs/relationship.png
Labels: docs, semver-patch

#2588 ASM Data listener to update rule data
  packages/dd-trace/src/appsec/callbacks/ddwaf.js
  packages/dd-trace/src/appsec/index.js
  packages/dd-trace/src/appsec/remote_config/index.js
  packages/dd-trace/src/appsec/remote_config/manager.js
  packages/dd-trace/src/appsec/rule_manager.js
  packages/dd-trace/src/config.js
  packages/dd-trace/test/appsec/callbacks/ddwaf.spec.js
  packages/dd-trace/test/appsec/index.spec.js
  packages/dd-trace/test/appsec/remote_config/index.spec.js
  packages/dd-trace/test/appsec/remote_config/manager.spec.js
  packages/dd-trace/test/appsec/rule_manager.spec.js
  packages/dd-trace/test/config.spec.js
Labels: appsec, semver-minor

#2589 Fix dependencies telemetry in windows
  packages/dd-trace/src/telemetry/dependencies.js
  packages/dd-trace/test/telemetry/dependencies.spec.js
Labels: semver-patch

#2615 [ci-visibility] Add support for buddy.works
  packages/dd-trace/src/plugins/util/ci.js
  packages/dd-trace/test/plugins/util/ci-env/appveyor.json
  packages/dd-trace/test/plugins/util/ci-env/azurepipelines.json
  packages/dd-trace/test/plugins/util/ci-env/bitbucket.json
  packages/dd-trace/test/plugins/util/ci-env/bitrise.json
  packages/dd-trace/test/plugins/util/ci-env/buddy.json
  packages/dd-trace/test/plugins/util/ci-env/buildkite.json
  packages/dd-trace/test/plugins/util/ci-env/circleci.json
  packages/dd-trace/test/plugins/util/ci-env/github.json
  packages/dd-trace/test/plugins/util/ci-env/gitlab.json
  packages/dd-trace/test/plugins/util/ci-env/jenkins.json
  packages/dd-trace/test/plugins/util/ci-env/travisci.json
  packages/dd-trace/test/plugins/util/ci-env/usersupplied.json
Labels: ci-app, semver-minor

#2601 add mocha eslint plugin
  .eslintrc.json
  LICENSE-3rdparty.csv
  package.json
  packages/datadog-instrumentations/test/helpers/instrument.spec.js
  packages/datadog-plugin-amqp10/test/leak.js
  packages/datadog-plugin-bunyan/test/index.spec.js
  packages/datadog-plugin-cypress/test/index.spec.js
  packages/datadog-plugin-jest/test/jest-focus.js
  packages/datadog-plugin-jest/test/jest-test.js
  packages/datadog-plugin-limitd-client/test/index.spec.js
  packages/datadog-plugin-pino/test/index.spec.js
  packages/datadog-plugin-winston/test/index.spec.js
  yarn.lock
Labels: semver-patch

#2620 fix opensearch version range
  packages/datadog-instrumentations/src/opensearch.js
Labels: semver-patch

#2619 [ci-visibility] Update test session tags to include info about ITR config
  integration-tests/ci-visibility.spec.js
  packages/datadog-instrumentations/src/jest.js
  packages/datadog-instrumentations/src/mocha.js
  packages/datadog-plugin-jest/src/index.js
  packages/datadog-plugin-mocha/src/index.js
  packages/dd-trace/src/plugins/util/test.js
Labels: ci-app, semver-patch

#2568 CSI trim methods rewriting
  package.json
  packages/dd-trace/src/appsec/iast/iast-context.js
  packages/dd-trace/src/appsec/iast/taint-tracking/csi-methods.js
  packages/dd-trace/src/appsec/iast/taint-tracking/operations.js
  packages/dd-trace/src/appsec/iast/taint-tracking/rewriter.js
  packages/dd-trace/src/appsec/iast/taint-tracking/taint-tracking-impl.js
  packages/dd-trace/test/appsec/iast/taint-tracking/resources/propagationFunctions.js
  packages/dd-trace/test/appsec/iast/taint-tracking/taint-tracking-impl.spec.js
  packages/dd-trace/test/appsec/iast/taint-tracking/taint-tracking-operations.spec.js
  packages/dd-trace/test/appsec/iast/utils.js
  yarn.lock
Labels: semver-patch, appsec, iast

#2623 add bits to readme
  README.md
  docs/relationship.png
Labels: docs, semver-patch

#2617 migrating node.js APM configuration to documentation repo
  .github/pull_request_template.md
  README.md
  docs/API.md
Labels: docs, semver-patch

#2626 Revert "Use the existing context if any to start the web spans (#1647)"
  packages/dd-trace/src/plugins/util/web.js
  packages/dd-trace/test/plugins/util/web.spec.js
Labels: bug, semver-patch, serverless

#2544 [testing] Lib injection and System-tests integration
  .github/actions/injection/action.yml
  .github/workflows/system-tests.yml
  .github/workflows/test-k8s-lib-injection.yaml
  k8s/README.md
  k8s/dd-apm-test-agent-config.yaml
  k8s/kind-config.yaml
  k8s/pod.yml
  k8s/sample-app/Dockerfile
  k8s/sample-app/index.js
  k8s/test-pod.yaml
  lib-injection/Dockerfile
  lib-injection/copy-lib.sh
  lib-injection/npm_dd_trace.sh
  lib-injection/package.json
Labels: dev/testing, semver-patch

#2631 Remove query string from resource.name by default
  index.d.ts
  packages/datadog-plugin-mongodb-core/src/index.js
  packages/datadog-plugin-mongodb-core/test/core.spec.js
  packages/datadog-plugin-mongodb-core/test/mongodb.spec.js
Labels: bug, semver-patch

#2584 [ci-visibility] ITR related requests can use EVP Proxy
  ci/init.js
  integration-tests/ci-visibility-intake.js
  integration-tests/ci-visibility.spec.js
  packages/datadog-instrumentations/src/jest.js
  packages/datadog-instrumentations/src/mocha.js
  packages/datadog-plugin-jest/src/index.js
  packages/datadog-plugin-jest/test/circus.spec.js
  packages/datadog-plugin-jest/test/jasmine2.spec.js
  packages/datadog-plugin-jest/test/jest-coverage.js
  packages/datadog-plugin-jest/test/jest-itr-pass.js
  packages/datadog-plugin-jest/test/jest-itr-skip.js
  packages/datadog-plugin-jest/test/sum-coverage-test.js
  packages/datadog-plugin-mocha/src/index.js
  packages/datadog-plugin-mocha/test/index.spec.js
  packages/dd-trace/src/ci-visibility/exporters/agent-proxy/index.js
  packages/dd-trace/src/ci-visibility/exporters/agentless/index.js
  packages/dd-trace/src/ci-visibility/exporters/ci-visibility-exporter.js
  packages/dd-trace/src/ci-visibility/exporters/git/git_metadata.js
  packages/dd-trace/src/ci-visibility/intelligent-test-runner/get-itr-configuration.js
  packages/dd-trace/src/ci-visibility/intelligent-test-runner/get-skippable-suites.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/exporters/common/agent-info-exporter.js
  packages/dd-trace/src/plugin_manager.js
  packages/dd-trace/src/plugins/ci_plugin.js
  packages/dd-trace/src/proxy.js
  packages/dd-trace/test/ci-visibility/exporters/agent-proxy/agent-proxy.spec.js
  packages/dd-trace/test/ci-visibility/exporters/agentless/exporter.spec.js
  packages/dd-trace/test/ci-visibility/exporters/ci-visibility-exporter.spec.js
  packages/dd-trace/test/ci-visibility/exporters/git/git_metadata.spec.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/plugins/agent.js
Labels: ci-app, semver-minor

#2621 allow next('route') and next('router') in router plugin
  packages/datadog-instrumentations/src/router.js
  packages/datadog-plugin-router/test/index.spec.js
  packages/dd-trace/test/plugins/agent.js
Labels: semver-patch

#2625 fix: Publish request finish on close or finish, but only once for a r…
  packages/datadog-instrumentations/src/http/server.js
Labels: semver-patch

#2618 LDAP analyzer
  .github/workflows/plugins.yml
  docker-compose.yml
  docs/API.md
  index.d.ts
  packages/datadog-instrumentations/src/helpers/hooks.js
  packages/datadog-instrumentations/src/ldapjs.js
  packages/dd-trace/src/appsec/iast/analyzers/analyzers.js
  packages/dd-trace/src/appsec/iast/analyzers/ldap-injection-analyzer.js
  packages/dd-trace/src/appsec/iast/analyzers/vulnerability-analyzer.js
  packages/dd-trace/test/appsec/iast/analyzers/ldap-injection-analyzer.ldapjs.plugin.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/ldap-injection-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/vulnerability-analyzer.spec.js
  packages/dd-trace/test/setup/services/openldap.js
Labels: semver-patch, appsec, iast

#2642 Update rewriter version
  package.json
  yarn.lock
Labels: semver-patch, appsec, iast
