Repository DataDog/dd-trace-js, pull requests merged in 2023-07, with the labels that each got.

#3324 update docker compose mssql
  docker-compose.yml
Labels: dev/testing, semver-patch

#3309 elasticsearch and opensearch: extract connection host for peer.service
  packages/datadog-instrumentations/src/elasticsearch.js
  packages/datadog-instrumentations/src/opensearch.js
  packages/datadog-plugin-elasticsearch/test/index.spec.js
  packages/datadog-plugin-opensearch/test/index.spec.js
Labels: semver-minor

#3326 extract cassandra contact points and use for peer.service
  packages/datadog-instrumentations/src/cassandra-driver.js
  packages/datadog-plugin-cassandra-driver/src/index.js
  packages/datadog-plugin-cassandra-driver/test/index.spec.js
Labels: semver-minor

#3305 Use env var to provide consistent service names in naming schema `v0`
  package.json
  packages/datadog-plugin-amqp10/test/index.spec.js
  packages/datadog-plugin-amqplib/test/index.spec.js
  packages/datadog-plugin-cassandra-driver/test/index.spec.js
  packages/datadog-plugin-elasticsearch/test/index.spec.js
  packages/datadog-plugin-google-cloud-pubsub/test/index.spec.js
  packages/datadog-plugin-ioredis/test/index.spec.js
  packages/datadog-plugin-kafkajs/test/index.spec.js
  packages/datadog-plugin-memcached/test/index.spec.js
  packages/datadog-plugin-moleculer/test/index.spec.js
  packages/datadog-plugin-mongodb-core/test/core.spec.js
  packages/datadog-plugin-mongodb-core/test/mongodb.spec.js
  packages/datadog-plugin-opensearch/test/index.spec.js
  packages/datadog-plugin-pg/test/index.spec.js
  packages/datadog-plugin-redis/test/client.spec.js
  packages/datadog-plugin-redis/test/legacy.spec.js
  packages/datadog-plugin-rhea/test/index.spec.js
  packages/datadog-plugin-tedious/test/index.spec.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/plugins/tracing.js
  packages/dd-trace/src/service-naming/index.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/service-naming/schema.spec.js
  packages/dd-trace/test/setup/mocha.js
Labels: semver-minor

#3336 support latest aws-sdk
  packages/datadog-instrumentations/src/aws-sdk.js
  packages/datadog-instrumentations/src/helpers/hooks.js
  packages/dd-trace/src/plugins/index.js
Labels: semver-minor

#3321 [ci-visibility] Dogfood CI Visibility with integration tests
  .github/workflows/project.yml
  integration-tests/helpers.js
  integration-tests/playwright/playwright.spec.js
Labels: semver-patch

#3338 extract peer service from aws sdk
  packages/datadog-plugin-aws-sdk/src/base.js
  packages/datadog-plugin-aws-sdk/src/services/dynamodb.js
  packages/datadog-plugin-aws-sdk/src/services/kinesis.js
  packages/datadog-plugin-aws-sdk/src/services/s3.js
  packages/datadog-plugin-aws-sdk/src/services/sns.js
  packages/datadog-plugin-aws-sdk/src/services/sqs.js
  packages/datadog-plugin-aws-sdk/test/s3.spec.js
  packages/datadog-plugin-aws-sdk/test/sns.spec.js
  packages/datadog-plugin-aws-sdk/test/sqs.spec.js
  packages/dd-trace/src/plugins/outbound.js
Labels: semver-minor

#3327 grpc: service representation naming
  packages/datadog-plugin-grpc/src/client.js
  packages/datadog-plugin-grpc/src/server.js
  packages/datadog-plugin-grpc/test/client.spec.js
  packages/datadog-plugin-grpc/test/naming.js
  packages/datadog-plugin-grpc/test/server.spec.js
  packages/datadog-plugin-moleculer/test/index.spec.js
  packages/dd-trace/src/service-naming/schemas/v0/web.js
  packages/dd-trace/src/service-naming/schemas/v1/web.js
  packages/dd-trace/test/setup/mocha.js
Labels: semver-minor

#3092 Added support for data stream monitoring for kafkajs
  LICENSE-3rdparty.csv
  package.json
  packages/datadog-instrumentations/src/kafkajs.js
  packages/datadog-plugin-kafkajs/src/consumer.js
  packages/datadog-plugin-kafkajs/src/producer.js
  packages/datadog-plugin-kafkajs/test/index.spec.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/data_streams_context.js
  packages/dd-trace/src/datastreams/pathway.js
  packages/dd-trace/src/datastreams/processor.js
  packages/dd-trace/src/datastreams/writer.js
  packages/dd-trace/src/plugin_manager.js
  packages/dd-trace/src/tracer.js
  packages/dd-trace/test/datastreams/pathway.spec.js
  packages/dd-trace/test/datastreams/processor.spec.js
Labels: semver-minor

#3339 openai: make request body parsing more defensive
  packages/datadog-plugin-openai/src/index.js
  packages/datadog-plugin-openai/test/index.spec.js
Labels: semver-patch

#3340 database/dbm: no longer use _tracerConfig
  packages/dd-trace/src/plugin_manager.js
  packages/dd-trace/src/plugins/database.js
Labels: semver-patch

#3325 Add validation for git metadata env vars
  LICENSE-3rdparty.csv
  packages/dd-trace/src/plugins/util/user-provided-git.js
  packages/dd-trace/test/ci-visibility/exporters/git/git_metadata.spec.js
  packages/dd-trace/test/plugins/util/ci-env/azurepipelines.json
  packages/dd-trace/test/plugins/util/ci-env/bitbucket.json
  packages/dd-trace/test/plugins/util/ci-env/bitrise.json
  packages/dd-trace/test/plugins/util/ci-env/buildkite.json
  packages/dd-trace/test/plugins/util/ci-env/circleci.json
  packages/dd-trace/test/plugins/util/ci-env/gitlab.json
  packages/dd-trace/test/plugins/util/ci-env/jenkins.json
  packages/dd-trace/test/plugins/util/ci-env/teamcity.json
  packages/dd-trace/test/plugins/util/ci-env/travisci.json
Labels: ci-app, semver-patch

#3335 [ci-visibility] Improve git unshallow process
  packages/dd-trace/src/ci-visibility/exporters/git/git_metadata.js
  packages/dd-trace/src/plugins/util/git.js
  packages/dd-trace/test/plugins/util/git.spec.js
Labels: ci-app, semver-patch

#3284 add dc store binding polyfill and migrate http2
  packages/datadog-instrumentations/src/http2/client.js
  packages/datadog-plugin-http2/src/client.js
  packages/dd-trace/src/plugins/outbound.js
  packages/dd-trace/src/plugins/plugin.js
  packages/dd-trace/src/plugins/tracing.js
  packages/diagnostics_channel/src/index.js
Labels: semver-patch

#3341 Add distributions to instrumentation telemetry
  packages/dd-trace/src/telemetry/metrics.js
  packages/dd-trace/test/telemetry/metrics.spec.js
Labels: semver-minor

#3352 set peer.service naming expectations based on tracer version
  packages/datadog-plugin-grpc/test/client.spec.js
  packages/datadog-plugin-grpc/test/naming.js
  packages/dd-trace/src/service-naming/schemas/v0/web.js
Labels: semver-patch

#3342 update CI parametric tests
  .github/workflows/system-tests.yml
Labels: semver-patch

#3359 sirun: increasing log benchmark iterations 1000x
  benchmark/sirun/log/index.js
Labels: semver-patch

#3360 sirun: decreasing log benchmark iterations 100x
  benchmark/sirun/log/index.js
Labels: semver-patch

#3344 extract bootstrap servers from kafka producers and use for peer.service
  packages/datadog-instrumentations/src/kafkajs.js
  packages/datadog-plugin-kafkajs/src/producer.js
  packages/datadog-plugin-kafkajs/test/index.spec.js
Labels: semver-minor

#3345 redis: extract host and port
  packages/datadog-instrumentations/src/redis.js
  packages/datadog-plugin-redis/test/client.spec.js
Labels: semver-minor

#3361 openai: do not crash when dogstatsd not configured
  packages/datadog-plugin-openai/src/services.js
  packages/datadog-plugin-openai/test/index.spec.js
  packages/datadog-plugin-openai/test/services.spec.js
  packages/dd-trace/src/dogstatsd.js
  packages/dd-trace/src/metrics.js
  packages/dd-trace/test/dogstatsd.spec.js
  packages/dd-trace/test/metrics.spec.js
Labels: semver-patch

#3301 express: recognize regex with flags
  packages/datadog-plugin-express/test/index.spec.js
  packages/datadog-plugin-router/src/index.js
Labels: semver-patch

#3310 validate CI tags before sending them
  packages/dd-trace/src/plugins/util/ci.js
  packages/dd-trace/src/plugins/util/test.js
  packages/dd-trace/src/plugins/util/user-provided-git.js
  packages/dd-trace/test/plugins/util/ci-env/appveyor.json
  packages/dd-trace/test/plugins/util/ci-env/azurepipelines.json
  packages/dd-trace/test/plugins/util/ci-env/bitbucket.json
  packages/dd-trace/test/plugins/util/ci-env/bitrise.json
  packages/dd-trace/test/plugins/util/ci-env/buddy.json
  packages/dd-trace/test/plugins/util/ci-env/buildkite.json
  packages/dd-trace/test/plugins/util/ci-env/circleci.json
  packages/dd-trace/test/plugins/util/ci-env/github.json
  packages/dd-trace/test/plugins/util/ci-env/gitlab.json
  packages/dd-trace/test/plugins/util/ci-env/jenkins.json
  packages/dd-trace/test/plugins/util/ci-env/travisci.json
  packages/dd-trace/test/plugins/util/test.spec.js
Labels: ci-app, semver-patch

#3358 [ci-visibility] Change `test.type` in browser tests
  integration-tests/playwright/playwright.spec.js
  packages/datadog-plugin-cypress/src/plugin.js
  packages/datadog-plugin-cypress/test/index.spec.js
  packages/dd-trace/src/plugins/ci_plugin.js
  packages/dd-trace/src/plugins/util/test.js
Labels: ci-app, semver-patch

#3374 dep: bump protobufjs to 7.2.4
  package.json
  yarn.lock
Labels: semver-patch

#3368 [profiling] Adapt to new pprof-nodejs API
  package.json
  packages/dd-trace/src/profiling/config.js
  packages/dd-trace/src/profiling/index.js
  packages/dd-trace/src/profiling/profilers/cpu.js
  packages/dd-trace/src/profiling/profilers/wall.js
  packages/dd-trace/test/profiling/config.spec.js
  packages/dd-trace/test/profiling/profilers/cpu.spec.js
  packages/dd-trace/test/profiling/profilers/wall.spec.js
  yarn.lock
Labels: profiling, semver-minor

#3369 [ci-visibility] Intelligent test runner: only report skipped flag if tests were actually skipped
  integration-tests/ci-visibility.spec.js
  integration-tests/cucumber/cucumber.spec.js
  integration-tests/cypress/cypress.spec.js
  packages/datadog-instrumentations/src/cucumber.js
  packages/datadog-instrumentations/src/jest.js
  packages/datadog-instrumentations/src/mocha.js
  packages/datadog-plugin-cypress/src/plugin.js
Labels: ci-app, semver-patch

#2805 Report IAST metrics via telemetry
  packages/dd-trace/src/appsec/iast/analyzers/command-injection-analyzer.js
  packages/dd-trace/src/appsec/iast/analyzers/cookie-analyzer.js
  packages/dd-trace/src/appsec/iast/analyzers/ldap-injection-analyzer.js
  packages/dd-trace/src/appsec/iast/analyzers/path-traversal-analyzer.js
  packages/dd-trace/src/appsec/iast/analyzers/sql-injection-analyzer.js
  packages/dd-trace/src/appsec/iast/analyzers/ssrf-analyzer.js
  packages/dd-trace/src/appsec/iast/analyzers/unvalidated-redirect-analyzer.js
  packages/dd-trace/src/appsec/iast/analyzers/vulnerability-analyzer.js
  packages/dd-trace/src/appsec/iast/analyzers/weak-cipher-analyzer.js
  packages/dd-trace/src/appsec/iast/analyzers/weak-hash-analyzer.js
  packages/dd-trace/src/appsec/iast/iast-log.js
  packages/dd-trace/src/appsec/iast/iast-plugin.js
  packages/dd-trace/src/appsec/iast/index.js
  packages/dd-trace/src/appsec/iast/tags.js
  packages/dd-trace/src/appsec/iast/taint-tracking/csi-methods.js
  packages/dd-trace/src/appsec/iast/taint-tracking/index.js
  packages/dd-trace/src/appsec/iast/taint-tracking/operations.js
  packages/dd-trace/src/appsec/iast/taint-tracking/plugin.js
  packages/dd-trace/src/appsec/iast/taint-tracking/rewriter-telemetry.js
  packages/dd-trace/src/appsec/iast/taint-tracking/rewriter.js
  packages/dd-trace/src/appsec/iast/taint-tracking/source-types.js
  packages/dd-trace/src/appsec/iast/taint-tracking/taint-tracking-impl.js
  packages/dd-trace/src/appsec/iast/telemetry/iast-metric.js
  packages/dd-trace/src/appsec/iast/telemetry/index.js
  packages/dd-trace/src/appsec/iast/telemetry/log/index.js
  packages/dd-trace/src/appsec/iast/telemetry/log/log-collector.js
  packages/dd-trace/src/appsec/iast/telemetry/namespaces.js
  packages/dd-trace/src/appsec/iast/telemetry/span-tags.js
  packages/dd-trace/src/appsec/iast/telemetry/verbosity.js
  packages/dd-trace/src/config.js
  packages/dd-trace/test/appsec/iast/analyzers/ldap-injection-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/sql-injection-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/unvalidated-redirect-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/vulnerability-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/weak-cipher-analyzers.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/weak-hash-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/iast-log.spec.js
  packages/dd-trace/test/appsec/iast/iast-plugin.spec.js
  packages/dd-trace/test/appsec/iast/taint-tracking/plugin.spec.js
  packages/dd-trace/test/appsec/iast/taint-tracking/rewriter-telemetry.spec.js
  packages/dd-trace/test/appsec/iast/taint-tracking/rewriter.spec.js
  packages/dd-trace/test/appsec/iast/taint-tracking/sources/taint-tracking.cookie.plugin.spec.js
  packages/dd-trace/test/appsec/iast/taint-tracking/sources/taint-tracking.express.plugin.spec.js
  packages/dd-trace/test/appsec/iast/taint-tracking/sources/taint-tracking.headers.spec.js
  packages/dd-trace/test/appsec/iast/taint-tracking/taint-tracking-operations.spec.js
  packages/dd-trace/test/appsec/iast/telemetry/iast-metric.spec.js
  packages/dd-trace/test/appsec/iast/telemetry/index.spec.js
  packages/dd-trace/test/appsec/iast/telemetry/log/index.spec.js
  packages/dd-trace/test/appsec/iast/telemetry/log/log-collector.spec.js
  packages/dd-trace/test/appsec/iast/telemetry/namespaces.spec.js
  packages/dd-trace/test/appsec/iast/telemetry/span-tags.spec.js
  packages/dd-trace/test/appsec/iast/telemetry/verbosity.spec.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/telemetry/dependencies.spec.js
Labels: semver-patch, asm-iast

#3366 Convert grpc to use tracing channel
  packages/datadog-instrumentations/src/grpc/client.js
  packages/datadog-instrumentations/src/grpc/server.js
  packages/datadog-plugin-grpc/src/client.js
  packages/datadog-plugin-grpc/src/server.js
  packages/dd-trace/src/plugins/tracing.js
Labels: bug, semver-patch

#3381 docs: add link to openai docs
  docs/API.md
Labels: docs, semver-patch

#3320 Peer service mapping
  packages/dd-trace/src/config.js
  packages/dd-trace/src/constants.js
  packages/dd-trace/src/opentracing/tracer.js
  packages/dd-trace/src/plugins/outbound.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/plugins/outbound.spec.js
Labels: semver-minor

#3388 benchmarks: add node 12, 14, 20, upgrade node 14, 16
  benchmark/sirun/Dockerfile
Labels: semver-patch

#3371 [profiling] Associate tracing span IDs with samples in the wall profiler
  package.json
  packages/datadog-core/src/storage/async_resource.js
  packages/dd-trace/src/plugins/util/web.js
  packages/dd-trace/src/profiling/config.js
  packages/dd-trace/src/profiling/profiler.js
  packages/dd-trace/src/profiling/profilers/wall.js
  packages/dd-trace/src/span_processor.js
  packages/dd-trace/test/profiling/config.spec.js
  packages/dd-trace/test/profiling/profilers/wall.spec.js
Labels: enhancement, profiling, semver-minor

#3302 Taint request URI
  packages/dd-trace/src/appsec/iast/analyzers/unvalidated-redirect-analyzer.js
  packages/dd-trace/src/appsec/iast/index.js
  packages/dd-trace/src/appsec/iast/taint-tracking/plugin.js
  packages/dd-trace/src/appsec/iast/taint-tracking/source-types.js
  packages/dd-trace/test/appsec/iast/analyzers/unvalidated-redirect-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/taint-tracking/plugin.spec.js
  packages/dd-trace/test/appsec/iast/taint-tracking/sources/taint-tracking.express.plugin.spec.js
  packages/dd-trace/test/appsec/iast/telemetry/index.spec.js
Labels: semver-minor, asm-iast

#3394 Fix erroneous resetting of profiler state to undefined
  packages/dd-trace/src/profiling/profilers/wall.js
Labels: bug, profiling, semver-patch

#3269 Detect missing header vulnerabilities
  packages/dd-trace/src/appsec/iast/analyzers/analyzers.js
  packages/dd-trace/src/appsec/iast/analyzers/hsts-header-missing-analyzer.js
  packages/dd-trace/src/appsec/iast/analyzers/index.js
  packages/dd-trace/src/appsec/iast/analyzers/missing-header-analyzer.js
  packages/dd-trace/src/appsec/iast/analyzers/xcontenttype-header-missing-analyzer.js
  packages/dd-trace/src/appsec/iast/index.js
  packages/dd-trace/src/appsec/iast/vulnerabilities-formatter/index.js
  packages/dd-trace/src/appsec/iast/vulnerabilities.js
  packages/dd-trace/src/appsec/iast/vulnerability-reporter.js
  packages/dd-trace/test/appsec/iast/analyzers/hsts-header-missing-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/index.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/xcontenttype-header-missing-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/utils.js
Labels: semver-minor, asm-iast

#3398 [profiling] Update yarn.lock with current pprof-nodejs version
  yarn.lock
Labels: profiling, semver-patch

#3408 openai: be defensive about response object shape
  packages/datadog-plugin-openai/src/index.js
  packages/datadog-plugin-openai/test/index.spec.js
Labels: semver-patch, integration-openai

#3396 delete old build scripts
  scripts/version.js
Labels: semver-patch

#3406 Add eslint rule for object-curly-newline
  .eslintrc.json
  benchmark/sirun/get-results.js
  packages/datadog-plugin-elasticsearch/test/index.spec.js
  packages/datadog-plugin-kafkajs/test/index.spec.js
  packages/datadog-plugin-openai/test/index.spec.js
  packages/datadog-plugin-opensearch/test/index.spec.js
  packages/dd-trace/src/appsec/iast/taint-tracking/index.js
  packages/dd-trace/test/appsec/iast/analyzers/path-traversal-analyzer.spec.js
  packages/dd-trace/test/profiling/profilers/wall.spec.js
Labels: semver-patch

#3405 Fix a phrase in README
  README.md
Labels: docs, semver-patch

#3386 Fix same dependency detection
  packages/dd-trace/src/telemetry/dependencies.js
  packages/dd-trace/test/telemetry/dependencies.spec.js
Labels: semver-patch

#3410 Ignore esbuild output from integration tests in esbuild
  .eslintignore
Labels: semver-patch

#3399 [ci-visibility] Do not modify how jest reports timeouts
  integration-tests/ci-visibility.spec.js
  integration-tests/ci-visibility/run-jest.js
  integration-tests/ci-visibility/timeout-test/timeout-test.js
  packages/datadog-instrumentations/src/jest.js
  packages/datadog-plugin-jest/src/index.js
Labels: ci-app, semver-patch

#3194 Allow https datadog agent url in continuous profiling (#3190)
  packages/dd-trace/src/profiling/exporters/agent.js
Labels: profiling, semver-minor

#3413 Fix distributed tracing issue caused by single span ingestion changes
  packages/dd-trace/src/format.js
  packages/dd-trace/src/opentracing/span_context.js
  packages/dd-trace/src/span_sampler.js
  packages/dd-trace/test/format.spec.js
  packages/dd-trace/test/opentracing/span_context.spec.js
  packages/dd-trace/test/span_sampler.spec.js
Labels: bug, semver-patch

#3412 Ensure OTel span name is copied to resource.name
  packages/dd-trace/src/opentelemetry/span.js
  packages/dd-trace/test/opentelemetry/span.spec.js
Labels: semver-patch

#3414 Make datadog distributed tracing header take priority over tracecontext
  packages/dd-trace/src/config.js
  packages/dd-trace/test/config.spec.js
Labels: bug, semver-patch

#3421 Exclude empty telemetry metrics
  packages/dd-trace/src/telemetry/metrics.js
  packages/dd-trace/test/telemetry/metrics.spec.js
Labels: bug, semver-patch

#3420 openai: make services entirely optional when initializing
  .github/workflows/plugins.yml
  packages/datadog-plugin-openai/src/index.js
  packages/datadog-plugin-openai/src/services.js
  packages/datadog-plugin-openai/test/index.spec.js
  packages/datadog-plugin-openai/test/no-init.js
  packages/datadog-plugin-openai/test/services.spec.js
  packages/dd-trace/src/external-logger/src/index.js
  packages/dd-trace/src/external-logger/test/index.spec.js
Labels: semver-patch, integration-openai

#3419 Fix service representation config
  packages/dd-trace/src/config.js
  packages/dd-trace/src/service-naming/index.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/setup/mocha.js
Labels: semver-minor

#3279 implement naming schema for graphql plugin
  packages/datadog-plugin-graphql/src/execute.js
  packages/datadog-plugin-graphql/test/index.spec.js
  packages/datadog-plugin-graphql/test/naming.js
  packages/dd-trace/src/service-naming/schemas/v0/graphql.js
  packages/dd-trace/src/service-naming/schemas/v0/index.js
  packages/dd-trace/src/service-naming/schemas/v1/graphql.js
  packages/dd-trace/src/service-naming/schemas/v1/index.js
  packages/dd-trace/test/setup/mocha.js
Labels: semver-minor

#3265 Re-enable Couchbase testing
  .github/workflows/plugins.yml
  docker-compose.yml
  packages/datadog-instrumentations/src/couchbase.js
  scripts/install_plugin_modules.js
Labels: semver-minor

#3418 Fix flaky serverless integration test
  integration-tests/serverless/test-gcloud-function.sh
Labels: semver-patch, serverless

#3433 Fix native-iast-taint-tracking version number
  package.json
  yarn.lock
Labels: bug, semver-patch

#3432 openai: remove String#replaceAll for Node.js <=14
  packages/datadog-plugin-openai/src/index.js
  packages/datadog-plugin-openai/test/index.spec.js
Labels: semver-patch, integration-openai

#3401 Add BITBUCKET_GIT_HTTP_ORIGIN env variable
  packages/dd-trace/src/plugins/util/ci.js
  packages/dd-trace/test/plugins/util/ci-env/bitbucket.json
Labels: ci-app, semver-patch

#3440 [ci-visibility] Make integration test for jest compatible with node 12
  integration-tests/ci-visibility.spec.js
Labels: ci-app, semver-patch

#3438 fix fetch integration leaking its async context
  packages/datadog-instrumentations/src/fetch.js
  packages/datadog-instrumentations/src/http/client.js
  packages/datadog-instrumentations/src/http2/client.js
  packages/datadog-plugin-fetch/src/index.js
  packages/datadog-plugin-http/src/client.js
  packages/diagnostics_channel/src/index.js
Labels: semver-patch

#3434 feat: add the lib/core file which each client lib imports directly, s…
  packages/datadog-instrumentations/src/aws-sdk.js
  packages/datadog-plugin-aws-sdk/test/aws-sdk.spec.js
Labels: semver-minor, serverless

#3447 fix incorrect value for fetch method tag
  packages/datadog-plugin-fetch/src/index.js
  packages/datadog-plugin-fetch/test/index.spec.js
Labels: semver-patch

#3445 [ci-visibility] Fix cache issues with `jest` and CI Visibility
  packages/datadog-instrumentations/src/helpers/hooks.js
  packages/datadog-instrumentations/src/jest.js
  packages/dd-trace/src/plugins/index.js
Labels: ci-app, semver-patch

#3200 [Serverless] spawn mini agent in azure functions
  packages/dd-trace/src/config.js
  packages/dd-trace/src/proxy.js
  packages/dd-trace/src/serverless.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/serverless.spec.js
Labels: semver-minor, serverless

#3424 Add exclusions for weak hash vulnerabilities
  packages/dd-trace/src/appsec/iast/analyzers/weak-hash-analyzer.js
  packages/dd-trace/test/appsec/iast/analyzers/weak-hash-analyzer.spec.js
Labels: semver-patch, asm-iast

#3446 Fix flaky serverless integration test (part2)
  integration-tests/serverless/test-gcloud-function.sh
Labels: semver-patch, serverless

#3450 skip flaky redis error test
  packages/datadog-plugin-redis/test/legacy.spec.js
Labels: semver-patch

#3449 fix fetch propagation headers with headers option
  packages/datadog-plugin-fetch/src/index.js
  packages/datadog-plugin-fetch/test/index.spec.js
Labels: semver-patch

#3459 Opensearch: pin server version in CI
  .github/workflows/plugins.yml
Labels: semver-patch

#3448 esbuild: fix resolving of deep modules
  packages/datadog-esbuild/index.js
  packages/datadog-instrumentations/index.js
  packages/datadog-instrumentations/src/helpers/bundler-register.js
  packages/datadog-instrumentations/src/helpers/hook.js
  packages/datadog-instrumentations/src/helpers/hooks.js
  packages/datadog-instrumentations/src/helpers/register.js
  packages/dd-trace/src/dcitm.js
Labels: semver-patch, bundler

#3460 fix disable option for fetch instrumentation
  packages/datadog-instrumentations/src/helpers/register.js
Labels: semver-patch

#3409 Update trivially upgraded dependencies
  package.json
  yarn.lock
Labels: semver-patch, dependencies

#3463 W3C is no longer prioritized over Datadog headers.
  MIGRATING.md
Labels: docs, semver-patch

#3425 Allow PR commenter failure instead of silencing
  .gitlab/benchmarks.yml
Labels: semver-patch

#3458 Remove blank space in usr.id field.
  packages/dd-trace/src/appsec/passport.js
  packages/dd-trace/test/appsec/passport.spec.js
Labels: semver-patch, asm-waf

#3417 Fix stringifying mongodb queries that are self referencing but provide toJSON methods
  packages/datadog-plugin-mongodb-core/src/index.js
  packages/datadog-plugin-mongodb-core/test/mongodb.spec.js
Labels: semver-patch, integration-mongodb

#3452 [ci-visibility] Do not mess with jest's test-sequencer
  integration-tests/ci-visibility.spec.js
  integration-tests/ci-visibility/run-jest.js
  integration-tests/ci-visibility/sharding-test/sharding-test-1.js
  integration-tests/ci-visibility/sharding-test/sharding-test-2.js
  integration-tests/ci-visibility/sharding-test/sharding-test-3.js
  integration-tests/ci-visibility/sharding-test/sharding-test-4.js
  integration-tests/ci-visibility/sharding-test/sharding-test-5.js
  packages/datadog-instrumentations/src/helpers/hooks.js
  packages/datadog-instrumentations/src/jest.js
  packages/dd-trace/src/plugins/index.js
Labels: ci-app, semver-patch

#3313 implement naming schema for http plugins
  packages/datadog-plugin-aws-sdk/src/base.js
  packages/datadog-plugin-aws-sdk/src/services/lambda.js
  packages/datadog-plugin-aws-sdk/src/services/sns.js
  packages/datadog-plugin-aws-sdk/src/services/sqs.js
  packages/datadog-plugin-aws-sdk/test/kinesis-naming.js
  packages/datadog-plugin-aws-sdk/test/kinesis.spec.js
  packages/datadog-plugin-aws-sdk/test/lambda-naming.js
  packages/datadog-plugin-aws-sdk/test/lambda.spec.js
  packages/datadog-plugin-aws-sdk/test/s3-naming.js
  packages/datadog-plugin-aws-sdk/test/s3.spec.js
  packages/datadog-plugin-aws-sdk/test/sns-naming.js
  packages/datadog-plugin-aws-sdk/test/sns.spec.js
  packages/datadog-plugin-aws-sdk/test/sqs-naming.js
  packages/datadog-plugin-aws-sdk/test/sqs.spec.js
  packages/datadog-plugin-fetch/test/index.spec.js
  packages/datadog-plugin-fetch/test/naming.js
  packages/datadog-plugin-graphql/test/index.spec.js
  packages/datadog-plugin-http/src/client.js
  packages/datadog-plugin-http/src/server.js
  packages/datadog-plugin-http/test/client.spec.js
  packages/datadog-plugin-http/test/naming.js
  packages/datadog-plugin-http/test/server.spec.js
  packages/datadog-plugin-http2/src/client.js
  packages/datadog-plugin-http2/src/server.js
  packages/datadog-plugin-http2/test/client.spec.js
  packages/datadog-plugin-http2/test/naming.js
  packages/datadog-plugin-http2/test/server.spec.js
  packages/datadog-plugin-next/src/index.js
  packages/datadog-plugin-next/test/index.spec.js
  packages/datadog-plugin-next/test/naming.js
  packages/dd-trace/src/service-naming/schemas/util.js
  packages/dd-trace/src/service-naming/schemas/v0/messaging.js
  packages/dd-trace/src/service-naming/schemas/v0/web.js
  packages/dd-trace/src/service-naming/schemas/v1/messaging.js
  packages/dd-trace/src/service-naming/schemas/v1/web.js
  packages/dd-trace/test/setup/mocha.js
Labels: semver-minor

#3441 Couchbase service representation
  packages/datadog-instrumentations/src/couchbase.js
  packages/datadog-plugin-couchbase/src/index.js
  packages/datadog-plugin-couchbase/test/index.spec.js
  packages/datadog-plugin-couchbase/test/naming.js
  packages/dd-trace/src/service-naming/schemas/v0/storage.js
  packages/dd-trace/src/service-naming/schemas/v1/storage.js
  packages/dd-trace/test/setup/mocha.js
Labels: semver-minor

#3439 Expand CONTRIBUTING.md
  CONTRIBUTING.md
Labels: semver-patch

#3415 Add ci-app-libraries team as code owner of CI Visibility files
  CODEOWNERS
  packages/datadog-plugin-jest/test/circus.spec.js
  packages/datadog-plugin-jest/test/jasmine2.spec.js
  packages/datadog-plugin-mocha/test/index.spec.js
Labels: semver-patch, dont-land-on-v2.x, dont-land-on-v3.x, dont-land-on-v4.x

#3474 v2 codeowners
  CODEOWNERS
Labels: semver-patch, dont-land-on-v3.x, dont-land-on-v4.x

#3475 v3 codeowners
  CODEOWNERS
Labels: semver-patch, dont-land-on-v2.x, dont-land-on-v4.x

#3477 v4 codeowners
  CODEOWNERS
Labels: semver-patch, dont-land-on-v2.x, dont-land-on-v3.x

#3462 [Serverless] set default flush interval to 2000ms for GCP/Azure functions
  packages/dd-trace/src/config.js
Labels: semver-patch, serverless

#3487 add option to truncate pg query
  packages/datadog-plugin-pg/src/index.js
  packages/datadog-plugin-pg/test/index.spec.js
  packages/dd-trace/src/plugins/database.js
Labels: semver-minor

#3395 add support for remote tracing configuration
  packages/datadog-plugin-http/src/client.js
  packages/datadog-plugin-http/test/client.spec.js
  packages/dd-trace/src/appsec/remote_config/index.js
  packages/dd-trace/src/appsec/remote_config/manager.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/noop/tracer.js
  packages/dd-trace/src/plugin_manager.js
  packages/dd-trace/src/plugins/util/web.js
  packages/dd-trace/src/priority_sampler.js
  packages/dd-trace/src/proxy.js
  packages/dd-trace/src/startup-log.js
  packages/dd-trace/src/telemetry/index.js
  packages/dd-trace/src/tracer.js
  packages/dd-trace/test/appsec/remote_config/manager.spec.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/plugins/util/web.spec.js
  packages/dd-trace/test/proxy.spec.js
  packages/dd-trace/test/startup-log.spec.js
  packages/dd-trace/test/tracer.spec.js
Labels: semver-minor
