Repository DataDog/dd-trace-js, pull requests merged in 2023-05, with the labels that each got.

#3087 Add support for prepared statements in PG
  packages/datadog-instrumentations/src/pg.js
  packages/datadog-plugin-pg/src/index.js
  packages/datadog-plugin-pg/test/index.spec.js
Labels: semver-minor

#3088 fix testing next on unsupported node version in ci
  .github/workflows/plugins.yml
Labels: semver-patch

#3089 bump node version for ci integration tests
  .github/workflows/project.yml
Labels: semver-patch

#3091 Support query config objects in PG with DBM propagation
  packages/datadog-instrumentations/src/pg.js
  packages/datadog-plugin-pg/test/index.spec.js
Labels: semver-minor

#2902 [ci-visibility] Rename ITR and code cov tags
  integration-tests/ci-visibility.spec.js
  integration-tests/cucumber/cucumber.spec.js
  packages/dd-trace/src/plugins/util/test.js
Labels: ci-app, semver-patch

#3047 Support array payloads in telemetry send-data
  packages/dd-trace/src/telemetry/send-data.js
  packages/dd-trace/test/telemetry/send-data.spec.js
Labels: semver-patch

#3077 removed orphanable option for v4.0
  index.d.ts
  packages/dd-trace/src/tracer.js
  packages/dd-trace/test/tracer.spec.js
Labels: semver-major

#3046 [ci-visibility][major][breaking-change] Remove support for `jest-jasmine2`
  packages/datadog-instrumentations/src/helpers/register.js
  packages/datadog-instrumentations/src/jest.js
  packages/datadog-plugin-jest/test/jasmine2.spec.js
Labels: ci-app, semver-major

#3093 Revert "Introduce service naming framework (#2941)"
  packages/.eslintrc.json
  packages/datadog-plugin-amqp10/src/consumer.js
  packages/datadog-plugin-amqp10/src/producer.js
  packages/datadog-plugin-amqp10/test/index.spec.js
  packages/datadog-plugin-amqp10/test/naming.js
  packages/datadog-plugin-amqplib/src/client.js
  packages/datadog-plugin-amqplib/src/consumer.js
  packages/datadog-plugin-amqplib/src/producer.js
  packages/datadog-plugin-amqplib/test/index.spec.js
  packages/datadog-plugin-amqplib/test/naming.js
  packages/datadog-plugin-google-cloud-pubsub/src/client.js
  packages/datadog-plugin-google-cloud-pubsub/src/consumer.js
  packages/datadog-plugin-google-cloud-pubsub/src/producer.js
  packages/datadog-plugin-google-cloud-pubsub/test/index.spec.js
  packages/datadog-plugin-google-cloud-pubsub/test/naming.js
  packages/datadog-plugin-kafkajs/src/consumer.js
  packages/datadog-plugin-kafkajs/src/producer.js
  packages/datadog-plugin-kafkajs/test/index.spec.js
  packages/datadog-plugin-kafkajs/test/naming.js
  packages/datadog-plugin-rhea/src/consumer.js
  packages/datadog-plugin-rhea/src/producer.js
  packages/datadog-plugin-rhea/test/index.spec.js
  packages/datadog-plugin-rhea/test/naming.js
  packages/datadog-plugin-tedious/test/naming.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/plugin_manager.js
  packages/dd-trace/src/plugins/client.js
  packages/dd-trace/src/plugins/consumer.js
  packages/dd-trace/src/plugins/inbound.js
  packages/dd-trace/src/plugins/incoming.js
  packages/dd-trace/src/plugins/outgoing.js
  packages/dd-trace/src/plugins/producer.js
  packages/dd-trace/src/plugins/server.js
  packages/dd-trace/src/plugins/tracing.js
  packages/dd-trace/src/service-naming/index.js
  packages/dd-trace/src/service-naming/schemas/definition.js
  packages/dd-trace/src/service-naming/schemas/index.js
  packages/dd-trace/src/service-naming/schemas/v0.js
  packages/dd-trace/src/service-naming/schemas/v1.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/plugin_manager.spec.js
  packages/dd-trace/test/plugins/helpers.js
  packages/dd-trace/test/service-naming/schema.spec.js
  packages/dd-trace/test/setup/mocha.js
Labels: semver-patch

#3101 [ci-visibility] Fix potential issue when encoding `test_module_id`
  packages/dd-trace/src/encode/agentless-ci-visibility.js
  packages/dd-trace/test/encode/agentless-ci-visibility.spec.js
Labels: ci-app, semver-patch

#3105 use `withVersions` data for pg version
  packages/datadog-plugin-pg/test/index.spec.js
Labels: semver-patch

#2930 Consistent APM Span tags for AWS SDK Requests
  packages/datadog-plugin-aws-sdk/src/base.js
  packages/datadog-plugin-aws-sdk/src/services/cloudwatchlogs.js
  packages/datadog-plugin-aws-sdk/src/services/dynamodb.js
  packages/datadog-plugin-aws-sdk/src/services/eventbridge.js
  packages/datadog-plugin-aws-sdk/src/services/kinesis.js
  packages/datadog-plugin-aws-sdk/src/services/lambda.js
  packages/datadog-plugin-aws-sdk/src/services/redshift.js
  packages/datadog-plugin-aws-sdk/src/services/s3.js
  packages/datadog-plugin-aws-sdk/src/services/sns.js
  packages/datadog-plugin-aws-sdk/src/services/sqs.js
  packages/datadog-plugin-aws-sdk/test/aws-sdk.spec.js
  packages/datadog-plugin-aws-sdk/test/eventbridge.spec.js
  packages/datadog-plugin-aws-sdk/test/kinesis.spec.js
  packages/datadog-plugin-aws-sdk/test/lambda.spec.js
  packages/datadog-plugin-aws-sdk/test/s3.spec.js
  packages/datadog-plugin-aws-sdk/test/sns.spec.js
  packages/datadog-plugin-aws-sdk/test/sqs.spec.js
Labels: semver-minor, serverless

#3107 deprecate old versions of next only in older versions of dd-trace
  packages/datadog-instrumentations/src/next.js
  packages/datadog-plugin-next/test/index.spec.js
  version.js
Labels: semver-patch

#3001 [Serverless] spawn serverless mini agent child process
  .github/workflows/serverless-integration-test.yml
  integration-tests/serverless/serverless.spec.js
  integration-tests/serverless/test-gcloud-function.sh
  integration-tests/serverless/test-project/.env.yaml
  integration-tests/serverless/test-project/index.js
  integration-tests/serverless/test-project/package.json
  package.json
  packages/dd-trace/src/config.js
  packages/dd-trace/src/proxy.js
  packages/dd-trace/src/serverless.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/serverless.spec.js
Labels: semver-minor, serverless

#3110 [lambda] remove tests not needed for macos/windows
  .github/workflows/lambda.yml
Labels: semver-patch

#3108 fix missing version file when publishing
  .npmignore
Labels: semver-patch

#3113 Mini Agent: inherit stdio from parent
  integration-tests/serverless/test-project/.env.yaml
  packages/dd-trace/src/serverless.js
  packages/dd-trace/test/serverless.spec.js
Labels: semver-patch, serverless

#3125 Fix integration test for OOM profiler
  integration-tests/profiler.spec.js
Labels: semver-patch

#3119 [ci-visibility] Add warning about `jest-jasmine2` usage
  packages/datadog-instrumentations/src/jest.js
Labels: ci-app, semver-patch

#3120 [ci-visibility] Update CI Visibility spec
  packages/dd-trace/src/plugins/util/ci.js
  packages/dd-trace/src/plugins/util/tags.js
  packages/dd-trace/test/plugins/util/ci-env/buddy.json
  packages/dd-trace/test/plugins/util/ci-env/buildkite.json
  packages/dd-trace/test/plugins/util/ci-env/codefresh.json
  packages/dd-trace/test/plugins/util/ci-env/gitlab.json
  packages/dd-trace/test/plugins/util/ci-env/jenkins.json
  packages/dd-trace/test/plugins/util/test-environment.spec.js
Labels: ci-app, semver-minor

#3031 Report `out.host` for http and http2
  packages/datadog-plugin-http/src/client.js
  packages/datadog-plugin-http/test/client.spec.js
  packages/datadog-plugin-http2/src/client.js
  packages/datadog-plugin-http2/test/client.spec.js
Labels: semver-minor

#3127 Prevent reporting path traversal vulnerabilities from internal fs calls
  packages/dd-trace/src/appsec/iast/analyzers/path-traversal-analyzer.js
  packages/dd-trace/src/appsec/iast/path-line.js
  packages/dd-trace/test/appsec/iast/analyzers/path-traversal-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/utils.js
Labels: semver-patch, asm-iast

#3117 IAST Evidence redaction
  docs/test.ts
  index.d.ts
  package.json
  packages/dd-trace/src/appsec/iast/analyzers/command-injection-analyzer.js
  packages/dd-trace/src/appsec/iast/analyzers/ldap-injection-analyzer.js
  packages/dd-trace/src/appsec/iast/analyzers/path-traversal-analyzer.js
  packages/dd-trace/src/appsec/iast/analyzers/sql-injection-analyzer.js
  packages/dd-trace/src/appsec/iast/analyzers/weak-cipher-analyzer.js
  packages/dd-trace/src/appsec/iast/analyzers/weak-hash-analyzer.js
  packages/dd-trace/src/appsec/iast/vulnerabilities-formatter/evidence-redaction/range-utils.js
  packages/dd-trace/src/appsec/iast/vulnerabilities-formatter/evidence-redaction/sensitive-analyzers/command-sensitive-analyzer.js
  packages/dd-trace/src/appsec/iast/vulnerabilities-formatter/evidence-redaction/sensitive-analyzers/ldap-sensitive-analyzer.js
  packages/dd-trace/src/appsec/iast/vulnerabilities-formatter/evidence-redaction/sensitive-analyzers/sql-sensitive-analyzer.js
  packages/dd-trace/src/appsec/iast/vulnerabilities-formatter/evidence-redaction/sensitive-handler.js
  packages/dd-trace/src/appsec/iast/vulnerabilities-formatter/index.js
  packages/dd-trace/src/appsec/iast/vulnerabilities.js
  packages/dd-trace/src/appsec/iast/vulnerability-reporter.js
  packages/dd-trace/src/config.js
  packages/dd-trace/test/appsec/iast/analyzers/sql-injection-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/vulnerability-formatter/evidence-redaction/sensitive-handler.spec.js
  packages/dd-trace/test/appsec/iast/vulnerability-formatter/index.spec.js
  packages/dd-trace/test/appsec/iast/vulnerability-formatter/resources/evidence-redaction-suite.json
  packages/dd-trace/test/appsec/iast/vulnerability-reporter.spec.js
  packages/dd-trace/test/config.spec.js
  yarn.lock
Labels: semver-minor, asm-iast

#3132 update native metrics to 2.x
  package.json
  yarn.lock
Labels: breaking-change, semver-patch, dont-land-on-v2.x

#3133 restore orphanable only on older versions
  index.d.ts
  packages/dd-trace/src/tracer.js
  packages/dd-trace/test/tracer.spec.js
Labels: semver-patch

#3118 SCI Embedding of git metadata
  integration-tests/esbuild.spec.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/constants.js
  packages/dd-trace/src/git_metadata_tagger.js
  packages/dd-trace/src/span_processor.js
  packages/dd-trace/test/git_metadata_tagger.spec.js
Labels: semver-minor

#3141 update grpc tests to work with node 16
  .github/workflows/plugins.yml
  packages/datadog-instrumentations/src/grpc/client.js
  packages/datadog-instrumentations/src/grpc/server.js
  packages/datadog-plugin-grpc/test/client.spec.js
  packages/datadog-plugin-grpc/test/server.spec.js
Labels: semver-patch, dont-land-on-v2.x

#3139 update hapi tests to only test versions supported on current node
  .github/workflows/plugins.yml
  packages/datadog-plugin-hapi/test/index.spec.js
Labels: semver-patch, dont-land-on-v2.x

#3142 update postgres tests to also run on latest node
  .github/workflows/plugins.yml
Labels: semver-patch

#3135 SCI Embedding - read `git.properties` file
  packages/dd-trace/src/config.js
  packages/dd-trace/src/git_properties.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/fixtures/config/git.properties
  packages/dd-trace/test/fixtures/config/git.properties.credentials
  packages/dd-trace/test/git_properties.spec.js
  packages/dd-trace/test/serverless.spec.js
Labels: semver-minor

#3140 update ci config and bump minimum node version for v4
  .github/actions/node/oldest/action.yml
  .github/actions/node/setup/action.yml
  .github/workflows/appsec.yml
  .github/workflows/lambda.yml
  .github/workflows/package-size.yml
  .github/workflows/plugins.yml
  .github/workflows/profiling.yml
  .github/workflows/project.yml
  .github/workflows/release-3.yml
  .github/workflows/release-latest.yml
  .github/workflows/serverless-integration-test.yml
  .github/workflows/serverless-performance.yml
  .github/workflows/tracing.yml
  .gitlab/benchmarks.yml
  .nvmrc
  benchmark/sirun/Dockerfile
  package.json
  packages/datadog-plugin-aws-sdk/test/lambda.spec.js
  yarn.lock
Labels: semver-major, dont-land-on-v2.x, dont-land-on-v3.x

#3138 Send _dd.iast.enabled as number
  packages/dd-trace/src/appsec/iast/index.js
  packages/dd-trace/test/appsec/iast/overhead-controller.spec.js
Labels: semver-patch

#3137 add migration guide for 3.x to 4.x
  MIGRATING.md
  README.md
Labels: semver-patch

#3149 v5.0.0-pre
  package.json
Labels: semver-major, dont-land-on-v2.x, dont-land-on-v3.x, dont-land-on-v4.x

#3148 update readme for v4 and remove semver for version feature flags
  README.md
  packages/datadog-instrumentations/src/jest.js
  packages/datadog-instrumentations/src/next.js
  packages/datadog-plugin-jest/test/jasmine2.spec.js
  packages/datadog-plugin-next/test/index.spec.js
  packages/dd-trace/src/tracer.js
  packages/dd-trace/test/tracer.spec.js
  version.js
Labels: semver-patch

#3150 modifying benchmarks to reduce non-determinism
  benchmark/sirun/log/index.js
  benchmark/sirun/log/meta.json
Labels: semver-patch

#3160 Fix IAST evidence redaction
  packages/dd-trace/src/appsec/iast/vulnerabilities-formatter/evidence-redaction/sensitive-handler.js
  packages/dd-trace/test/appsec/iast/vulnerability-formatter/resources/evidence-redaction-suite.json
Labels: bug, semver-patch, asm-iast

#3136 Use 'process' as default strategy for oom export
  packages/dd-trace/src/profiling/config.js
  packages/dd-trace/test/profiling/config.spec.js
Labels: semver-minor

#3166 Improve appsec pg plugin test
  packages/dd-trace/test/appsec/iast/analyzers/sql-injection-analyzer.pg.plugin.spec.js
Labels: semver-patch, asm-iast

#3161 Service Naming API
  packages/.eslintrc.json
  packages/datadog-plugin-amqp10/src/consumer.js
  packages/datadog-plugin-amqp10/src/producer.js
  packages/datadog-plugin-amqp10/test/index.spec.js
  packages/datadog-plugin-amqp10/test/naming.js
  packages/datadog-plugin-amqplib/src/client.js
  packages/datadog-plugin-amqplib/src/consumer.js
  packages/datadog-plugin-amqplib/src/producer.js
  packages/datadog-plugin-amqplib/test/index.spec.js
  packages/datadog-plugin-amqplib/test/naming.js
  packages/datadog-plugin-google-cloud-pubsub/src/client.js
  packages/datadog-plugin-google-cloud-pubsub/src/consumer.js
  packages/datadog-plugin-google-cloud-pubsub/src/producer.js
  packages/datadog-plugin-google-cloud-pubsub/test/index.spec.js
  packages/datadog-plugin-google-cloud-pubsub/test/naming.js
  packages/datadog-plugin-kafkajs/src/consumer.js
  packages/datadog-plugin-kafkajs/src/producer.js
  packages/datadog-plugin-kafkajs/test/index.spec.js
  packages/datadog-plugin-kafkajs/test/naming.js
  packages/datadog-plugin-rhea/src/consumer.js
  packages/datadog-plugin-rhea/src/producer.js
  packages/datadog-plugin-rhea/test/index.spec.js
  packages/datadog-plugin-rhea/test/naming.js
  packages/datadog-plugin-tedious/test/naming.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/plugin_manager.js
  packages/dd-trace/src/plugins/client.js
  packages/dd-trace/src/plugins/consumer.js
  packages/dd-trace/src/plugins/inbound.js
  packages/dd-trace/src/plugins/incoming.js
  packages/dd-trace/src/plugins/outbound.js
  packages/dd-trace/src/plugins/producer.js
  packages/dd-trace/src/plugins/server.js
  packages/dd-trace/src/plugins/tracing.js
  packages/dd-trace/src/service-naming/index.js
  packages/dd-trace/src/service-naming/schemas/definition.js
  packages/dd-trace/src/service-naming/schemas/index.js
  packages/dd-trace/src/service-naming/schemas/v0.js
  packages/dd-trace/src/service-naming/schemas/v1.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/plugin_manager.spec.js
  packages/dd-trace/test/plugins/helpers.js
  packages/dd-trace/test/service-naming/schema.spec.js
  packages/dd-trace/test/setup/mocha.js
Labels: semver-minor

#3173 force a stop before starting metrics
  packages/dd-trace/test/metrics.spec.js
Labels: semver-patch

#3172 Fix path traversal vulnerability on close
  packages/dd-trace/src/appsec/iast/analyzers/path-traversal-analyzer.js
  packages/dd-trace/test/appsec/iast/analyzers/path-traversal-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/resources/fs-async-way-method.js
  packages/dd-trace/test/appsec/iast/analyzers/resources/fs-promise-way-method.js
  packages/dd-trace/test/appsec/iast/analyzers/resources/fs-sync-way-method.js
  packages/dd-trace/test/appsec/iast/utils.js
Labels: semver-patch, asm-iast

#3171 More beautiful debug logs
  packages/dd-trace/src/ci-visibility/exporters/agentless/coverage-writer.js
  packages/dd-trace/src/ci-visibility/exporters/agentless/writer.js
  packages/dd-trace/src/exporters/common/util.js
  packages/dd-trace/src/exporters/common/writer.js
Labels: semver-patch

#3156 [ci-visibility] Fix cucumber parallel mode
  integration-tests/cucumber/cucumber.spec.js
  packages/datadog-instrumentations/src/cucumber.js
Labels: ci-app, semver-patch

#3056 Cache integrations - service naming
  packages/datadog-plugin-ioredis/test/index.spec.js
  packages/datadog-plugin-ioredis/test/naming.js
  packages/datadog-plugin-memcached/src/index.js
  packages/datadog-plugin-memcached/test/index.spec.js
  packages/datadog-plugin-memcached/test/naming.js
  packages/datadog-plugin-redis/src/index.js
  packages/datadog-plugin-redis/test/client.spec.js
  packages/datadog-plugin-redis/test/legacy.spec.js
  packages/datadog-plugin-redis/test/naming.js
  packages/dd-trace/src/plugins/cache.js
  packages/dd-trace/src/plugins/storage.js
  packages/dd-trace/src/plugins/tracing.js
  packages/dd-trace/src/service-naming/index.js
  packages/dd-trace/src/service-naming/schemas/definition.js
  packages/dd-trace/src/service-naming/schemas/util.js
  packages/dd-trace/src/service-naming/schemas/v0.js
  packages/dd-trace/src/service-naming/schemas/v0/index.js
  packages/dd-trace/src/service-naming/schemas/v0/messaging.js
  packages/dd-trace/src/service-naming/schemas/v0/storage.js
  packages/dd-trace/src/service-naming/schemas/v1.js
  packages/dd-trace/src/service-naming/schemas/v1/index.js
  packages/dd-trace/src/service-naming/schemas/v1/messaging.js
  packages/dd-trace/src/service-naming/schemas/v1/storage.js
Labels: semver-minor

#3165 Fix ASM_DD batch update
  packages/dd-trace/src/appsec/rule_manager.js
  packages/dd-trace/test/appsec/rule_manager.spec.js
Labels: semver-patch, asm-waf

#3126 implement RC custom rules
  package.json
  packages/dd-trace/src/appsec/remote_config/capabilities.js
  packages/dd-trace/src/appsec/remote_config/index.js
  packages/dd-trace/src/appsec/rule_manager.js
  packages/dd-trace/test/appsec/remote_config/index.spec.js
  packages/dd-trace/test/appsec/rule_manager.spec.js
  yarn.lock
Labels: asm-waf, semver-minor

#3180 [ci-visibility] Fix playwright@1.30.0
  packages/datadog-instrumentations/src/playwright.js
  packages/dd-trace/src/plugins/ci_plugin.js
Labels: ci-app, semver-patch

#3181 Update AppSec blocking templates
  packages/dd-trace/src/appsec/blocked_templates.js
Labels: semver-patch, asm-waf

#3185 Update Appsec rules to 1.7.1
  packages/dd-trace/src/appsec/recommended.json
Labels: semver-patch, asm-waf

#3183 [ci-visibility] Change gitlab's pipeline URL extraction
  packages/dd-trace/src/plugins/util/ci.js
  packages/dd-trace/test/plugins/util/ci-env/gitlab.json
Labels: ci-app, semver-patch

#3182 Taint cookies and headers
  .github/workflows/appsec.yml
  packages/datadog-instrumentations/src/cookie.js
  packages/datadog-instrumentations/src/helpers/hooks.js
  packages/dd-trace/src/appsec/iast/index.js
  packages/dd-trace/src/appsec/iast/taint-tracking/index.js
  packages/dd-trace/src/appsec/iast/taint-tracking/operations.js
  packages/dd-trace/src/appsec/iast/taint-tracking/origin-types.js
  packages/dd-trace/src/appsec/iast/taint-tracking/plugin.js
  packages/dd-trace/test/appsec/iast/taint-tracking/plugin.spec.js
  packages/dd-trace/test/appsec/iast/taint-tracking/sources/taint-tracking.cookie.plugin.spec.js
  packages/dd-trace/test/appsec/iast/taint-tracking/sources/taint-tracking.headers.spec.js
  packages/dd-trace/test/appsec/iast/taint-tracking/taint-tracking-operations.spec.js
Labels: semver-minor, asm-iast

#3192 Revert "Taint cookies and headers (#3182)"
  .github/workflows/appsec.yml
  packages/datadog-instrumentations/src/cookie.js
  packages/datadog-instrumentations/src/helpers/hooks.js
  packages/dd-trace/src/appsec/iast/index.js
  packages/dd-trace/src/appsec/iast/taint-tracking/index.js
  packages/dd-trace/src/appsec/iast/taint-tracking/operations.js
  packages/dd-trace/src/appsec/iast/taint-tracking/origin-types.js
  packages/dd-trace/src/appsec/iast/taint-tracking/plugin.js
  packages/dd-trace/test/appsec/iast/taint-tracking/plugin.spec.js
  packages/dd-trace/test/appsec/iast/taint-tracking/sources/taint-tracking.cookie.plugin.spec.js
  packages/dd-trace/test/appsec/iast/taint-tracking/sources/taint-tracking.headers.spec.js
  packages/dd-trace/test/appsec/iast/taint-tracking/taint-tracking-operations.spec.js
Labels: semver-minor, asm-iast

#3186 postgres: DBM full service fallback w/ prepared statements
  packages/datadog-plugin-pg/src/index.js
  packages/datadog-plugin-pg/test/index.spec.js
  packages/dd-trace/src/plugins/database.js
Labels: semver-patch
