Repository DataDog/dd-trace-js, pull requests merged in 2023-04, with the labels that each got.

#2963 Improve integration tests for CI Visibility
  integration-tests/cucumber/cucumber.spec.js
  integration-tests/cypress/cypress.spec.js
Labels: dev/testing, semver-patch

#2969 Disable appsec if missing or malformed user custom rules file
  .github/actions/check-release-branch/action.yml
  .github/workflows/project.yml
  README.md
  integration-tests/esbuild/basic-test.js
  packages/dd-trace/src/appsec/index.js
  packages/dd-trace/src/config.js
  packages/dd-trace/test/appsec/index.spec.js
  packages/dd-trace/test/config.spec.js
Labels: semver-patch

#2972 Update ASM WAF rules to version 1.6.0.
  packages/dd-trace/src/appsec/recommended.json
Labels: semver-patch, asm-waf

#2938 Fix to DBM propagation - comment is injected before query is sent
  packages/datadog-instrumentations/src/pg.js
  packages/datadog-plugin-pg/test/index.spec.js
Labels: semver-minor

#2966 fix error when using pubsub while plugin is disabled
  packages/datadog-instrumentations/src/google-cloud-pubsub.js
  packages/datadog-plugin-google-cloud-pubsub/test/index.spec.js
Labels: semver-patch

#2974 skip extraction of upper bits for 64-bit trace id
  packages/dd-trace/src/opentracing/propagation/text_map.js
  packages/dd-trace/test/opentracing/propagation/text_map.spec.js
Labels: semver-patch

#2976 Fix #2938
  packages/datadog-instrumentations/src/pg.js
  packages/dd-trace/src/appsec/iast/analyzers/sql-injection-analyzer.js
Labels: semver-patch

#2953 split next testing by version range
  .github/workflows/plugins.yml
  package.json
  packages/datadog-plugin-next/test/index.spec.js
  packages/dd-trace/test/setup/mocha.js
  scripts/install_plugin_modules.js
  yarn.lock
Labels: semver-patch

#2971 Fix Next.js getServerSideProps error handling
  packages/datadog-plugin-next/src/index.js
  packages/datadog-plugin-next/test/index.spec.js
  packages/datadog-plugin-next/test/pages/error/get_server_side_props.js
  packages/datadog-plugin-next/test/pages/error/not_found.js
Labels: bug, semver-patch, next

#2981 [lambda] update context extraction
  packages/dd-trace/src/lambda/handler.js
  packages/dd-trace/test/lambda/fixtures/handler.js
  packages/dd-trace/test/lambda/index.spec.js
Labels: semver-patch

#2988 Remove job for checking release branches
  .github/actions/check-release-branch/action.yml
  .github/workflows/release-branches-check.yml
Labels: dev/testing, semver-patch

#3002 switch to internal diagnostics channel with node bug patch
  .eslintrc.json
  LICENSE-3rdparty.csv
  package.json
  packages/datadog-core/src/storage/async_resource.js
  packages/datadog-instrumentations/src/helpers/instrument.js
  packages/datadog-instrumentations/src/helpers/register.js
  packages/datadog-plugin-fs/test/index.spec.js
  packages/dd-trace/src/appsec/gateway/channels.js
  packages/dd-trace/src/appsec/iast/index.js
  packages/dd-trace/src/appsec/iast/telemetry/logs.js
  packages/dd-trace/src/dcitm.js
  packages/dd-trace/src/iitm.js
  packages/dd-trace/src/log/channels.js
  packages/dd-trace/src/plugin_manager.js
  packages/dd-trace/src/plugins/plugin.js
  packages/dd-trace/src/profiling/profilers/cpu.js
  packages/dd-trace/src/ritm.js
  packages/dd-trace/src/telemetry/dependencies.js
  packages/dd-trace/src/telemetry/index.js
  packages/dd-trace/test/appsec/iast/analyzers/vulnerability-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/iast-log.spec.js
  packages/dd-trace/test/appsec/iast/telemetry/logs.spec.js
  packages/dd-trace/test/iitm.spec.js
  packages/dd-trace/test/plugin_manager.spec.js
  packages/dd-trace/test/plugins/log_plugin.spec.js
  packages/dd-trace/test/ritm.spec.js
  packages/dd-trace/test/telemetry/dependencies.spec.js
  packages/diagnostics_channel/index.js
  packages/diagnostics_channel/src/index.js
  yarn.lock
Labels: semver-patch

#2997 Optimizations in tags-procesors.js
  packages/dd-trace/src/encode/tags-processors.js
  packages/dd-trace/test/encode/agentless-ci-visibility.spec.js
Labels: semver-patch

#2991 [esbuild] add esbuild.js to npm package, change warning message
  .npmignore
  packages/datadog-esbuild/index.js
Labels: semver-patch, bundler

#2999 [ci-visibility] Fix jest error when using `jest-jasmine2`
  integration-tests/ci-visibility.spec.js
  integration-tests/ci-visibility/run-jest.js
  packages/datadog-plugin-jest/src/index.js
Labels: ci-app, semver-patch

#3000 Fix trace stats duration
  packages/dd-trace/src/span_stats.js
  packages/dd-trace/test/span_stats.spec.js
Labels: bug, semver-patch

#3008 redis command names in blocklist/allowlist now case insensitive
  packages/datadog-plugin-redis/src/index.js
  packages/datadog-plugin-redis/test/client.spec.js
  packages/datadog-plugin-redis/test/legacy.spec.js
Labels: semver-patch

#3014 debugging the slack reporter, fixing slack link
  .github/workflows/plugins.yml
  packages/dd-trace/test/setup/slack-report.js
Labels: semver-patch

#3029 add support for node 20
  .github/actions/node/latest/action.yml
  integration-tests/esm.spec.js
  package.json
  packages/datadog-plugin-http/src/client.js
  packages/datadog-plugin-http/test/client.spec.js
  packages/datadog-plugin-http/test/server.spec.js
  packages/datadog-plugin-net/test/index.spec.js
  packages/dd-trace/src/format.js
  yarn.lock
Labels: semver-minor

#2998 force hyphen prefix for decision making header
  packages/dd-trace/src/opentracing/propagation/text_map.js
  packages/dd-trace/test/opentracing/propagation/text_map.spec.js
Labels: semver-patch

#3020 [ci-visibility] Speed up CI Vis e2e tests
  .github/workflows/ci-visibility-performance.yml
  benchmark/e2e-ci/benchmark-run.js
Labels: dev/testing, ci-app, semver-patch

#2977 Prevent null values from breaking taint tracking
  packages/dd-trace/src/appsec/iast/taint-tracking/operations.js
  packages/dd-trace/test/appsec/iast/taint-tracking/plugin.spec.js
  packages/dd-trace/test/appsec/iast/taint-tracking/taint-tracking-operations.spec.js
Labels: bug, semver-patch, asm-iast

#3011 [ci-visibility] Add test start line
  integration-tests/playwright/playwright.spec.js
  packages/datadog-instrumentations/src/cucumber.js
  packages/datadog-instrumentations/src/jest.js
  packages/datadog-instrumentations/src/mocha.js
  packages/datadog-instrumentations/src/playwright.js
  packages/datadog-plugin-cucumber/src/index.js
  packages/datadog-plugin-cucumber/test/index.spec.js
  packages/datadog-plugin-cypress/src/plugin.js
  packages/datadog-plugin-cypress/src/support.js
  packages/datadog-plugin-cypress/test/index.spec.js
  packages/datadog-plugin-jest/src/index.js
  packages/datadog-plugin-jest/test/circus.spec.js
  packages/datadog-plugin-mocha/src/index.js
  packages/datadog-plugin-mocha/test/index.spec.js
  packages/datadog-plugin-playwright/src/index.js
  packages/dd-trace/src/plugins/util/test.js
Labels: ci-app, semver-minor

#2995 Add flag to check if rules have been provided by config and check it …
  packages/dd-trace/src/appsec/remote_config/index.js
  packages/dd-trace/src/config.js
  packages/dd-trace/test/appsec/remote_config/index.spec.js
  packages/dd-trace/test/config.spec.js
Labels: bug, semver-patch, asm-waf

#3013 remove old plugin loader system
  packages/dd-trace/src/instrumenter.js
  packages/dd-trace/src/loader.js
  packages/dd-trace/test/instrumenter.spec.js
Labels: semver-patch

#3023 remove dependency on wait-on
  LICENSE-3rdparty.csv
  benchmark/profiler/index.js
  package.json
  yarn.lock
Labels: semver-patch

#3033 [docs] clarify disabling grahql signature caveat
  index.d.ts
Labels: docs, semver-patch

#3037 fix integration tests failing on node 12
  integration-tests/ci-visibility.spec.js
Labels: semver-patch

#2979 Remove very verbose log line with the encoded trace
  packages/dd-trace/src/encode/0.4.js
  packages/dd-trace/test/encode/0.4.spec.js
Labels: core, semver-patch

#2654 Update appsec rules from Remote Config
  package.json
  packages/datadog-plugin-http/src/server.js
  packages/datadog-plugin-http/test/server.spec.js
  packages/datadog-plugin-http2/src/server.js
  packages/datadog-plugin-http2/test/server.spec.js
  packages/dd-trace/src/appsec/addresses.js
  packages/dd-trace/src/appsec/callbacks/ddwaf.js
  packages/dd-trace/src/appsec/callbacks/index.js
  packages/dd-trace/src/appsec/channels.js
  packages/dd-trace/src/appsec/gateway/als.js
  packages/dd-trace/src/appsec/gateway/engine/engine.js
  packages/dd-trace/src/appsec/gateway/engine/index.js
  packages/dd-trace/src/appsec/gateway/engine/runner.js
  packages/dd-trace/src/appsec/index.js
  packages/dd-trace/src/appsec/remote_config/apply_states.js
  packages/dd-trace/src/appsec/remote_config/capabilities.js
  packages/dd-trace/src/appsec/remote_config/index.js
  packages/dd-trace/src/appsec/remote_config/manager.js
  packages/dd-trace/src/appsec/reporter.js
  packages/dd-trace/src/appsec/rule_manager.js
  packages/dd-trace/src/appsec/sdk/user_blocking.js
  packages/dd-trace/src/appsec/waf/index.js
  packages/dd-trace/src/appsec/waf/waf_context_wrapper.js
  packages/dd-trace/src/appsec/waf/waf_manager.js
  packages/dd-trace/test/appsec/callbacks/ddwaf.spec.js
  packages/dd-trace/test/appsec/gateway/engine/engine.spec.js
  packages/dd-trace/test/appsec/gateway/engine/index.spec.js
  packages/dd-trace/test/appsec/gateway/engine/runner.spec.js
  packages/dd-trace/test/appsec/index.spec.js
  packages/dd-trace/test/appsec/remote_config/index.spec.js
  packages/dd-trace/test/appsec/remote_config/manager.spec.js
  packages/dd-trace/test/appsec/reporter.spec.js
  packages/dd-trace/test/appsec/rule_manager.spec.js
  packages/dd-trace/test/appsec/sdk/user_blocking.spec.js
  packages/dd-trace/test/appsec/waf/index.spec.js
  packages/dd-trace/test/plugins/util/ip_extractor.spec.js
  packages/dd-trace/test/plugins/util/web.spec.js
  yarn.lock
Labels: asm-waf, semver-minor

#3059 [ci-visibility] Fix `playwright` integration tests
  packages/datadog-instrumentations/src/playwright.js
Labels: ci-app, semver-patch

#2994 Add pg to appsec plugins tests.
  .github/workflows/appsec.yml
Labels: semver-patch, asm-iast

#3082 Update AppSec rules to 1.7.0
  packages/dd-trace/src/appsec/recommended.json
Labels: asm-waf, semver-minor

#3039 Switch reliability env deploys to be scheduled
  .gitlab-ci.yml
Labels: semver-patch

#2789 Suspicious request blocking
  .github/workflows/appsec.yml
  .github/workflows/plugins.yml
  package.json
  packages/datadog-instrumentations/src/body-parser.js
  packages/datadog-instrumentations/src/express.js
  packages/datadog-instrumentations/src/http/server.js
  packages/datadog-instrumentations/test/body-parser.spec.js
  packages/datadog-instrumentations/test/express.spec.js
  packages/datadog-plugin-http/src/server.js
  packages/datadog-plugin-http2/src/server.js
  packages/datadog-plugin-http2/test/server.spec.js
  packages/dd-trace/src/appsec/blocked_templates.js
  packages/dd-trace/src/appsec/blocking.js
  packages/dd-trace/src/appsec/channels.js
  packages/dd-trace/src/appsec/iast/taint-tracking/plugin.js
  packages/dd-trace/src/appsec/index.js
  packages/dd-trace/src/appsec/remote_config/capabilities.js
  packages/dd-trace/src/appsec/remote_config/index.js
  packages/dd-trace/test/appsec/blocking.spec.js
  packages/dd-trace/test/appsec/body-parser-rules.json
  packages/dd-trace/test/appsec/express-rules.json
  packages/dd-trace/test/appsec/index.body-parser.plugin.spec.js
  packages/dd-trace/test/appsec/index.express.plugin.spec.js
  packages/dd-trace/test/appsec/index.spec.js
  packages/dd-trace/test/appsec/remote_config/index.spec.js
  packages/dd-trace/test/appsec/reporter.spec.js
Labels: asm-waf, semver-minor

#3083 Skip Appsec plugin test for pg version <8.0.3
  packages/dd-trace/test/appsec/iast/analyzers/sql-injection-analyzer.pg.plugin.spec.js
Labels: semver-patch, asm-iast
