Repository DataDog/dd-trace-js, pull requests merged in 2023-06, with the labels that each got.

#3115 Detect SSRF vulnerabilities
  packages/datadog-instrumentations/src/http/client.js
  packages/datadog-instrumentations/src/http2/client.js
  packages/dd-trace/src/appsec/iast/analyzers/analyzers.js
  packages/dd-trace/src/appsec/iast/analyzers/ssrf-analyzer.js
  packages/dd-trace/src/appsec/iast/vulnerabilities-formatter/evidence-redaction/sensitive-analyzers/url-sensitive-analyzer.js
  packages/dd-trace/src/appsec/iast/vulnerabilities-formatter/evidence-redaction/sensitive-handler.js
  packages/dd-trace/src/appsec/iast/vulnerabilities.js
  packages/dd-trace/test/appsec/iast/analyzers/ssrf-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/vulnerability-formatter/resources/evidence-redaction-suite.json
Labels: semver-patch, asm-iast

#3184 Insecure cookie vulnerability detection
  packages/datadog-instrumentations/src/http/server.js
  packages/dd-trace/src/appsec/channels.js
  packages/dd-trace/src/appsec/iast/analyzers/analyzers.js
  packages/dd-trace/src/appsec/iast/analyzers/index.js
  packages/dd-trace/src/appsec/iast/analyzers/insecure-cookie-analyzer.js
  packages/dd-trace/src/appsec/iast/analyzers/set-cookies-header-interceptor.js
  packages/dd-trace/src/appsec/iast/analyzers/sql-injection-analyzer.js
  packages/dd-trace/src/appsec/iast/analyzers/vulnerability-analyzer.js
  packages/dd-trace/src/appsec/iast/path-line.js
  packages/dd-trace/src/appsec/iast/vulnerabilities.js
  packages/dd-trace/src/appsec/iast/vulnerability-reporter.js
  packages/dd-trace/test/appsec/iast/analyzers/insecure-cookie-analyzer.express.plugin.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/insecure-cookie-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/resources/set-cookie-express-functions.js
  packages/dd-trace/test/appsec/iast/analyzers/set-cookies-header-interceptor.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/vulnerability-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/utils.js
  packages/dd-trace/test/appsec/iast/vulnerability-reporter.spec.js
Labels: semver-patch, asm-iast

#3195 Update blocking page and status from RC or rules file
  packages/dd-trace/src/appsec/blocking.js
  packages/dd-trace/src/appsec/remote_config/capabilities.js
  packages/dd-trace/src/appsec/remote_config/index.js
  packages/dd-trace/src/appsec/rule_manager.js
  packages/dd-trace/test/appsec/blocking.spec.js
  packages/dd-trace/test/appsec/index.spec.js
  packages/dd-trace/test/appsec/remote_config/index.spec.js
  packages/dd-trace/test/appsec/rule_manager.spec.js
Labels: asm-waf, semver-minor

#3167 [ci-visibility] Test skipping logic for cypress
  integration-tests/ci-visibility-intake.js
  integration-tests/ci-visibility.spec.js
  integration-tests/cucumber/cucumber.spec.js
  integration-tests/cypress-config.json
  integration-tests/cypress.config.js
  integration-tests/cypress/cypress.spec.js
  packages/datadog-plugin-cypress/src/plugin.js
  packages/datadog-plugin-cypress/src/support.js
  packages/dd-trace/src/ci-visibility/intelligent-test-runner/get-skippable-suites.js
Labels: ci-app, semver-minor

#3178 Make HTTP clients fit in the plugin hierarchy
  packages/datadog-plugin-http/src/client.js
  packages/datadog-plugin-http2/src/client.js
Labels: semver-minor

#3208 Replace rmSync by unlinkSync
  packages/dd-trace/test/appsec/iast/analyzers/insecure-cookie-analyzer.express.plugin.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/path-traversal-analyzer.spec.js
Labels: semver-patch, asm-iast

#2887 add test agent to CI
  .github/actions/testagent/logs/action.yml
  .github/actions/testagent/start/action.yml
  .github/workflows/lambda.yml
  .github/workflows/plugins.yml
  docker-compose.yml
  packages/dd-trace/test/plugins/agent.js
Labels: semver-patch

#3203 improve express regex middleware path parsing
  packages/datadog-plugin-express/test/index.spec.js
  packages/datadog-plugin-router/src/index.js
Labels: semver-patch, integration-express

#3055 Include send-data missing headers and organize telemetry config variables
  packages/dd-trace/src/appsec/iast/telemetry/logs.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/telemetry/index.js
  packages/dd-trace/src/telemetry/send-data.js
  packages/dd-trace/test/appsec/iast/iast-log.spec.js
  packages/dd-trace/test/appsec/iast/telemetry/logs.spec.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/telemetry/index.spec.js
  packages/dd-trace/test/telemetry/send-data.spec.js
Labels: semver-patch

#3189 Add ability to create and publish .deb and .rpm packages
  .gitlab-ci.yml
  .gitlab/build-deb-rpm.sh
Labels: semver-patch

#3212 pg: do not throw when query contains getter
  packages/datadog-instrumentations/src/pg.js
  packages/datadog-plugin-pg/test/index.spec.js
Labels: semver-patch, integration-pg

#3215 esbuild: graceful continue when bundling dead code
  LICENSE-3rdparty.csv
  integration-tests/esbuild/basic-test.js
  integration-tests/esbuild/build.js
  integration-tests/esbuild/package.json
  package.json
  packages/datadog-esbuild/index.js
Labels: semver-patch, bundler

#3216 resolve oracledb plugin step failing
  .github/actions/testagent/logs/action.yml
  .github/workflows/plugins.yml
Labels: semver-patch

#2498 OTel SDK
  LICENSE-3rdparty.csv
  docs/API.md
  docs/test.ts
  index.d.ts
  integration-tests/opentelemetry.spec.js
  integration-tests/opentelemetry/basic.js
  integration-tests/opentelemetry/server.js
  package.json
  packages/dd-trace/src/opentelemetry/context_manager.js
  packages/dd-trace/src/opentelemetry/sampler.js
  packages/dd-trace/src/opentelemetry/span.js
  packages/dd-trace/src/opentelemetry/span_context.js
  packages/dd-trace/src/opentelemetry/span_processor.js
  packages/dd-trace/src/opentelemetry/tracer.js
  packages/dd-trace/src/opentelemetry/tracer_provider.js
  packages/dd-trace/src/opentracing/span.js
  packages/dd-trace/src/proxy.js
  packages/dd-trace/test/opentelemetry/sampler.spec.js
  packages/dd-trace/test/opentelemetry/span.spec.js
  packages/dd-trace/test/opentelemetry/span_context.spec.js
  packages/dd-trace/test/opentelemetry/span_processor.spec.js
  packages/dd-trace/test/opentelemetry/tracer.spec.js
  packages/dd-trace/test/opentelemetry/tracer_provider.spec.js
  yarn.lock
Labels: semver-minor

#3214 [ci-visibility] Fix `after` and `afterEach` hooks in Cypress
  integration-tests/cypress/cypress.spec.js
  integration-tests/cypress/e2e/hook-describe-error.cy.js
  integration-tests/cypress/e2e/hook-test-error.cy.js
  packages/datadog-plugin-cypress/src/plugin.js
  packages/datadog-plugin-cypress/src/support.js
  packages/datadog-plugin-cypress/test/index.spec.js
Labels: ci-app, semver-patch

#3223 Add exclusions from weak hash vulnerabilities
  packages/dd-trace/src/appsec/iast/analyzers/weak-hash-analyzer.js
  packages/dd-trace/test/appsec/iast/analyzers/weak-hash-analyzer.spec.js
Labels: semver-patch

#3227 Enable SSRF evidence redaction test
  packages/dd-trace/test/appsec/iast/vulnerability-formatter/index.spec.js
Labels: semver-patch

#3233 Use older @opentelemetry/core for v12 compatibility
  docs/test.ts
  package.json
  packages/dd-trace/src/opentelemetry/span.js
  packages/dd-trace/test/opentelemetry/tracer.spec.js
  yarn.lock
Labels: semver-patch

#3204 Unvalidated redirect analyzer
  packages/dd-trace/src/appsec/iast/analyzers/analyzers.js
  packages/dd-trace/src/appsec/iast/analyzers/insecure-cookie-analyzer.js
  packages/dd-trace/src/appsec/iast/analyzers/sql-injection-analyzer.js
  packages/dd-trace/src/appsec/iast/analyzers/unvalidated-redirect-analyzer.js
  packages/dd-trace/src/appsec/iast/path-line.js
  packages/dd-trace/src/appsec/iast/taint-tracking/origin-types.js
  packages/dd-trace/src/appsec/iast/vulnerabilities-formatter/evidence-redaction/sensitive-handler.js
  packages/dd-trace/src/appsec/iast/vulnerabilities.js
  packages/dd-trace/test/appsec/iast/analyzers/resources/redirect-express-functions.js
  packages/dd-trace/test/appsec/iast/analyzers/unvalidated-redirect-analyzer.express.plugin.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/unvalidated-redirect-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/path-line.spec.js
  packages/dd-trace/test/appsec/iast/utils.js
  packages/dd-trace/test/appsec/iast/vulnerability-formatter/resources/evidence-redaction-suite.json
Labels: semver-minor, asm-iast

#3235 make tracer config available to plugins
  packages/dd-trace/src/plugin_manager.js
  packages/dd-trace/src/plugins/database.js
  packages/dd-trace/src/plugins/plugin.js
Labels: semver-patch

#3231 Add _dd.iast.enabled=1 in out of request vulnerabilities tags
  packages/dd-trace/src/appsec/iast/index.js
  packages/dd-trace/src/appsec/iast/tags.js
  packages/dd-trace/src/appsec/iast/vulnerability-reporter.js
  packages/dd-trace/test/appsec/iast/utils.js
  packages/dd-trace/test/appsec/iast/vulnerability-reporter.spec.js
Labels: semver-patch, asm-iast

#3236 [ci-visibility] Better git commands
  packages/dd-trace/src/plugins/util/exec.js
  packages/dd-trace/src/plugins/util/git.js
  packages/dd-trace/test/plugins/util/git.spec.js
Labels: ci-app, semver-patch

#3241 [ci-visibility] Fix agentless exporter test
  packages/dd-trace/test/ci-visibility/exporters/agentless/exporter.spec.js
  packages/dd-trace/test/ci-visibility/exporters/ci-visibility-exporter.spec.js
Labels: ci-app, semver-patch

#3061 Tedious - service naming
  docker-compose.yml
  packages/datadog-plugin-tedious/src/index.js
  packages/datadog-plugin-tedious/test/index.spec.js
  packages/datadog-plugin-tedious/test/naming.js
  packages/dd-trace/src/service-naming/schemas/v0/storage.js
  packages/dd-trace/src/service-naming/schemas/v1/storage.js
Labels: semver-minor

#3237 Add test in shimmer wrap to preserve function name
  packages/datadog-shimmer/test/shimmer.spec.js
Labels: semver-patch

#3057 MySQL databases - service naming
  packages/datadog-plugin-mariadb/test/index.spec.js
  packages/datadog-plugin-mariadb/test/naming.js
  packages/datadog-plugin-mysql/src/index.js
  packages/datadog-plugin-mysql/test/index.spec.js
  packages/datadog-plugin-mysql/test/naming.js
  packages/datadog-plugin-mysql2/test/index.spec.js
  packages/datadog-plugin-mysql2/test/naming.js
  packages/dd-trace/src/service-naming/schemas/v0/storage.js
  packages/dd-trace/src/service-naming/schemas/v1/storage.js
Labels: semver-minor

#3243 [ci-visibility] Fix windows tracing test
  packages/dd-trace/test/plugins/util/git.spec.js
Labels: ci-app, semver-patch

#3232 Taint cookies and headers
  .github/workflows/appsec.yml
  package.json
  packages/datadog-instrumentations/src/cookie.js
  packages/datadog-instrumentations/src/helpers/hooks.js
  packages/dd-trace/src/appsec/iast/index.js
  packages/dd-trace/src/appsec/iast/taint-tracking/index.js
  packages/dd-trace/src/appsec/iast/taint-tracking/operations.js
  packages/dd-trace/src/appsec/iast/taint-tracking/origin-types.js
  packages/dd-trace/src/appsec/iast/taint-tracking/plugin.js
  packages/dd-trace/test/appsec/iast/taint-tracking/plugin.spec.js
  packages/dd-trace/test/appsec/iast/taint-tracking/sources/taint-tracking.cookie.plugin.spec.js
  packages/dd-trace/test/appsec/iast/taint-tracking/sources/taint-tracking.headers.spec.js
  packages/dd-trace/test/appsec/iast/taint-tracking/taint-tracking-operations.spec.js
  yarn.lock
Labels: semver-minor, asm-iast

#3246 No SameSite cookie vulnerability detection
  packages/dd-trace/src/appsec/iast/analyzers/analyzers.js
  packages/dd-trace/src/appsec/iast/analyzers/no-samesite-cookie-analyzer.js
  packages/dd-trace/src/appsec/iast/vulnerabilities.js
  packages/dd-trace/test/appsec/iast/analyzers/no-samesite-cookie-analyzer.express.plugin.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/no-samesite-cookie-analyzer.spec.js
Labels: semver-minor, asm-iast

#3252 Fix unvalidated redirects
  packages/dd-trace/src/appsec/iast/analyzers/unvalidated-redirect-analyzer.js
  packages/dd-trace/test/appsec/iast/analyzers/unvalidated-redirect-analyzer.express.plugin.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/unvalidated-redirect-analyzer.spec.js
Labels: semver-patch, asm-iast

#3234 add environment variable to disable instrumentations completely
  package.json
  packages/datadog-instrumentations/src/helpers/register.js
  packages/dd-trace/test/config/disabled_instrumentations.spec.js
Labels: semver-minor

#3250 Disable `metrics.spec.js` tests (part of tracing tests) for windows
  packages/dd-trace/test/metrics.spec.js
Labels: semver-patch

#3249 Add sources tests
  packages/dd-trace/test/appsec/iast/taint-tracking/plugin.express.plugin.spec.js
  packages/dd-trace/test/appsec/iast/utils.js
Labels: semver-patch, asm-iast

#3253 [ci-visibility] Use correct repository URL for git metadata upload
  packages/dd-trace/src/ci-visibility/exporters/ci-visibility-exporter.js
  packages/dd-trace/src/ci-visibility/exporters/git/git_metadata.js
  packages/dd-trace/test/ci-visibility/exporters/ci-visibility-exporter.spec.js
  packages/dd-trace/test/ci-visibility/exporters/git/git_metadata.spec.js
Labels: ci-app, semver-patch

#3255 [ci-visibility] Fix random cypress integration tests timeouts
  .github/workflows/project.yml
  integration-tests/cypress/cypress.spec.js
Labels: ci-app, semver-patch

#3260 Reduce request per iteration in IAST benchmarks
  benchmark/sirun/appsec-iast/common.js
  benchmark/sirun/appsec-iast/meta.json
Labels: semver-patch, asm-iast

#3257 Check `store` has value before use it
  packages/dd-trace/src/appsec/iast/analyzers/sql-injection-analyzer.js
  packages/dd-trace/test/appsec/iast/analyzers/sql-injection-analyzer.spec.js
Labels: semver-patch, asm-iast

#3254 Fix setup in integration tests
  .github/workflows/project.yml
Labels: semver-patch

#3248 Auto-instrument @opentelemetry/sdk-trace-node
  integration-tests/opentelemetry.spec.js
  integration-tests/opentelemetry/env-var.js
  package.json
  packages/datadog-instrumentations/src/helpers/hooks.js
  packages/datadog-instrumentations/src/otel-sdk-trace.js
  packages/dd-trace/src/noop/proxy.js
  packages/dd-trace/src/opentelemetry/context_manager.js
  yarn.lock
Labels: semver-patch

#3242 [profiling] Add debug log listing found source maps
  package.json
  packages/dd-trace/src/profiling/profiler.js
  yarn.lock
Labels: profiling, semver-minor

#3258 add support for global fetch
  .github/workflows/plugins.yml
  docs/API.md
  docs/test.ts
  index.d.ts
  packages/datadog-instrumentations/src/fetch.js
  packages/datadog-instrumentations/src/helpers/register.js
  packages/datadog-plugin-fetch/src/index.js
  packages/datadog-plugin-fetch/test/index.spec.js
  packages/datadog-plugin-http/src/client.js
  packages/dd-trace/src/plugin_manager.js
Labels: integrations, semver-minor

#3270 Fix typo --ignore-engine => --ignore-engines
  .github/workflows/plugins.yml
Labels: bug, semver-patch

#3276 Publish "dev" injection image
  .github/workflows/release-dev.yml
  .gitlab-ci.yml
Labels: semver-patch

#3277 Skip OTel auto-instrumentation test as sdk-node does not support Node.js 12
  integration-tests/opentelemetry.spec.js
Labels: semver-patch

#3282 Unify test code between release branches
  packages/datadog-plugin-fetch/test/index.spec.js
  packages/datadog-plugin-http/test/client.spec.js
  packages/datadog-plugin-http2/test/client.spec.js
Labels: semver-patch

#3285 upgrade semver to fix audit lint errors
  yarn.lock
Labels: semver-patch

#3286 Bump profiler version to 2.2.3
  package.json
  packages/dd-trace/src/profiling/config.js
  packages/dd-trace/src/profiling/profiler.js
  yarn.lock
Labels: profiling, semver-minor

#3261 move `HttpServer`, `Http2Server` plugins to `ServerPlugin`s
  packages/datadog-plugin-http/src/server.js
  packages/datadog-plugin-http2/src/server.js
Labels: semver-minor

#3256 Apply service naming workflow to databases
  packages/datadog-plugin-cassandra-driver/src/index.js
  packages/datadog-plugin-cassandra-driver/test/index.spec.js
  packages/datadog-plugin-cassandra-driver/test/naming.js
  packages/datadog-plugin-elasticsearch/src/index.js
  packages/datadog-plugin-elasticsearch/test/index.spec.js
  packages/datadog-plugin-elasticsearch/test/naming.js
  packages/datadog-plugin-mongodb-core/src/index.js
  packages/datadog-plugin-mongodb-core/test/core.spec.js
  packages/datadog-plugin-mongodb-core/test/mongodb.spec.js
  packages/datadog-plugin-mongodb-core/test/naming.js
  packages/datadog-plugin-opensearch/test/index.spec.js
  packages/datadog-plugin-opensearch/test/naming.js
  packages/datadog-plugin-oracledb/src/index.js
  packages/datadog-plugin-oracledb/test/index.spec.js
  packages/datadog-plugin-oracledb/test/naming.js
  packages/datadog-plugin-pg/src/index.js
  packages/datadog-plugin-pg/test/index.spec.js
  packages/datadog-plugin-pg/test/naming.js
  packages/dd-trace/src/service-naming/schemas/v0/storage.js
  packages/dd-trace/src/service-naming/schemas/v1/storage.js
Labels: semver-minor

#3177 Peer service computation
  packages/.eslintrc.json
  packages/datadog-plugin-amqp10/test/index.spec.js
  packages/datadog-plugin-amqplib/test/index.spec.js
  packages/datadog-plugin-dns/src/lookup.js
  packages/datadog-plugin-google-cloud-pubsub/src/consumer.js
  packages/datadog-plugin-graphql/src/execute.js
  packages/datadog-plugin-graphql/src/parse.js
  packages/datadog-plugin-graphql/src/resolve.js
  packages/datadog-plugin-graphql/src/validate.js
  packages/datadog-plugin-grpc/src/client.js
  packages/datadog-plugin-grpc/src/server.js
  packages/datadog-plugin-http/src/client.js
  packages/datadog-plugin-http/test/client.spec.js
  packages/datadog-plugin-http2/src/client.js
  packages/datadog-plugin-http2/test/client.spec.js
  packages/datadog-plugin-memcached/test/index.spec.js
  packages/datadog-plugin-moleculer/src/client.js
  packages/datadog-plugin-moleculer/test/index.spec.js
  packages/datadog-plugin-net/test/index.spec.js
  packages/datadog-plugin-redis/test/legacy.spec.js
  packages/datadog-plugin-rhea/test/index.spec.js
  packages/datadog-plugin-sharedb/src/index.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/constants.js
  packages/dd-trace/src/opentracing/tracer.js
  packages/dd-trace/src/plugins/outbound.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/plugins/outbound.spec.js
  packages/dd-trace/test/setup/mocha.js
Labels: semver-minor

#3251 [ci-visibility] More verbose logging for git upload
  packages/dd-trace/src/ci-visibility/exporters/git/git_metadata.js
  packages/dd-trace/src/plugins/util/exec.js
  packages/dd-trace/src/plugins/util/git.js
Labels: ci-app, semver-patch

#3155 add instrumentation for the openai package
  index.d.ts
  packages/datadog-instrumentations/src/helpers/hooks.js
  packages/datadog-instrumentations/src/openai.js
  packages/datadog-plugin-openai/src/index.js
  packages/datadog-plugin-openai/src/services.js
  packages/datadog-plugin-openai/test/dave-hal.jsonl
  packages/datadog-plugin-openai/test/guten-tag.m4a
  packages/datadog-plugin-openai/test/hal.png
  packages/datadog-plugin-openai/test/hello-friend.m4a
  packages/datadog-plugin-openai/test/index.spec.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/dogstatsd.js
  packages/dd-trace/src/external-logger/src/index.js
  packages/dd-trace/src/plugins/index.js
Labels: semver-minor

#3218 Fix s3 package upload
  .gitlab-ci.yml
Labels: semver-patch

#3259 Telemetry metrics for OTel
  integration-tests/helpers.js
  integration-tests/opentelemetry.spec.js
  integration-tests/opentelemetry/basic.js
  packages/dd-trace/src/opentelemetry/span.js
  packages/dd-trace/src/opentracing/span.js
  packages/dd-trace/src/opentracing/tracer.js
  packages/dd-trace/src/plugins/tracing.js
  packages/dd-trace/src/telemetry/index.js
  packages/dd-trace/src/telemetry/metrics.js
  packages/dd-trace/test/opentracing/tracer.spec.js
  packages/dd-trace/test/telemetry/metrics.spec.js
Labels: semver-minor

#3280 Fix job name
  .github/workflows/release-dev.yml
Labels: semver-patch

#3292 [profiling] Enable OOM monitoring by default
  packages/dd-trace/src/profiling/config.js
  packages/dd-trace/test/profiling/config.spec.js
Labels: profiling, semver-minor

#3281 moleculer - service naming
  packages/datadog-plugin-moleculer/src/client.js
  packages/datadog-plugin-moleculer/src/server.js
  packages/datadog-plugin-moleculer/test/index.spec.js
  packages/datadog-plugin-moleculer/test/naming.js
  packages/dd-trace/src/plugins/client.js
  packages/dd-trace/src/plugins/server.js
  packages/dd-trace/src/service-naming/schemas/v0/index.js
  packages/dd-trace/src/service-naming/schemas/v0/web.js
  packages/dd-trace/src/service-naming/schemas/v1/index.js
  packages/dd-trace/src/service-naming/schemas/v1/web.js
Labels: semver-minor

#3294 openai: use a public domain test image
  packages/datadog-plugin-openai/test/hal.png
  packages/datadog-plugin-openai/test/index.spec.js
  packages/datadog-plugin-openai/test/ntsc.png
Labels: semver-patch

#3287 move next plugin to ServerPlugin
  packages/datadog-plugin-next/src/index.js
Labels: semver-minor

#3187 Taint express route paramaters
  packages/datadog-instrumentations/src/express.js
  packages/dd-trace/src/appsec/iast/taint-tracking/origin-types.js
  packages/dd-trace/src/appsec/iast/taint-tracking/plugin.js
  packages/dd-trace/test/appsec/iast/taint-tracking/plugin.spec.js
  packages/dd-trace/test/appsec/iast/taint-tracking/sources/taint-tracking.express.plugin.spec.js
Labels: semver-minor, asm-iast

#3295 pg: update error string comparison in test
  packages/datadog-plugin-pg/test/index.spec.js
Labels: semver-patch

#3202 [ci-visibility] Support CI Visibility's manual API
  integration-tests/ci-visibility/test-api-manual/run-fake-test-framework.js
  integration-tests/ci-visibility/test-api-manual/setup-fake-test-framework.js
  integration-tests/ci-visibility/test-api-manual/test.fake.js
  integration-tests/test-api-manual.spec.js
  packages/datadog-plugin-mocha/src/index.js
  packages/dd-trace/src/ci-visibility/test-api-manual/test-api-manual-plugin.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/plugin_manager.js
  packages/dd-trace/src/proxy.js
  packages/dd-trace/test/config.spec.js
Labels: ci-app, semver-minor

#3307 pg: retain prototype when injecting DBM comment
  packages/datadog-instrumentations/src/pg.js
  packages/datadog-plugin-pg/src/index.js
  packages/datadog-plugin-pg/test/index.spec.js
Labels: semver-patch, integration-pg

#3303 mongodb expose peer.service
  packages/datadog-plugin-mongodb-core/src/index.js
  packages/datadog-plugin-mongodb-core/test/mongodb.spec.js
  packages/datadog-plugin-mongoose/test/index.spec.js
  packages/dd-trace/src/plugins/outbound.js
Labels: semver-minor

#3299 rdbms: add precursors and test for peer.service calculation
  packages/datadog-plugin-mariadb/test/index.spec.js
  packages/datadog-plugin-mysql/test/index.spec.js
  packages/datadog-plugin-mysql2/test/index.spec.js
  packages/datadog-plugin-oracledb/src/index.js
  packages/datadog-plugin-oracledb/test/index.spec.js
  packages/datadog-plugin-pg/test/index.spec.js
  packages/datadog-plugin-tedious/test/index.spec.js
  packages/dd-trace/src/plugins/database.js
Labels: semver-minor

#3297 add peer.service precursor for gprc client
  packages/datadog-plugin-grpc/src/client.js
  packages/datadog-plugin-grpc/test/client.spec.js
Labels: semver-minor

#3291 [profiling] Add support for standard profiling env variables
  packages/dd-trace/src/profiling/config.js
  packages/dd-trace/test/profiling/config.spec.js
Labels: profiling, semver-minor
