Repository DataDog/dd-trace-js, pull requests merged in 2023-02, with the labels that each got.

#2742 Update asm waf rules to 1.5.0 version.
  packages/dd-trace/src/appsec/recommended.json
Labels: semver-minor

#2748 Fix mongodb 5.0 test
  packages/datadog-plugin-mongodb-core/test/mongodb.spec.js
Labels: semver-patch

#2747 Fix path traversal test in node 12
  packages/dd-trace/test/appsec/iast/analyzers/path-traversal-analyzer.spec.js
Labels: semver-patch

#2749 [ci-visibility] Do not run latest version of playwright integration tests in node 12
  integration-tests/playwright.spec.js
Labels: ci-app, semver-patch

#2751 Fix mongodb test in node12
  packages/datadog-plugin-mongodb-core/test/mongodb.spec.js
Labels: semver-patch

#2556 Add appsec folder to CODEOWNERS
  CODEOWNERS
Labels: semver-patch

#2758 Fix require("node:fs") bug
  packages/datadog-instrumentations/src/fs.js
  packages/datadog-instrumentations/test/fs.spec.js
Labels: semver-patch

#2761 Fix fs instrumentation test in node12
  packages/datadog-instrumentations/test/fs.spec.js
Labels: semver-patch

#2756 [ci-visibility] Keep functionality with `.asyncResource`
  packages/datadog-instrumentations/src/mocha.js
Labels: semver-patch

#2757 Fix log error message when intake request fails
  packages/dd-trace/src/exporters/common/request.js
  packages/dd-trace/test/ci-visibility/exporters/git/git_metadata.spec.js
  packages/dd-trace/test/exporters/common/request.spec.js
Labels: semver-patch

#2755 Add `dev` release line on merge to `master`
  .github/workflows/release-dev.yml
Labels: dev/tooling, semver-patch

#2767 [ci-visibility] Update ITR tags
  integration-tests/ci-visibility.spec.js
  packages/datadog-plugin-jest/src/index.js
  packages/datadog-plugin-jest/test/circus.spec.js
  packages/datadog-plugin-mocha/src/index.js
  packages/dd-trace/src/plugins/util/test.js
Labels: ci-app, semver-patch

#2770 Check if channel has subscribers before call unsubscribe
  packages/dd-trace/src/log/writer.js
Labels: semver-patch, asm-iast

#2752 Reduce flaky tests
  packages/dd-trace/test/appsec/iast/analyzers/command-injection-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/ldap-injection-analyzer.ldapjs.plugin.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/path-traversal-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/sql-injection-analyzer.mysql.plugin.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/sql-injection-analyzer.mysql2.plugin.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/sql-injection-analyzer.pg.plugin.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/weak-cipher-analyzers.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/weak-hash-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/taint-tracking/taint-tracking-impl.spec.js
  packages/dd-trace/test/appsec/iast/utils.js
  packages/dd-trace/test/appsec/index.spec.js
Labels: semver-patch, asm-waf, asm-iast

#2777 Fix lib-injection test
  .github/workflows/test-k8s-lib-injection.yaml
Labels: semver-minor

#2774 [ci-visibility] One git upload per test session
  ci/init.js
  packages/datadog-instrumentations/src/jest.js
  packages/datadog-instrumentations/src/mocha.js
  packages/dd-trace/src/ci-visibility/exporters/agent-proxy/index.js
  packages/dd-trace/src/ci-visibility/exporters/agentless/index.js
  packages/dd-trace/src/ci-visibility/exporters/ci-visibility-exporter.js
  packages/dd-trace/src/plugins/ci_plugin.js
  packages/dd-trace/test/ci-visibility/exporters/agent-proxy/agent-proxy.spec.js
  packages/dd-trace/test/ci-visibility/exporters/agentless/exporter.spec.js
  packages/dd-trace/test/ci-visibility/exporters/ci-visibility-exporter.spec.js
Labels: semver-patch

#2782 [ci-visibility] Add test suite level visibility to cucumber
  integration-tests/ci-visibility/features/farewell.feature
  integration-tests/ci-visibility/features/greetings.feature
  integration-tests/ci-visibility/features/support/steps.js
  integration-tests/cucumber.spec.js
  packages/datadog-instrumentations/src/cucumber.js
  packages/datadog-instrumentations/src/helpers/register.js
  packages/datadog-plugin-cucumber/src/index.js
  packages/datadog-plugin-jest/src/index.js
  packages/datadog-plugin-mocha/src/index.js
  packages/datadog-plugin-playwright/src/index.js
Labels: ci-app, semver-minor

#2794 rename topSpan to rootSpan
  packages/dd-trace/src/appsec/reporter.js
  packages/dd-trace/test/appsec/index.spec.js
Labels: semver-patch, asm-waf

#2778 remove unused config fields from telemetry
  packages/dd-trace/src/telemetry/send-data.js
Labels: semver-patch

#2783 [ci-visibility] Add test suite level visibility to cypress
  integration-tests/cypress-config.json
  integration-tests/cypress.config.js
  integration-tests/cypress.spec.js
  integration-tests/cypress/e2e/other.cy.js
  integration-tests/cypress/e2e/spec.cy.js
  integration-tests/cypress/plugins-old/index.js
  integration-tests/cypress/support/e2e.js
  packages/datadog-plugin-cypress/src/plugin.js
  packages/datadog-plugin-cypress/src/support.js
Labels: ci-app, semver-minor

#2793 [ci-visibility] Update framework version calculation in ci plugins
  packages/datadog-instrumentations/src/cucumber.js
  packages/datadog-instrumentations/src/jest.js
  packages/datadog-instrumentations/src/mocha.js
  packages/datadog-instrumentations/src/playwright.js
  packages/datadog-plugin-cucumber/src/index.js
  packages/datadog-plugin-jest/src/index.js
  packages/datadog-plugin-mocha/src/index.js
  packages/datadog-plugin-playwright/src/index.js
  packages/dd-trace/src/plugins/ci_plugin.js
Labels: semver-patch

#2781 remove resource truncation w/ agent, keep w/ agentless
  packages/datadog-plugin-pg/test/index.spec.js
  packages/dd-trace/src/encode/0.4.js
  packages/dd-trace/src/encode/0.5.js
  packages/dd-trace/src/encode/tags-processors.js
  packages/dd-trace/test/encode/0.4.spec.js
  packages/dd-trace/test/encode/0.5.spec.js
Labels: semver-patch

#2477 Fully support W3C Trace Context headers
  index.d.ts
  packages/dd-trace/src/config.js
  packages/dd-trace/src/opentracing/propagation/text_map.js
  packages/dd-trace/src/opentracing/propagation/tracestate.js
  packages/dd-trace/src/opentracing/span.js
  packages/dd-trace/src/opentracing/span_context.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/opentracing/propagation/text_map.spec.js
  packages/dd-trace/test/opentracing/propagation/tracestate.spec.js
  packages/dd-trace/test/opentracing/span_context.spec.js
Labels: semver-minor

#2788 [ci-visibility] Increase timeout for `/skippable` call
  packages/dd-trace/src/ci-visibility/intelligent-test-runner/get-skippable-suites.js
Labels: ci-app, semver-patch

#2798 [ci-visibility] Fix cypress test suite level visibility for some cases
  packages/datadog-instrumentations/src/cypress.js
  packages/datadog-plugin-cypress/src/plugin.js
Labels: ci-app, semver-patch

#2801 [ci-visibility] Fix cypress integration test for older node versions
  integration-tests/cypress.spec.js
Labels: ci-app, semver-patch

#2795 [ci-visibility] Move common functionality to `CiPlugin`
  packages/datadog-plugin-cucumber/src/index.js
  packages/datadog-plugin-jest/src/index.js
  packages/datadog-plugin-mocha/src/index.js
  packages/datadog-plugin-playwright/src/index.js
  packages/dd-trace/src/plugins/ci_plugin.js
Labels: ci-app, semver-patch

#2811 set minimum version for aws-sdk tests to node 14
  .github/workflows/plugins.yml
Labels: semver-patch

#2812 no longer test mariadb against node v12
  .github/workflows/plugins.yml
Labels: semver-patch

#2810 fix traceparent version and version propagation
  packages/datadog-plugin-mysql/test/index.spec.js
  packages/datadog-plugin-mysql2/test/index.spec.js
  packages/datadog-plugin-pg/test/index.spec.js
  packages/dd-trace/src/opentracing/propagation/text_map.js
  packages/dd-trace/src/opentracing/span_context.js
  packages/dd-trace/test/opentracing/propagation/text_map.spec.js
  packages/dd-trace/test/opentracing/span_context.spec.js
Labels: bug, semver-patch

#2813 fix client errors being flagged as errors for boom
  packages/datadog-plugin-hapi/src/index.js
  packages/datadog-plugin-hapi/test/index.spec.js
  packages/dd-trace/test/plugins/externals.json
Labels: bug, semver-patch

#2818 Update rules to version 1.5.1.
  packages/dd-trace/src/appsec/recommended.json
Labels: asm-waf, semver-minor

#2807 Don't block request if headers have been sent
  packages/dd-trace/src/appsec/blocking.js
  packages/dd-trace/test/appsec/blocking.spec.js
  packages/dd-trace/test/appsec/sdk/user_blocking.spec.js
Labels: semver-patch, asm-waf

#2809 [ci-visibility] Support custom test configurations in ITR
  packages/dd-trace/src/ci-visibility/exporters/ci-visibility-exporter.js
  packages/dd-trace/src/ci-visibility/intelligent-test-runner/get-itr-configuration.js
  packages/dd-trace/src/ci-visibility/intelligent-test-runner/get-skippable-suites.js
  packages/dd-trace/test/ci-visibility/exporters/ci-visibility-exporter.spec.js
Labels: ci-app, semver-patch

#2803 [ci-visibility] Automatically unshallow repo
  packages/dd-trace/src/ci-visibility/exporters/git/git_metadata.js
  packages/dd-trace/src/plugins/util/exec.js
  packages/dd-trace/src/plugins/util/git.js
  packages/dd-trace/test/ci-visibility/exporters/agentless/exporter.spec.js
  packages/dd-trace/test/ci-visibility/exporters/ci-visibility-exporter.spec.js
  packages/dd-trace/test/ci-visibility/exporters/git/git_metadata.spec.js
Labels: ci-app, semver-minor

#2779 Fix span sampling
  packages/dd-trace/src/opentracing/span_context.js
  packages/dd-trace/src/span_processor.js
  packages/dd-trace/src/span_sampler.js
  packages/dd-trace/test/opentracing/span_context.spec.js
  packages/dd-trace/test/span_processor.spec.js
  packages/dd-trace/test/span_sampler.spec.js
Labels: bug, semver-patch

#2806 Control naming of profile filename for file exporter
  packages/dd-trace/src/profiling/config.js
  packages/dd-trace/src/profiling/exporters/file.js
  packages/dd-trace/test/profiling/exporters/file.spec.js
Labels: semver-minor

#2720 Make sure that current profiles are collected and exported when process exits
  integration-tests/helpers.js
  integration-tests/profiler.spec.js
  integration-tests/profiler/index.js
  packages/dd-trace/src/profiler.js
  packages/dd-trace/src/profiling/profiler.js
  packages/dd-trace/src/profiling/profilers/wall.js
  packages/dd-trace/test/profiling/profiler.spec.js
  packages/dd-trace/test/profiling/profilers/wall.spec.js
Labels: semver-patch

#2832 Skip breaking playwright version
  integration-tests/playwright.spec.js
Labels: bug, ci-app, semver-patch

#2830 [docs] clarify supported node.js version ranges
  README.md
Labels: semver-patch

#2829 [ci-visibility] Change git upload to opt out
  integration-tests/helpers.js
  packages/dd-trace/src/config.js
  packages/dd-trace/test/config.spec.js
Labels: ci-app, semver-minor

#2839 [ci-visibility] Fix jest worker shutdown
  ci/init.js
  packages/datadog-instrumentations/src/helpers/hooks.js
  packages/datadog-instrumentations/src/jest.js
  packages/datadog-plugin-jest/src/index.js
  packages/dd-trace/src/plugins/index.js
Labels: ci-app, semver-patch, dont-land-on-v2.x, dont-land-on-v3.x

#2840 [ci-visibility] Undo `jest` flush interval change
  ci/init.js
Labels: ci-app, semver-patch, dont-land-on-v2.x, dont-land-on-v3.x

#2838 Ldap plugin fixes
  package.json
  packages/datadog-instrumentations/src/ldapjs.js
  packages/dd-trace/src/appsec/iast/iast-context.js
  packages/dd-trace/src/appsec/iast/index.js
  packages/dd-trace/test/appsec/iast/analyzers/ldap-injection-analyzer.ldapjs.plugin.spec.js
  packages/dd-trace/test/appsec/iast/iast-context.spec.js
  yarn.lock
Labels: bug, semver-patch, asm-iast
