Repository DataDog/dd-trace-js, pull requests merged in 2023-10, with the labels that each got.

#3664 [ci-visibility] Improve git unshallow command
  packages/dd-trace/src/plugins/util/git.js
  packages/dd-trace/test/plugins/util/git.spec.js
Labels: ci-app, semver-patch

#3641 Support threat detection in nextjs [APPSEC-10719]
  .github/workflows/appsec.yml
  .gitignore
  packages/datadog-instrumentations/src/body-parser.js
  packages/datadog-instrumentations/src/express.js
  packages/datadog-instrumentations/src/next.js
  packages/dd-trace/src/appsec/channels.js
  packages/dd-trace/src/appsec/index.js
  packages/dd-trace/test/appsec/index.next.plugin.spec.js
  packages/dd-trace/test/appsec/index.spec.js
  packages/dd-trace/test/appsec/next/app-dir/app/api/test-text/route.js
  packages/dd-trace/test/appsec/next/app-dir/app/api/test/route.js
  packages/dd-trace/test/appsec/next/app-dir/app/layout.js
  packages/dd-trace/test/appsec/next/app-dir/app/page.js
  packages/dd-trace/test/appsec/next/app-dir/appsec-rules.json
  packages/dd-trace/test/appsec/next/app-dir/datadog.js
  packages/dd-trace/test/appsec/next/app-dir/jsconfig.json
  packages/dd-trace/test/appsec/next/app-dir/next.config.js
  packages/dd-trace/test/appsec/next/pages-dir/appsec-rules.json
  packages/dd-trace/test/appsec/next/pages-dir/datadog.js
  packages/dd-trace/test/appsec/next/pages-dir/naming.js
  packages/dd-trace/test/appsec/next/pages-dir/next.config.js
  packages/dd-trace/test/appsec/next/pages-dir/pages/api/test/index.js
  packages/dd-trace/test/appsec/next/pages-dir/public/test.txt
  packages/dd-trace/test/appsec/next/pages-dir/server.js
Labels: semver-minor

#3607 Fix SQLi location when using knex [APPSEC-10688]
  .github/workflows/appsec.yml
  packages/datadog-instrumentations/src/knex.js
  packages/dd-trace/src/appsec/iast/analyzers/sql-injection-analyzer.js
  packages/dd-trace/test/appsec/iast/analyzers/resources/knex-sql-injection-methods.js
  packages/dd-trace/test/appsec/iast/analyzers/resources/sql-injection-methods.js
  packages/dd-trace/test/appsec/iast/analyzers/sql-injection-analyzer.knex.plugin.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/sql-injection-analyzer.spec.js
Labels: semver-patch, asm-iast

#3668 [ci-visibility] Fix unshallow logic
  packages/dd-trace/src/plugins/util/git.js
Labels: ci-app, semver-patch

#3644 Change source origin from HTTP_REQUEST_PATH to HTTP_REQUEST_URI [APPSEC-11398]
  packages/dd-trace/src/appsec/iast/analyzers/unvalidated-redirect-analyzer.js
  packages/dd-trace/src/appsec/iast/taint-tracking/plugin.js
  packages/dd-trace/src/appsec/iast/taint-tracking/source-types.js
  packages/dd-trace/test/appsec/iast/analyzers/unvalidated-redirect-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/taint-tracking/plugin.spec.js
  packages/dd-trace/test/appsec/iast/taint-tracking/sources/taint-tracking.express.plugin.spec.js
  packages/dd-trace/test/appsec/iast/telemetry/index.spec.js
Labels: semver-minor, asm-iast

#3672 Fix flakiness in `serverless-performance`
  .github/workflows/serverless-performance.yml
Labels: semver-patch

#3671 Prevent sending query address twice to the waf
  packages/dd-trace/src/appsec/index.js
  packages/dd-trace/src/appsec/waf/waf_context_wrapper.js
  packages/dd-trace/test/appsec/index.spec.js
  packages/dd-trace/test/appsec/waf/waf_context_wrapper.spec.js
Labels: semver-patch

#3675 Fix flakiness in integration tests
  integration-tests/helpers.js
  integration-tests/startup.spec.js
Labels: semver-patch

#3665 Fix `exporting-pipeline` benchmark
  benchmark/sirun/exporting-pipeline/index.js
Labels: semver-patch

#3483 Mongodb nosqli detection [APPSEC-10226]
  .github/workflows/appsec.yml
  .github/workflows/plugins.yml
  package.json
  packages/datadog-instrumentations/src/express-mongo-sanitize.js
  packages/datadog-instrumentations/src/helpers/hooks.js
  packages/datadog-instrumentations/src/mongodb.js
  packages/datadog-instrumentations/src/mongoose.js
  packages/datadog-instrumentations/test/express-mongo-sanitize.spec.js
  packages/datadog-instrumentations/test/mongoose.spec.js
  packages/dd-trace/src/appsec/iast/analyzers/analyzers.js
  packages/dd-trace/src/appsec/iast/analyzers/nosql-injection-mongodb-analyzer.js
  packages/dd-trace/src/appsec/iast/analyzers/vulnerability-analyzer.js
  packages/dd-trace/src/appsec/iast/iast-plugin.js
  packages/dd-trace/src/appsec/iast/taint-tracking/operations.js
  packages/dd-trace/src/appsec/iast/taint-tracking/secure-marks-generator.js
  packages/dd-trace/src/appsec/iast/vulnerabilities-formatter/evidence-redaction/sensitive-analyzers/json-sensitive-analyzer.js
  packages/dd-trace/src/appsec/iast/vulnerabilities-formatter/evidence-redaction/sensitive-handler.js
  packages/dd-trace/src/appsec/iast/vulnerabilities-formatter/evidence-redaction/sensitive-regex.js
  packages/dd-trace/src/appsec/iast/vulnerabilities-formatter/index.js
  packages/dd-trace/src/appsec/iast/vulnerabilities-formatter/utils.js
  packages/dd-trace/src/appsec/iast/vulnerabilities.js
  packages/dd-trace/test/appsec/iast/analyzers/nosql-injection-mongodb-analyzer.express-mongo-sanitize.plugin.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/nosql-injection-mongodb-analyzer.mongoose.plugin.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/nosql-injection-mongodb-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/resources/mongodb-vulnerable-method.js
  packages/dd-trace/test/appsec/iast/analyzers/resources/mongoose-vulnerable-method.js
  packages/dd-trace/test/appsec/iast/taint-tracking/secure-marks-generator.spec.js
  packages/dd-trace/test/appsec/iast/utils.js
  packages/dd-trace/test/appsec/iast/vulnerability-formatter/resources/evidence-redaction-suite.json
  packages/dd-trace/test/appsec/iast/vulnerability-formatter/utils.spec.js
  packages/dd-trace/test/plugins/externals.json
  yarn.lock
Labels: semver-minor, asm-iast

#3661 [ci-visibility] Unskippable tests for mocha
  integration-tests/ci-visibility.spec.js
  integration-tests/ci-visibility/run-jest.js
  integration-tests/ci-visibility/run-jest.mjs
  integration-tests/ci-visibility/run-mocha.js
  integration-tests/ci-visibility/run-mocha.mjs
  packages/datadog-instrumentations/src/jest.js
  packages/datadog-instrumentations/src/mocha.js
  packages/datadog-plugin-jest/src/index.js
  packages/datadog-plugin-jest/src/util.js
  packages/datadog-plugin-jest/test/util.spec.js
  packages/datadog-plugin-mocha/src/index.js
  packages/dd-trace/src/plugins/util/test.js
Labels: ci-app, semver-minor

#3681 [ci-visibility] Unskippable suites for cucumber
  integration-tests/ci-visibility/features/greetings.feature
  integration-tests/cucumber/cucumber.spec.js
  packages/datadog-instrumentations/src/cucumber.js
  packages/datadog-plugin-cucumber/src/index.js
Labels: ci-app, semver-minor

#3692 [ci-visibility] Add support for AWS Codepipeline
  packages/dd-trace/src/plugins/util/ci.js
  packages/dd-trace/test/plugins/util/ci-env/awscodepipeline.json
Labels: ci-app, semver-minor

#3698 [ci-visibility] Fix cucumber integration tests
  integration-tests/cucumber/cucumber.spec.js
Labels: ci-app, semver-patch

#3688 Add an integration test for Code Hotspots and Endpoint Profiling
  integration-tests/profiler.spec.js
  integration-tests/profiler/codehotspots.js
Labels: profiling, semver-minor

#3701 fix failing sirun benchmark tests for graphql
  benchmark/sirun/plugin-graphql/index.js
  benchmark/sirun/plugin-graphql/schema.js
Labels: semver-patch

#3693 Enable appsec telemetry before waf init
  packages/dd-trace/src/appsec/index.js
  packages/dd-trace/test/appsec/index.spec.js
Labels: semver-patch, asm-waf

#3712 [ci-visibility] Fix playwright latest release
  packages/datadog-instrumentations/src/playwright.js
Labels: ci-app, semver-patch

#3717 Fix supported MongoDB versions in NoSQL injection test
  packages/datadog-instrumentations/src/mongodb.js
  packages/dd-trace/test/appsec/iast/analyzers/nosql-injection-mongodb-analyzer.express-mongo-sanitize.plugin.spec.js
  packages/dd-trace/test/plugins/externals.json
Labels: semver-minor, asm-iast

#3723 Fix release scripts
  .github/workflows/release-3.yml
  .github/workflows/release-latest.yml
Labels: dev/tooling, semver-patch

#3669 report tested integrations and their tested versions
  .github/actions/testagent/logs/action.yml
  docker-compose.yml
  packages/dd-trace/test/plugins/agent.js
  packages/dd-trace/test/setup/mocha.js
Labels: semver-minor

#3729 Support node21
  .github/actions/node/20/action.yml
  .github/workflows/appsec.yml
  .github/workflows/lambda.yml
  .github/workflows/plugins.yml
  .github/workflows/profiling.yml
  .github/workflows/tracing.yml
  package.json
  packages/dd-trace/test/appsec/iast/analyzers/sql-injection-analyzer.knex.plugin.spec.js
  yarn.lock
Labels: semver-patch

#3569 Add a security review section to PR template
  .github/pull_request_template.md
Labels: dev/tooling, semver-patch

#3726 PROF-8457 Emit thread names in wall profiles
  integration-tests/profiler.spec.js
  packages/dd-trace/src/profiling/profilers/wall.js
Labels: profiling, semver-minor

#3741 [ci-visibility] Add custom tags capability to playwright tests
  integration-tests/ci-visibility/playwright-tests/landing-page-test.js
  integration-tests/playwright/playwright.spec.js
  packages/datadog-instrumentations/src/playwright.js
  packages/datadog-plugin-playwright/src/index.js
  packages/dd-trace/src/plugins/util/test.js
  packages/dd-trace/test/plugins/util/test.spec.js
Labels: ci-app, semver-minor

#3735 [ci-visibility] Instrument suite parsing errors as failed suites
  integration-tests/ci-visibility.spec.js
  integration-tests/ci-visibility/test-parsing-error/parsing-error-2.js
  integration-tests/ci-visibility/test-parsing-error/parsing-error.js
  packages/datadog-instrumentations/src/jest.js
  packages/datadog-plugin-jest/src/index.js
Labels: ci-app, semver-patch

#3742 [ci-visibility] Better logs for intelligent test runner
  packages/datadog-instrumentations/src/cucumber.js
  packages/datadog-instrumentations/src/jest.js
  packages/datadog-instrumentations/src/mocha.js
  packages/dd-trace/src/ci-visibility/intelligent-test-runner/get-itr-configuration.js
  packages/dd-trace/src/ci-visibility/intelligent-test-runner/get-skippable-suites.js
Labels: ci-app, semver-minor

#3744 Remove user credentials from `DD_GIT_REPOSITORY_URL`
  packages/dd-trace/src/config.js
  packages/dd-trace/src/git_properties.js
  packages/dd-trace/test/config.spec.js
Labels: semver-patch

#3746 [ci-visibility] Add test for playwright custom metrics
  integration-tests/ci-visibility/playwright-tests/landing-page-test.js
  integration-tests/playwright/playwright.spec.js
Labels: ci-app, semver-patch

#3748 Fix Next.js Build Errors When `node:*` Modules Present
  packages/datadog-plugin-next/test/index.spec.js
  packages/datadog-plugin-next/test/next.config.js
Labels: semver-patch

#3702 [core] Next.js: Don't Trace Middleware
  packages/datadog-instrumentations/src/next.js
  packages/datadog-plugin-next/src/index.js
  packages/datadog-plugin-next/test/middleware.js
  packages/datadog-plugin-next/test/server.js
Labels: semver-minor, integration-nextjs

#3747 Enable telemetry metrics by default
  packages/dd-trace/src/appsec/iast/telemetry/index.js
  packages/dd-trace/src/config.js
  packages/dd-trace/test/appsec/iast/taint-tracking/taint-tracking-operations.spec.js
  packages/dd-trace/test/appsec/iast/telemetry/index.spec.js
  packages/dd-trace/test/config.spec.js
Labels: semver-minor

#3687 Hardcoded secret detection [APPSEC-11805]
  package.json
  packages/dd-trace/src/appsec/iast/analyzers/analyzers.js
  packages/dd-trace/src/appsec/iast/analyzers/hardcoded-secret-analyzer.js
  packages/dd-trace/src/appsec/iast/analyzers/hardcoded-secrets-rules.js
  packages/dd-trace/src/appsec/iast/path-line.js
  packages/dd-trace/src/appsec/iast/taint-tracking/rewriter.js
  packages/dd-trace/src/appsec/iast/vulnerabilities.js
  packages/dd-trace/test/appsec/iast/analyzers/hardcoded-secret-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/resources/hardcoded-secret-functions.js
  packages/dd-trace/test/appsec/iast/analyzers/resources/hardcoded-secrets-suite.json
  yarn.lock
Labels: semver-minor, asm-iast

#3720 Add configurable IAST redaction pattern
  docs/test.ts
  index.d.ts
  packages/dd-trace/src/appsec/iast/vulnerabilities-formatter/evidence-redaction/sensitive-handler.js
  packages/dd-trace/src/appsec/iast/vulnerabilities-formatter/index.js
  packages/dd-trace/src/appsec/iast/vulnerability-reporter.js
  packages/dd-trace/src/config.js
  packages/dd-trace/test/appsec/iast/vulnerability-formatter/evidence-redaction/sensitive-handler.spec.js
  packages/dd-trace/test/appsec/iast/vulnerability-formatter/index.spec.js
  packages/dd-trace/test/appsec/iast/vulnerability-reporter.spec.js
  packages/dd-trace/test/config.spec.js
Labels: semver-minor, asm-iast

#3647 Generic telemetry logs [APPSEC-10883]
  .gitignore
  packages/dd-trace/src/appsec/iast/iast-log.js
  packages/dd-trace/src/appsec/iast/telemetry/index.js
  packages/dd-trace/src/appsec/iast/telemetry/log/index.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/telemetry/index.js
  packages/dd-trace/src/telemetry/logs/index.js
  packages/dd-trace/src/telemetry/logs/log-collector.js
  packages/dd-trace/test/appsec/iast/iast-log.spec.js
  packages/dd-trace/test/appsec/iast/telemetry/index.spec.js
  packages/dd-trace/test/appsec/iast/telemetry/log/index.spec.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/telemetry/logs/index.spec.js
  packages/dd-trace/test/telemetry/logs/log-collector.spec.js
Labels: semver-minor

#3690 Add benchmark startup time for IAST
  benchmark/sirun/Dockerfile
  benchmark/sirun/appsec-iast/insecure-bank.js
  benchmark/sirun/appsec-iast/meta.json
  benchmark/sirun/appsec/insecure-bank.js
  benchmark/sirun/appsec/meta.json
Labels: semver-minor, asm-iast

#3725 Check only query and body parameters in nosql injections
  packages/dd-trace/src/appsec/iast/analyzers/nosql-injection-mongodb-analyzer.js
  packages/dd-trace/test/appsec/iast/analyzers/nosql-injection-mongodb-analyzer.express-mongo-sanitize.plugin.spec.js
Labels: bug, semver-patch, asm-iast

#3740 fix error in http plugin when it was enabled after request start
  packages/datadog-plugin-http/src/client.js
  packages/datadog-plugin-http/test/client.spec.js
Labels: bug, semver-patch, integration-http

#3751 Handle headers with array values [APPSEC-11971]
  packages/dd-trace/src/appsec/iast/analyzers/hsts-header-missing-analyzer.js
  packages/dd-trace/src/appsec/iast/analyzers/missing-header-analyzer.js
  packages/dd-trace/src/appsec/iast/analyzers/xcontenttype-header-missing-analyzer.js
  packages/dd-trace/test/appsec/iast/analyzers/hsts-header-missing-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/xcontenttype-header-missing-analyzer.spec.js
Labels: semver-patch, asm-iast
