Repository DataDog/dd-trace-js, pull requests merged in 2023-12, with the labels that each got.

#3790 [ci-visibility] New ITR settings logic
  packages/dd-trace/src/ci-visibility/exporters/ci-visibility-exporter.js
  packages/dd-trace/src/ci-visibility/intelligent-test-runner/get-itr-configuration.js
  packages/dd-trace/src/plugins/ci_plugin.js
  packages/dd-trace/test/ci-visibility/exporters/agentless/exporter.spec.js
  packages/dd-trace/test/ci-visibility/exporters/ci-visibility-exporter.spec.js
Labels: ci-app, semver-minor

#3828 [ci-visibility] Do not report total code coverage unless user has explicitly added code coverage
  integration-tests/ci-visibility-intake.js
  integration-tests/ci-visibility.spec.js
  integration-tests/ci-visibility/run-jest.js
  integration-tests/ci-visibility/run-jest.mjs
  integration-tests/cucumber/cucumber.spec.js
  packages/datadog-instrumentations/src/jest.js
  packages/dd-trace/src/ci-visibility/intelligent-test-runner/get-itr-configuration.js
  packages/dd-trace/src/plugins/util/test.js
  packages/dd-trace/test/ci-visibility/exporters/ci-visibility-exporter.spec.js
Labels: ci-app, semver-patch

#3822 PROF-8520: Add DNS events to timeline
  integration-tests/profiler.spec.js
  integration-tests/profiler/dnstest.js
  packages/dd-trace/src/profiling/profilers/events.js
Labels: profiling, semver-minor

#3836 configurable tracing header w/ aws signed request
  docs/test.ts
  index.d.ts
  packages/datadog-plugin-http/src/client.js
  packages/datadog-plugin-http/test/client.spec.js
  packages/datadog-plugin-openai/test/index.spec.js
Labels: semver-minor

#3841 [core] Do Not Report HTTP Requests Over 5 Seconds as Errors on Node 20
  packages/datadog-instrumentations/src/http/client.js
  packages/datadog-plugin-http/src/client.js
  packages/datadog-plugin-http/test/client.spec.js
Labels: semver-patch

#3844 PROF-8520: Fix integration test for DNS
  integration-tests/profiler.spec.js
Labels: bug, profiling, semver-minor

#3843 [profiling] Add integration test for OOM in worker
  integration-tests/profiler.spec.js
  integration-tests/profiler/oom.js
  package.json
  yarn.lock
Labels: bug, profiling, semver-minor

#3853 [core] Ensure Explicit Timeouts from Underlying Request Socket are Recorded as Errors When Using Node 20
  packages/datadog-instrumentations/src/http/client.js
  packages/datadog-plugin-http/src/client.js
  packages/datadog-plugin-http/test/client.spec.js
  packages/datadog-plugin-http/test/integration-test/server.mjs
  packages/datadog-plugin-http2/test/integration-test/server.mjs
Labels: semver-patch

#3851 chore: updating protobuf for security reasons
  package.json
  yarn.lock
Labels: semver-patch

#3832 PROF-8523: Add Net events to timeline
  packages/dd-trace/src/profiling/profilers/events.js
Labels: profiling, semver-minor

#3859 PROF-8520: Emit address and port as separate labels
  integration-tests/profiler.spec.js
  packages/dd-trace/src/profiling/profilers/events.js
Labels: profiling, semver-minor

#3839 [ci-visibility] Speed up git unshallow
  packages/dd-trace/src/ci-visibility/exporters/git/git_metadata.js
  packages/dd-trace/src/plugins/util/git.js
  packages/dd-trace/test/ci-visibility/exporters/git/git_metadata.spec.js
  packages/dd-trace/test/plugins/util/git.spec.js
Labels: ci-app, semver-patch

#3857 Update rules version to v1.10.0
  packages/dd-trace/src/appsec/recommended.json
  packages/dd-trace/src/appsec/reporter.js
  packages/dd-trace/test/appsec/reporter.spec.js
Labels: asm-waf, semver-minor

#3849 configurable logging and manual gc of old spans
  LICENSE-3rdparty.csv
  integration-tests/memory-leak/index.js
  package.json
  packages/dd-trace/src/config.js
  packages/dd-trace/src/opentracing/span.js
  packages/dd-trace/src/proxy.js
  packages/dd-trace/src/spanleak.js
  yarn.lock
Labels: semver-minor

#3860 chore: fix aws-sdk failing test suite
  .github/workflows/plugins.yml
  docker-compose.yml
  packages/datadog-plugin-aws-sdk/test/kinesis.spec.js
  packages/datadog-plugin-aws-sdk/test/kinesis_helpers.js
  packages/datadog-plugin-aws-sdk/test/lambda.spec.js
  packages/datadog-plugin-aws-sdk/test/s3.spec.js
Labels: semver-patch

#3863 Create a GitHub security policy via SECURITY.md
  SECURITY.md
Labels: semver-patch

#3867 Apply new rules for header injection detection to prevent false positives
  packages/dd-trace/src/appsec/iast/analyzers/header-injection-analyzer.js
  packages/dd-trace/test/appsec/iast/analyzers/header-injection.express.plugin.spec.js
Labels: semver-minor, asm-iast

#3818 restify: resolve 0th promise arg, not arguments
  packages/datadog-instrumentations/src/restify.js
  packages/datadog-plugin-restify/test/index.spec.js
Labels: semver-patch

#3870 PROF-8523: Bugfix and integration test for Net timeline events
  integration-tests/profiler.spec.js
  integration-tests/profiler/dnstest.js
  integration-tests/profiler/nettest.js
  packages/dd-trace/src/profiling/profilers/events.js
Labels: bug, profiling, semver-patch

#3873 Fix failing Aerospike tests
  .github/workflows/plugins.yml
  packages/datadog-plugin-aerospike/test/index.spec.js
Labels: semver-patch

#3879 Only run DNS and Net timeline events integration tests on Node 16+
  integration-tests/profiler.spec.js
Labels: bug, profiling, semver-patch

#3877 Fix tedious and elasticsearch plugin tests
  .github/workflows/plugins.yml
Labels: semver-patch

#3761 DSM: add kafka offset lag
  docker-compose.yml
  packages/datadog-instrumentations/src/kafkajs.js
  packages/datadog-plugin-kafkajs/src/consumer.js
  packages/datadog-plugin-kafkajs/src/producer.js
  packages/datadog-plugin-kafkajs/test/index.spec.js
  packages/dd-trace/src/datastreams/processor.js
  packages/dd-trace/src/tracer.js
  packages/dd-trace/test/datastreams/encoding.spec.js
  packages/dd-trace/test/datastreams/processor.spec.js
Labels: semver-minor

#3881 ci: no longer test sharedb against node v14
  .github/workflows/plugins.yml
Labels: semver-patch

#3880 PROF-8521: Remove lane logic from profiler library
  integration-tests/profiler.spec.js
  packages/dd-trace/src/profiling/profilers/events.js
Labels: profiling, semver-patch

#3882 quick telemetry test fix
  packages/dd-trace/test/telemetry/index.spec.js
Labels: semver-patch

#3878 Fix pino tests
  .github/workflows/plugins.yml
  packages/datadog-plugin-pino/test/index.spec.js
Labels: semver-patch

#3833 fix rhea memory leak concerning inFlightDeliveries
  packages/datadog-instrumentations/src/rhea.js
  packages/datadog-plugin-rhea/test/index.spec.js
Labels: semver-patch

#3883 Upgrade iast rewriter version to 2.2.2
  package.json
  yarn.lock
Labels: semver-patch, asm-iast

#3876 [ci-visibility] Update repository url validation
  packages/dd-trace/src/plugins/util/user-provided-git.js
  packages/dd-trace/test/ci-visibility/exporters/git/git_metadata.spec.js
  packages/dd-trace/test/plugins/util/ci-env/azurepipelines.json
  packages/dd-trace/test/plugins/util/ci-env/bitbucket.json
  packages/dd-trace/test/plugins/util/ci-env/bitrise.json
  packages/dd-trace/test/plugins/util/ci-env/buddy.json
  packages/dd-trace/test/plugins/util/ci-env/buildkite.json
  packages/dd-trace/test/plugins/util/ci-env/circleci.json
  packages/dd-trace/test/plugins/util/ci-env/codefresh.json
  packages/dd-trace/test/plugins/util/ci-env/gitlab.json
  packages/dd-trace/test/plugins/util/ci-env/jenkins.json
  packages/dd-trace/test/plugins/util/ci-env/teamcity.json
  packages/dd-trace/test/plugins/util/ci-env/usersupplied.json
  packages/dd-trace/test/plugins/util/test-environment.spec.js
  packages/dd-trace/test/plugins/util/test.spec.js
Labels: ci-app, semver-patch

#3842 flush custom metrics before process exit
  packages/dd-trace/src/proxy.js
  packages/dd-trace/test/custom-metrics-app.js
  packages/dd-trace/test/custom-metrics.spec.js
Labels: semver-minor

#3890 Add variable to choose downstream branch for rel-env deploys
  .gitlab-ci.yml
Labels: dev/tooling, semver-patch

#3892 [core] Default Error Tagging for Pages in Next.js
  packages/datadog-instrumentations/src/next.js
  packages/datadog-plugin-next/src/index.js
  packages/datadog-plugin-next/test/index.spec.js
Labels: semver-patch, integration-nextjs

#3889 Configure parametric test to get the nodejs tracer in same way as sys…
  .github/workflows/system-tests.yml
Labels: dev/testing, ci-app, semver-minor

#3888 [profiling] Add thread id labels to heap and wall profiles
  integration-tests/profiler.spec.js
  packages/dd-trace/src/profiling/profilers/events.js
  packages/dd-trace/src/profiling/profilers/shared.js
  packages/dd-trace/src/profiling/profilers/space.js
  packages/dd-trace/src/profiling/profilers/wall.js
Labels: enhancement, profiling, semver-minor

#3868 API security sample rate via RC
  packages/dd-trace/src/appsec/activation.js
  packages/dd-trace/src/appsec/api_security_sampler.js
  packages/dd-trace/src/appsec/index.js
  packages/dd-trace/src/appsec/remote_config/capabilities.js
  packages/dd-trace/src/appsec/remote_config/index.js
  packages/dd-trace/test/appsec/activation.spec.js
  packages/dd-trace/test/appsec/api_security_sampler.spec.js
  packages/dd-trace/test/appsec/remote_config/index.spec.js
Labels: asm-waf, semver-minor

#3891 PROF-8829: Fix recording times
  packages/dd-trace/src/profiling/profiler.js
  packages/dd-trace/src/profiling/profilers/events.js
Labels: bug, profiling, semver-patch

#3896 Revert "[core] Ensure Explicit Timeouts from Underlying Request Socket are Recorded as Errors When Using Node 20 (#3853)"
  packages/datadog-instrumentations/src/http/client.js
  packages/datadog-plugin-http/src/client.js
  packages/datadog-plugin-http/test/client.spec.js
  packages/datadog-plugin-http/test/integration-test/server.mjs
  packages/datadog-plugin-http2/test/integration-test/server.mjs
Labels: bug, semver-patch, performance

#3894 github: suggest new issues use helpdesk instead
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: dev/tooling, docs, semver-patch

#3806 docs: fix typos and improve grammar.
  docs/API.md
Labels: docs, semver-patch

#3897 Pass resolver address as ephemeral type
  package.json
  packages/dd-trace/src/appsec/graphql.js
  packages/dd-trace/src/appsec/index.js
  packages/dd-trace/src/appsec/sdk/user_blocking.js
  packages/dd-trace/src/appsec/waf/waf_context_wrapper.js
  packages/dd-trace/test/appsec/graphql.spec.js
  packages/dd-trace/test/appsec/index.spec.js
  packages/dd-trace/test/appsec/sdk/user_blocking.spec.js
  packages/dd-trace/test/appsec/waf/index.spec.js
  packages/dd-trace/test/appsec/waf/waf_context_wrapper.spec.js
  yarn.lock
Labels: asm-waf, semver-minor

#3875 add remote config support for custom tags
  packages/dd-trace/src/appsec/remote_config/capabilities.js
  packages/dd-trace/src/appsec/remote_config/index.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/opentracing/tracer.js
  packages/dd-trace/src/telemetry/index.js
  packages/dd-trace/test/appsec/remote_config/index.spec.js
  packages/dd-trace/test/config.spec.js
Labels: semver-minor

#3372 Update test agent configuration
  .github/workflows/plugins.yml
  docker-compose.yml
Labels: semver-patch

#2825 Add `@Datadog/serverless` as codeowners for `ddtrace/{src|test}/lambda`
  CODEOWNERS
Labels: semver-patch, dont-land-on-v2.x, dont-land-on-v3.x, dont-land-on-v4.x

#3752 [ci-visibility] CI Visibility telemetry - agentful
  packages/datadog-instrumentations/src/jest.js
  packages/datadog-plugin-cucumber/src/index.js
  packages/datadog-plugin-cypress/src/plugin.js
  packages/datadog-plugin-jest/src/index.js
  packages/datadog-plugin-mocha/src/index.js
  packages/datadog-plugin-playwright/src/index.js
  packages/dd-trace/src/ci-visibility/exporters/agentless/coverage-writer.js
  packages/dd-trace/src/ci-visibility/exporters/agentless/writer.js
  packages/dd-trace/src/ci-visibility/exporters/git/git_metadata.js
  packages/dd-trace/src/ci-visibility/intelligent-test-runner/get-itr-configuration.js
  packages/dd-trace/src/ci-visibility/intelligent-test-runner/get-skippable-suites.js
  packages/dd-trace/src/ci-visibility/telemetry.js
  packages/dd-trace/src/encode/agentless-ci-visibility.js
  packages/dd-trace/src/encode/coverage-ci-visibility.js
  packages/dd-trace/src/exporters/common/agent-info-exporter.js
  packages/dd-trace/src/exporters/common/form-data.js
  packages/dd-trace/src/plugins/ci_plugin.js
  packages/dd-trace/src/plugins/util/exec.js
  packages/dd-trace/src/plugins/util/git.js
  packages/dd-trace/src/telemetry/index.js
  packages/dd-trace/test/ci-visibility/exporters/agentless/coverage-writer.spec.js
  packages/dd-trace/test/ci-visibility/exporters/ci-visibility-exporter.spec.js
  packages/dd-trace/test/plugins/util/git.spec.js
Labels: ci-app, semver-minor

#3902 [ci-visibility] Fix cucumber plugin tests for node<16
  packages/datadog-plugin-cucumber/test/index.spec.js
Labels: ci-app, semver-patch

#3893 add support for node specifiers
  packages/datadog-instrumentations/src/child-process.js
  packages/datadog-instrumentations/src/crypto.js
  packages/datadog-instrumentations/src/dns.js
  packages/datadog-instrumentations/src/helpers/hooks.js
  packages/datadog-instrumentations/src/helpers/instrument.js
  packages/datadog-instrumentations/src/helpers/register.js
  packages/datadog-instrumentations/src/http/client.js
  packages/datadog-instrumentations/src/http/server.js
  packages/datadog-instrumentations/src/http2/client.js
  packages/datadog-instrumentations/src/http2/server.js
  packages/datadog-instrumentations/src/net.js
  packages/datadog-plugin-dns/test/index.spec.js
  packages/datadog-plugin-fastify/test/integration-test/client.spec.js
  packages/datadog-plugin-http/test/client.spec.js
  packages/datadog-plugin-http/test/server.spec.js
  packages/datadog-plugin-http2/test/client.spec.js
  packages/datadog-plugin-http2/test/server.spec.js
  packages/datadog-plugin-net/test/index.spec.js
  packages/dd-trace/src/plugins/index.js
Labels: semver-minor

#3886 simplify ci build for aerospike
  .github/workflows/plugins.yml
Labels: semver-patch

#3909 Fix integration tests by pinned chai to v4 as v5 went ESM-only
  integration-tests/ci-visibility.spec.js
Labels: ci-app, semver-patch

#3903 Add install_signature to app-started telemetry event
  packages/dd-trace/src/config.js
  packages/dd-trace/src/telemetry/index.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/telemetry/index.spec.js
Labels: semver-minor

#3908 [profiling] Fix compatibility with node < 14.18
  integration-tests/profiler.spec.js
  integration-tests/profiler/nettest.js
  packages/dd-trace/src/profiling/profilers/events.js
  packages/dd-trace/src/profiling/profilers/shared.js
Labels: bug, profiling, semver-minor

#3910 Fix timeouts from aws-sdk kinesis tests
  packages/datadog-plugin-aws-sdk/test/kinesis.spec.js
  packages/datadog-plugin-aws-sdk/test/kinesis_helpers.js
Labels: semver-patch, integration-aws-sdk

#3907 Update actions versions
  .github/actions/testagent/start/action.yml
  .github/workflows/appsec.yml
  .github/workflows/ci-visibility-performance.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/core.yml
  .github/workflows/lambda.yml
  .github/workflows/package-size.yml
  .github/workflows/plugins.yml
  .github/workflows/profiling.yml
  .github/workflows/project.yml
  .github/workflows/release-3.yml
  .github/workflows/release-dev.yml
  .github/workflows/release-latest.yml
  .github/workflows/release-proposal.yml
  .github/workflows/serverless-integration-test.yml
  .github/workflows/serverless-performance.yml
  .github/workflows/system-tests.yml
  .github/workflows/test-k8s-lib-injection.yaml
  .github/workflows/tracing.yml
Labels: semver-patch
