Repository DataDog/dd-trace-js, pull requests merged in 2023-01, with the labels that each got.

#2574 Introduce a way to block incoming requests
  LICENSE-3rdparty.csv
  docs/test.ts
  index.d.ts
  package.json
  packages/datadog-instrumentations/src/http/server.js
  packages/datadog-plugin-http/src/server.js
  packages/datadog-plugin-http/test/server.spec.js
  packages/dd-trace/src/appsec/addresses.js
  packages/dd-trace/src/appsec/blocking.js
  packages/dd-trace/src/appsec/callbacks/ddwaf.js
  packages/dd-trace/src/appsec/gateway/engine/engine.js
  packages/dd-trace/src/appsec/gateway/engine/index.js
  packages/dd-trace/src/appsec/gateway/engine/runner.js
  packages/dd-trace/src/appsec/index.js
  packages/dd-trace/src/appsec/ip_blocklist.js
  packages/dd-trace/src/appsec/ip_extractor.js
  packages/dd-trace/src/appsec/remote_config/index.js
  packages/dd-trace/src/appsec/templates/blocked.html
  packages/dd-trace/src/appsec/templates/blocked.json
  packages/dd-trace/src/config.js
  packages/dd-trace/src/plugin_manager.js
  packages/dd-trace/src/plugins/util/web.js
  packages/dd-trace/test/appsec/gateway/engine/runner.spec.js
  packages/dd-trace/test/appsec/index.spec.js
  packages/dd-trace/test/appsec/ip_extractor.spec.js
  packages/dd-trace/test/appsec/remote_config/index.spec.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/plugin_manager.spec.js
  packages/dd-trace/test/plugins/util/web.spec.js
  yarn.lock
Labels: appsec, semver-minor

#2647 remove dependence on timers in CI Visibility exporter test
  packages/dd-trace/test/ci-visibility/exporters/agent-proxy/agent-proxy.spec.js
Labels: semver-patch

#2646 handle GitHub/npm rate limits
  packages/dd-trace/test/plugins/suite.js
Labels: semver-patch

#2641 Fix router plugin state restore on exit
  packages/datadog-plugin-router/src/index.js
Labels: bug, semver-patch

#2639 [ci-visibility] Clean up CI Visibility integration tests
  integration-tests/ci-visibility-intake.js
  integration-tests/ci-visibility.spec.js
  integration-tests/helpers.js
Labels: dev/testing, ci-app, semver-patch

#2655 Revert not releasable commits
  .github/workflows/plugins.yml
  docker-compose.yml
  docs/API.md
  index.d.ts
  package.json
  packages/datadog-instrumentations/src/fs.js
  packages/datadog-instrumentations/src/helpers/hooks.js
  packages/datadog-instrumentations/src/ldapjs.js
  packages/datadog-instrumentations/src/pg.js
  packages/dd-trace/src/appsec/iast/analyzers/analyzers.js
  packages/dd-trace/src/appsec/iast/analyzers/ldap-injection-analyzer.js
  packages/dd-trace/src/appsec/iast/analyzers/path-traversal-analyzer.js
  packages/dd-trace/src/appsec/iast/analyzers/sql-injection-analyzer.js
  packages/dd-trace/src/appsec/iast/analyzers/vulnerability-analyzer.js
  packages/dd-trace/src/appsec/iast/iast-context.js
  packages/dd-trace/src/appsec/iast/taint-tracking/csi-methods.js
  packages/dd-trace/src/appsec/iast/taint-tracking/operations.js
  packages/dd-trace/src/appsec/iast/taint-tracking/rewriter.js
  packages/dd-trace/src/appsec/iast/taint-tracking/taint-tracking-impl.js
  packages/dd-trace/test/appsec/iast/analyzers/command-injection-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/ldap-injection-analyzer.ldapjs.plugin.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/ldap-injection-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/path-traversal-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/sql-injection-analyzer.mysql.plugin.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/sql-injection-analyzer.mysql2.plugin.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/sql-injection-analyzer.pg.plugin.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/vulnerability-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/weak-cipher-analyzers.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/weak-hash-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/taint-tracking/resources/propagationFunctions.js
  packages/dd-trace/test/appsec/iast/taint-tracking/taint-tracking-impl.spec.js
  packages/dd-trace/test/appsec/iast/taint-tracking/taint-tracking-operations.spec.js
  packages/dd-trace/test/appsec/iast/utils.js
  packages/dd-trace/test/setup/services/openldap.js
  yarn.lock
Labels: semver-patch

#2665 [ci-visibility] Move CI visibility performance and correctness test to GHA
  .circleci/config.yml
  .github/workflows/ci-visibility-performance.yml
  benchmark/e2e-ci/benchmark-run.js
Labels: dev/testing, ci-app, semver-patch

#2651 Add _dd.iast.enabled tag
  packages/dd-trace/src/appsec/iast/index.js
  packages/dd-trace/test/appsec/iast/overhead-controller.spec.js
Labels: semver-patch, appsec, iast

#2666 Remove circle-ci jobs
  .circleci/config.yml
Labels: semver-patch

#2635 Send relative path for the vulnerability instead of the absolute path
  packages/dd-trace/src/appsec/iast/path-line.js
  packages/dd-trace/test/appsec/iast/path-line.spec.js
Labels: semver-patch

#2656 Apply again release compatible commits (#2565 #2568 #2618 #2642)
  .github/workflows/plugins.yml
  docker-compose.yml
  docs/API.md
  index.d.ts
  package.json
  packages/datadog-instrumentations/src/helpers/hooks.js
  packages/datadog-instrumentations/src/ldapjs.js
  packages/datadog-instrumentations/src/pg.js
  packages/dd-trace/src/appsec/iast/analyzers/analyzers.js
  packages/dd-trace/src/appsec/iast/analyzers/ldap-injection-analyzer.js
  packages/dd-trace/src/appsec/iast/analyzers/sql-injection-analyzer.js
  packages/dd-trace/src/appsec/iast/analyzers/vulnerability-analyzer.js
  packages/dd-trace/src/appsec/iast/iast-context.js
  packages/dd-trace/src/appsec/iast/taint-tracking/csi-methods.js
  packages/dd-trace/src/appsec/iast/taint-tracking/operations.js
  packages/dd-trace/src/appsec/iast/taint-tracking/rewriter.js
  packages/dd-trace/src/appsec/iast/taint-tracking/taint-tracking-impl.js
  packages/dd-trace/test/appsec/iast/analyzers/command-injection-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/ldap-injection-analyzer.ldapjs.plugin.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/ldap-injection-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/sql-injection-analyzer.mysql.plugin.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/sql-injection-analyzer.mysql2.plugin.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/sql-injection-analyzer.pg.plugin.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/vulnerability-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/weak-cipher-analyzers.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/weak-hash-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/taint-tracking/resources/propagationFunctions.js
  packages/dd-trace/test/appsec/iast/taint-tracking/taint-tracking-impl.spec.js
  packages/dd-trace/test/appsec/iast/taint-tracking/taint-tracking-operations.spec.js
  packages/dd-trace/test/appsec/iast/utils.js
  packages/dd-trace/test/setup/services/openldap.js
  yarn.lock
Labels: semver-patch, appsec, iast

#2664 [ci-visibility] Fix URL for intelligent test runner when using agentless
  packages/dd-trace/src/ci-visibility/exporters/agent-proxy/index.js
  packages/dd-trace/src/ci-visibility/exporters/agentless/index.js
  packages/dd-trace/src/ci-visibility/exporters/ci-visibility-exporter.js
  packages/dd-trace/test/ci-visibility/exporters/agentless/exporter.spec.js
  packages/dd-trace/test/ci-visibility/exporters/ci-visibility-exporter.spec.js
Labels: ci-app, semver-patch

#2670 Fix sql injection pg test for 2.x branch
  packages/dd-trace/test/appsec/iast/analyzers/sql-injection-analyzer.pg.plugin.spec.js
Labels: semver-patch

#2675 Configurable remote config poll interval
  docs/test.ts
  index.d.ts
  packages/dd-trace/src/appsec/remote_config/manager.js
  packages/dd-trace/src/config.js
  packages/dd-trace/test/appsec/remote_config/manager.spec.js
  packages/dd-trace/test/config.spec.js
Labels: appsec, semver-minor

#2681 run package size on pull_request
  .github/workflows/package-size.yml
Labels: semver-patch

#2673 [ci-visibility] Add `_dd.ci.env_vars` to azure pipelines metadata extraction
  packages/dd-trace/src/plugins/util/ci.js
  packages/dd-trace/test/plugins/util/ci-env/azurepipelines.json
Labels: ci-app, semver-patch

#2672 [ci-visibility] Remove user credentials from user provided git
  packages/dd-trace/src/plugins/util/user-provided-git.js
  packages/dd-trace/test/plugins/util/ci-env/azurepipelines.json
  packages/dd-trace/test/plugins/util/ci-env/bitbucket.json
  packages/dd-trace/test/plugins/util/ci-env/bitrise.json
  packages/dd-trace/test/plugins/util/ci-env/buildkite.json
  packages/dd-trace/test/plugins/util/ci-env/circleci.json
  packages/dd-trace/test/plugins/util/ci-env/gitlab.json
  packages/dd-trace/test/plugins/util/ci-env/jenkins.json
  packages/dd-trace/test/plugins/util/ci-env/travisci.json
  packages/dd-trace/test/plugins/util/ci-env/usersupplied.json
Labels: ci-app, semver-patch

#2671 [ci-visibility] Add github job name to the extracted CI metadata
  packages/dd-trace/src/plugins/util/ci.js
  packages/dd-trace/test/plugins/util/ci-env/buddy.json
  packages/dd-trace/test/plugins/util/ci-env/github.json
Labels: ci-app, semver-patch

#2680 [ci-visibility] Fix code_coverage tag in test session
  integration-tests/ci-visibility.spec.js
  packages/datadog-plugin-jest/src/index.js
  packages/datadog-plugin-mocha/src/index.js
  packages/dd-trace/src/plugins/util/test.js
Labels: ci-app, semver-patch

#2667 Update addRequestHeaders to stringify header value when an array
  packages/datadog-plugin-http/src/client.js
  packages/datadog-plugin-http/test/client.spec.js
Labels: semver-minor

#2687 Do not crash when prototype-free objects used for tags
  packages/dd-trace/src/format.js
  packages/dd-trace/src/priority_sampler.js
  packages/dd-trace/test/format.spec.js
  packages/dd-trace/test/priority_sampler.spec.js
Labels: bug, semver-patch

#2678 Support serviceMapping programmatic config
  docs/test.ts
  index.d.ts
  packages/dd-trace/src/config.js
  packages/dd-trace/test/config.spec.js
Labels: semver-minor

#2691 Support IPv6 URLs for agent address
  packages/dd-trace/src/exporters/common/request.js
  packages/dd-trace/test/exporters/common/request.spec.js
Labels: bug, semver-patch

#2689 Update asm waf rules to 1.4.3 version
  packages/dd-trace/src/appsec/recommended.json
Labels: asm-waf, semver-minor

#2629 Add taint tracking support for concat, substring, substr, slice and replace methods
  package.json
  packages/dd-trace/src/appsec/iast/taint-tracking/csi-methods.js
  packages/dd-trace/src/appsec/iast/taint-tracking/taint-tracking-impl.js
  packages/dd-trace/test/appsec/iast/taint-tracking/resources/propagationFunctions.js
  packages/dd-trace/test/appsec/iast/taint-tracking/taint-tracking-impl.spec.js
  yarn.lock
Labels: semver-patch, asm-iast

#2694 [ci-visibility] Fix `mocha#run` wrapper
  integration-tests/ci-visibility.spec.js
  integration-tests/ci-visibility/run-mocha.js
  integration-tests/helpers.js
  packages/datadog-instrumentations/src/mocha.js
Labels: ci-app, semver-patch

#2476 Aj/optionally timeout tracer
  .github/workflows/lambda.yml
  LICENSE-3rdparty.csv
  package.json
  packages/datadog-instrumentations/src/helpers/register.js
  packages/dd-trace/src/lambda/handler.js
  packages/dd-trace/src/lambda/index.js
  packages/dd-trace/src/lambda/runtime/errors.js
  packages/dd-trace/src/lambda/runtime/patch.js
  packages/dd-trace/src/lambda/runtime/ritm.js
  packages/dd-trace/src/plugin_manager.js
  packages/dd-trace/src/ritm.js
  packages/dd-trace/src/span_processor.js
  packages/dd-trace/src/span_sampler.js
  packages/dd-trace/test/lambda/fixtures/datadog-lambda.js
  packages/dd-trace/test/lambda/fixtures/handler.js
  packages/dd-trace/test/lambda/index.spec.js
  packages/dd-trace/test/lambda/runtime/ritm.spec.js
Labels: semver-minor, serverless

#2701 Split dd_tags on spaces
  packages/dd-trace/src/profiling/tagger.js
  packages/dd-trace/test/profiling/tagger.spec.js
Labels: semver-minor

#2696 Always log inject service, version, and env
  packages/datadog-plugin-bunyan/test/index.spec.js
  packages/datadog-plugin-paperplane/test/index.spec.js
  packages/datadog-plugin-pino/test/index.spec.js
  packages/dd-trace/src/plugins/log_plugin.js
  packages/dd-trace/test/plugins/log_plugin.spec.js
Labels: bug, semver-patch

#2702 Rename environment variable for remote configuration polling interval
  packages/dd-trace/src/config.js
  packages/dd-trace/test/config.spec.js
Labels: asm-waf, semver-minor

#2674 add remoteConfigEnabled config
  packages/dd-trace/src/config.js
  packages/dd-trace/src/proxy.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/proxy.spec.js
Labels: semver-minor, serverless

#2711 [ci-visibility] Fix `CiPlugin` crashing when no CI Vis init is used
  integration-tests/ci-visibility.spec.js
  packages/dd-trace/src/plugins/ci_plugin.js
Labels: ci-app, semver-patch

#2714 Revert "split DD_TAGS on spaces (#2701)"
  packages/dd-trace/src/profiling/tagger.js
  packages/dd-trace/test/profiling/tagger.spec.js
Labels: semver-patch

#2700 require db name when calling injectDbmQuery()
  packages/datadog-instrumentations/src/pg.js
  packages/datadog-plugin-pg/src/index.js
  packages/datadog-plugin-pg/test/index.spec.js
  packages/dd-trace/src/plugins/database.js
Labels: semver-patch

#2686 Create spans for vulnerabilities outside of requests
  packages/dd-trace/src/appsec/iast/analyzers/vulnerability-analyzer.js
  packages/dd-trace/src/appsec/iast/index.js
  packages/dd-trace/src/appsec/iast/overhead-controller.js
  packages/dd-trace/src/appsec/iast/vulnerability-reporter.js
  packages/dd-trace/src/proxy.js
  packages/dd-trace/test/appsec/iast/analyzers/vulnerability-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/weak-hash-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/index.spec.js
  packages/dd-trace/test/appsec/iast/overhead-controller.spec.js
  packages/dd-trace/test/appsec/iast/utils.js
  packages/dd-trace/test/appsec/iast/vulnerability-reporter.spec.js
Labels: semver-patch, asm-iast

#2715 [CONTSEC-707] Upgrade CodeQL Github Action versions
  .github/workflows/codeql-analysis.yml
Labels: semver-patch

#2721 [lambda] Remove minimum version requirement for patch
  packages/datadog-instrumentations/src/helpers/register.js
  packages/dd-trace/src/lambda/runtime/patch.js
  packages/dd-trace/src/lambda/runtime/ritm.js
Labels: semver-patch

#2728 [ci-visibility] Update CI env var extraction spec
  packages/dd-trace/src/plugins/util/user-provided-git.js
  packages/dd-trace/test/plugins/util/ci-env/azurepipelines.json
  packages/dd-trace/test/plugins/util/ci-env/buddy.json
  packages/dd-trace/test/plugins/util/test-environment.spec.js
Labels: ci-app, semver-patch

#2614 [ci-visibility] New Test Code Coverage Format
  integration-tests/ci-visibility.spec.js
  packages/dd-trace/src/encode/coverage-ci-visibility.js
  packages/dd-trace/test/encode/coverage-ci-visibility.spec.js
Labels: do-not-merge/WIP, ci-app, semver-patch

#2587 Migrate fs plugin to the new plugin system and path traversal detection implementation
  ci/init.js
  packages/datadog-instrumentations/src/fs.js
  packages/datadog-instrumentations/src/helpers/hooks.js
  packages/datadog-plugin-fs/src/index.js
  packages/datadog-plugin-fs/test/index.spec.js
  packages/dd-trace/src/appsec/iast/analyzers/analyzers.js
  packages/dd-trace/src/appsec/iast/analyzers/path-traversal-analyzer.js
  packages/dd-trace/src/plugins/index.js
  packages/dd-trace/test/appsec/iast/analyzers/path-traversal-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/utils.js
Labels: semver-patch, dont-land-on-v2.x, dont-land-on-v3.x

#2717 Make automatic client IP extraction available as opt-in outside of AppSec
  docs/test.ts
  index.d.ts
  packages/dd-trace/src/appsec/index.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/plugins/util/ip_blocklist.js
  packages/dd-trace/src/plugins/util/ip_extractor.js
  packages/dd-trace/src/plugins/util/web.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/plugins/util/ip_extractor.spec.js
  packages/dd-trace/test/plugins/util/web.spec.js
Labels: semver-minor

#2708 [ci-visibility] Support `@playwright/test`
  docs/test.ts
  index.d.ts
  integration-tests/ci-visibility-intake.js
  integration-tests/ci-visibility/playwright-tests/landing-page-test.js
  integration-tests/ci-visibility/playwright-tests/todo-list-page-test.js
  integration-tests/ci-visibility/web-app-server.js
  integration-tests/playwright.config.js
  integration-tests/playwright.spec.js
  packages/datadog-instrumentations/src/helpers/hooks.js
  packages/datadog-instrumentations/src/playwright.js
  packages/datadog-plugin-playwright/src/index.js
  packages/dd-trace/src/plugins/index.js
Labels: ci-app, semver-minor

#2732 [ci-visibility] Fix playwright integration tests
  integration-tests/playwright.spec.js
  packages/datadog-instrumentations/src/playwright.js
Labels: ci-app, semver-patch

#2731 Disable fs plugin
  packages/datadog-plugin-fs/test/index.spec.js
  packages/dd-trace/src/plugins/index.js
Labels: semver-patch, dont-land-on-v2.x

#2657 [Serverless] Add performance test for serverless
  .github/workflows/serverless-performance.yml
Labels: semver-patch

#2648 APM DBM Link for MySQL & MySQL2
  packages/datadog-instrumentations/src/mysql.js
  packages/datadog-instrumentations/src/mysql2.js
  packages/datadog-plugin-mysql/src/index.js
  packages/datadog-plugin-mysql/test/index.spec.js
  packages/datadog-plugin-mysql2/test/index.spec.js
Labels: semver-minor

#2698 Application Security Events Tracking SDK
  docs/test.ts
  index.d.ts
  packages/dd-trace/src/appsec/callbacks/ddwaf.js
  packages/dd-trace/src/appsec/sdk/index.js
  packages/dd-trace/src/appsec/sdk/noop.js
  packages/dd-trace/src/appsec/sdk/track_event.js
  packages/dd-trace/src/appsec/sdk/utils.js
  packages/dd-trace/src/noop/proxy.js
  packages/dd-trace/src/proxy.js
  packages/dd-trace/test/appsec/callbacks/ddwaf.spec.js
  packages/dd-trace/test/appsec/sdk/index.spec.js
  packages/dd-trace/test/appsec/sdk/track_event.spec.js
  packages/dd-trace/test/proxy.spec.js
Labels: asm-waf, semver-minor

#2735 Prevent release proposals with invalid labels
  .github/workflows/release-proposal.yml
  scripts/check-proposal-labels.js
Labels: semver-patch

#2738 [ci-visibility] Update CI Visibility spec
  packages/dd-trace/src/plugins/util/ci.js
  packages/dd-trace/test/plugins/util/ci-env/appveyor.json
Labels: ci-app, semver-patch

#2679 log through diagnostics channel
  packages/dd-trace/src/log.js
  packages/dd-trace/src/log/channels.js
  packages/dd-trace/src/log/index.js
  packages/dd-trace/src/log/writer.js
  packages/dd-trace/src/startup-log.js
  packages/dd-trace/test/log.spec.js
Labels: semver-minor

#2725 [ci-visibility] Add support for test modules
  integration-tests/playwright.spec.js
  packages/datadog-instrumentations/src/jest.js
  packages/datadog-instrumentations/src/mocha.js
  packages/datadog-plugin-jest/src/index.js
  packages/datadog-plugin-jest/test/circus.spec.js
  packages/datadog-plugin-mocha/src/index.js
  packages/datadog-plugin-mocha/test/index.spec.js
  packages/datadog-plugin-playwright/src/index.js
  packages/dd-trace/src/ci-visibility/exporters/ci-visibility-exporter.js
  packages/dd-trace/src/encode/agentless-ci-visibility.js
  packages/dd-trace/src/plugins/util/test.js
Labels: ci-app, semver-patch

#2740 Fix Lib Injection Test
  .github/workflows/test-k8s-lib-injection.yaml
Labels: semver-patch

#2739 Pin buildx
  .github/actions/injection/action.yml
Labels: bug, dev/tooling, semver-patch
