Repository DataDog/dd-trace-js, pull requests merged in 2023-11, with the labels that each got.

#3715 NextJS error handling
  packages/datadog-instrumentations/src/next.js
  packages/datadog-plugin-next/src/index.js
  packages/datadog-plugin-next/test/app/api/appDir/error/route.js
  packages/datadog-plugin-next/test/index.spec.js
Labels: semver-minor

#3756 PROF-8551: Call the right method to unsubscribe from a channel
  packages/dd-trace/src/profiling/profilers/wall.js
Labels: profiling, semver-patch

#3727 PROF-8461: make endpoint profiling independent of code hotspots
  packages/dd-trace/src/profiling/config.js
  packages/dd-trace/src/profiling/profilers/wall.js
  packages/dd-trace/test/profiling/config.spec.js
Labels: profiling, semver-minor

#3760 Upgrade rewriter version to 2.2.1
  package.json
  yarn.lock
Labels: semver-patch, asm-iast

#3758 Fix ci for mongoose in node 14
  packages/datadog-instrumentations/test/mongoose.spec.js
  packages/datadog-plugin-mongoose/test/index.spec.js
  packages/datadog-plugin-mongoose/test/integration-test/client.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/nosql-injection-mongodb-analyzer.mongoose.plugin.spec.js
Labels: semver-patch

#3734 add payload size to kafka stats
  package.json
  packages/datadog-plugin-kafkajs/src/consumer.js
  packages/datadog-plugin-kafkajs/src/producer.js
  packages/datadog-plugin-kafkajs/test/index.spec.js
  packages/dd-trace/src/datastreams/processor.js
  packages/dd-trace/src/tracer.js
  packages/dd-trace/test/datastreams/encoding.spec.js
  packages/dd-trace/test/datastreams/pathway.spec.js
  packages/dd-trace/test/datastreams/processor.spec.js
Labels: semver-minor

#3722 use dc-polyfill instead of diagnostics_channel directly
  LICENSE-3rdparty.csv
  README.md
  integration-tests/ci-visibility/test-api-manual/test.fake.js
  package.json
  packages/datadog-core/src/storage/async_resource.js
  packages/datadog-esbuild/index.js
  packages/datadog-instrumentations/src/helpers/bundler-register.js
  packages/datadog-instrumentations/src/helpers/instrument.js
  packages/datadog-instrumentations/src/helpers/register.js
  packages/datadog-instrumentations/test/body-parser.spec.js
  packages/datadog-instrumentations/test/cookie-parser.spec.js
  packages/datadog-instrumentations/test/express-mongo-sanitize.spec.js
  packages/datadog-instrumentations/test/express.spec.js
  packages/datadog-instrumentations/test/passport-http.spec.js
  packages/datadog-instrumentations/test/passport-local.spec.js
  packages/datadog-plugin-fs/test/index.spec.js
  packages/datadog-plugin-http/test/client.spec.js
  packages/dd-trace/src/appsec/channels.js
  packages/dd-trace/src/appsec/iast/iast-log.js
  packages/dd-trace/src/appsec/iast/iast-plugin.js
  packages/dd-trace/src/appsec/iast/index.js
  packages/dd-trace/src/appsec/iast/path-line.js
  packages/dd-trace/src/appsec/iast/taint-tracking/rewriter.js
  packages/dd-trace/src/iitm.js
  packages/dd-trace/src/log/channels.js
  packages/dd-trace/src/plugin_manager.js
  packages/dd-trace/src/plugins/plugin.js
  packages/dd-trace/src/profiling/profilers/wall.js
  packages/dd-trace/src/ritm.js
  packages/dd-trace/src/telemetry/dependencies.js
  packages/dd-trace/src/telemetry/index.js
  packages/dd-trace/src/telemetry/logs/index.js
  packages/dd-trace/test/appsec/iast/analyzers/set-cookies-header-interceptor.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/sql-injection-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/vulnerability-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/iast-log.spec.js
  packages/dd-trace/test/appsec/iast/iast-plugin.spec.js
  packages/dd-trace/test/appsec/iast/path-line.spec.js
  packages/dd-trace/test/appsec/iast/taint-tracking/plugin.spec.js
  packages/dd-trace/test/iitm.spec.js
  packages/dd-trace/test/plugin_manager.spec.js
  packages/dd-trace/test/plugins/log_plugin.spec.js
  packages/dd-trace/test/plugins/tracing.spec.js
  packages/dd-trace/test/ritm.spec.js
  packages/dd-trace/test/telemetry/dependencies.spec.js
  packages/dd-trace/test/telemetry/logs/index.spec.js
  packages/diagnostics_channel/index.js
  packages/diagnostics_channel/src/index.js
  yarn.lock
Labels: semver-minor

#3772 Update appsec rules to 1.9.0
  packages/dd-trace/src/appsec/recommended.json
Labels: asm-waf, semver-minor

#3765 Modified telemetry.enabled to comply with instrumentation telemetry specs
  benchmark/sirun/run-all-variants.js
  benchmark/sirun/run-one-variant.js
  packages/dd-trace/src/config.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/plugins/suite.js
  packages/dd-trace/test/setup/core.js
Labels: semver-minor

#3778 Use exact version for @datadog/native-appsec
  package.json
  yarn.lock
Labels: semver-patch

#3767 [ci-visibility] Add flags to force code coverage reporting and test skipping
  packages/dd-trace/src/ci-visibility/intelligent-test-runner/get-itr-configuration.js
Labels: ci-app, semver-minor

#3759 PROF-8545: (Simplified) Restore eager release of tags, adapt endpoint profiling code
  packages/dd-trace/src/profiling/profilers/wall.js
  packages/dd-trace/src/span_processor.js
  packages/dd-trace/test/tracer.spec.js
Labels: profiling, semver-patch

#3777 Run nextjs system-test in tracer CI
  .github/workflows/system-tests.yml
Labels: semver-patch

#3779 PROF-8545: Cache web tags lookup, so we only perform it once per span
  packages/dd-trace/src/profiling/profilers/wall.js
Labels: profiling, semver-patch

#3771 [ci-visibility] Update git metadata extraction
  packages/dd-trace/src/plugins/util/ci.js
  packages/dd-trace/src/plugins/util/git.js
  packages/dd-trace/src/plugins/util/url.js
  packages/dd-trace/src/plugins/util/user-provided-git.js
  packages/dd-trace/test/plugins/util/ci-env/azurepipelines.json
  packages/dd-trace/test/plugins/util/ci-env/bitbucket.json
  packages/dd-trace/test/plugins/util/ci-env/bitrise.json
  packages/dd-trace/test/plugins/util/ci-env/buddy.json
  packages/dd-trace/test/plugins/util/ci-env/buildkite.json
  packages/dd-trace/test/plugins/util/ci-env/circleci.json
  packages/dd-trace/test/plugins/util/ci-env/codefresh.json
  packages/dd-trace/test/plugins/util/ci-env/github.json
  packages/dd-trace/test/plugins/util/ci-env/gitlab.json
  packages/dd-trace/test/plugins/util/ci-env/jenkins.json
  packages/dd-trace/test/plugins/util/ci-env/teamcity.json
  packages/dd-trace/test/plugins/util/ci-env/usersupplied.json
  packages/dd-trace/test/plugins/util/git.spec.js
  packages/dd-trace/test/plugins/util/url.spec.js
Labels: ci-app, semver-patch

#3781 PROF-8545: Eagerly release cached reference to web span tags when the span finishes
  packages/dd-trace/src/opentracing/span.js
  packages/dd-trace/src/profiling/profilers/wall.js
Labels: profiling, semver-patch

#3780 PROF-8545: only consider ancestor spans when looking for web tags
  packages/dd-trace/src/profiling/profilers/wall.js
Labels: profiling, semver-patch

#3791 enable arm builds for single-step
  .gitlab-ci.yml
Labels: semver-patch

#3768 Add owners for all CI files
  CODEOWNERS
Labels: semver-patch

#3786 Obfuscate secret tokens
  packages/dd-trace/test/appsec/iast/analyzers/hardcoded-secret-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/resources/hardcoded-secrets-suite.json
Labels: semver-patch

#3795 ASM - Update collected request headers [APPSEC-11226]
  packages/dd-trace/src/appsec/reporter.js
  packages/dd-trace/src/plugins/util/ip_extractor.js
  packages/dd-trace/test/appsec/reporter.spec.js
Labels: asm-waf, semver-minor

#3763 feat: add DSM pathway hash to Kafka spans
  ext/tags.d.ts
  ext/tags.js
  packages/datadog-plugin-kafkajs/src/consumer.js
  packages/datadog-plugin-kafkajs/src/producer.js
  packages/datadog-plugin-kafkajs/test/index.spec.js
  packages/dd-trace/src/datastreams/processor.js
  packages/dd-trace/src/tracer.js
Labels: semver-minor

#3787 Update native-iast-taint-tracking to v1.6.4
  package.json
  yarn.lock
Labels: semver-minor, asm-iast

#3796 enable tracing header injection for AWS requests
  packages/datadog-plugin-aws-sdk/test/aws-sdk.spec.js
  packages/datadog-plugin-fetch/test/index.spec.js
  packages/datadog-plugin-http/src/client.js
  packages/datadog-plugin-http/test/client.spec.js
  packages/datadog-plugin-http2/src/client.js
  packages/datadog-plugin-http2/test/client.spec.js
Labels: semver-minor, integration-http2, integration-http, integration-fetch

#3782 restify: emit on DC channels w/ async handlers
  packages/datadog-instrumentations/src/restify.js
  packages/datadog-plugin-restify/test/index.spec.js
Labels: semver-patch, integration-restify

#3656 core: enable 128-bit ids by default for v5+
  packages/datadog-plugin-mysql/test/index.spec.js
  packages/datadog-plugin-mysql2/test/index.spec.js
  packages/datadog-plugin-pg/test/index.spec.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/opentracing/span_context.js
  packages/dd-trace/src/plugins/database.js
  packages/dd-trace/test/config.spec.js
Labels: semver-minor

#3766 Otel span name translator
  ext/kinds.d.ts
  ext/kinds.js
  packages/dd-trace/src/format.js
  packages/dd-trace/src/opentelemetry/span.js
  packages/dd-trace/src/opentelemetry/tracer.js
  packages/dd-trace/test/format.spec.js
  packages/dd-trace/test/opentelemetry/span.spec.js
Labels: semver-minor, open-telemetry

#3800 make 128bit ids default even in v4.x release line
  packages/datadog-plugin-mysql/test/index.spec.js
  packages/datadog-plugin-mysql2/test/index.spec.js
  packages/datadog-plugin-pg/test/index.spec.js
  packages/dd-trace/src/config.js
Labels: semver-patch

#3799 Revert "enable tracing header injection for AWS requests (#3796)"
  packages/datadog-plugin-aws-sdk/test/aws-sdk.spec.js
  packages/datadog-plugin-fetch/test/index.spec.js
  packages/datadog-plugin-http/src/client.js
  packages/datadog-plugin-http/test/client.spec.js
  packages/datadog-plugin-http2/src/client.js
  packages/datadog-plugin-http2/test/client.spec.js
Labels: semver-patch

#3807 PROF-8458: Enhance the way GC profiler is enabled
  packages/dd-trace/src/profiling/config.js
Labels: profiling, semver-patch

#3805 Load appsec rules in appsec/rule_manager.js
  packages/dd-trace/src/appsec/index.js
  packages/dd-trace/src/appsec/rule_manager.js
  packages/dd-trace/src/config.js
  packages/dd-trace/test/appsec/bad-formatted-rules.json
  packages/dd-trace/test/appsec/blocking-actions-rules.json
  packages/dd-trace/test/appsec/index.spec.js
  packages/dd-trace/test/appsec/rule_manager.spec.js
  packages/dd-trace/test/config.spec.js
Labels: asm-waf, semver-minor

#3792 PROF-8545: Memoize web tags in all ancestors
  integration-tests/profiler/codehotspots.js
  packages/dd-trace/src/profiling/profilers/wall.js
Labels: profiling, semver-patch

#3808 PROF-8649: Emit wall sample timestamps even when code hotspots aren't used
  integration-tests/profiler.spec.js
  packages/dd-trace/src/profiling/profilers/events.js
  packages/dd-trace/src/profiling/profilers/wall.js
Labels: profiling, semver-patch

#3810 always propagate tracestate when tracecontext is configured
  packages/dd-trace/src/config.js
  packages/dd-trace/src/id.js
  packages/dd-trace/src/opentracing/propagation/text_map.js
  packages/dd-trace/test/opentracing/propagation/text_map.spec.js
Labels: semver-patch

#3809 [core] Collapse Next.js Static Resources to Reduce Cardinality
  packages/datadog-instrumentations/src/next.js
  packages/datadog-plugin-next/src/index.js
  packages/datadog-plugin-next/test/index.spec.js
Labels: semver-patch

#3685 API Security integration
  docs/test.ts
  index.d.ts
  package.json
  packages/dd-trace/src/appsec/addresses.js
  packages/dd-trace/src/appsec/index.js
  packages/dd-trace/src/appsec/reporter.js
  packages/dd-trace/src/appsec/waf/waf_context_wrapper.js
  packages/dd-trace/src/appsec/waf/waf_manager.js
  packages/dd-trace/src/config.js
  packages/dd-trace/test/appsec/api_security_rules.json
  packages/dd-trace/test/appsec/index.express.plugin.spec.js
  packages/dd-trace/test/appsec/index.spec.js
  packages/dd-trace/test/appsec/reporter.spec.js
  packages/dd-trace/test/appsec/waf/index.spec.js
  packages/dd-trace/test/appsec/waf/waf_context_wrapper.spec.js
  packages/dd-trace/test/config.spec.js
  yarn.lock
Labels: asm-waf, semver-minor

#3817 Expose a promise for profiler start
  integration-tests/profiler/codehotspots.js
  packages/dd-trace/src/noop/proxy.js
  packages/dd-trace/src/profiler.js
  packages/dd-trace/src/profiling/profiler.js
  packages/dd-trace/src/proxy.js
Labels: profiling, semver-minor

#3821 Add source code integration tags to profiles
  packages/dd-trace/src/profiler.js
  packages/dd-trace/src/profiling/config.js
  packages/dd-trace/test/profiling/config.spec.js
Labels: bug, profiling, semver-minor

#3825 [ci-visibility] Fix debug message for ITR settings
  packages/dd-trace/src/ci-visibility/intelligent-test-runner/get-itr-configuration.js
Labels: ci-app, semver-patch

#3804 instrument aerospike v4, v5
  .github/workflows/plugins.yml
  docker-compose.yml
  packages/datadog-instrumentations/src/aerospike.js
  packages/datadog-instrumentations/src/helpers/hooks.js
  packages/datadog-plugin-aerospike/src/index.js
  packages/datadog-plugin-aerospike/test/index.spec.js
  packages/datadog-plugin-aerospike/test/naming.js
  packages/dd-trace/src/plugins/index.js
  packages/dd-trace/src/service-naming/schemas/v0/storage.js
  packages/dd-trace/src/service-naming/schemas/v1/storage.js
  packages/dd-trace/test/setup/mocha.js
  scripts/install_plugin_modules.js
Labels: semver-minor

#3830 Instrument Aerospike V3
  .github/workflows/plugins.yml
  packages/datadog-instrumentations/src/aerospike.js
  packages/datadog-plugin-aerospike/test/index.spec.js
Labels: semver-minor
