Repository DataDog/dd-trace-js, pull requests merged in 2024-10, with the labels that each got.

#4747 Update workflows to fix release process
  .github/workflows/rebase-release-proposal.yml
  .github/workflows/release-latest.yml
Labels: semver-patch

#4727 [DI] Add stack trace to log probe results
  integration-tests/debugger/index.spec.js
  packages/dd-trace/src/debugger/devtools_client/index.js
  packages/dd-trace/src/debugger/devtools_client/remote_config.js
  packages/dd-trace/src/debugger/devtools_client/state.js
Labels: semver-minor

#4743 Don't use deprecated url.parse function
  packages/dd-trace/src/exporters/common/request.js
  packages/dd-trace/src/exporters/common/url-to-http-options-polyfill.js
Labels: semver-patch

#4745 [test visibility] Read `pull_request` and `pull_request_target` event info from GHA
  packages/dd-trace/src/plugins/util/ci.js
  packages/dd-trace/src/plugins/util/tags.js
  packages/dd-trace/test/plugins/util/fixtures/github_event_payload.json
  packages/dd-trace/test/plugins/util/fixtures/github_event_payload_malformed.json
  packages/dd-trace/test/plugins/util/test-environment.spec.js
Labels: ci-app, semver-minor

#4728 [DI] Switch unit tests to Mocha instead of Tap
  package.json
  packages/dd-trace/test/debugger/devtools_client/status.spec.js
Labels: semver-patch

#4750 [DI] Fix probe.location.lines to be string[] instead of number[]
  integration-tests/debugger/index.spec.js
  packages/dd-trace/src/debugger/devtools_client/remote_config.js
Labels: semver-patch

#4751 [DI] Add GitHub repo and SHA tags to probe results
  packages/dd-trace/src/debugger/devtools_client/config.js
  packages/dd-trace/src/debugger/devtools_client/send.js
Labels: semver-minor

#4746 chore: prefix system tests credentials environment variable
  .github/workflows/system-tests.yml
Labels: semver-patch

#4752 Fix child process not maintaining previous parent span after execution
  packages/datadog-instrumentations/src/child_process.js
  packages/datadog-plugin-child_process/test/index.spec.js
Labels: semver-patch

#4754 Fix appsec rate limiter flaky test
  packages/dd-trace/test/appsec/reporter.spec.js
Labels: semver-patch

#4756 [DI] Add hostname to probe result
  integration-tests/debugger/index.spec.js
  packages/dd-trace/src/debugger/devtools_client/send.js
Labels: semver-minor

#4712 Sql injection Exploit Prevention implementation for mysql2 library
  packages/datadog-instrumentations/src/mysql2.js
  packages/datadog-instrumentations/test/mysql2.spec.js
  packages/dd-trace/src/appsec/channels.js
  packages/dd-trace/src/appsec/rasp/sql_injection.js
  packages/dd-trace/test/appsec/index.sequelize.plugin.spec.js
  packages/dd-trace/test/appsec/rasp/sql_injection.mysql2.plugin.spec.js
  packages/dd-trace/test/appsec/rasp/sql_injection.spec.js
  packages/dd-trace/test/plugins/externals.json
Labels: semver-minor

#4549 [DI] Add ability to take state snapshot
  integration-tests/debugger/index.spec.js
  integration-tests/debugger/target-app/index.js
  packages/dd-trace/src/debugger/devtools_client/index.js
  packages/dd-trace/src/debugger/devtools_client/remote_config.js
  packages/dd-trace/src/debugger/devtools_client/snapshot/collector.js
  packages/dd-trace/src/debugger/devtools_client/snapshot/index.js
  packages/dd-trace/src/debugger/devtools_client/snapshot/processor.js
  packages/dd-trace/test/.eslintrc.json
  packages/dd-trace/test/debugger/devtools_client/_inspected_file.js
  packages/dd-trace/test/debugger/devtools_client/snapshot.spec.js
Labels: semver-minor

#4701 feat(tracing): implement protobufjs DSM schema support
  .github/workflows/plugins.yml
  docs/API.md
  docs/add-redirects.sh
  docs/test.ts
  index.d.ts
  packages/datadog-instrumentations/src/helpers/hooks.js
  packages/datadog-instrumentations/src/protobufjs.js
  packages/datadog-plugin-protobufjs/src/index.js
  packages/datadog-plugin-protobufjs/src/schema_iterator.js
  packages/datadog-plugin-protobufjs/test/helpers.js
  packages/datadog-plugin-protobufjs/test/index.spec.js
  packages/datadog-plugin-protobufjs/test/schemas/all_types.proto
  packages/datadog-plugin-protobufjs/test/schemas/expected_schemas.json
  packages/datadog-plugin-protobufjs/test/schemas/message.proto
  packages/datadog-plugin-protobufjs/test/schemas/other_message.proto
  packages/datadog-plugin-protobufjs/test/schemas/other_message_proto.json
  packages/dd-trace/src/datastreams/schemas/schema_builder.js
  packages/dd-trace/src/plugins/index.js
  packages/dd-trace/src/plugins/schema.js
  packages/dd-trace/test/datastreams/schemas/schema_builder.spec.js
Labels: semver-minor, datastreams

#4201 use AsyncLocalStorage instead of our home-grown solutions
  packages/datadog-core/index.js
  packages/datadog-core/src/storage/async_resource.js
  packages/datadog-core/src/storage/index.js
  packages/datadog-core/test/setup.js
  packages/datadog-core/test/storage/async_resource.spec.js
  packages/datadog-core/test/storage/test.js
  packages/dd-trace/src/profiling/profilers/wall.js
Labels: semver-patch

#4761 Upgrade iast rewriter to 2.5.0
  package.json
  packages/dd-trace/src/appsec/iast/taint-tracking/csi-methods.js
  packages/dd-trace/src/appsec/iast/taint-tracking/taint-tracking-impl.js
  packages/dd-trace/test/appsec/iast/taint-tracking/resources/propagationFunctions.js
  packages/dd-trace/test/appsec/iast/taint-tracking/taint-tracking-impl.spec.js
  yarn.lock
Labels: semver-minor, asm-iast

#4676 Exploit Prevention LFI
  packages/datadog-instrumentations/src/express.js
  packages/datadog-instrumentations/src/fs.js
  packages/dd-trace/src/appsec/addresses.js
  packages/dd-trace/src/appsec/channels.js
  packages/dd-trace/src/appsec/iast/analyzers/path-traversal-analyzer.js
  packages/dd-trace/src/appsec/iast/index.js
  packages/dd-trace/src/appsec/rasp/fs-plugin.js
  packages/dd-trace/src/appsec/rasp/index.js
  packages/dd-trace/src/appsec/rasp/lfi.js
  packages/dd-trace/src/appsec/rasp/utils.js
  packages/dd-trace/src/appsec/remote_config/capabilities.js
  packages/dd-trace/src/appsec/remote_config/index.js
  packages/dd-trace/test/appsec/iast/analyzers/path-traversal-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/index.spec.js
  packages/dd-trace/test/appsec/index.spec.js
  packages/dd-trace/test/appsec/rasp/fs-plugin.spec.js
  packages/dd-trace/test/appsec/rasp/index.spec.js
  packages/dd-trace/test/appsec/rasp/lfi.express.plugin.spec.js
  packages/dd-trace/test/appsec/rasp/lfi.integration.express.plugin.spec.js
  packages/dd-trace/test/appsec/rasp/lfi.spec.js
  packages/dd-trace/test/appsec/rasp/resources/lfi-app/index.js
  packages/dd-trace/test/appsec/rasp/resources/lfi_rasp_rules.json
  packages/dd-trace/test/appsec/rasp/utils.js
  packages/dd-trace/test/appsec/remote_config/index.spec.js
  packages/dd-trace/test/appsec/response_blocking.spec.js
  packages/dd-trace/test/plugins/agent.js
Labels: semver-minor, appsec

#4698 [ASM] Add support for attacker fingerprinting
  .github/workflows/appsec.yml
  packages/dd-trace/src/appsec/addresses.js
  packages/dd-trace/src/appsec/remote_config/capabilities.js
  packages/dd-trace/src/appsec/remote_config/index.js
  packages/dd-trace/src/appsec/reporter.js
  packages/dd-trace/src/appsec/sdk/track_event.js
  packages/dd-trace/src/appsec/waf/waf_context_wrapper.js
  packages/dd-trace/test/appsec/attacker-fingerprinting-rules.json
  packages/dd-trace/test/appsec/attacker-fingerprinting.express.plugin.spec.js
  packages/dd-trace/test/appsec/attacker-fingerprinting.passport-http.plugin.spec.js
  packages/dd-trace/test/appsec/attacker-fingerprinting.passport-local.plugin.spec.js
  packages/dd-trace/test/appsec/attacker-fingerprinting.spec.js
  packages/dd-trace/test/appsec/remote_config/index.spec.js
  packages/dd-trace/test/appsec/reporter.spec.js
  packages/dd-trace/test/appsec/sdk/track_event.spec.js
  packages/dd-trace/test/appsec/waf/index.spec.js
  packages/dd-trace/test/plugins/externals.json
Labels: asm-waf, semver-minor, appsec

#4763 Keep a profiling context object in spans
  packages/dd-trace/src/profiling/profilers/wall.js
Labels: profiling, semver-minor

#4762 [test visibility] Add option to automatically report logs within tests when using `winston`
  integration-tests/automatic-log-submission.spec.js
  integration-tests/ci-visibility-intake.js
  integration-tests/ci-visibility/automatic-log-submission-cucumber/automatic-log-submission.feature
  integration-tests/ci-visibility/automatic-log-submission-cucumber/support/logger.js
  integration-tests/ci-visibility/automatic-log-submission-cucumber/support/steps.js
  integration-tests/ci-visibility/automatic-log-submission-cucumber/support/sum.js
  integration-tests/ci-visibility/automatic-log-submission/automatic-log-submission-test.js
  integration-tests/ci-visibility/automatic-log-submission/config-jest.js
  integration-tests/ci-visibility/automatic-log-submission/logger.js
  integration-tests/ci-visibility/automatic-log-submission/sum.js
  integration-tests/selenium/selenium.spec.js
  packages/datadog-instrumentations/src/jest.js
  packages/datadog-instrumentations/src/winston.js
  packages/dd-trace/src/ci-visibility/log-submission/log-submission-plugin.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/plugin_manager.js
  packages/dd-trace/src/plugins/ci_plugin.js
  packages/dd-trace/src/plugins/log_plugin.js
  packages/dd-trace/src/proxy.js
Labels: ci-app, semver-minor

#4764 Use static vulnerability hash source when the cookie name is too long
  docs/test.ts
  index.d.ts
  packages/dd-trace/src/appsec/iast/analyzers/cookie-analyzer.js
  packages/dd-trace/src/appsec/iast/iast-plugin.js
  packages/dd-trace/src/config.js
  packages/dd-trace/test/appsec/iast/analyzers/cookie-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/insecure-cookie-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/no-httponly-cookie-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/no-samesite-cookie-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/utils.js
  packages/dd-trace/test/config.spec.js
Labels: semver-minor, asm-iast

#4716 Add Plugin for @azure/functions
  .github/workflows/plugins.yml
  .gitignore
  docs/API.md
  docs/test.ts
  ext/types.d.ts
  ext/types.js
  index.d.ts
  integration-tests/helpers/index.js
  packages/datadog-instrumentations/src/azure-functions.js
  packages/datadog-instrumentations/src/helpers/hooks.js
  packages/datadog-plugin-azure-functions/src/index.js
  packages/datadog-plugin-azure-functions/test/integration-test/client.spec.js
  packages/datadog-plugin-azure-functions/test/integration-test/fixtures/host.json
  packages/datadog-plugin-azure-functions/test/integration-test/fixtures/local.settings.json
  packages/datadog-plugin-azure-functions/test/integration-test/fixtures/package.json
  packages/datadog-plugin-azure-functions/test/integration-test/fixtures/src/functions/server.mjs
  packages/datadog-plugin-azure-functions/test/integration-test/fixtures/yarn.lock
  packages/dd-trace/src/plugins/index.js
  packages/dd-trace/src/plugins/util/serverless.js
  packages/dd-trace/src/plugins/util/web.js
  packages/dd-trace/src/service-naming/schemas/v0/index.js
  packages/dd-trace/src/service-naming/schemas/v0/serverless.js
  packages/dd-trace/src/service-naming/schemas/v1/index.js
  packages/dd-trace/src/service-naming/schemas/v1/serverless.js
Labels: semver-minor, serverless

#4768 Update waf rules to 1.13.1
  packages/dd-trace/src/appsec/recommended.json
Labels: asm-waf, semver-minor

#4449 [DEBUG-2972] Add initial support for Code Origin for Spans (Fastify entry spans only)
  CODEOWNERS
  packages/datadog-code-origin/index.js
  packages/datadog-instrumentations/src/fastify.js
  packages/datadog-instrumentations/src/mocha/common.js
  packages/datadog-plugin-fastify/src/code_origin.js
  packages/datadog-plugin-fastify/src/index.js
  packages/datadog-plugin-fastify/src/tracing.js
  packages/datadog-plugin-fastify/test/code_origin.spec.js
  packages/datadog-plugin-fastify/test/tracing.spec.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/plugins/util/stacktrace.js
  packages/dd-trace/src/plugins/util/test.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/plugins/util/stacktrace.spec.js
Labels: enhancement, semver-minor, integration-fastify

#4776 Unsubscribe NextJS body and query channels on appsec disable
  packages/dd-trace/src/appsec/index.js
  packages/dd-trace/test/appsec/index.spec.js
Labels: semver-patch, appsec

#4777 [DI] Refactor unit tests
  packages/dd-trace/test/debugger/devtools_client/_inspected_file.js
  packages/dd-trace/test/debugger/devtools_client/snapshot.spec.js
  packages/dd-trace/test/debugger/devtools_client/snapshot/complex-types.spec.js
  packages/dd-trace/test/debugger/devtools_client/snapshot/max-reference-depth.spec.js
  packages/dd-trace/test/debugger/devtools_client/snapshot/primitives.spec.js
  packages/dd-trace/test/debugger/devtools_client/snapshot/scopes.spec.js
  packages/dd-trace/test/debugger/devtools_client/snapshot/target-code/complex-types.js
  packages/dd-trace/test/debugger/devtools_client/snapshot/target-code/max-reference-depth.js
  packages/dd-trace/test/debugger/devtools_client/snapshot/target-code/primitives.js
  packages/dd-trace/test/debugger/devtools_client/snapshot/target-code/scopes.js
  packages/dd-trace/test/debugger/devtools_client/snapshot/utils.js
Labels: semver-patch

#4782 Upgrading jsonpath-plus to v10 to resolve CVE-2024-21534
  package.json
  yarn.lock
Labels: semver-patch, dont-land-on-v4.x

#4769 Suspicious request blocking - Express Path Parameters
  packages/datadog-instrumentations/src/express.js
  packages/dd-trace/src/appsec/channels.js
  packages/dd-trace/src/appsec/index.js
  packages/dd-trace/test/appsec/express-rules.json
  packages/dd-trace/test/appsec/index.express.plugin.spec.js
  packages/dd-trace/test/appsec/index.spec.js
Labels: asm-waf, semver-minor, appsec

#4785 vendor jsonpath-plus
  .eslintignore
  LICENSE-3rdparty.csv
  package.json
  packages/dd-trace/src/payload-tagging/index.js
  packages/dd-trace/src/payload-tagging/jsonpath-plus.js
  yarn.lock
Labels: semver-patch

#4779 Don't stop the profiler if encoding a profile fails
  packages/dd-trace/src/profiling/profiler.js
  packages/dd-trace/src/profiling/profilers/events.js
  packages/dd-trace/test/profiling/profiler.spec.js
Labels: profiling, semver-patch

#4786 Remove old debug option from docs
  docs/API.md
Labels: docs, semver-patch

#4793 pin latest to 22
  .github/actions/node/latest/action.yml
Labels: semver-patch

#4790 update body-parser
  package.json
  yarn.lock
Labels: semver-patch

#4794 update sinon
  .github/workflows/project.yml
  package.json
  yarn.lock
Labels: semver-patch

#4798 fix WAF update rules version
  packages/dd-trace/src/appsec/waf/waf_manager.js
  packages/dd-trace/test/appsec/waf/index.spec.js
Labels: semver-patch, asm-waf

#4791 [ASM] Ssrf handle request options
  packages/dd-trace/src/appsec/rasp/ssrf.js
  packages/dd-trace/test/appsec/rasp/ssrf.express.plugin.spec.js
  packages/dd-trace/test/plugins/externals.json
Labels: semver-patch

#4801 Don't update waf version if it doesn't exist
  packages/dd-trace/src/appsec/waf/waf_manager.js
  packages/dd-trace/test/appsec/waf/index.spec.js
Labels: semver-patch, asm-waf

#4724 Identify span metrics from OpenTelemetry libraries with 'otel.library' tag
  integration-tests/opentelemetry.spec.js
  packages/dd-trace/src/opentelemetry/span.js
  packages/dd-trace/src/opentelemetry/tracer.js
Labels: semver-minor, open-telemetry

#4774 Fix: esbuild plugin when requiring esm files
  LICENSE-3rdparty.csv
  integration-tests/esbuild/basic-test.js
  integration-tests/esbuild/package.json
  package.json
  packages/datadog-esbuild/index.js
  packages/datadog-instrumentations/src/utils/src/extract-package-and-module-path.js
Labels: semver-patch, bundler

#4725 Implement Config Consistency
  packages/datadog-instrumentations/src/helpers/register.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/opentracing/tracer.js
  packages/dd-trace/src/telemetry/index.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/config/disabled_instrumentations.spec.js
  packages/dd-trace/test/opentracing/tracer.spec.js
Labels: semver-minor

#4771 [CI] Enable Fastify suite.js
  packages/datadog-plugin-fastify/test/suite.js
Labels: semver-patch

#4809 Fix yarn.lock
  yarn.lock
Labels: semver-patch

#4807 also audit devDependencies
  package.json
Labels: semver-patch

#4810 Update @datadog/native-appsec to 8.2.1
  package.json
  yarn.lock
Labels: semver-minor

#4780 [DI] Adhere to maxCollectionSize limit in snapshots
  integration-tests/debugger/index.spec.js
  integration-tests/debugger/target-app/index.js
  packages/dd-trace/src/debugger/devtools_client/index.js
  packages/dd-trace/src/debugger/devtools_client/snapshot/collector.js
  packages/dd-trace/src/debugger/devtools_client/snapshot/index.js
  packages/dd-trace/src/debugger/devtools_client/snapshot/processor.js
  packages/dd-trace/src/debugger/devtools_client/snapshot/symbols.js
  packages/dd-trace/test/debugger/devtools_client/snapshot/max-collection-size.spec.js
  packages/dd-trace/test/debugger/devtools_client/snapshot/target-code/max-collection-size.js
Labels: semver-patch

#4811 refactor system tests
  .github/workflows/system-tests.yml
Labels: semver-minor

#4800 Add Support For Overriding GRPC Error Statuses
  packages/datadog-plugin-grpc/src/client.js
  packages/datadog-plugin-grpc/src/server.js
  packages/datadog-plugin-grpc/test/client.spec.js
  packages/datadog-plugin-grpc/test/server.spec.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/constants.js
  packages/dd-trace/src/telemetry/index.js
  packages/dd-trace/test/config.spec.js
Labels: semver-minor

#4753 add requirements json with native deps and denylist
  .gitlab-ci.yml
  .gitlab/prepare-oci-package.sh
  .gitlab/requirements_allow.json
  .gitlab/requirements_block.json
  requirements.json
Labels: semver-patch

#4803 Add support for Azure App Services tags in profiler
  packages/dd-trace/src/azure_metadata.js
  packages/dd-trace/src/profiling/config.js
  packages/dd-trace/test/azure_metadata.spec.js
Labels: semver-minor

#4813 [test visibility] Add errors in retried tests in mocha
  integration-tests/mocha/mocha.spec.js
  packages/datadog-instrumentations/src/mocha/utils.js
  packages/datadog-plugin-mocha/src/index.js
Labels: ci-app, semver-minor

#4816 [DI] Guard against invalid probe config and related edge-cases
  packages/dd-trace/src/debugger/index.js
Labels: semver-patch

#4815 Support Node 23 in the profiler
  package.json
  yarn.lock
Labels: semver-minor

#4820 Protect some lines in text_map.js
  packages/dd-trace/src/opentracing/propagation/text_map.js
  packages/dd-trace/test/opentracing/propagation/text_map.spec.js
Labels: semver-patch

#4822 Separating Plugin Tests to Their Own CI Run
  .github/workflows/plugins.yml
  packages/dd-trace/test/plugins/externals.json
Labels: semver-minor

#4824 Update @datadog/native-iast-taint-tracking
  package.json
  yarn.lock
Labels: semver-minor

#4808 feat(kafkajs): add kafka cluster id to spans and dsm metrics
  docker-compose.yml
  packages/datadog-instrumentations/src/kafkajs.js
  packages/datadog-plugin-kafkajs/src/batch-consumer.js
  packages/datadog-plugin-kafkajs/src/consumer.js
  packages/datadog-plugin-kafkajs/src/producer.js
  packages/datadog-plugin-kafkajs/test/index.spec.js
  packages/dd-trace/src/datastreams/pathway.js
  packages/dd-trace/test/datastreams/data_streams_checkpointer.spec.js
Labels: semver-minor

#4817 [DI] Refactor integration tests
  integration-tests/debugger/basic.spec.js
  integration-tests/debugger/index.spec.js
  integration-tests/debugger/snapshot.spec.js
  integration-tests/debugger/target-app/basic.js
  integration-tests/debugger/target-app/snapshot.js
  integration-tests/debugger/utils.js
Labels: semver-patch

#4739 Replace manual.keep tag usage with an specific method to keep the trace
  integration-tests/standalone-asm.spec.js
  packages/dd-trace/src/appsec/iast/vulnerability-reporter.js
  packages/dd-trace/src/appsec/reporter.js
  packages/dd-trace/src/appsec/sdk/track_event.js
  packages/dd-trace/src/priority_sampler.js
  packages/dd-trace/test/appsec/iast/vulnerability-reporter.spec.js
  packages/dd-trace/test/appsec/reporter.spec.js
  packages/dd-trace/test/appsec/sdk/track_event.spec.js
  packages/dd-trace/test/appsec/waf/index.spec.js
  packages/dd-trace/test/priority_sampler.spec.js
Labels: semver-minor

#4834 Update recommended waf rules to 1.13.2
  packages/dd-trace/src/appsec/recommended.json
Labels: asm-waf, semver-minor, appsec

#4829 [DI] Adhere to maxFieldCount limit in snapshots
  integration-tests/debugger/snapshot.spec.js
  packages/dd-trace/src/debugger/devtools_client/index.js
  packages/dd-trace/src/debugger/devtools_client/snapshot/collector.js
  packages/dd-trace/src/debugger/devtools_client/snapshot/index.js
  packages/dd-trace/src/debugger/devtools_client/snapshot/processor.js
  packages/dd-trace/src/debugger/devtools_client/snapshot/symbols.js
  packages/dd-trace/test/debugger/devtools_client/snapshot/complex-types.spec.js
  packages/dd-trace/test/debugger/devtools_client/snapshot/max-field-count-scopes.spec.js
  packages/dd-trace/test/debugger/devtools_client/snapshot/max-field-count.spec.js
  packages/dd-trace/test/debugger/devtools_client/snapshot/target-code/max-field-count-scopes.js
  packages/dd-trace/test/debugger/devtools_client/snapshot/target-code/max-field-count.js
Labels: semver-patch, dynamic-instrumentation

#4781 [ASM] multer instrumentation
  .github/workflows/appsec.yml
  integration-tests/appsec/multer.spec.js
  integration-tests/appsec/multer/body-parser-rules.json
  integration-tests/appsec/multer/index.js
  packages/datadog-instrumentations/src/helpers/hooks.js
  packages/datadog-instrumentations/src/multer.js
  packages/datadog-instrumentations/test/multer.spec.js
  packages/dd-trace/src/appsec/channels.js
  packages/dd-trace/src/appsec/iast/taint-tracking/plugin.js
  packages/dd-trace/src/appsec/index.js
  packages/dd-trace/test/appsec/iast/taint-tracking/plugin.spec.js
  packages/dd-trace/test/appsec/iast/utils.js
  packages/dd-trace/test/plugins/externals.json
Labels: semver-minor, appsec

#4742 [MLOB-1524] feat(llmobs): Introduce LLM Observability SDK
  .github/workflows/llmobs.yml
  CODEOWNERS
  docs/package.json
  docs/test.ts
  docs/yarn.lock
  index.d.ts
  integration-tests/helpers/fake-agent.js
  package.json
  packages/dd-trace/src/config.js
  packages/dd-trace/src/llmobs/constants/tags.js
  packages/dd-trace/src/llmobs/constants/text.js
  packages/dd-trace/src/llmobs/constants/writers.js
  packages/dd-trace/src/llmobs/index.js
  packages/dd-trace/src/llmobs/noop.js
  packages/dd-trace/src/llmobs/sdk.js
  packages/dd-trace/src/llmobs/span_processor.js
  packages/dd-trace/src/llmobs/storage.js
  packages/dd-trace/src/llmobs/tagger.js
  packages/dd-trace/src/llmobs/util.js
  packages/dd-trace/src/llmobs/writers/base.js
  packages/dd-trace/src/llmobs/writers/evaluations.js
  packages/dd-trace/src/llmobs/writers/spans/agentProxy.js
  packages/dd-trace/src/llmobs/writers/spans/agentless.js
  packages/dd-trace/src/llmobs/writers/spans/base.js
  packages/dd-trace/src/noop/proxy.js
  packages/dd-trace/src/proxy.js
  packages/dd-trace/src/span_processor.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/llmobs/index.spec.js
  packages/dd-trace/test/llmobs/noop.spec.js
  packages/dd-trace/test/llmobs/sdk/index.spec.js
  packages/dd-trace/test/llmobs/sdk/integration.spec.js
  packages/dd-trace/test/llmobs/sdk/typescript/index.spec.js
  packages/dd-trace/test/llmobs/sdk/typescript/index.ts
  packages/dd-trace/test/llmobs/sdk/typescript/noop.ts
  packages/dd-trace/test/llmobs/span_processor.spec.js
  packages/dd-trace/test/llmobs/tagger.spec.js
  packages/dd-trace/test/llmobs/util.js
  packages/dd-trace/test/llmobs/util.spec.js
  packages/dd-trace/test/llmobs/writers/base.spec.js
  packages/dd-trace/test/llmobs/writers/evaluations.spec.js
  packages/dd-trace/test/llmobs/writers/spans/agentProxy.spec.js
  packages/dd-trace/test/llmobs/writers/spans/agentless.spec.js
  packages/dd-trace/test/llmobs/writers/spans/base.spec.js
  packages/dd-trace/test/proxy.spec.js
Labels: semver-minor

#4818 [DI] Drop snapshot if JSON payload is too large
  integration-tests/debugger/snapshot-pruning.spec.js
  integration-tests/debugger/target-app/snapshot-pruning.js
  integration-tests/debugger/utils.js
  packages/dd-trace/src/debugger/devtools_client/send.js
  packages/dd-trace/test/debugger/devtools_client/snapshot/complex-types.spec.js
Labels: semver-patch, dynamic-instrumentation

#4772 Add support for exit spans in Code Origin for Spans
  packages/datadog-code-origin/index.js
  packages/datadog-core/src/utils/src/parse-tags.js
  packages/datadog-core/test/utils/src/parse-tags.spec.js
  packages/datadog-plugin-fastify/src/code_origin.js
  packages/datadog-plugin-fastify/test/code_origin.spec.js
  packages/datadog-plugin-http/test/code_origin.spec.js
  packages/dd-trace/src/plugins/outbound.js
  packages/dd-trace/test/plugins/helpers.js
  packages/dd-trace/test/plugins/outbound.spec.js
  packages/dd-trace/test/plugins/util/stacktrace.spec.js
Labels: semver-minor

#4838 update native metrics to 3.0.1
  package.json
  yarn.lock
Labels: semver-patch

#3855 add dsm for google pub sub
  packages/datadog-plugin-google-cloud-pubsub/src/consumer.js
  packages/datadog-plugin-google-cloud-pubsub/src/producer.js
  packages/datadog-plugin-google-cloud-pubsub/test/index.spec.js
Labels: semver-minor, datastreams

#4844 Fix header injection test for `access-control-allow-origin` exclusion
  packages/dd-trace/test/appsec/iast/analyzers/header-injection.express.plugin.spec.js
Labels: semver-patch, asm-iast, appsec

#4831 Defend against ref being undefined
  packages/dd-trace/src/profiling/profilers/wall.js
Labels: profiling, semver-patch

#4845 upgrade to latest @azure/functions version
  packages/datadog-plugin-azure-functions/test/integration-test/fixtures/package.json
  packages/datadog-plugin-azure-functions/test/integration-test/fixtures/yarn.lock
Labels: semver-patch

#4846 fix(ci): revert typescript 5.0 for docs tests
  docs/package.json
  docs/test.ts
  docs/yarn.lock
Labels: semver-patch
