Repository DataDog/dd-trace-js, pull requests merged in 2024-02, with the labels that each got.

#4010 [ci-visibility] Refactor ITR config to library config
  integration-tests/ci-visibility.spec.js
  integration-tests/cucumber/cucumber.spec.js
  packages/datadog-instrumentations/src/cucumber.js
  packages/datadog-instrumentations/src/jest.js
  packages/datadog-instrumentations/src/mocha.js
  packages/datadog-plugin-cucumber/src/index.js
  packages/datadog-plugin-cypress/src/plugin.js
  packages/datadog-plugin-jest/src/index.js
  packages/datadog-plugin-mocha/src/index.js
  packages/dd-trace/src/ci-visibility/exporters/ci-visibility-exporter.js
  packages/dd-trace/src/ci-visibility/requests/get-library-configuration.js
  packages/dd-trace/src/plugins/ci_plugin.js
  packages/dd-trace/test/ci-visibility/exporters/agent-proxy/agent-proxy.spec.js
  packages/dd-trace/test/ci-visibility/exporters/agentless/exporter.spec.js
  packages/dd-trace/test/ci-visibility/exporters/ci-visibility-exporter.spec.js
Labels: ci-app, semver-patch

#4016 [ci-visibility] Use gzip for skippable endpoint if it's available
  packages/dd-trace/src/ci-visibility/exporters/ci-visibility-exporter.js
  packages/dd-trace/src/ci-visibility/intelligent-test-runner/get-skippable-suites.js
  packages/dd-trace/test/ci-visibility/exporters/ci-visibility-exporter.spec.js
Labels: ci-app, semver-minor

#4021 [ci-visibility] Attempt to use repository root to find CODEOWNERS file
  packages/datadog-plugin-cypress/src/plugin.js
  packages/dd-trace/src/plugins/ci_plugin.js
  packages/dd-trace/src/plugins/util/test.js
  packages/dd-trace/test/plugins/util/test.spec.js
Labels: ci-app, semver-minor

#4008 Supports form data for nextjs body instrumentation
  packages/datadog-instrumentations/src/next.js
  packages/dd-trace/test/appsec/index.next.plugin.spec.js
  packages/dd-trace/test/appsec/next/app-dir/app/api/test-formdata/route.js
  packages/dd-trace/test/appsec/next/pages-dir/pages/api/test-formdata/index.js
Labels: asm-waf, semver-minor

#4028 Update rewriter to fix `Error.prepareStackTrace` overrides with iast enabled
  package.json
  yarn.lock
Labels: semver-patch, asm-iast

#4029 Fix error in http client plugin
  packages/datadog-plugin-http/src/client.js
Labels: semver-patch

#4015 [ci-visibility] Add get known tests request
  packages/dd-trace/src/ci-visibility/early-flake-detection/get-known-tests.js
  packages/dd-trace/src/ci-visibility/exporters/ci-visibility-exporter.js
  packages/dd-trace/src/ci-visibility/requests/get-library-configuration.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/plugins/ci_plugin.js
  packages/dd-trace/test/ci-visibility/exporters/ci-visibility-exporter.spec.js
  packages/dd-trace/test/config.spec.js
Labels: ci-app, semver-minor

#4023 [ci-visibility] Fix appClosing telemetry event
  packages/datadog-plugin-cypress/test/app-10/CODEOWNERS
  packages/datadog-plugin-cypress/test/app/CODEOWNERS
  packages/datadog-plugin-cypress/test/index.spec.js
  packages/dd-trace/src/telemetry/index.js
  packages/dd-trace/test/telemetry/index.spec.js
Labels: ci-app, semver-patch

#4025 upgrade docs/ packages: VULN-5529 VULN-5527 VULN-5525 VULN-5522
  docs/yarn.lock
Labels: semver-patch

#4005 Api security enabled by default and configurable by non experimental environment variable
  packages/dd-trace/src/config.js
  packages/dd-trace/test/config.spec.js
Labels: asm-waf, semver-minor

#4034 docs: remove bundling section from README
  README.md
Labels: semver-patch

#3924 Implement Span Links
  index.d.ts
  packages/dd-trace/src/encode/agentless-ci-visibility.js
  packages/dd-trace/src/format.js
  packages/dd-trace/src/noop/span.js
  packages/dd-trace/src/opentelemetry/span.js
  packages/dd-trace/src/opentracing/span.js
  packages/dd-trace/src/opentracing/span_context.js
  packages/dd-trace/src/opentracing/tracer.js
  packages/dd-trace/test/encode/0.4.spec.js
  packages/dd-trace/test/encode/0.5.spec.js
  packages/dd-trace/test/format.spec.js
  packages/dd-trace/test/opentelemetry/span.spec.js
  packages/dd-trace/test/opentracing/span.spec.js
  packages/dd-trace/test/opentracing/tracer.spec.js
Labels: semver-minor

#4036 upgrade mocha@8 to mocha@9 (VULN-5521, VULN-5526)
  package.json
  packages/datadog-plugin-mysql/test/index.spec.js
  packages/datadog-plugin-mysql2/test/index.spec.js
  packages/datadog-plugin-pg/test/index.spec.js
  yarn.lock
Labels: semver-patch

#4040 Sort the list of env vars for profiler config
  packages/dd-trace/src/profiling/config.js
Labels: semver-patch

#4041 allow unix URLs for datastreams
  packages/dd-trace/src/datastreams/writer.js
  packages/dd-trace/test/datastreams/writer.spec.js
Labels: semver-patch, datastreams

#3976 Support schema extraction in express response objects
  packages/datadog-instrumentations/src/express.js
  packages/dd-trace/src/appsec/addresses.js
  packages/dd-trace/src/appsec/api_security_sampler.js
  packages/dd-trace/src/appsec/channels.js
  packages/dd-trace/src/appsec/index.js
  packages/dd-trace/test/appsec/api_security_rules.json
  packages/dd-trace/test/appsec/api_security_sampler.spec.js
  packages/dd-trace/test/appsec/index.express.plugin.spec.js
  packages/dd-trace/test/appsec/index.spec.js
Labels: asm-waf, semver-minor

#4044 [ci-visibility] Fix `DD_TAGS`
  ci/init.js
  integration-tests/ci-visibility.spec.js
  integration-tests/cucumber/cucumber.spec.js
  integration-tests/cypress/cypress.spec.js
  integration-tests/playwright/playwright.spec.js
  packages/dd-trace/src/config.js
Labels: ci-app, semver-patch

#4030 [ci-visibility] Fix test source file to be relative to the repository root
  integration-tests/ci-visibility.spec.js
  integration-tests/cucumber/cucumber.spec.js
  integration-tests/cypress/cypress.spec.js
  integration-tests/helpers.js
  integration-tests/playwright/playwright.spec.js
  packages/datadog-instrumentations/src/cucumber.js
  packages/datadog-instrumentations/src/jest.js
  packages/datadog-plugin-cucumber/src/index.js
  packages/datadog-plugin-cypress/src/plugin.js
  packages/datadog-plugin-cypress/test/index.spec.js
  packages/datadog-plugin-jest/src/index.js
  packages/datadog-plugin-mocha/src/index.js
  packages/datadog-plugin-playwright/src/index.js
  packages/dd-trace/src/plugins/ci_plugin.js
  packages/dd-trace/src/plugins/util/test.js
Labels: ci-app, semver-patch

#4045 Fix mongoose iast exec
  packages/datadog-instrumentations/src/mongoose.js
  packages/dd-trace/test/appsec/iast/analyzers/nosql-injection-mongodb-analyzer.mongoose.plugin.spec.js
Labels: semver-patch, asm-iast

#4014 APM uninstrumentation
  packages/dd-trace/src/config.js
  packages/dd-trace/src/proxy.js
  packages/dd-trace/src/span_processor.js
  packages/dd-trace/test/proxy.spec.js
  packages/dd-trace/test/span_processor.spec.js
Labels: semver-minor

#4048 [ci-visibility] Add browser name as test configuration in playwright
  integration-tests/playwright/playwright.spec.js
  packages/datadog-instrumentations/src/playwright.js
  packages/datadog-plugin-playwright/src/index.js
  packages/dd-trace/src/plugins/util/test.js
Labels: ci-app, semver-patch

#4055 [ci-visibility] Fix typo in `log.error`
  packages/dd-trace/src/ci-visibility/early-flake-detection/get-known-tests.js
Labels: ci-app, semver-patch

#4059 Fix child_process test in node <16
  packages/datadog-instrumentations/test/child_process.spec.js
  packages/datadog-plugin-child_process/test/index.spec.js
Labels: semver-patch

#4062 [ci-visibility] Fix ci visibility tests
  integration-tests/ci-visibility-intake.js
  integration-tests/ci-visibility.spec.js
Labels: ci-app, semver-patch

#4061 Reduce dogstatsd flakyness
  packages/dd-trace/test/dogstatsd.spec.js
Labels: semver-patch

#4064 fix node v14 compat for #4041 contribution
  packages/dd-trace/test/datastreams/writer.spec.js
Labels: semver-patch

#4057 APM uninstrumentation: small fix to preserve original behaviour
  packages/dd-trace/src/proxy.js
Labels: semver-patch

#4033 chore(serverless): benchmark on AWS Lambda
  .github/workflows/serverless-performance.yml
  .gitlab/benchmarks.yml
Labels: semver-patch, serverless

#3835 Support graphql resolver arguments as vulnerability source
  packages/dd-trace/src/appsec/iast/taint-tracking/plugin.js
  packages/dd-trace/test/appsec/iast/taint-tracking/plugin.spec.js
  packages/dd-trace/test/appsec/iast/taint-tracking/sources/graphql.sources.test-utils.js
  packages/dd-trace/test/appsec/iast/taint-tracking/sources/plugin.apollo-server-express.plugin.spec.js
  packages/dd-trace/test/appsec/iast/taint-tracking/sources/plugin.apollo-server.plugin.spec.js
  packages/dd-trace/test/plugins/externals.json
Labels: semver-minor, asm-iast

#4067 fixing the eu endpoint for agentless telemetry
  packages/dd-trace/src/telemetry/send-data.js
  packages/dd-trace/test/telemetry/send-data.spec.js
Labels: semver-patch

#4068 Avoid Max call stack size exceeded on vulnerability format
  packages/dd-trace/src/appsec/iast/vulnerabilities-formatter/utils.js
  packages/dd-trace/test/appsec/iast/vulnerability-formatter/utils.spec.js
Labels: bug, semver-patch, asm-iast

#3977 Iast kafka consumer support
  package.json
  packages/datadog-plugin-kafkajs/src/consumer.js
  packages/datadog-plugin-kafkajs/test/index.spec.js
  packages/dd-trace/src/appsec/iast/context/context-plugin.js
  packages/dd-trace/src/appsec/iast/context/kafka-ctx-plugin.js
  packages/dd-trace/src/appsec/iast/iast-plugin.js
  packages/dd-trace/src/appsec/iast/index.js
  packages/dd-trace/src/appsec/iast/overhead-controller.js
  packages/dd-trace/src/appsec/iast/taint-tracking/csi-methods.js
  packages/dd-trace/src/appsec/iast/taint-tracking/index.js
  packages/dd-trace/src/appsec/iast/taint-tracking/operations-taint-object.js
  packages/dd-trace/src/appsec/iast/taint-tracking/operations.js
  packages/dd-trace/src/appsec/iast/taint-tracking/plugin.js
  packages/dd-trace/src/appsec/iast/taint-tracking/plugins/kafka.js
  packages/dd-trace/src/appsec/iast/taint-tracking/source-types.js
  packages/dd-trace/src/appsec/iast/taint-tracking/taint-tracking-impl.js
  packages/dd-trace/test/appsec/iast/analyzers/command-injection-analyzer.kafkajs.plugin.spec.js
  packages/dd-trace/test/appsec/iast/context/context-plugin.spec.js
  packages/dd-trace/test/appsec/iast/context/kafka-ctx-plugin.spec.js
  packages/dd-trace/test/appsec/iast/taint-tracking/plugins/kafka.spec.js
  packages/dd-trace/test/appsec/iast/taint-tracking/resources/propagationFunctions.js
  packages/dd-trace/test/appsec/iast/taint-tracking/taint-tracking-impl.spec.js
  packages/dd-trace/test/appsec/iast/taint-tracking/taint-tracking-operations.spec.js
  packages/dd-trace/test/appsec/iast/utils.js
  yarn.lock
Labels: semver-minor, asm-iast

#4065 add APM_TRACING_ENABLED capability for remote config
  packages/dd-trace/src/appsec/remote_config/capabilities.js
  packages/dd-trace/src/appsec/remote_config/index.js
Labels: semver-minor

#4060 [ci-visibility] Early flake detection for mocha
  integration-tests/ci-visibility.spec.js
  integration-tests/ci-visibility/test-early-flake-detection/mocha-parameterized.js
  integration-tests/ci-visibility/test-early-flake-detection/skipped-and-todo-test.js
  packages/datadog-instrumentations/src/jest.js
  packages/datadog-instrumentations/src/mocha.js
  packages/datadog-plugin-mocha/src/index.js
  packages/dd-trace/src/plugins/ci_plugin.js
  packages/dd-trace/src/plugins/util/test.js
Labels: ci-app, semver-minor

#4072 [ci-visibility] Cypress: do not lose all the trace if `testSuiteSpan` can't be created
  integration-tests/cypress-esm-config.mjs
  integration-tests/cypress.config.js
  integration-tests/cypress/cypress.spec.js
  integration-tests/cypress/plugins-old/index.js
  integration-tests/cypress/support/e2e.js
  packages/datadog-plugin-cypress/src/plugin.js
Labels: ci-app, semver-patch

#4074 [ci-visibility] Improve performance of test source file calculation
  packages/datadog-instrumentations/src/jest.js
  packages/datadog-plugin-jest/src/index.js
Labels: ci-app, semver-patch

#4079 Re-enable telemetry logs
  packages/dd-trace/src/telemetry/index.js
  packages/dd-trace/src/telemetry/logs/index.js
  packages/dd-trace/test/appsec/iast/telemetry/logs.spec.js
Labels: semver-minor, asm-iast

#4080 Fix flaky kafkajs test
  packages/datadog-plugin-kafkajs/test/index.spec.js
Labels: semver-patch

#4082 PROF-9189: Use new intake format for profiles
  integration-tests/profiler/profiler.spec.js
  packages/dd-trace/src/profiling/exporters/agent.js
  packages/dd-trace/test/profiling/exporters/agent.spec.js
Labels: profiling, semver-minor

#4086 Fix tracestate decision maker
  packages/dd-trace/src/opentracing/propagation/text_map.js
  packages/dd-trace/test/opentracing/propagation/text_map.spec.js
Labels: bug, semver-patch

#4076 [ci-visibility] Add early flake detection to cucumber
  CODEOWNERS
  integration-tests/ci-visibility.spec.js
  integration-tests/ci-visibility/features-flaky/flaky.feature
  integration-tests/ci-visibility/features-flaky/support/steps.js
  integration-tests/ci-visibility/features/farewell.feature
  integration-tests/ci-visibility/features/support/steps.js
  integration-tests/cucumber/cucumber.spec.js
  packages/datadog-instrumentations/src/cucumber.js
  packages/datadog-plugin-cucumber/src/index.js
Labels: ci-app, semver-minor

#4083 [ci-visibility] Fix `cypress open` error when passing `experimentalInteractiveRunEvents`
  integration-tests/cypress/cypress.spec.js
  packages/datadog-plugin-cypress/src/plugin.js
Labels: ci-app, semver-patch

#4088 [ci-visibility] Fix ITR when jest is using a custom test sequencer
  integration-tests/ci-visibility.spec.js
  integration-tests/ci-visibility/jest-custom-test-sequencer.js
  integration-tests/ci-visibility/run-jest.js
  packages/datadog-instrumentations/src/jest.js
Labels: ci-app, semver-patch

#4096 fix: typeerror due to missing header properties for amqplib when dsm is enabled
  packages/datadog-plugin-amqplib/src/consumer.js
  packages/datadog-plugin-rhea/src/consumer.js
Labels: semver-patch

#4087 feat(aws-sdk): create DSM checkpoint for each message in batch sends
  packages/datadog-plugin-amqplib/src/consumer.js
  packages/datadog-plugin-aws-sdk/src/services/kinesis.js
  packages/datadog-plugin-aws-sdk/src/services/sns.js
  packages/datadog-plugin-aws-sdk/src/services/sqs.js
  packages/datadog-plugin-aws-sdk/test/kinesis.spec.js
  packages/datadog-plugin-aws-sdk/test/kinesis_helpers.js
  packages/datadog-plugin-aws-sdk/test/sns.spec.js
  packages/datadog-plugin-aws-sdk/test/sqs.spec.js
Labels: semver-minor

#4090 [ci-visibility] Allow using `after:run` directly
  ci/cypress/after-run.js
  integration-tests/cypress.config.js
  integration-tests/cypress/cypress.spec.js
  packages/datadog-plugin-cypress/src/after-run.js
  packages/datadog-plugin-cypress/src/cypress-plugin.js
  packages/datadog-plugin-cypress/src/plugin.js
Labels: ci-app, semver-minor

#4101 aws-sdk: fix request_id tag for errors
  packages/datadog-plugin-aws-sdk/src/base.js
  packages/datadog-plugin-aws-sdk/test/aws-sdk.spec.js
Labels: bug, semver-patch, integration-aws-sdk

#4070 Update types
  docs/package.json
  docs/typedoc.js
  docs/yarn.lock
  index.d.ts
Labels: semver-patch

#4111 Fix issue with graphql.execute span naming
  packages/dd-trace/src/format.js
  packages/dd-trace/test/format.spec.js
Labels: bug, semver-patch

#3928 Active tracing configuration
  packages/datadog-core/src/utils/src/get.js
  packages/datadog-core/src/utils/src/has.js
  packages/datadog-core/src/utils/src/kebabcase.js
  packages/datadog-core/src/utils/src/pick.js
  packages/datadog-core/src/utils/src/set.js
  packages/datadog-core/src/utils/src/uniq.js
  packages/datadog-core/test/utils/src/get.spec.js
  packages/datadog-core/test/utils/src/has.spec.js
  packages/datadog-core/test/utils/src/set.spec.js
  packages/datadog-instrumentations/src/amqplib.js
  packages/datadog-plugin-graphql/src/index.js
  packages/datadog-plugin-grpc/src/util.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/opentracing/propagation/text_map.js
  packages/dd-trace/src/plugins/util/web.js
  packages/dd-trace/src/telemetry/index.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/telemetry/index.spec.js
Labels: semver-minor

#4110 Add register.js for use with --import flag
  .npmignore
  README.md
  integration-tests/startup.spec.js
  register.js
Labels: semver-minor

#4115 ci: remove nightly package failure slack reporter
  .github/workflows/plugins.yml
  packages/dd-trace/test/setup/mocha.js
  packages/dd-trace/test/setup/slack-report.js
Labels: semver-patch

#4117 Update appsec rules to 1.11.0
  packages/dd-trace/src/appsec/recommended.json
Labels: asm-waf, semver-minor

#4116 Fix "directives is not iterable" error when directives is not defined in the document
  packages/datadog-plugin-graphql/src/resolve.js
  packages/datadog-plugin-graphql/test/index.spec.js
Labels: bug, semver-patch

#4113 [ci-visibility] Fix negative duration in playwright steps
  integration-tests/ci-visibility/playwright-tests-error/before-all-timeout-test.js
  integration-tests/playwright.config.js
  integration-tests/playwright/playwright.spec.js
  packages/datadog-instrumentations/src/playwright.js
  packages/datadog-plugin-playwright/src/index.js
Labels: ci-app, semver-patch

#4108 Fix flaky kafkajs test
  packages/datadog-plugin-kafkajs/test/index.spec.js
Labels: semver-patch
