Repository DataDog/dd-trace-js, pull requests merged in 2024-11, with the labels that each got.

#4850 add some clarity in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: semver-patch

#4852 add `yarn env <plugin-name>`
  package.json
  plugin-env
Labels: semver-patch

#4839 Fix amqp instrumentation
  packages/datadog-instrumentations/src/amqplib.js
  packages/datadog-plugin-amqplib/src/consumer.js
  packages/datadog-plugin-amqplib/test/index.spec.js
Labels: semver-minor, mergequeue-status: waiting

#4792 Exploit prevention Shell injection
  packages/datadog-instrumentations/src/child_process.js
  packages/datadog-instrumentations/test/child_process.spec.js
  packages/dd-trace/src/appsec/addresses.js
  packages/dd-trace/src/appsec/channels.js
  packages/dd-trace/src/appsec/rasp/command_injection.js
  packages/dd-trace/src/appsec/rasp/index.js
  packages/dd-trace/src/appsec/rasp/utils.js
  packages/dd-trace/src/appsec/remote_config/capabilities.js
  packages/dd-trace/src/appsec/remote_config/index.js
  packages/dd-trace/test/appsec/rasp/command_injection.express.plugin.spec.js
  packages/dd-trace/test/appsec/rasp/command_injection.integration.spec.js
  packages/dd-trace/test/appsec/rasp/command_injection.spec.js
  packages/dd-trace/test/appsec/rasp/resources/rasp_rules.json
  packages/dd-trace/test/appsec/rasp/resources/shi-app/index.js
  packages/dd-trace/test/appsec/remote_config/index.spec.js
Labels: semver-minor

#4563 Baggage support
  packages/datadog-plugin-aws-sdk/test/eventbridge.spec.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/noop/span.js
  packages/dd-trace/src/opentracing/propagation/text_map.js
  packages/dd-trace/src/opentracing/span.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/opentracing/propagation/text_map.spec.js
  packages/dd-trace/test/opentracing/span.spec.js
Labels: semver-minor

#4854 fix incompatibilities with node 16 for 4.49.0 release
  docs/package.json
  docs/tsconfig.json
  integration-tests/appsec/multer.spec.js
Labels: semver-patch

#4855 Onboarding tests: simple installer scenario
  .gitlab-ci.yml
Labels: semver-patch

#4836 Support url.parse, url.URL.parse and new url.URL for IAST taint tracking
  .github/workflows/plugins.yml
  packages/datadog-instrumentations/src/helpers/hooks.js
  packages/datadog-instrumentations/src/url.js
  packages/datadog-instrumentations/test/url.spec.js
  packages/dd-trace/src/appsec/iast/taint-tracking/plugin.js
  packages/dd-trace/test/appsec/iast/taint-tracking/plugin.express.plugin.spec.js
  packages/dd-trace/test/appsec/iast/taint-tracking/plugin.spec.js
Labels: semver-minor, asm-iast

#4826 [test visibility] Simple dynamic instrumentation - test visibility client
  packages/dd-trace/src/ci-visibility/dynamic-instrumentation/index.js
  packages/dd-trace/src/ci-visibility/dynamic-instrumentation/worker/index.js
  packages/dd-trace/src/debugger/devtools_client/index.js
  packages/dd-trace/src/debugger/devtools_client/state.js
  packages/dd-trace/test/ci-visibility/dynamic-instrumentation/dynamic-instrumentation.spec.js
  packages/dd-trace/test/ci-visibility/dynamic-instrumentation/target-app/di-dependency.js
  packages/dd-trace/test/ci-visibility/dynamic-instrumentation/target-app/test-visibility-dynamic-instrumentation-script.js
Labels: ci-app, semver-minor

#4859 update AWS payload extraction rules
  packages/datadog-plugin-aws-sdk/src/services/eventbridge.js
  packages/datadog-plugin-aws-sdk/src/services/kinesis.js
  packages/datadog-plugin-aws-sdk/src/services/s3.js
  packages/datadog-plugin-aws-sdk/src/services/sqs.js
  packages/dd-trace/src/payload-tagging/config/aws.json
Labels: semver-patch

#4867 Revert "always enable tracing header injection for AWS requests (#4717)"
  docs/test.ts
  index.d.ts
  packages/datadog-plugin-aws-sdk/test/aws-sdk.spec.js
  packages/datadog-plugin-fetch/test/index.spec.js
  packages/datadog-plugin-http/src/client.js
  packages/datadog-plugin-http/test/client.spec.js
  packages/datadog-plugin-http2/src/client.js
  packages/datadog-plugin-http2/test/client.spec.js
Labels: semver-patch, integration-aws-sdk

#4871 [ASM] Fix `checkNoVulnerabilityInRequest` for IAST tests
  packages/dd-trace/test/appsec/iast/utils.js
Labels: semver-patch, asm-iast, appsec

#4841 Add exclusions for header injection vulnerability
  packages/dd-trace/src/appsec/iast/analyzers/header-injection-analyzer.js
  packages/dd-trace/test/appsec/iast/analyzers/header-injection.express.plugin.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/resources/set-header-function.js
Labels: semver-minor, asm-iast, appsec

#4853 add release proposal script for use locally
  .gitignore
  scripts/release/proposal.js
Labels: semver-patch

#4857 Have one version tag in metrics
  packages/dd-trace/src/telemetry/metrics.js
Labels: semver-patch

#4872 Prevent errors in Express 5.x applications
  packages/datadog-instrumentations/src/router.js
Labels: semver-minor

#4837 feat(tracing): AWS API Gateway Inferred Span Support
  packages/dd-trace/src/config.js
  packages/dd-trace/src/plugins/util/inferred_proxy.js
  packages/dd-trace/src/plugins/util/web.js
  packages/dd-trace/test/plugins/util/inferred_proxy.spec.js
Labels: semver-minor

#4878 add guardrail to completely bail out in very old versions
  .github/workflows/project.yml
  init.js
  version.js
Labels: semver-patch

#4879 add more node version tests to unsupported guardrails matrix
  .github/workflows/project.yml
Labels: semver-patch

#4866 skip warning if propagator is baggage
  packages/dd-trace/src/opentracing/propagation/text_map.js
Labels: semver-patch

#4885 chore(llmobs): tracer version tagging
  packages/dd-trace/src/llmobs/sdk.js
  packages/dd-trace/src/llmobs/span_processor.js
  packages/dd-trace/src/llmobs/writers/spans/base.js
  packages/dd-trace/test/llmobs/sdk/index.spec.js
  packages/dd-trace/test/llmobs/sdk/integration.spec.js
  packages/dd-trace/test/llmobs/span_processor.spec.js
  packages/dd-trace/test/llmobs/util.js
Labels: semver-patch

#4775 add namespace support for async storage
  packages/datadog-core/index.js
  packages/datadog-core/src/storage.js
  packages/datadog-core/test/storage.spec.js
Labels: semver-patch

#4882 Remove `x-forwarded` from ipHeaderList
  packages/dd-trace/src/appsec/reporter.js
  packages/dd-trace/src/plugins/util/ip_extractor.js
  packages/dd-trace/test/plugins/util/ip_extractor.spec.js
Labels: semver-patch, appsec

#4863 [test optimization] Fix active span being null in cypress
  packages/datadog-plugin-cypress/src/cypress-plugin.js
Labels: semver-patch

#4827 Template injection vulnerability detection in handlebars and pug
  .github/workflows/appsec.yml
  packages/datadog-instrumentations/src/handlebars.js
  packages/datadog-instrumentations/src/helpers/hooks.js
  packages/datadog-instrumentations/src/pug.js
  packages/dd-trace/src/appsec/iast/analyzers/analyzers.js
  packages/dd-trace/src/appsec/iast/analyzers/template-injection-analyzer.js
  packages/dd-trace/src/appsec/iast/vulnerabilities-formatter/evidence-redaction/sensitive-analyzers/tainted-range-based-sensitive-analyzer.js
  packages/dd-trace/src/appsec/iast/vulnerabilities-formatter/evidence-redaction/sensitive-handler.js
  packages/dd-trace/src/appsec/iast/vulnerabilities.js
  packages/dd-trace/test/appsec/iast/analyzers/template-injection-analyzer.handlebars.plugin.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/template-injection-analyzer.pug.plugin.spec.js
  packages/dd-trace/test/appsec/iast/vulnerability-formatter/index.spec.js
  packages/dd-trace/test/appsec/iast/vulnerability-formatter/resources/evidence-redaction-suite.json
Labels: semver-minor, asm-iast, appsec

#4892 Ignore elasticsearch 8.16.0 from esm tests
  packages/datadog-plugin-elasticsearch/test/integration-test/client.spec.js
Labels: semver-patch

#4880 update release script to also create pr
  .gitignore
  package.json
  scripts/release/helpers/requirements.js
  scripts/release/helpers/terminal.js
  scripts/release/proposal.js
Labels: semver-patch

#4851 [DSM] Set checkpoints for DSM even when there is no context if the service is instrumented and fix typo
  packages/datadog-plugin-aws-sdk/src/services/kinesis.js
  packages/datadog-plugin-aws-sdk/src/services/sqs.js
  packages/datadog-plugin-aws-sdk/test/kinesis.spec.js
  packages/datadog-plugin-aws-sdk/test/sqs.spec.js
  packages/dd-trace/test/plugins/agent.js
Labels: semver-patch, mergequeue-status: removed

#4891 Update WAF rules and bindings
  package.json
  packages/dd-trace/src/appsec/recommended.json
  yarn.lock
Labels: asm-waf, semver-minor, appsec

#4883 Adding new ST scenarios for rasp
  .github/workflows/system-tests.yml
Labels: semver-patch, asm-waf

#4755 add support to api security sampling
  LICENSE-3rdparty.csv
  docs/test.ts
  index.d.ts
  integration-tests/standalone-asm.spec.js
  package.json
  packages/datadog-instrumentations/src/express.js
  packages/dd-trace/src/appsec/api_security_sampler.js
  packages/dd-trace/src/appsec/index.js
  packages/dd-trace/src/appsec/remote_config/capabilities.js
  packages/dd-trace/src/appsec/remote_config/index.js
  packages/dd-trace/src/config.js
  packages/dd-trace/test/appsec/api_security_sampler.spec.js
  packages/dd-trace/test/appsec/index.express.plugin.spec.js
  packages/dd-trace/test/appsec/index.sequelize.plugin.spec.js
  packages/dd-trace/test/appsec/index.spec.js
  packages/dd-trace/test/appsec/remote_config/index.spec.js
  packages/dd-trace/test/appsec/response_blocking.spec.js
  packages/dd-trace/test/config.spec.js
  yarn.lock
Labels: semver-minor, appsec

#4899 Upgrade `cross-spawn` to `v7.0.5` - patched ReDoS
  yarn.lock
Labels: semver-patch, dependencies

#4874 Adding Span Link support for distributed tracing header extractions with invalid traces
  packages/datadog-plugin-amqplib/src/consumer.js
  packages/datadog-plugin-aws-sdk/src/services/kinesis.js
  packages/datadog-plugin-aws-sdk/src/services/sqs.js
  packages/datadog-plugin-child_process/test/index.spec.js
  packages/datadog-plugin-google-cloud-pubsub/src/consumer.js
  packages/datadog-plugin-grpc/src/server.js
  packages/datadog-plugin-jest/src/index.js
  packages/datadog-plugin-kafkajs/src/consumer.js
  packages/datadog-plugin-moleculer/src/server.js
  packages/datadog-plugin-rhea/src/consumer.js
  packages/datadog-plugin-vitest/src/index.js
  packages/dd-trace/src/opentracing/propagation/text_map.js
  packages/dd-trace/src/opentracing/span_context.js
  packages/dd-trace/src/plugins/tracing.js
  packages/dd-trace/src/plugins/util/web.js
  packages/dd-trace/test/opentracing/propagation/text_map.spec.js
  packages/dd-trace/test/opentracing/span_context.spec.js
Labels: semver-minor

#4893 automate release notes from github actions
  .github/workflows/release-4.yml
  .github/workflows/release-latest.yml
  scripts/release/notes.js
Labels: semver-patch

#4897 improve output for release proposal script
  scripts/release/helpers/requirements.js
  scripts/release/helpers/terminal.js
  scripts/release/proposal.js
Labels: semver-patch

#4875 [serverless] Add S3 Span Pointers
  packages/datadog-plugin-aws-sdk/src/base.js
  packages/datadog-plugin-aws-sdk/src/services/s3.js
  packages/datadog-plugin-aws-sdk/test/s3.spec.js
  packages/dd-trace/src/constants.js
  packages/dd-trace/src/noop/span.js
  packages/dd-trace/src/opentelemetry/span.js
  packages/dd-trace/src/opentracing/span.js
  packages/dd-trace/src/util.js
  packages/dd-trace/test/opentelemetry/span.spec.js
  packages/dd-trace/test/opentracing/span.spec.js
  packages/dd-trace/test/util.spec.js
Labels: semver-minor, mergequeue-status: waiting

#4905 disable merge queue
  repository.datadog.yml
Labels: semver-patch

#4856 log template messages and errors
  packages/dd-trace/src/log/index.js
  packages/dd-trace/src/log/log.js
  packages/dd-trace/src/log/writer.js
  packages/dd-trace/src/telemetry/logs/index.js
  packages/dd-trace/src/telemetry/logs/log-collector.js
  packages/dd-trace/test/log.spec.js
  packages/dd-trace/test/telemetry/logs/index.spec.js
  packages/dd-trace/test/telemetry/logs/log-collector.spec.js
Labels: semver-minor

#4903 [test optimization] Report code coverage relative to the repository root, not the project's root dir or working directory
  integration-tests/ci-visibility/subproject/dependency.js
  integration-tests/ci-visibility/subproject/subproject-test.js
  integration-tests/cucumber/cucumber.spec.js
  integration-tests/cypress/cypress.spec.js
  integration-tests/jest/jest.spec.js
  integration-tests/mocha/mocha.spec.js
  packages/datadog-instrumentations/src/jest.js
  packages/datadog-plugin-cypress/src/cypress-plugin.js
  packages/datadog-plugin-cypress/src/support.js
  packages/datadog-plugin-mocha/src/index.js
Labels: ci-app, semver-patch

#4907 Increase timeout on RASP integration test for windows
  packages/dd-trace/test/appsec/rasp/command_injection.integration.spec.js
Labels: semver-patch, appsec

#4908 fix release script hanging on applying new changes
  scripts/release/helpers/terminal.js
  scripts/release/proposal.js
Labels: semver-patch

#4910 fix release notes always flagged as latest
  scripts/release/notes.js
Labels: semver-patch

#4832 Add profiler API telemetry metrics
  integration-tests/profiler/index.js
  integration-tests/profiler/profiler.spec.js
  packages/dd-trace/src/profiling/exporters/agent.js
  packages/dd-trace/src/profiling/profiler.js
  packages/dd-trace/test/profiling/exporters/agent.spec.js
  packages/dd-trace/test/profiling/profiler.spec.js
Labels: profiling, semver-minor

#4917 fix crashtracker not working with uds
  packages/dd-trace/src/crashtracking/crashtracker.js
  packages/dd-trace/test/crashtracking/crashtracker.spec.js
Labels: semver-patch

#4881 [ASM] Discard inferred spans when resolving the root span of a trace
  packages/dd-trace/src/appsec/sdk/utils.js
  packages/dd-trace/test/appsec/sdk/utils.spec.js
Labels: semver-patch, appsec

#4916 next.js: complete v14.x compatibility (fixing >=14.2.7)
  .github/workflows/appsec.yml
  .github/workflows/plugins.yml
  packages/datadog-instrumentations/src/next.js
Labels: semver-patch, integration-nextjs

#4920 update crashtracker timeout to 5 seconds
  packages/dd-trace/src/crashtracking/crashtracker.js
Labels: semver-patch

#4921 add package manager symlinks to denylist
  .gitlab/requirements_block.json
  requirements.json
Labels: semver-patch

#4922 fix missing commands in denylist by allowing all
  requirements.json
Labels: semver-patch

#4926 fix langchain tests trying to run on unsupported node
  .github/workflows/plugins.yml
Labels: semver-patch

#4928 next.js: support v15.x
  .github/workflows/appsec.yml
  .github/workflows/plugins.yml
  packages/datadog-instrumentations/src/next.js
Labels: semver-minor, integration-nextjs

#4919 Remove iast-log and review ASM log messages
  packages/dd-trace/src/appsec/api_security_sampler.js
  packages/dd-trace/src/appsec/blocking.js
  packages/dd-trace/src/appsec/iast/analyzers/cookie-analyzer.js
  packages/dd-trace/src/appsec/iast/iast-log.js
  packages/dd-trace/src/appsec/iast/iast-plugin.js
  packages/dd-trace/src/appsec/iast/taint-tracking/operations-taint-object.js
  packages/dd-trace/src/appsec/iast/taint-tracking/rewriter.js
  packages/dd-trace/src/appsec/iast/taint-tracking/taint-tracking-impl.js
  packages/dd-trace/src/appsec/iast/telemetry/namespaces.js
  packages/dd-trace/src/appsec/iast/vulnerabilities-formatter/evidence-redaction/sensitive-analyzers/command-sensitive-analyzer.js
  packages/dd-trace/src/appsec/iast/vulnerabilities-formatter/evidence-redaction/sensitive-analyzers/ldap-sensitive-analyzer.js
  packages/dd-trace/src/appsec/iast/vulnerabilities-formatter/evidence-redaction/sensitive-analyzers/sql-sensitive-analyzer.js
  packages/dd-trace/src/appsec/iast/vulnerabilities-formatter/evidence-redaction/sensitive-analyzers/url-sensitive-analyzer.js
  packages/dd-trace/src/appsec/iast/vulnerabilities-formatter/evidence-redaction/sensitive-handler.js
  packages/dd-trace/src/appsec/index.js
  packages/dd-trace/src/appsec/passport.js
  packages/dd-trace/src/appsec/rasp/fs-plugin.js
  packages/dd-trace/src/appsec/rasp/utils.js
  packages/dd-trace/src/appsec/remote_config/manager.js
  packages/dd-trace/src/appsec/sdk/set_user.js
  packages/dd-trace/src/appsec/sdk/track_event.js
  packages/dd-trace/src/appsec/sdk/user_blocking.js
  packages/dd-trace/src/appsec/waf/index.js
  packages/dd-trace/src/appsec/waf/waf_context_wrapper.js
  packages/dd-trace/src/appsec/waf/waf_manager.js
  packages/dd-trace/test/appsec/blocking.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/sql-injection-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/iast-log.spec.js
  packages/dd-trace/test/appsec/iast/iast-plugin.spec.js
  packages/dd-trace/test/appsec/iast/taint-tracking/taint-tracking-operations.spec.js
  packages/dd-trace/test/appsec/iast/vulnerability-formatter/evidence-redaction/sensitive-handler.spec.js
  packages/dd-trace/test/appsec/index.spec.js
  packages/dd-trace/test/appsec/passport.spec.js
  packages/dd-trace/test/appsec/remote_config/manager.spec.js
  packages/dd-trace/test/appsec/sdk/set_user.spec.js
  packages/dd-trace/test/appsec/sdk/track_event.spec.js
  packages/dd-trace/test/appsec/sdk/user_blocking.spec.js
  packages/dd-trace/test/appsec/waf/waf_context_wrapper.spec.js
Labels: semver-minor, appsec

#4931 Revert log change to avoid a conflict
  packages/dd-trace/src/appsec/passport.js
  packages/dd-trace/test/appsec/passport.spec.js
Labels: semver-patch, asm-waf

#4933 fix(langchain): do not throw when result is undefined
  packages/datadog-plugin-langchain/src/handlers/language_models/chat_model.js
  packages/datadog-plugin-langchain/src/handlers/language_models/llm.js
  packages/datadog-plugin-langchain/test/index.spec.js
Labels: semver-patch

#4914 Update Azure Functions operation name to azure.functions.invoke
  packages/datadog-instrumentations/src/azure-functions.js
  packages/datadog-plugin-azure-functions/src/index.js
  packages/datadog-plugin-azure-functions/test/integration-test/client.spec.js
  packages/dd-trace/src/service-naming/schemas/v0/serverless.js
  packages/dd-trace/src/service-naming/schemas/v1/serverless.js
Labels: semver-minor, serverless

#4934 make SSI not crash on node 12.0.0, 18.0.0, et.c
  .github/workflows/project.yml
  init.js
  initialize.mjs
  integration-tests/init.spec.js
Labels: semver-patch

#4943 fix oracledb ci job using a node version incompatible with container
  .github/workflows/plugins.yml
Labels: semver-patch

#4942 fix race condition in initialization file on latest node
  initialize.mjs
Labels: semver-patch

#4935 fix baggage extraction
  packages/dd-trace/src/opentracing/propagation/text_map.js
  packages/dd-trace/test/opentracing/propagation/text_map.spec.js
Labels: semver-patch

#4927 Fix IAST standalone sampling priority propagation
  packages/dd-trace/src/appsec/iast/vulnerability-reporter.js
  packages/dd-trace/test/appsec/iast/overhead-controller.spec.js
  packages/dd-trace/test/appsec/iast/vulnerability-reporter.spec.js
Labels: semver-patch, asm-iast, appsec

#4876 [test optimization] Add Dynamic Instrumentation to jest retries
  LICENSE-3rdparty.csv
  integration-tests/ci-visibility/dynamic-instrumentation/dependency.js
  integration-tests/ci-visibility/dynamic-instrumentation/test-hit-breakpoint.js
  integration-tests/ci-visibility/dynamic-instrumentation/test-not-hit-breakpoint.js
  integration-tests/jest/jest.spec.js
  package.json
  packages/datadog-instrumentations/src/jest.js
  packages/datadog-plugin-jest/src/index.js
  packages/dd-trace/src/ci-visibility/dynamic-instrumentation/index.js
  packages/dd-trace/src/ci-visibility/dynamic-instrumentation/worker/index.js
  packages/dd-trace/src/ci-visibility/exporters/ci-visibility-exporter.js
  packages/dd-trace/src/debugger/devtools_client/state.js
  packages/dd-trace/src/plugin_manager.js
  packages/dd-trace/src/plugins/ci_plugin.js
  packages/dd-trace/src/plugins/util/test.js
  packages/dd-trace/src/proxy.js
  yarn.lock
Labels: ci-app, semver-minor

#4948 add runtime version to crash report metadata
  packages/dd-trace/src/crashtracking/crashtracker.js
Labels: semver-patch

#4949 update guardrails to report telemetry in old node versions
  .github/workflows/project.yml
  init.js
  integration-tests/init.spec.js
  packages/datadog-instrumentations/src/helpers/register.js
  packages/dd-trace/src/guardrails/index.js
  packages/dd-trace/src/guardrails/log.js
  packages/dd-trace/src/guardrails/telemetry.js
  packages/dd-trace/src/guardrails/util.js
  packages/dd-trace/src/telemetry/init-telemetry.js
Labels: semver-patch

#4946 [test optimization] Do not init on package managers
  ci/init.js
  integration-tests/test-api-manual.spec.js
  integration-tests/test-optimization-startup.spec.js
Labels: ci-app, semver-minor

#4955 Fix original url instanceOf url.URL
  packages/datadog-instrumentations/src/url.js
  packages/datadog-instrumentations/test/url.spec.js
Labels: semver-patch, asm-iast

#4953 use weakmap to avoid references from node to datadog stores
  packages/datadog-core/src/storage.js
  packages/datadog-core/test/storage.spec.js
  packages/dd-trace/src/llmobs/storage.js
  packages/dd-trace/src/opentelemetry/context_manager.js
  packages/dd-trace/src/profiling/profilers/event_plugins/event.js
Labels: semver-patch
