Repository DataDog/dd-trace-js, pull requests merged in 2024-01, with the labels that each got.

#2002 Adding Pino Integration-test
  integration-tests/pino.spec.js
  integration-tests/pino/index.js
Labels: semver-patch, integration-pino

#3911 [profiling] Add `process_id` tag to profiles
  packages/dd-trace/src/profiling/exporters/agent.js
  packages/dd-trace/test/profiling/exporters/agent.spec.js
Labels: feature-request, profiling, semver-minor

#3922 Parametric tests: Remove obsolete code
  .github/workflows/system-tests.yml
Labels: dev/testing, ci-app, semver-patch

#3923 [ci-visibility] Fix slowness in `test-environment.spec.js`
  packages/dd-trace/test/plugins/util/test-environment.spec.js
Labels: ci-app, semver-patch

#3912 Fix ts errors
  docs/test.ts
  index.d.ts
Labels: bug, semver-major

#3904 Implement extended sampling
  packages/dd-trace/src/priority_sampler.js
  packages/dd-trace/src/sampling_rule.js
  packages/dd-trace/src/span_sampler.js
  packages/dd-trace/test/priority_sampler.spec.js
  packages/dd-trace/test/sampling_rule.spec.js
  packages/dd-trace/test/span_sampler.spec.js
Labels: semver-minor

#3905 drop support for node 16 in preparation for v5 release
  .github/actions/node/oldest/action.yml
  .github/actions/node/setup/action.yml
  .github/workflows/appsec.yml
  .github/workflows/lambda.yml
  .github/workflows/package-size.yml
  .github/workflows/plugins.yml
  .github/workflows/profiling.yml
  .github/workflows/project.yml
  .github/workflows/serverless-integration-test.yml
  .github/workflows/serverless-performance.yml
  .github/workflows/tracing.yml
  .gitlab/benchmarks.yml
  .nvmrc
  README.md
  benchmark/sirun/Dockerfile
  docs/package.json
  docs/yarn.lock
  integration-tests/esbuild/build-and-test-aws-sdk.js
  integration-tests/esbuild/build-and-test-skip-external.js
  integration-tests/esbuild/build.js
  lib-injection/Dockerfile
  package.json
  packages/datadog-plugin-aws-sdk/test/lambda.spec.js
  yarn.lock
Labels: semver-major, dont-land-on-v3.x, dont-land-on-v4.x

#3927 PROF-8850: Add diagnostic to flaky test
  integration-tests/profiler.spec.js
Labels: semver-patch

#3926 Fix couchbase segfault. On >=3.2.0 <3.2.2 it would segfault on cluster.close()
  packages/datadog-instrumentations/src/couchbase.js
Labels: bug, semver-patch, integration-couchbase

#3929 bump up iitm version
  package.json
Labels: semver-patch

#3940 PROF-8714: GA Code hotspots and endpoint collection by defaulting them to true
  packages/dd-trace/src/profiling/config.js
  packages/dd-trace/test/profiling/config.spec.js
Labels: profiling, semver-minor

#3938 Pin `limiter` version to 1.1.5
  package.json
  yarn.lock
Labels: semver-patch, dependencies

#3942 Fix hapi tests
  packages/datadog-plugin-hapi/test/index.spec.js
Labels: semver-patch

#3944 PROF-8714: Code hotspots and endpoint collection shouldn't be enabled on Windows
  packages/dd-trace/src/profiling/config.js
  packages/dd-trace/test/profiling/config.spec.js
Labels: profiling, semver-minor

#3943 Fix aws-sdk tests by making withNamingSchema handle multiple failures properly
  packages/dd-trace/test/setup/mocha.js
Labels: semver-patch

#2716 Handle google-cloud-pubsub subscription closing
  packages/datadog-plugin-google-cloud-pubsub/src/consumer.js
  packages/datadog-plugin-google-cloud-pubsub/test/index.spec.js
Labels: bug, semver-patch

#3934 [ci-visibility] Agentless telemetry for CI Visibility
  packages/dd-trace/src/config.js
  packages/dd-trace/src/telemetry/send-data.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/telemetry/send-data.spec.js
Labels: ci-app, semver-minor

#3935 Update Next.js tests to work with Node 18
  .github/workflows/appsec.yml
  .github/workflows/plugins.yml
  packages/datadog-plugin-next/test/index.spec.js
  packages/datadog-plugin-next/test/integration-test/client.spec.js
  packages/dd-trace/test/appsec/index.next.plugin.spec.js
Labels: semver-patch

#3953 [ci-visibility] Fix logic to add unskippable and forced to run tags in `jest`
  integration-tests/ci-visibility.spec.js
  integration-tests/ci-visibility/unskippable-test/test-to-run.js
  packages/datadog-instrumentations/src/jest.js
  packages/datadog-plugin-jest/src/index.js
  packages/datadog-plugin-jest/src/util.js
  packages/datadog-plugin-jest/test/util.spec.js
Labels: ci-app, semver-patch

#3919 v6.0.0-pre
  package.json
Labels: semver-patch, dont-land-on-v2.x, dont-land-on-v3.x, dont-land-on-v4.x, dont-land-on-v5.x

#3952 fix empty strings being kept as valid values in config
  packages/dd-trace/src/config.js
  packages/dd-trace/test/config.spec.js
Labels: semver-patch

#3958 fix readme for v5 preview
  README.md
Labels: semver-patch

#3959 fix: Do not reuse `requestOptions` object
  packages/dd-trace/src/appsec/remote_config/manager.js
  packages/dd-trace/test/appsec/remote_config/manager.spec.js
Labels: semver-patch

#3955 PROF-8850: Fix flaky code hotspots test
  integration-tests/profiler.spec.js
  integration-tests/profiler/codehotspots.js
Labels: profiling, semver-patch

#3961 add convenience script to run the system-tests
  scripts/st.js
Labels: dev/testing, dev/tooling, semver-patch

#3963 PROF-8872: Better handling of multiple errors thrown in FakeAgent
  integration-tests/helpers.js
Labels: dev/testing, semver-patch

#3962 Ignore header vulnerabilities in cors headers
  packages/dd-trace/src/appsec/iast/analyzers/header-injection-analyzer.js
  packages/dd-trace/test/appsec/iast/analyzers/header-injection.express.plugin.spec.js
Labels: semver-patch, asm-iast

#3964 [ci-visibility] Fix telemetry in ci visibility
  packages/datadog-plugin-cucumber/src/index.js
  packages/datadog-plugin-cypress/src/plugin.js
  packages/datadog-plugin-playwright/src/index.js
  packages/dd-trace/src/telemetry/index.js
  packages/dd-trace/src/telemetry/send-data.js
  packages/dd-trace/test/telemetry/send-data.spec.js
Labels: ci-app, semver-patch

#3971 fix failing aerospike tests, and update CI job names to be more specific
  .github/workflows/plugins.yml
Labels: semver-patch

#3970 fix failing Nextjs tests on Node versions < 18
  packages/datadog-plugin-next/test/index.spec.js
  packages/datadog-plugin-next/test/integration-test/client.spec.js
  packages/dd-trace/test/appsec/index.next.plugin.spec.js
Labels: semver-patch

#3969 PROF-8935: Remove timelines experimental flag, disable timelines and CPU profiler on Windows
  packages/dd-trace/src/profiling/config.js
  packages/dd-trace/test/profiling/config.spec.js
Labels: semver-minor

#3973 Update @datadog/native-appsec to v7.0.0
  package.json
  yarn.lock
Labels: semver-patch, asm-waf

#3974 [profiling] Disable oom monitoring on windows
  integration-tests/profiler/profiler.spec.js
  packages/dd-trace/src/profiling/config.js
  packages/dd-trace/test/profiling/config.spec.js
Labels: bug, profiling, semver-minor

#3960 Add support for weak randomness vulnerability
  packages/dd-trace/src/appsec/iast/analyzers/analyzers.js
  packages/dd-trace/src/appsec/iast/analyzers/weak-randomness-analyzer.js
  packages/dd-trace/src/appsec/iast/taint-tracking/csi-methods.js
  packages/dd-trace/src/appsec/iast/taint-tracking/taint-tracking-impl.js
  packages/dd-trace/src/appsec/iast/vulnerabilities.js
  packages/dd-trace/test/appsec/iast/analyzers/resources/random-functions.js
  packages/dd-trace/test/appsec/iast/analyzers/weak-randomness-analyzer.spec.js
Labels: semver-minor, asm-iast

#3975 update import-in-the-middle to 1.7.3
  package.json
  yarn.lock
Labels: semver-patch

#3979 [profiling] Fix bad copy/paste
  packages/dd-trace/src/profiling/config.js
Labels: bug, profiling, semver-patch

#3984 Collect the X-Amzn-Trace-Id header
  packages/dd-trace/src/appsec/reporter.js
  packages/dd-trace/test/appsec/reporter.spec.js
Labels: asm-waf, semver-minor, appsec

#3980 [ci-visibility] Add correlation ID to ITR requests
  integration-tests/ci-visibility-intake.js
  integration-tests/ci-visibility.spec.js
  integration-tests/cucumber/cucumber.spec.js
  integration-tests/cypress/cypress.spec.js
  packages/datadog-instrumentations/src/cucumber.js
  packages/datadog-instrumentations/src/jest.js
  packages/datadog-instrumentations/src/mocha.js
  packages/datadog-plugin-cucumber/src/index.js
  packages/datadog-plugin-cypress/src/plugin.js
  packages/datadog-plugin-jest/src/index.js
  packages/datadog-plugin-mocha/src/index.js
  packages/dd-trace/src/ci-visibility/intelligent-test-runner/get-skippable-suites.js
  packages/dd-trace/src/encode/agentless-ci-visibility.js
  packages/dd-trace/src/plugins/ci_plugin.js
  packages/dd-trace/src/plugins/util/test.js
  packages/dd-trace/test/ci-visibility/exporters/ci-visibility-exporter.spec.js
Labels: ci-app, semver-minor

#3864 feat: add DSM for AWS SQS/SNS/Kinesis
  .github/workflows/plugins.yml
  packages/datadog-plugin-aws-sdk/src/services/kinesis.js
  packages/datadog-plugin-aws-sdk/src/services/sns.js
  packages/datadog-plugin-aws-sdk/src/services/sqs.js
  packages/datadog-plugin-aws-sdk/test/kinesis.spec.js
  packages/datadog-plugin-aws-sdk/test/kinesis_helpers.js
  packages/datadog-plugin-aws-sdk/test/sns.spec.js
  packages/datadog-plugin-aws-sdk/test/spec_helpers.js
  packages/datadog-plugin-aws-sdk/test/sqs.spec.js
  packages/dd-trace/src/datastreams/processor.js
  packages/dd-trace/src/datastreams/writer.js
  packages/dd-trace/src/tracer.js
  packages/dd-trace/test/plugins/agent.js
Labels: semver-minor, datastreams

#3988 test ci reporter output
  packages/dd-trace/test/setup/mocha.js
  packages/dd-trace/test/setup/slack-report.js
Labels: dev/testing, semver-patch

#3797 Fix mquery vulnerability location [APPSEC-12226]
  .github/workflows/appsec.yml
  packages/datadog-instrumentations/src/helpers/hooks.js
  packages/datadog-instrumentations/src/mquery.js
  packages/dd-trace/src/appsec/iast/analyzers/nosql-injection-mongodb-analyzer.js
  packages/dd-trace/test/appsec/iast/analyzers/nosql-injection-mongodb-analyzer.mquery.plugin.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/resources/mquery-vulnerable-method.js
  packages/dd-trace/test/appsec/iast/utils.js
  packages/dd-trace/test/plugins/externals.json
Labels: semver-minor, asm-iast

#3999 remove lodash
  LICENSE-3rdparty.csv
  package.json
  packages/datadog-instrumentations/src/amqplib.js
  packages/datadog-plugin-graphql/src/index.js
  packages/datadog-plugin-grpc/src/util.js
  packages/dd-trace/src/opentracing/propagation/text_map.js
  packages/dd-trace/src/plugins/util/web.js
  packages/utils/src/kebabcase.js
  packages/utils/src/pick.js
  packages/utils/src/uniq.js
  yarn.lock
Labels: semver-patch

#3874 feat: add datadog trace context extraction to aws kinesis
  packages/datadog-plugin-aws-sdk/src/services/kinesis.js
  packages/datadog-plugin-aws-sdk/test/kinesis.spec.js
  packages/dd-trace/test/plugins/agent.js
Labels: semver-minor

#4004 Fix workflow for plugins
  .github/workflows/plugins.yml
Labels: dev/testing, semver-patch

#3998 [ci-visibility] Add support for `evp_proxy/v4` (gzip compatible)
  packages/dd-trace/src/ci-visibility/exporters/agent-proxy/index.js
  packages/dd-trace/src/ci-visibility/exporters/agentless/index.js
  packages/dd-trace/src/ci-visibility/exporters/ci-visibility-exporter.js
  packages/dd-trace/src/ci-visibility/exporters/git/git_metadata.js
  packages/dd-trace/src/ci-visibility/intelligent-test-runner/get-itr-configuration.js
  packages/dd-trace/src/ci-visibility/intelligent-test-runner/get-skippable-suites.js
  packages/dd-trace/test/ci-visibility/exporters/agent-proxy/agent-proxy.spec.js
  packages/dd-trace/test/ci-visibility/exporters/git/git_metadata.spec.js
Labels: ci-app, semver-minor

#4006 Fix location in mysql vulnerability
  packages/dd-trace/src/appsec/iast/analyzers/sql-injection-analyzer.js
  packages/dd-trace/src/appsec/iast/analyzers/vulnerability-analyzer.js
  packages/dd-trace/test/appsec/iast/analyzers/sql-injection-analyzer.spec.js
Labels: semver-patch, asm-iast

#3608 Shell execution integration
  .github/workflows/plugins.yml
  LICENSE-3rdparty.csv
  ci/init.js
  package.json
  packages/datadog-instrumentations/src/child-process.js
  packages/datadog-instrumentations/src/child_process.js
  packages/datadog-instrumentations/src/helpers/hooks.js
  packages/datadog-instrumentations/test/child_process.spec.js
  packages/datadog-plugin-child_process/src/index.js
  packages/datadog-plugin-child_process/src/scrub-cmd-params.js
  packages/datadog-plugin-child_process/test/index.spec.js
  packages/datadog-plugin-child_process/test/scrub-cmd-params.spec.js
  packages/dd-trace/src/appsec/iast/analyzers/command-injection-analyzer.js
  packages/dd-trace/src/appsec/iast/iast-plugin.js
  packages/dd-trace/src/plugins/index.js
  packages/dd-trace/src/plugins/util/exec.js
  packages/dd-trace/src/plugins/util/git.js
  packages/dd-trace/test/appsec/iast/iast-plugin.spec.js
  yarn.lock
Labels: asm-waf, semver-minor

#3981 Support processors and scanners updates for API Sec via RC
  packages/dd-trace/src/appsec/rule_manager.js
  packages/dd-trace/test/appsec/rule_manager.spec.js
Labels: asm-waf, semver-minor

#4011 [ci-visibility] Use system's node instead of the bundled one in cypress tests
  .github/workflows/project.yml
  integration-tests/cypress-config.json
  integration-tests/cypress/cypress.spec.js
Labels: ci-app, semver-patch

#3992 [request] Allow accepting gzip
  packages/dd-trace/src/exporters/common/request.js
  packages/dd-trace/test/exporters/common/request.spec.js
Labels: semver-minor
