Repository DataDog/dd-trace-js, pull requests merged in 2024-05, with the labels that each got.

#4275 docs: fix ambiguity regarding blocklist/allowlist
  index.d.ts
Labels: docs, semver-patch

#4261 Fix configuration test
  packages/dd-trace/test/config.spec.js
Labels: semver-minor

#4262 add peer.service tags to database monitoring sql injector
  packages/datadog-plugin-mysql/test/index.spec.js
  packages/datadog-plugin-mysql2/test/index.spec.js
  packages/datadog-plugin-pg/test/index.spec.js
  packages/dd-trace/src/plugins/database.js
Labels: semver-minor

#4119 Activate AVM OSS via environment variable
  packages/dd-trace/src/config.js
  packages/dd-trace/src/telemetry/index.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/telemetry/index.spec.js
Labels: semver-minor, appsec

#4226 Add Onboarding tests on gitlab pipelines
  .gitlab-ci.yml
  .gitlab/build-deb-rpm-snapshot.sh
  .gitlab/single-step-instrumentation-tests.yml
Labels: semver-patch

#4279 Sort config entries in test assertion
  packages/dd-trace/test/config.spec.js
Labels: semver-patch

#4266 Use variable name as evidence in hardcoded password vulnerability
  packages/dd-trace/src/appsec/iast/analyzers/hardcoded-base-analyzer.js
  packages/dd-trace/src/appsec/iast/analyzers/hardcoded-password-analyzer.js
  packages/dd-trace/src/appsec/iast/vulnerabilities-formatter/evidence-redaction/sensitive-analyzers/hardcoded-password-analyzer.js
  packages/dd-trace/src/appsec/iast/vulnerabilities-formatter/evidence-redaction/sensitive-handler.js
  packages/dd-trace/src/appsec/iast/vulnerabilities-formatter/index.js
  packages/dd-trace/test/appsec/iast/analyzers/hardcoded-password-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/hardcoded-secret-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/vulnerability-formatter/resources/evidence-redaction-suite.json
Labels: semver-minor, asm-iast

#4284 insisting upon import-in-the-middle >= 1.7.4
  package.json
  yarn.lock
Labels: semver-patch

#4281 IAST support node 22
  .github/workflows/appsec.yml
  package.json
  yarn.lock
Labels: semver-minor, asm-iast

#4283 feat(telemetry): adding instrumentation_config_id
  packages/dd-trace/src/config.js
  packages/dd-trace/test/config.spec.js
Labels: semver-minor

#4297 [ci-visibility] Fix playwright >=1.44.0
  packages/datadog-instrumentations/src/playwright.js
Labels: ci-app, semver-patch

#4294 esbuild: clarify warnings, hide behind debug
  packages/datadog-esbuild/index.js
Labels: semver-patch

#4239 Implement common taint tracking operations
  .github/workflows/appsec.yml
  package.json
  packages/datadog-instrumentations/src/helpers/hooks.js
  packages/datadog-instrumentations/src/lodash.js
  packages/dd-trace/src/appsec/iast/taint-tracking/csi-methods.js
  packages/dd-trace/src/appsec/iast/taint-tracking/operations.js
  packages/dd-trace/src/appsec/iast/taint-tracking/taint-tracking-impl.js
  packages/dd-trace/test/appsec/iast/taint-tracking/resources/propagationFunctions.js
  packages/dd-trace/test/appsec/iast/taint-tracking/resources/propagationLodashFunctions.js
  packages/dd-trace/test/appsec/iast/taint-tracking/taint-tracking-impl.spec.js
  packages/dd-trace/test/appsec/iast/taint-tracking/taint-tracking.lodash.plugin.spec.js
  packages/dd-trace/test/plugins/externals.json
  yarn.lock
Labels: semver-minor, asm-iast

#4278 PROF-9722: Send profiler errors to the telemetry log
  packages/dd-trace/src/appsec/iast/iast-log.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/profiling/profiler.js
  packages/dd-trace/src/proxy.js
  packages/dd-trace/src/telemetry/logs/log-collector.js
  packages/dd-trace/test/appsec/iast/iast-log.spec.js
  packages/dd-trace/test/telemetry/logs/log-collector.spec.js
Labels: semver-minor

#4306 Add `child_process` plugin to typings
  docs/test.ts
  index.d.ts
Labels: semver-minor

#4287 Support meta_struct in v0.4
  packages/dd-trace/src/encode/0.4.js
  packages/dd-trace/test/encode/0.4.spec.js
  packages/dd-trace/test/encode/0.5.spec.js
Labels: asm-waf, semver-minor

#4312 Add profiler support for node 22
  .github/workflows/profiling.yml
  .github/workflows/tracing.yml
  package.json
  yarn.lock
Labels: profiling, semver-minor

#4304 Enable Serverless Mini Agent for Azure Functions on All Plans
  packages/dd-trace/src/config.js
  packages/dd-trace/src/proxy.js
  packages/dd-trace/src/serverless.js
  packages/dd-trace/test/serverless.spec.js
Labels: semver-minor, serverless, mergequeue-status: waiting

#4300 don't clobber manually-installed tracer with SSI
  init.js
  integration-tests/init.spec.js
  integration-tests/init/index.js
Labels: semver-minor

#4318 set an explicit version range for the @opentelemetry/api
  README.md
  package.json
Labels: semver-minor

#4315 [ci-visibility] Remove `jest-jasmine2` code
  packages/datadog-instrumentations/src/helpers/hooks.js
  packages/datadog-instrumentations/src/jest.js
  packages/datadog-plugin-jest/test/jasmine2.spec.js
  packages/dd-trace/src/plugins/index.js
Labels: ci-app, semver-patch, dont-land-on-v3.x

#4316 Remove last node 21 references in GH actions
  .github/actions/node/21/action.yml
  .github/workflows/appsec.yml
Labels: semver-patch

#4323 [ci-visibility] Fix EFD with jest and jsdom
  integration-tests/ci-visibility.spec.js
  integration-tests/ci-visibility/run-jest.js
  integration-tests/ci-visibility/run-jest.mjs
  packages/datadog-instrumentations/src/jest.js
Labels: ci-app, semver-patch

#4330 [ci-visibility] Fix selenium when run outside of a supported test framework
  integration-tests/ci-visibility/test/selenium-no-framework.js
  integration-tests/selenium/selenium.spec.js
  packages/datadog-instrumentations/src/selenium.js
Labels: ci-app, semver-patch

#4328 amqplib: node>=v22.2.0 incompat amqplib<=v0.5.2
  packages/datadog-instrumentations/src/amqplib.js
Labels: semver-patch

#4324 docs: direct readers to the correct doc site
  docs/README.md
Labels: docs, semver-patch

#4317 docs: mark v3 of the tracer as EoL in readme
  README.md
Labels: docs, semver-patch

#4331 quick readme update for ESM
  README.md
Labels: semver-minor

#4337 Updating next plugin to handle version change causing failure in tests
  packages/datadog-plugin-next/src/index.js
Labels: semver-minor

#4338 Update lib-injection docker image tags
  .gitlab-ci.yml
  .gitlab/build-lib-init.sh
Labels: semver-patch

#4339 OnBoarding tests: fix gitlab pipeline
  .gitlab/single-step-instrumentation-tests.yml
Labels: semver-patch

#4341 Improve lib-injection tagging script
  .gitlab/build-lib-init.sh
Labels: semver-patch

#4336 [ci-visibility] Add back calculation of untested files when calculating total code coverage
  integration-tests/ci-visibility.spec.js
  integration-tests/ci-visibility/run-jest.js
  integration-tests/ci-visibility/test-total-code-coverage/test-run.js
  integration-tests/ci-visibility/test-total-code-coverage/test-skipped.js
  integration-tests/ci-visibility/test-total-code-coverage/unused-dependency.js
  integration-tests/ci-visibility/test-total-code-coverage/used-dependency.js
  packages/datadog-instrumentations/src/jest.js
Labels: ci-app, semver-patch

#4340 add a job that passes only if all others pass
  .github/workflows/project.yml
Labels: semver-patch

#4298 Fix patching behavior for require-in-the-middle
  packages/dd-trace/src/ritm.js
  packages/dd-trace/test/ritm.spec.js
Labels: semver-minor, serverless, mergequeue-status: waiting

#4342 make the all-green job only run on PRs
  .github/workflows/all-green.yml
  .github/workflows/project.yml
Labels: semver-patch

#4314 [ci-visibility] Support mocha parallel mode
  ci/init.js
  ext/exporters.d.ts
  ext/exporters.js
  integration-tests/ci-visibility.spec.js
  integration-tests/ci-visibility/run-workerpool.js
  packages/datadog-instrumentations/src/helpers/hooks.js
  packages/datadog-instrumentations/src/mocha.js
  packages/datadog-instrumentations/src/mocha/common.js
  packages/datadog-instrumentations/src/mocha/main.js
  packages/datadog-instrumentations/src/mocha/utils.js
  packages/datadog-instrumentations/src/mocha/worker.js
  packages/datadog-plugin-mocha/src/index.js
  packages/dd-trace/src/ci-visibility/exporters/test-worker/index.js
  packages/dd-trace/src/exporter.js
  packages/dd-trace/src/plugins/index.js
  packages/dd-trace/src/plugins/util/test.js
  packages/dd-trace/test/ci-visibility/exporters/test-worker/exporter.spec.js
Labels: ci-app, semver-minor

#4345 Fix `describe.only` in `ci-visibility.spec.js`
  integration-tests/ci-visibility.spec.js
Labels: ci-app, semver-patch

#4344 Add OCI package building
  .gitlab-ci.yml
  .gitlab/build_oci_package.sh
Labels: dev/tooling, semver-patch

#4009 Remove outdated polyfills
  LICENSE-3rdparty.csv
  package.json
  packages/datadog-instrumentations/src/apollo-server-core.js
  packages/datadog-instrumentations/src/apollo-server.js
  packages/datadog-instrumentations/src/body-parser.js
  packages/datadog-instrumentations/src/cookie-parser.js
  packages/datadog-instrumentations/src/express.js
  packages/datadog-instrumentations/src/graphql.js
  packages/datadog-instrumentations/src/http/server.js
  packages/datadog-instrumentations/src/router.js
  packages/datadog-plugin-http/test/server.spec.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/plugins/util/ip_blocklist.js
  packages/dd-trace/src/plugins/util/ip_extractor.js
  packages/dd-trace/test/appsec/blocking.spec.js
  yarn.lock
Labels: semver-patch, dont-land-on-v3.x

#4348 [ci-visibility] Remove usage of `.asyncResource` in mocha plugin
  packages/datadog-instrumentations/src/mocha/main.js
  packages/datadog-instrumentations/src/mocha/utils.js
  packages/datadog-plugin-mocha/test/index.spec.js
  packages/dd-trace/test/setup/mocha.js
Labels: ci-app, semver-patch

#4349 Send meta_struct properties as byte array
  packages/dd-trace/src/encode/0.4.js
  packages/dd-trace/test/encode/0.4.spec.js
Labels: semver-patch, asm-waf

#4353 [ci-visibility] Playwright: Do not use `_allTests` property
  packages/datadog-instrumentations/src/playwright.js
Labels: ci-app, semver-patch

#4357 update lockfile
  yarn.lock
Labels: semver-patch

#4356 bump .eslintrc.json ecmaVersion to 2021
  .eslintrc.json
Labels: semver-patch

#4352 fix(openai): finish span on error
  packages/datadog-instrumentations/src/openai.js
  packages/datadog-plugin-openai/src/index.js
  packages/datadog-plugin-openai/test/index.spec.js
Labels: semver-patch, integration-openai

#4354 fix(oci): Use same version as deb/rpms
  .gitlab/build_oci_package.sh
Labels: dev/tooling, semver-patch, mergequeue-status: removed

#4322 PROF-9791: Use heuristics to start the profiler when requested through SSI
  integration-tests/profiler/profiler.spec.js
  integration-tests/profiler/ssi.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/profiler.js
  packages/dd-trace/src/profiling/config.js
  packages/dd-trace/src/profiling/profiler.js
  packages/dd-trace/src/profiling/ssi-heuristics.js
  packages/dd-trace/src/profiling/ssi-telemetry-mock-profiler.js
  packages/dd-trace/src/proxy.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/profiling/ssi-heuristics.spec.js
Labels: profiling, semver-minor

#4351 add tracer flare
  packages/dd-trace/src/flare/file.js
  packages/dd-trace/src/flare/index.js
  packages/dd-trace/src/log/channels.js
  packages/dd-trace/src/log/writer.js
  packages/dd-trace/src/proxy.js
  packages/dd-trace/src/startup-log.js
  packages/dd-trace/test/flare.spec.js
  packages/dd-trace/test/proxy.spec.js
Labels: semver-minor

#4332 debug: warn if loaded with conflicting packages
  packages/datadog-instrumentations/src/check_require_cache.js
  packages/datadog-instrumentations/src/helpers/register.js
  packages/dd-trace/src/tracer.js
Labels: semver-patch

#4343 parallelize next plugin test
  .github/workflows/appsec.yml
  .github/workflows/plugins.yml
Labels: semver-patch

#4360 fix(openai): multiple choices on streamed requests are tagged properly
  packages/datadog-instrumentations/src/openai.js
  packages/datadog-plugin-openai/test/index.spec.js
  packages/datadog-plugin-openai/test/streamed-responses/chat.completions.multiple.txt
Labels: semver-patch, integration-openai

#4242 add remote config support for sampling rules
  .github/workflows/system-tests.yml
  packages/dd-trace/src/appsec/remote_config/capabilities.js
  packages/dd-trace/src/appsec/remote_config/index.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/telemetry/index.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/telemetry/index.spec.js
Labels: semver-minor

#4365 user dockerhub image for elasticsearch instead of elastic's registry
  .github/workflows/plugins.yml
Labels: semver-patch

#4362 refactor system tests yaml to parallelize
  .github/workflows/system-tests.yml
Labels: semver-patch

#4367 retry get-port
  package.json
  packages/dd-trace/test/setup/core.js
Labels: semver-patch
