Repository DataDog/dd-trace-js, pull requests merged in 2024-06, with the labels that each got.

#4363 Add Support For Mapping OTEL_LOG_LEVEL='debug'
  packages/dd-trace/src/config.js
  packages/dd-trace/test/config.spec.js
Labels: semver-patch

#4361 Exploit prevention monitoring ssrf
  docs/test.ts
  index.d.ts
  packages/dd-trace/src/appsec/addresses.js
  packages/dd-trace/src/appsec/channels.js
  packages/dd-trace/src/appsec/index.js
  packages/dd-trace/src/appsec/rasp.js
  packages/dd-trace/src/config.js
  packages/dd-trace/test/appsec/index.spec.js
  packages/dd-trace/test/appsec/rasp.express.plugin.spec.js
  packages/dd-trace/test/appsec/rasp.spec.js
  packages/dd-trace/test/appsec/rasp_rules.json
  packages/dd-trace/test/config.spec.js
Labels: asm-waf, semver-minor

#4376 fix next node 18 flaky test by removing cache
  .github/workflows/plugins.yml
Labels: semver-minor

#4366 feat(openai): support token metrics for completions and chat completions when not provided
  packages/datadog-instrumentations/src/openai.js
  packages/datadog-plugin-openai/src/index.js
  packages/datadog-plugin-openai/test/index.spec.js
  packages/datadog-plugin-openai/test/streamed-responses/chat.completions.simple.usage.txt
  packages/datadog-plugin-openai/test/streamed-responses/completions.simple.usage.txt
Labels: semver-patch, integration-openai

#4325 implement w3c phase 3
  ext/tags.d.ts
  ext/tags.js
  packages/dd-trace/src/opentracing/propagation/text_map.js
  packages/dd-trace/test/opentracing/propagation/text_map.spec.js
Labels: semver-minor

#4377 make initialize.mjs backportable for node 16
  initialize.mjs
  integration-tests/init.spec.js
Labels: semver-patch

#4371 upgrade(CI): Test OCI system-tests scenarios on every commit
  .gitlab/single-step-instrumentation-tests.yml
Labels: semver-patch

#4388 pin otel api version in integration test
  integration-tests/opentelemetry.spec.js
Labels: semver-patch

#4387 Fix graphql.resolve span durations
  packages/datadog-plugin-graphql/src/resolve.js
  packages/datadog-plugin-graphql/test/index.spec.js
Labels: semver-minor

#4384 Remap `http.response.status_code` to `http.status_code` for otel spans
  packages/dd-trace/src/opentelemetry/span.js
  packages/dd-trace/test/opentelemetry/span.spec.js
Labels: semver-minor, open-telemetry

#4378 Send original config value to telemetry
  packages/dd-trace/src/config.js
  packages/dd-trace/test/config.spec.js
Labels: semver-minor

#4381 RC support for sampling rules patch
  packages/dd-trace/src/config.js
  packages/dd-trace/src/constants.js
  packages/dd-trace/src/priority_sampler.js
  packages/dd-trace/src/sampling_rule.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/priority_sampler.spec.js
Labels: semver-patch

#3837 Suspicious Response Blocking
  packages/datadog-instrumentations/src/http/server.js
  packages/dd-trace/src/appsec/blocking.js
  packages/dd-trace/src/appsec/channels.js
  packages/dd-trace/src/appsec/index.js
  packages/dd-trace/src/appsec/remote_config/capabilities.js
  packages/dd-trace/src/appsec/remote_config/index.js
  packages/dd-trace/test/appsec/blocking.spec.js
  packages/dd-trace/test/appsec/index.spec.js
  packages/dd-trace/test/appsec/remote_config/index.spec.js
  packages/dd-trace/test/appsec/response_blocking.spec.js
  packages/dd-trace/test/appsec/response_blocking_rules.json
  packages/dd-trace/test/appsec/streamtest.txt
Labels: asm-waf, semver-minor

#4393 chore(severless): update `CODEOWNERS`
  CODEOWNERS
Labels: semver-patch, serverless

#4386 Khanayan123/implement span events
  packages/dd-trace/src/format.js
  packages/dd-trace/src/opentelemetry/span.js
  packages/dd-trace/src/opentracing/span.js
  packages/dd-trace/src/tagger.js
  packages/dd-trace/test/encode/0.4.spec.js
  packages/dd-trace/test/encode/0.5.spec.js
  packages/dd-trace/test/format.spec.js
  packages/dd-trace/test/opentelemetry/span.spec.js
  packages/dd-trace/test/opentracing/span.spec.js
  packages/dd-trace/test/tagger.spec.js
Labels: semver-minor

#4293 crysmags/ Adding support for Undici
  .github/workflows/plugins.yml
  docs/API.md
  docs/add-redirects.sh
  docs/test.ts
  index.d.ts
  packages/datadog-instrumentations/src/helpers/hooks.js
  packages/datadog-instrumentations/src/undici.js
  packages/datadog-plugin-undici/src/index.js
  packages/datadog-plugin-undici/test/index.spec.js
  packages/datadog-plugin-undici/test/naming.js
  packages/dd-trace/src/plugins/index.js
  packages/dd-trace/src/service-naming/schemas/v0/web.js
  packages/dd-trace/src/service-naming/schemas/v1/web.js
Labels: semver-minor

#4370 Exploit prevention metrics
  packages/dd-trace/src/appsec/rasp.js
  packages/dd-trace/src/appsec/reporter.js
  packages/dd-trace/src/appsec/telemetry.js
  packages/dd-trace/src/appsec/waf/index.js
  packages/dd-trace/src/appsec/waf/waf_context_wrapper.js
  packages/dd-trace/test/appsec/rasp.express.plugin.spec.js
  packages/dd-trace/test/appsec/rasp.spec.js
  packages/dd-trace/test/appsec/reporter.spec.js
  packages/dd-trace/test/appsec/telemetry.spec.js
  packages/dd-trace/test/appsec/waf/index.spec.js
Labels: semver-minor

#4398 update appsec rules to 1.12.0
  packages/dd-trace/src/appsec/recommended.json
Labels: asm-waf, semver-minor

#4403 Fix cassandra tests
  .github/workflows/plugins.yml
  docker-compose.yml
Labels: semver-patch

#4382 Add support to `generate_stack` action
  docs/test.ts
  index.d.ts
  packages/dd-trace/src/appsec/iast/path-line.js
  packages/dd-trace/src/appsec/index.js
  packages/dd-trace/src/appsec/rasp.js
  packages/dd-trace/src/appsec/stack_trace.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/format.js
  packages/dd-trace/test/appsec/index.spec.js
  packages/dd-trace/test/appsec/rasp.express.plugin.spec.js
  packages/dd-trace/test/appsec/rasp.spec.js
  packages/dd-trace/test/appsec/stack_trace.spec.js
  packages/dd-trace/test/config.spec.js
Labels: asm-waf, semver-minor

#4407 Add js hapi
  .gitlab-ci.yml
  .gitlab/benchmarks.yml
  .gitlab/macrobenchmarks.yml
Labels: semver-patch, performance

#4409 Add datadog static analyzer
  .github/workflows/datadog-static-analysis.yml
  static-analysis.datadog.yml
Labels: dev/tooling, semver-minor

#4414 update dep: import-in-the-middle@^1.8.1 from ^1.7.4
  package.json
  yarn.lock
Labels: semver-patch

#4411 Improve nextjs tests flakyness
  packages/datadog-plugin-next/test/index.spec.js
Labels: semver-patch

#4291 Standalone ASM configuration and span tags
  docs/test.ts
  index.d.ts
  packages/dd-trace/src/appsec/iast/vulnerability-reporter.js
  packages/dd-trace/src/appsec/reporter.js
  packages/dd-trace/src/appsec/sdk/track_event.js
  packages/dd-trace/src/appsec/standalone.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/constants.js
  packages/dd-trace/src/opentracing/span.js
  packages/dd-trace/src/proxy.js
  packages/dd-trace/test/appsec/iast/vulnerability-reporter.spec.js
  packages/dd-trace/test/appsec/reporter.spec.js
  packages/dd-trace/test/appsec/sdk/track_event.spec.js
  packages/dd-trace/test/appsec/standalone.spec.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/opentracing/span.spec.js
  packages/dd-trace/test/proxy.spec.js
Labels: semver-minor

#4417 fix: child_process: default to tracer service name
  packages/datadog-plugin-child_process/src/index.js
  packages/datadog-plugin-child_process/test/index.spec.js
Labels: semver-patch

#4410 Fix stack trace collection for appsec events
  packages/dd-trace/src/appsec/stack_trace.js
  packages/dd-trace/test/appsec/stack_trace.spec.js
Labels: asm-waf, semver-minor

#4421 increase timeout for aws-sdk and next tests
  package.json
  packages/datadog-plugin-aws-sdk/test/integration-test/client.spec.js
  packages/datadog-plugin-next/test/index.spec.js
  packages/dd-trace/test/appsec/index.spec.js
  packages/dd-trace/test/setup/mocha.js
Labels: semver-patch

#4422 fix missing on section in static analysis yaml
  .github/workflows/datadog-static-analysis.yml
Labels: semver-patch

#4426 remove get-port usage from http tests and test agent
  packages/datadog-plugin-http/test/client.spec.js
  packages/datadog-plugin-http/test/server.spec.js
  packages/dd-trace/test/plugins/agent.js
Labels: semver-patch

#4432 Fix rasp tests
  packages/dd-trace/test/appsec/rasp.express.plugin.spec.js
Labels: semver-patch

#4423 test: add a test for express 404 errors
  packages/datadog-plugin-express/test/index.spec.js
Labels: semver-patch

#4428 remove most get-port usage in appsec tests
  packages/dd-trace/test/appsec/graphql.apollo-server-express.plugin.spec.js
  packages/dd-trace/test/appsec/graphql.apollo-server-fastify.plugin.spec.js
  packages/dd-trace/test/appsec/graphql.apollo-server.plugin.spec.js
  packages/dd-trace/test/appsec/iast/taint-tracking/sources/plugin.apollo-server-express.plugin.spec.js
  packages/dd-trace/test/appsec/iast/taint-tracking/sources/plugin.apollo-server.plugin.spec.js
  packages/dd-trace/test/appsec/iast/taint-tracking/sources/taint-tracking.express.plugin.spec.js
  packages/dd-trace/test/appsec/iast/utils.js
  packages/dd-trace/test/appsec/index.body-parser.plugin.spec.js
  packages/dd-trace/test/appsec/index.cookie-parser.plugin.spec.js
  packages/dd-trace/test/appsec/index.express.plugin.spec.js
  packages/dd-trace/test/appsec/index.sequelize.plugin.spec.js
  packages/dd-trace/test/appsec/index.spec.js
  packages/dd-trace/test/appsec/rasp.express.plugin.spec.js
  packages/dd-trace/test/appsec/response_blocking.spec.js
  packages/dd-trace/test/appsec/sdk/set_user.spec.js
  packages/dd-trace/test/appsec/sdk/track_event.spec.js
  packages/dd-trace/test/appsec/sdk/user_blocking.spec.js
Labels: semver-patch

#4431 increase timeout of profiler integration test to 30s
  integration-tests/profiler/profiler.spec.js
Labels: semver-patch

#4425 tracing(aws-sdk): improve sqs dsm tracing experience
  packages/datadog-instrumentations/src/aws-sdk.js
  packages/datadog-plugin-aws-sdk/src/base.js
  packages/datadog-plugin-aws-sdk/src/services/kinesis.js
  packages/datadog-plugin-aws-sdk/src/services/sqs.js
  packages/datadog-plugin-aws-sdk/test/sqs.spec.js
Labels: semver-minor

#4435 deps: upgrade lru-cache@^7.14.0 -> ^10.2.2
  package.json
  packages/dd-trace/src/appsec/iast/vulnerability-reporter.js
  packages/dd-trace/src/datastreams/pathway.js
  yarn.lock
Labels: semver-patch

#4429 remove most usage of get-port for plugin tests
  packages/datadog-instrumentations/test/body-parser.spec.js
  packages/datadog-instrumentations/test/cookie-parser.spec.js
  packages/datadog-instrumentations/test/express-mongo-sanitize.spec.js
  packages/datadog-instrumentations/test/express.spec.js
  packages/datadog-instrumentations/test/passport-http.spec.js
  packages/datadog-instrumentations/test/passport-local.spec.js
  packages/datadog-plugin-apollo/test/index.spec.js
  packages/datadog-plugin-connect/test/index.spec.js
  packages/datadog-plugin-cypress/test/index.spec.js
  packages/datadog-plugin-express/test/index.spec.js
  packages/datadog-plugin-express/test/leak.js
  packages/datadog-plugin-fastify/test/index.spec.js
  packages/datadog-plugin-fetch/test/index.spec.js
  packages/datadog-plugin-graphql/test/index.spec.js
  packages/datadog-plugin-hapi/test/index.spec.js
  packages/datadog-plugin-http2/test/client.spec.js
  packages/datadog-plugin-http2/test/server.spec.js
  packages/datadog-plugin-koa/test/index.spec.js
  packages/datadog-plugin-microgateway-core/test/index.spec.js
  packages/datadog-plugin-net/test/index.spec.js
  packages/datadog-plugin-paperplane/test/index.spec.js
  packages/datadog-plugin-restify/test/index.spec.js
  packages/datadog-plugin-router/test/index.spec.js
  packages/datadog-plugin-undici/test/index.spec.js
Labels: semver-patch

#4437 Revert "deps: upgrade lru-cache@^7.14.0 -> ^10.2.2"
  package.json
  packages/dd-trace/src/appsec/iast/vulnerability-reporter.js
  packages/dd-trace/src/datastreams/pathway.js
  yarn.lock
Labels: semver-patch

#4438 [CI] Use system-tests reusable workflow for PARAMETRIC scenario
  .github/workflows/system-tests.yml
Labels: semver-patch

#4433 fix(openai): safe require `tiktoken` for webpack bundlers
  LICENSE-3rdparty.csv
  package.json
  packages/datadog-plugin-openai/src/index.js
  packages/datadog-plugin-openai/src/token-estimator.js
  packages/datadog-plugin-openai/test/index.spec.js
  packages/datadog-plugin-openai/test/streamed-responses/completions.simple.txt
  packages/datadog-plugin-openai/test/token-estimator.spec.js
  yarn.lock
Labels: semver-patch, integration-openai

#4439 split couchbase tests by major version
  .github/workflows/plugins.yml
Labels: semver-patch

#4441 split nextjs tests by major versions
  .github/workflows/plugins.yml
  scripts/install_plugin_modules.js
Labels: semver-patch

#4443 increase timeout for integration test helpers to 30s
  integration-tests/helpers.js
Labels: semver-patch

#4319 Add runtime guardrail for SSI
  .github/workflows/project.yml
  init.js
  initialize.mjs
  integration-tests/helpers.js
  integration-tests/init.spec.js
  integration-tests/package-guardrails.spec.js
  integration-tests/package-guardrails/index.js
  integration-tests/telemetry-forwarder.sh
  packages/datadog-instrumentations/src/helpers/register.js
  packages/dd-trace/src/telemetry/init-telemetry.js
Labels: semver-minor

#4399 remove async_hooks implem
  packages/datadog-core/src/storage/async_hooks.js
  packages/datadog-core/src/storage/index.js
  packages/datadog-core/test/storage/async_hooks.spec.js
Labels: semver-patch

#4385 Collect request headers on user event
  packages/dd-trace/src/appsec/reporter.js
  packages/dd-trace/test/appsec/reporter.spec.js
Labels: asm-waf, semver-minor

#4444 [appsec] do not ping `ifconfig.pro` in RASP tests
  packages/dd-trace/test/appsec/rasp.express.plugin.spec.js
Labels: semver-patch, appsec

#4436 split parametric tests on multiple machines
  .github/workflows/system-tests.yml
Labels: semver-patch

#4445 fix(openai): handle `image_url` option on chat completion request gracefully
  packages/datadog-plugin-openai/src/index.js
  packages/datadog-plugin-openai/test/index.spec.js
Labels: semver-patch, integration-openai

#4447 test: enable an esbuild test for early node v16 versions
  integration-tests/esbuild/basic-test.js
Labels: semver-patch
