Repository DataDog/dd-trace-js, pull requests merged in 2024-09, with the labels that each got.

#4621 [test visibility] Add test session name
  integration-tests/cucumber/cucumber.spec.js
  integration-tests/cypress/cypress.spec.js
  integration-tests/jest/jest.spec.js
  integration-tests/mocha/mocha.spec.js
  integration-tests/playwright/playwright.spec.js
  integration-tests/vitest/vitest.spec.js
  packages/datadog-instrumentations/src/jest.js
  packages/datadog-plugin-cucumber/src/index.js
  packages/datadog-plugin-cypress/src/cypress-plugin.js
  packages/datadog-plugin-jest/src/index.js
  packages/datadog-plugin-mocha/src/index.js
  packages/datadog-plugin-playwright/src/index.js
  packages/datadog-plugin-vitest/src/index.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/plugin_manager.js
  packages/dd-trace/src/plugins/ci_plugin.js
  packages/dd-trace/src/plugins/util/test.js
  packages/dd-trace/test/config.spec.js
Labels: ci-app, semver-minor

#4645 feat(kafka): add datastreams monitoring support for kafkajs batches
  packages/datadog-instrumentations/src/kafkajs.js
  packages/datadog-plugin-kafkajs/src/batch-consumer.js
  packages/datadog-plugin-kafkajs/src/index.js
  packages/datadog-plugin-kafkajs/test/index.spec.js
Labels: semver-minor, integration-kafkajs

#4650 Add permissions to package-size-report workflow
  .github/workflows/package-size.yml
Labels: semver-patch

#4638 Allow Remote Config acknowledgements to be async
  packages/dd-trace/src/appsec/remote_config/index.js
  packages/dd-trace/src/appsec/remote_config/manager.js
  packages/dd-trace/src/proxy.js
  packages/dd-trace/test/appsec/index.spec.js
  packages/dd-trace/test/appsec/remote_config/index.spec.js
  packages/dd-trace/test/appsec/remote_config/manager.spec.js
  packages/dd-trace/test/proxy.spec.js
Labels: semver-patch

#4651 fix(openai): content and tool calls in streamed responses do not error
  packages/datadog-instrumentations/src/openai.js
  packages/datadog-plugin-openai/test/index.spec.js
  packages/datadog-plugin-openai/test/streamed-responses/chat.completions.tool.and.content.txt
Labels: semver-patch, integration-openai

#4653 Check context disposal before calling WAF run
  packages/dd-trace/src/appsec/waf/waf_context_wrapper.js
  packages/dd-trace/test/appsec/waf/waf_context_wrapper.spec.js
Labels: semver-patch, asm-waf, appsec

#4649 [test visibility] Use new metadata field in citestcycle
  integration-tests/cucumber/cucumber.spec.js
  integration-tests/cypress/cypress.spec.js
  integration-tests/jest/jest.spec.js
  integration-tests/mocha/mocha.spec.js
  integration-tests/playwright/playwright.spec.js
  integration-tests/vitest/vitest.spec.js
  packages/datadog-plugin-cucumber/src/index.js
  packages/datadog-plugin-cypress/src/cypress-plugin.js
  packages/datadog-plugin-jest/src/index.js
  packages/datadog-plugin-mocha/src/index.js
  packages/datadog-plugin-playwright/src/index.js
  packages/datadog-plugin-vitest/src/index.js
  packages/dd-trace/src/ci-visibility/exporters/agentless/writer.js
  packages/dd-trace/src/ci-visibility/exporters/ci-visibility-exporter.js
  packages/dd-trace/src/encode/agentless-ci-visibility.js
  packages/dd-trace/src/plugins/ci_plugin.js
  packages/dd-trace/src/plugins/util/test.js
Labels: do-not-merge/WIP, ci-app, semver-patch

#4664 Bump path-to-regexp dependency to v0.1.10
  package.json
  yarn.lock
Labels: semver-patch

#4657 [test visibility] Enable log collection for test visibility
  packages/dd-trace/src/config.js
  packages/dd-trace/src/telemetry/index.js
  packages/dd-trace/test/config.spec.js
Labels: ci-app, semver-patch

#4658 Revert "[test visibility] Use new metadata field in citestcycle "
  integration-tests/cucumber/cucumber.spec.js
  integration-tests/cypress/cypress.spec.js
  integration-tests/jest/jest.spec.js
  integration-tests/mocha/mocha.spec.js
  integration-tests/playwright/playwright.spec.js
  integration-tests/vitest/vitest.spec.js
  packages/datadog-plugin-cucumber/src/index.js
  packages/datadog-plugin-cypress/src/cypress-plugin.js
  packages/datadog-plugin-jest/src/index.js
  packages/datadog-plugin-mocha/src/index.js
  packages/datadog-plugin-playwright/src/index.js
  packages/datadog-plugin-vitest/src/index.js
  packages/dd-trace/src/ci-visibility/exporters/agentless/writer.js
  packages/dd-trace/src/ci-visibility/exporters/ci-visibility-exporter.js
  packages/dd-trace/src/encode/agentless-ci-visibility.js
  packages/dd-trace/src/plugins/ci_plugin.js
  packages/dd-trace/src/plugins/util/test.js
Labels: ci-app, semver-patch

#4669 Update to actions/upload-artifact@v4 in system tests workflow
  .github/workflows/system-tests.yml
Labels: semver-patch

#4566 Exploit prevention SQLi in pg
  packages/datadog-instrumentations/src/pg.js
  packages/datadog-instrumentations/test/pg.spec.js
  packages/dd-trace/src/appsec/addresses.js
  packages/dd-trace/src/appsec/channels.js
  packages/dd-trace/src/appsec/rasp.js
  packages/dd-trace/src/appsec/rasp/index.js
  packages/dd-trace/src/appsec/rasp/sql_injection.js
  packages/dd-trace/src/appsec/rasp/ssrf.js
  packages/dd-trace/src/appsec/rasp/utils.js
  packages/dd-trace/src/appsec/waf/waf_context_wrapper.js
  packages/dd-trace/test/appsec/rasp.spec.js
  packages/dd-trace/test/appsec/rasp/index.spec.js
  packages/dd-trace/test/appsec/rasp/resources/postgress-app/index.js
  packages/dd-trace/test/appsec/rasp/resources/rasp_rules.json
  packages/dd-trace/test/appsec/rasp/sql_injection.integration.pg.plugin.spec.js
  packages/dd-trace/test/appsec/rasp/sql_injection.pg.plugin.spec.js
  packages/dd-trace/test/appsec/rasp/sql_injection.spec.js
  packages/dd-trace/test/appsec/rasp/ssrf.express.plugin.spec.js
  packages/dd-trace/test/appsec/rasp/ssrf.spec.js
  packages/dd-trace/test/appsec/rasp/utils.js
  packages/dd-trace/test/appsec/rasp/utils.spec.js
  packages/dd-trace/test/appsec/waf/waf_context_wrapper.spec.js
  packages/dd-trace/test/plugins/externals.json
Labels: asm-waf, semver-minor

#4667 split couchbase tests by node versions
  .github/workflows/plugins.yml
Labels: semver-patch

#4647 clearer profiling error
  packages/dd-trace/src/profiling/exporters/agent.js
  packages/dd-trace/test/profiling/exporters/agent.spec.js
Labels: semver-patch

#4631 Revert "Fix Node.js version to v22.6 instead of "latest" (#4629)"
  .github/actions/node/latest/action.yml
  .github/workflows/appsec.yml
  .github/workflows/plugins.yml
  .github/workflows/project.yml
Labels: semver-patch

#4681 [test visibility] Cap vitest support until we fix it
  integration-tests/vitest/vitest.spec.js
  packages/datadog-instrumentations/src/vitest.js
Labels: ci-app, semver-patch

#4655 PROF-10497: Add span IDs to timeline DNS and TCP events
  integration-tests/profiler/profiler.spec.js
  packages/dd-trace/src/profiling/profilers/event_plugins/dns.js
  packages/dd-trace/src/profiling/profilers/event_plugins/dns_lookup.js
  packages/dd-trace/src/profiling/profilers/event_plugins/dns_lookupservice.js
  packages/dd-trace/src/profiling/profilers/event_plugins/dns_resolve.js
  packages/dd-trace/src/profiling/profilers/event_plugins/dns_reverse.js
  packages/dd-trace/src/profiling/profilers/event_plugins/event.js
  packages/dd-trace/src/profiling/profilers/event_plugins/net.js
  packages/dd-trace/src/profiling/profilers/events.js
  packages/dd-trace/src/profiling/profilers/shared.js
  packages/dd-trace/src/profiling/profilers/wall.js
Labels: profiling, semver-minor

#4682 [test visibility] Fix vitest@2.1.0
  integration-tests/vitest/vitest.spec.js
  packages/datadog-instrumentations/src/vitest.js
Labels: ci-app, semver-patch

#4678 [test visibility] Fix `@jest/test-sequencer` instrumentation
  packages/datadog-instrumentations/src/jest.js
Labels: ci-app, semver-patch

#4492 Prepare support for Dynamic Instrumentation
  .github/workflows/debugger.yml
  CODEOWNERS
  integration-tests/debugger/index.spec.js
  integration-tests/debugger/target-app/index.js
  integration-tests/helpers/fake-agent.js
  integration-tests/helpers/index.js
  package.json
  packages/dd-trace/src/config.js
  packages/dd-trace/src/debugger/devtools_client/config.js
  packages/dd-trace/src/debugger/devtools_client/index.js
  packages/dd-trace/src/debugger/devtools_client/inspector_promises_polyfill.js
  packages/dd-trace/src/debugger/devtools_client/remote_config.js
  packages/dd-trace/src/debugger/devtools_client/send.js
  packages/dd-trace/src/debugger/devtools_client/session.js
  packages/dd-trace/src/debugger/devtools_client/state.js
  packages/dd-trace/src/debugger/devtools_client/status.js
  packages/dd-trace/src/debugger/index.js
  packages/dd-trace/src/proxy.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/debugger/devtools_client/status.spec.js
Labels: semver-minor

#4683 [DI] Make it easier to debug integration test
  integration-tests/debugger/index.spec.js
Labels: semver-patch

#4684 [DI] Improve variable naming
  integration-tests/debugger/index.spec.js
Labels: semver-patch

#4690 Ensure CODEOWNERS is correct for .github/workflows/system-tests.yml
  CODEOWNERS
Labels: semver-patch

#4685 [DI] DRY up integration test code
  integration-tests/debugger/index.spec.js
Labels: semver-patch

#4677 [test visibility] Add test source file to test suites
  integration-tests/cucumber/cucumber.spec.js
  integration-tests/cypress/cypress.spec.js
  integration-tests/jest/jest.spec.js
  integration-tests/mocha/mocha.spec.js
  integration-tests/playwright/playwright.spec.js
  integration-tests/vitest/vitest.spec.js
  packages/datadog-instrumentations/src/cucumber.js
  packages/datadog-instrumentations/src/jest.js
  packages/datadog-plugin-cucumber/src/index.js
  packages/datadog-plugin-cypress/src/cypress-plugin.js
  packages/datadog-plugin-cypress/src/support.js
  packages/datadog-plugin-jest/src/index.js
  packages/datadog-plugin-mocha/src/index.js
  packages/datadog-plugin-playwright/src/index.js
  packages/datadog-plugin-vitest/src/index.js
  packages/dd-trace/src/plugins/ci_plugin.js
Labels: ci-app, semver-minor

#4686 [DI] Simplify integration test by not using async/await
  integration-tests/debugger/index.spec.js
Labels: semver-patch

#4688 fix system tests
  .github/workflows/system-tests.yml
Labels: semver-minor

#4673 Revert "Revert "[test visibility] Use new metadata field in citestcycle ""
  integration-tests/cucumber/cucumber.spec.js
  integration-tests/cypress/cypress.spec.js
  integration-tests/jest/jest.spec.js
  integration-tests/mocha/mocha.spec.js
  integration-tests/playwright/playwright.spec.js
  integration-tests/vitest/vitest.spec.js
  packages/datadog-plugin-cucumber/src/index.js
  packages/datadog-plugin-cypress/src/cypress-plugin.js
  packages/datadog-plugin-jest/src/index.js
  packages/datadog-plugin-mocha/src/index.js
  packages/datadog-plugin-playwright/src/index.js
  packages/datadog-plugin-vitest/src/index.js
  packages/dd-trace/src/ci-visibility/exporters/agentless/writer.js
  packages/dd-trace/src/ci-visibility/exporters/ci-visibility-exporter.js
  packages/dd-trace/src/encode/agentless-ci-visibility.js
  packages/dd-trace/src/plugins/ci_plugin.js
  packages/dd-trace/src/plugins/util/test.js
Labels: do-not-merge/WIP, ci-app, semver-patch

#4687 feat(dsm): add datastreams monitoring schema tracking
  packages/dd-trace/src/constants.js
  packages/dd-trace/src/datastreams/fnv.js
  packages/dd-trace/src/datastreams/processor.js
  packages/dd-trace/src/datastreams/schemas/schema.js
  packages/dd-trace/src/datastreams/schemas/schema_builder.js
  packages/dd-trace/src/datastreams/schemas/schema_sampler.js
  packages/dd-trace/test/datastreams/schemas/schema_builder.spec.js
  packages/dd-trace/test/datastreams/schemas/schema_sampler.spec.js
Labels: semver-minor

#4710 Fix tedious and fastify plugin tests
  .github/workflows/plugins.yml
  packages/datadog-plugin-fastify/test/integration-test/helper.mjs
Labels: semver-patch

#4708 Revert "Enable log collection for all products"
  packages/dd-trace/src/config.js
  packages/dd-trace/src/telemetry/index.js
  packages/dd-trace/test/config.spec.js
Labels: semver-patch

#4709 [test visibility] Report logical CPU count
  integration-tests/cucumber/cucumber.spec.js
  integration-tests/cypress/cypress.spec.js
  integration-tests/jest/jest.spec.js
  integration-tests/mocha/mocha.spec.js
  integration-tests/playwright/playwright.spec.js
  integration-tests/vitest/vitest.spec.js
  packages/dd-trace/src/plugins/util/env.js
  packages/dd-trace/test/plugins/util/env.spec.js
Labels: ci-app, semver-minor

#4711 restore next test version range
  .github/workflows/appsec.yml
  .github/workflows/plugins.yml
Labels: semver-patch

#4705 [test visibility] Remove beta flag from manual test API
  integration-tests/ci-visibility/test-api-manual/test.fake.js
  integration-tests/test-api-manual.spec.js
  packages/dd-trace/src/config.js
  packages/dd-trace/test/config.spec.js
Labels: ci-app, semver-patch

#4714 [test visibility] Early Flake Detection for vitest
  integration-tests/ci-visibility/vitest-tests/early-flake-detection.mjs
  integration-tests/vitest/vitest.spec.js
  packages/datadog-instrumentations/src/vitest.js
  packages/datadog-plugin-vitest/src/index.js
Labels: ci-app, semver-minor

#4721 Remove debug code in test file
  packages/dd-trace/test/profiling/exporters/agent.spec.js
Labels: semver-patch

#4722 Update/fix settings in .vscode directory
  .vscode/launch.json
  .vscode/settings.json
Labels: semver-patch

#4717 always enable tracing header injection for AWS requests
  docs/test.ts
  index.d.ts
  packages/datadog-plugin-aws-sdk/test/aws-sdk.spec.js
  packages/datadog-plugin-fetch/test/index.spec.js
  packages/datadog-plugin-http/src/client.js
  packages/datadog-plugin-http/test/client.spec.js
  packages/datadog-plugin-http2/src/client.js
  packages/datadog-plugin-http2/test/client.spec.js
Labels: semver-minor

#4723 [test visibility] Early flake detection for mocha (parallel mode)
  integration-tests/mocha/mocha.spec.js
  packages/datadog-instrumentations/src/mocha/main.js
  packages/datadog-instrumentations/src/mocha/utils.js
  packages/datadog-instrumentations/src/mocha/worker.js
  packages/datadog-plugin-mocha/src/index.js
  packages/dd-trace/test/plugins/externals.json
Labels: ci-app, semver-minor

#4732 Pin import-in-the-middle to 1.11.0
  package.json
  yarn.lock
Labels: semver-patch

#4731 Moving Rhea plugin test to its own job
  .github/workflows/plugins.yml
  packages/dd-trace/test/plugins/externals.json
Labels: semver-minor

#4734 Fix: Calculate correct Content-Length in requests to agent
  packages/dd-trace/src/exporters/common/request.js
  packages/dd-trace/test/exporters/common/request.spec.js
Labels: semver-patch

#4733 [test visibility] Support early flake detection for cucumber
  integration-tests/cucumber/cucumber.spec.js
  packages/datadog-instrumentations/src/cucumber.js
  packages/datadog-plugin-cucumber/src/index.js
Labels: ci-app, semver-minor

#4737 Do not run fastify >=5 plugin tests in node <=18
  packages/datadog-plugin-cucumber/test/index.spec.js
  packages/datadog-plugin-fastify/test/index.spec.js
  packages/datadog-plugin-fastify/test/integration-test/client.spec.js
  packages/datadog-plugin-undici/test/index.spec.js
Labels: semver-patch

#4740 Bump `import-in-the-middle` to 1.11.2
  package.json
  yarn.lock
Labels: semver-patch

#4741 fix: still set dsm consume checkpoint when no DSM parent context is available
  packages/datadog-plugin-amqplib/src/consumer.js
  packages/datadog-plugin-aws-sdk/src/services/kinesis.js
  packages/datadog-plugin-aws-sdk/src/services/sqs.js
  packages/datadog-plugin-kafkajs/src/batch-consumer.js
  packages/datadog-plugin-kafkajs/src/consumer.js
  packages/datadog-plugin-rhea/src/consumer.js
  packages/dd-trace/src/data_streams_context.js
  packages/dd-trace/src/datastreams/pathway.js
  packages/dd-trace/src/datastreams/processor.js
Labels: semver-minor
