Repository DataDog/dd-trace-js, pull requests merged in 2024-07, with the labels that each got.

#4450 PROF-9979: use SIMPLE_HOST_AUTO_INJECTION_PROFILING target
  .gitlab/single-step-instrumentation-tests.yml
Labels: dev/testing, semver-minor

#4457 [test visibility] Speed up cypress tests
  integration-tests/cypress/cypress.spec.js
  integration-tests/cypress/plugins-old/index.js
Labels: dev/testing, ci-app, semver-patch

#4434 tracing(aws): add configuration option to inject all messages with trace context during SQS, SNS, and Kinesis batch send operations
  docs/test.ts
  index.d.ts
  packages/datadog-plugin-aws-sdk/src/base.js
  packages/datadog-plugin-aws-sdk/src/services/kinesis.js
  packages/datadog-plugin-aws-sdk/src/services/sns.js
  packages/datadog-plugin-aws-sdk/src/services/sqs.js
  packages/datadog-plugin-aws-sdk/test/kinesis.spec.js
  packages/datadog-plugin-aws-sdk/test/sns.spec.js
  packages/datadog-plugin-aws-sdk/test/sqs.spec.js
Labels: semver-minor

#4463 ci: fix issue with actions/checkout@v3
  .github/workflows/plugins.yml
Labels: semver-patch

#4461 Use OS-independent path separators in scripts/install_plugin_modules.js
  scripts/install_plugin_modules.js
Labels: semver-patch

#4462 docs: add a Testing Prerequisites section to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: semver-patch

#4459 ci: exclude aerospike on arm64 archs when running 'yarn services'
  CONTRIBUTING.md
  scripts/install_plugin_modules.js
Labels: semver-patch

#4464 Update @datadog/native-iast-taint-tracking module to 3.0.0
  package.json
  yarn.lock
Labels: semver-patch

#4467 split aws-sdk and http tests by node version
  .github/workflows/plugins.yml
Labels: semver-patch

#4469 disable caching for windows ci
  .github/workflows/appsec.yml
  .github/workflows/profiling.yml
  .github/workflows/tracing.yml
Labels: semver-patch

#4416 Standalone ASM priority sampler and tag propagation
  integration-tests/standalone-asm.spec.js
  integration-tests/standalone-asm/index.js
  packages/dd-trace/src/appsec/standalone.js
  packages/dd-trace/src/exporters/agent/index.js
  packages/dd-trace/src/opentracing/propagation/text_map.js
  packages/dd-trace/src/opentracing/tracer.js
  packages/dd-trace/src/priority_sampler.js
  packages/dd-trace/src/proxy.js
  packages/dd-trace/src/rate_limiter.js
  packages/dd-trace/src/span_stats.js
  packages/dd-trace/src/tracer.js
  packages/dd-trace/src/util.js
  packages/dd-trace/test/appsec/standalone.spec.js
  packages/dd-trace/test/exporters/agent/exporter.spec.js
  packages/dd-trace/test/opentracing/propagation/text_map.spec.js
  packages/dd-trace/test/opentracing/tracer.spec.js
  packages/dd-trace/test/span_stats.spec.js
Labels: semver-minor, appsec

#4468 split appsec nextjs tests by nextjs version
  .github/workflows/appsec.yml
Labels: semver-patch

#4470 split cypress integration tests by module type
  .github/workflows/project.yml
  integration-tests/cypress/cypress.spec.js
Labels: semver-patch

#4472 Update default appsec obfuscation regex
  packages/dd-trace/src/config.js
  packages/dd-trace/test/config.spec.js
Labels: semver-minor

#4471 [test-visibility] Do not unsafely access `.steps` from test result in playwright
  integration-tests/ci-visibility/playwright-tests-max-failures/failing-test-and-another-test.js
  integration-tests/playwright.config.js
  integration-tests/playwright/playwright.spec.js
  packages/datadog-instrumentations/src/playwright.js
Labels: ci-app, semver-patch

#4480 [test-visibility] Fix vitest instrumentation
  CODEOWNERS
  packages/datadog-instrumentations/src/vitest.js
Labels: ci-app, semver-patch

#4369 Update Otel Invalid Telemetry Calculation
  integration-tests/opentelemetry.spec.js
  packages/dd-trace/src/config.js
Labels: semver-patch

#4478 ci: upgrade elasticsearch service to latest 7.x
  .github/workflows/plugins.yml
  docker-compose.yml
Labels: semver-patch

#4473 PROF-9979: Use SIMPLE_CONTAINER_AUTO_INJECTION_PROFILING in SSI tests
  .gitlab/single-step-instrumentation-tests.yml
Labels: dev/testing, semver-minor

#4453 [test visibility] Add automatic flaky test retries to Mocha
  integration-tests/ci-visibility/test-flaky-test-retries/eventually-passing-test.js
  integration-tests/mocha/mocha.spec.js
  packages/datadog-instrumentations/src/mocha/main.js
  packages/datadog-instrumentations/src/mocha/utils.js
  packages/datadog-instrumentations/src/mocha/worker.js
  packages/datadog-plugin-mocha/src/index.js
  packages/dd-trace/src/ci-visibility/exporters/ci-visibility-exporter.js
  packages/dd-trace/src/ci-visibility/requests/get-library-configuration.js
Labels: ci-app, semver-minor

#4490 Fix a typo that disabled debug message logging
  packages/dd-trace/src/profiling/profiler.js
Labels: profiling, semver-patch

#4484 remove node 14 tests for aerospike
  .github/workflows/plugins.yml
Labels: semver-patch

#4485 increase timeout to 60s for ci integration tests
  package.json
Labels: semver-patch

#4483 release dev version only when a label is used
  .github/workflows/release-dev.yml
Labels: semver-patch

#4491 [test-visibility] Flaky test retries for cucumber
  integration-tests/ci-visibility/features-retry/flaky.feature
  integration-tests/ci-visibility/features-retry/support/steps.js
  integration-tests/cucumber/cucumber.spec.js
  packages/datadog-instrumentations/src/cucumber.js
  packages/datadog-instrumentations/src/mocha/utils.js
  packages/datadog-plugin-cucumber/src/index.js
  packages/dd-trace/src/plugins/util/test.js
Labels: ci-app, semver-minor

#4499 Fix `init.spec.js` test for node 16 (v4 release)
  integration-tests/init.spec.js
Labels: semver-patch

#4481 feat: add dd_tags to datastreams monitoring stats payload
  packages/dd-trace/src/datastreams/processor.js
  packages/dd-trace/test/datastreams/processor.spec.js
Labels: semver-minor

#4486 split nextjs tests even more and increase timeout
  .github/workflows/appsec.yml
  .github/workflows/plugins.yml
  packages/datadog-plugin-next/test/index.spec.js
  packages/dd-trace/test/setup/mocha.js
  scripts/install_plugin_modules.js
Labels: semver-patch

#4493 add mocha configuration file and increase default timeout
  .mocharc.yml
  package.json
Labels: semver-patch

#4501 Do not run undici tests for node16 and >=6.0.0
  packages/datadog-plugin-undici/test/index.spec.js
Labels: semver-patch

#4495 [test-visibility] Fix mocha plugin tests
  packages/datadog-plugin-mocha/test/index.spec.js
Labels: ci-app, semver-patch

#4494 add action to retry yarn install when it fails
  .github/actions/install/action.yml
  .github/workflows/appsec.yml
  .github/workflows/core.yml
  .github/workflows/lambda.yml
  .github/workflows/plugins.yml
  .github/workflows/profiling.yml
  .github/workflows/project.yml
  .github/workflows/release-dev.yml
  .github/workflows/serverless-integration-test.yml
  .github/workflows/tracing.yml
  integration-tests/helpers.js
  packages/datadog-plugin-next/test/index.spec.js
  packages/dd-trace/test/appsec/index.next.plugin.spec.js
  scripts/install_plugin_modules.js
  scripts/publish_docs.js
Labels: semver-patch

#4498 Update waf obfuscator key regex
  packages/dd-trace/src/config.js
  packages/dd-trace/test/config.spec.js
Labels: semver-minor

#4504 [test-visibility] Add flaky test retries for playwright
  integration-tests/ci-visibility/playwright-tests-automatic-retry/automatic-retry-test.js
  integration-tests/playwright/playwright.spec.js
  packages/datadog-instrumentations/src/playwright.js
  packages/datadog-plugin-playwright/src/index.js
Labels: ci-app, semver-minor

#4503 remove unused memory leak tests
  CONTRIBUTING.md
  LICENSE-3rdparty.csv
  package.json
  packages/datadog-plugin-amqp10/test/leak.js
  packages/datadog-plugin-amqplib/test/leak.js
  packages/datadog-plugin-express/test/leak.js
  packages/datadog-plugin-graphql/test/leak.js
  packages/datadog-plugin-memcached/test/leak.js
  packages/datadog-plugin-mongodb-core/test/leak.js
  packages/datadog-plugin-mysql/test/leak.js
  packages/datadog-plugin-pg/test/leak.js
  packages/datadog-plugin-redis/test/leak.js
  packages/dd-trace/test/leak/tracer.js
  yarn.lock
Labels: semver-patch

#4508 update dev release action to run on workflow dispatch
  .github/workflows/release-dev.yml
Labels: semver-patch

#4509 Update child_process redaction pattern
  packages/datadog-plugin-child_process/src/scrub-cmd-params.js
  packages/datadog-plugin-child_process/test/scrub-cmd-params.spec.js
Labels: semver-minor

#4489 Make iast config available out of experimental config properties
  docs/test.ts
  index.d.ts
  packages/dd-trace/src/config.js
  packages/dd-trace/test/config.spec.js
Labels: semver-minor, asm-iast

#4460 pull system test images in parallel
  .github/workflows/system-tests.yml
Labels: semver-patch

#4514 remove collection of http.useragent in appsec reporter
  packages/dd-trace/src/appsec/reporter.js
  packages/dd-trace/test/appsec/reporter.spec.js
Labels: semver-patch, asm-waf

#4512 [test visibility] Fix suite-less tests in vitest
  integration-tests/ci-visibility/vitest-tests/test-visibility-passed-suite.mjs
  integration-tests/vitest/vitest.spec.js
  packages/datadog-instrumentations/src/vitest.js
Labels: ci-app, semver-patch

#4516 Prefer equal check over typeof check when possible
  packages/dd-trace/src/appsec/iast/vulnerabilities-formatter/index.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/opentelemetry/span.js
Labels: semver-patch

#4519 aws-sdk: ensure correct response data is being extracted from
  packages/datadog-plugin-aws-sdk/src/base.js
Labels: semver-minor

#4513 [test-visibility] Add support for flaky test retries for vitest
  CODEOWNERS
  integration-tests/ci-visibility/vitest-tests/flaky-test-retries.mjs
  integration-tests/vitest.config.mjs
  integration-tests/vitest/vitest.spec.js
  packages/datadog-instrumentations/src/vitest.js
  packages/datadog-plugin-vitest/src/index.js
Labels: ci-app, semver-minor

#4526 hardcode the latest version of node as 22.4
  .github/actions/node/latest/action.yml
  .github/workflows/appsec.yml
  .github/workflows/plugins.yml
  .github/workflows/project.yml
Labels: semver-patch

#4523 [test-visibility] Improve debugging of cypress flaky test
  integration-tests/cypress/cypress.spec.js
Labels: ci-app, semver-patch

#4528 Upgrade eslint-plugin-n from 15.7.0 to 16.6.2
  package.json
  yarn.lock
Labels: semver-patch

#4511 Add getSpanLimits()
  packages/dd-trace/src/opentelemetry/tracer.js
Labels: bug, semver-minor, open-telemetry

#4536 Bump misc sub-dependencies
  yarn.lock
Labels: semver-patch

#4517 Add missing null guards in typeof object checks
  benchmark/sirun/results-diff.js
  integration-tests/helpers.js
  packages/datadog-instrumentations/src/child_process.js
  packages/datadog-instrumentations/src/fs.js
  packages/datadog-instrumentations/src/hapi.js
  packages/datadog-instrumentations/src/http/client.js
  packages/datadog-instrumentations/src/kafkajs.js
  packages/datadog-instrumentations/src/ldapjs.js
  packages/datadog-instrumentations/src/mquery.js
  packages/datadog-instrumentations/src/next.js
  packages/datadog-instrumentations/src/pg.js
  packages/datadog-instrumentations/src/restify.js
  packages/datadog-plugin-aws-sdk/src/services/dynamodb.js
  packages/datadog-plugin-aws-sdk/src/services/stepfunctions.js
  packages/datadog-plugin-child_process/src/scrub-cmd-params.js
  packages/datadog-plugin-fs/src/index.js
  packages/datadog-plugin-http2/test/integration-test/client.spec.js
  packages/datadog-plugin-kafkajs/src/producer.js
  packages/datadog-plugin-mongodb-core/src/index.js
  packages/datadog-plugin-openai/src/index.js
  packages/datadog-plugin-sharedb/src/index.js
  packages/dd-trace/src/analytics_sampler.js
  packages/dd-trace/src/appsec/iast/analyzers/nosql-injection-mongodb-analyzer.js
  packages/dd-trace/src/appsec/iast/taint-tracking/plugin.js
  packages/dd-trace/src/appsec/iast/taint-tracking/plugins/kafka.js
  packages/dd-trace/src/appsec/iast/vulnerabilities-formatter/index.js
  packages/dd-trace/src/appsec/index.js
  packages/dd-trace/src/appsec/passport.js
  packages/dd-trace/src/appsec/waf/waf_context_wrapper.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/datastreams/processor.js
  packages/dd-trace/test/appsec/iast/utils.js
  packages/dd-trace/test/plugins/agent.js
  packages/dd-trace/test/plugins/helpers.js
Labels: semver-patch

#4533 remove yarn caching for windows job in tracing workflow
  .github/workflows/tracing.yml
Labels: semver-patch

#4534 eslint: better match desired Node.js support
  .eslintrc.json
Labels: semver-patch

#4518 [test-visibility] Flaky test retries for cypress
  integration-tests/cypress-esm-config.mjs
  integration-tests/cypress.config.js
  integration-tests/cypress/cypress.spec.js
  integration-tests/cypress/e2e/flaky-test-retries.js
  integration-tests/cypress/plugins-old/index.js
  packages/datadog-plugin-cypress/src/cypress-plugin.js
  packages/datadog-plugin-cypress/src/plugin.js
Labels: ci-app, semver-minor

#4530 [test-visibility] Add flaky test retries to jest
  integration-tests/ci-visibility/jest-flaky/flaky-fails.js
  integration-tests/ci-visibility/jest-flaky/flaky-passes.js
  integration-tests/jest/jest.spec.js
  packages/datadog-instrumentations/src/jest.js
  packages/datadog-plugin-jest/src/index.js
Labels: ci-app, semver-minor

#4529 Clean up yarn.lock
  yarn.lock
Labels: semver-patch

#4525 aws-sdk: add batchPropagationEnabled env variable configuration
  packages/datadog-plugin-aws-sdk/src/base.js
  packages/datadog-plugin-aws-sdk/src/services/kinesis.js
  packages/datadog-plugin-aws-sdk/src/services/sns.js
  packages/datadog-plugin-aws-sdk/src/services/sqs.js
  packages/datadog-plugin-aws-sdk/test/aws-sdk.spec.js
Labels: semver-minor

#4538 switch to kafka-native as the container for kafkajs tests
  .github/workflows/plugins.yml
  docker-compose.yml
  packages/dd-trace/test/setup/services/kafka.js
Labels: semver-patch

#4546 Revert "hardcode the latest version of node as 22.4"
  .github/actions/node/latest/action.yml
  .github/workflows/appsec.yml
  .github/workflows/plugins.yml
  .github/workflows/project.yml
Labels: semver-patch

#4515 Remove tight coupling between logger and config
  init.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/log/index.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/log.spec.js
Labels: semver-patch

#4502 use name and version as key for package package-guardrails
  integration-tests/package-guardrails.spec.js
  integration-tests/package-guardrails/index.js
  packages/datadog-instrumentations/src/helpers/register.js
Labels: semver-patch

#4545 [test-visibility] Fix mocha plugin tests flakiness
  packages/datadog-instrumentations/src/mocha/main.js
  packages/datadog-plugin-mocha/test/index.spec.js
Labels: semver-patch

#4537 feat: create DSM public api
  ext/formats.d.ts
  ext/formats.js
  packages/datadog-plugin-aws-sdk/src/services/sqs.js
  packages/dd-trace/src/data_streams.js
  packages/dd-trace/src/datastreams/pathway.js
  packages/dd-trace/src/opentracing/propagation/text_map_dsm.js
  packages/dd-trace/src/opentracing/tracer.js
  packages/dd-trace/src/proxy.js
  packages/dd-trace/src/tracer.js
  packages/dd-trace/test/datastreams/data_streams_checkpointer.spec.js
  packages/dd-trace/test/plugins/agent.js
Labels: semver-minor

#4521 Hide non-config properties on config object
  packages/dd-trace/src/config.js
Labels: semver-patch

#4532 Fix @types/node to version 16.x
  package.json
  yarn.lock
Labels: semver-patch

#4552 Update the expected telemetry tags for OTel env-var mapping
  integration-tests/opentelemetry.spec.js
  packages/dd-trace/src/config.js
Labels: semver-patch, open-telemetry

#4397 Use unified Gitlab pipeline for APM libraries
  .github/actions/injection/action.yml
  .github/workflows/release-3.yml
  .github/workflows/release-4.yml
  .github/workflows/release-dev.yml
  .github/workflows/release-latest.yml
  .github/workflows/test-k8s-lib-injection.yaml
  .gitlab-ci.yml
  .gitlab/benchmarks.yml
  .gitlab/build-deb-rpm-snapshot.sh
  .gitlab/build-deb-rpm.sh
  .gitlab/build-lib-init.sh
  .gitlab/prepare-oci-package.sh
  .gitlab/single-step-instrumentation-tests.yml
  lib-injection/Dockerfile
  lib-injection/copy-lib.sh
  lib-injection/npm_dd_trace.sh
  lib-injection/package.json
Labels: dev/tooling, semver-minor

#4559 Update default AppSec rules to 1.13.0
  packages/dd-trace/src/appsec/recommended.json
Labels: asm-waf, semver-minor

#4556 Iast protect WeakHashAnalyzer from undefined locations
  packages/dd-trace/src/appsec/iast/analyzers/weak-hash-analyzer.js
  packages/dd-trace/test/appsec/iast/analyzers/weak-hash-analyzer.spec.js
Labels: semver-patch, asm-iast

#4488 Code injection vulnerability detection
  package.json
  packages/dd-trace/src/appsec/iast/analyzers/analyzers.js
  packages/dd-trace/src/appsec/iast/analyzers/code-injection-analyzer.js
  packages/dd-trace/src/appsec/iast/taint-tracking/csi-methods.js
  packages/dd-trace/src/appsec/iast/taint-tracking/taint-tracking-impl.js
  packages/dd-trace/src/appsec/iast/vulnerabilities-formatter/evidence-redaction/sensitive-analyzers/code-injection-sensitive-analyzer.js
  packages/dd-trace/src/appsec/iast/vulnerabilities-formatter/evidence-redaction/sensitive-handler.js
  packages/dd-trace/src/appsec/iast/vulnerabilities-formatter/evidence-redaction/sensitive-regex.js
  packages/dd-trace/src/appsec/iast/vulnerabilities.js
  packages/dd-trace/test/appsec/iast/analyzers/code-injection-analyzer.express.plugin.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/resources/eval-methods.js
  packages/dd-trace/test/appsec/iast/utils.js
  packages/dd-trace/test/appsec/iast/vulnerability-formatter/index.spec.js
  packages/dd-trace/test/appsec/iast/vulnerability-formatter/resources/evidence-redaction-suite.json
  yarn.lock
Labels: semver-minor, asm-iast

#4558 [test visibility] Fix memory leak in workerpool hook
  CODEOWNERS
  packages/datadog-instrumentations/src/mocha/main.js
Labels: ci-app, semver-patch
