Repository DataDog/dd-trace-js, pull requests merged in 2024-12, with the labels that each got.

#4944 [test optimization] Add Dynamic Instrumentation to mocha retries
  integration-tests/ci-visibility/dynamic-instrumentation/is-jest.js
  integration-tests/ci-visibility/dynamic-instrumentation/test-hit-breakpoint.js
  integration-tests/ci-visibility/dynamic-instrumentation/test-not-hit-breakpoint.js
  integration-tests/jest/jest.spec.js
  integration-tests/mocha/mocha.spec.js
  packages/datadog-instrumentations/src/mocha/utils.js
  packages/datadog-plugin-jest/src/index.js
  packages/datadog-plugin-mocha/src/index.js
  packages/dd-trace/src/ci-visibility/dynamic-instrumentation/worker/index.js
  packages/dd-trace/src/plugins/ci_plugin.js
Labels: ci-app, semver-minor

#4954 Protect req.socket.remoteAddress in appsec reporter
  packages/dd-trace/src/appsec/reporter.js
  packages/dd-trace/test/appsec/reporter.spec.js
Labels: semver-patch, asm-waf

#4941 fix(config): test for completeness of config telemetry
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/fixtures/telemetry/config_aggregation_list.json
  packages/dd-trace/test/fixtures/telemetry/config_norm_rules.json
  packages/dd-trace/test/fixtures/telemetry/config_prefix_block_list.json
  packages/dd-trace/test/fixtures/telemetry/nodejs_config_rules.json
Labels: semver-patch

#4962 fix mysql2 3.11.5 support
  packages/datadog-instrumentations/src/mysql2.js
Labels: semver-patch

#4956 [test optimization] Add dynamic instrumentation support for cucumber
  integration-tests/ci-visibility-intake.js
  integration-tests/ci-visibility/features-di/support/steps.js
  integration-tests/ci-visibility/features-di/support/sum.js
  integration-tests/ci-visibility/features-di/test-hit-breakpoint.feature
  integration-tests/ci-visibility/features-di/test-not-hit-breakpoint.feature
  integration-tests/cucumber/cucumber.spec.js
  packages/datadog-instrumentations/src/cucumber.js
  packages/datadog-plugin-cucumber/src/index.js
Labels: ci-app, semver-minor

#4959 [test optimization] [SDTEST-1191] Add Dynamic Instrumentation support for Vitest
  integration-tests/ci-visibility/vitest-tests/bad-sum.mjs
  integration-tests/ci-visibility/vitest-tests/breakpoint-not-hit.mjs
  integration-tests/ci-visibility/vitest-tests/dynamic-instrumentation.mjs
  integration-tests/vitest/vitest.spec.js
  packages/datadog-instrumentations/src/vitest.js
  packages/datadog-plugin-vitest/src/index.js
  packages/dd-trace/src/ci-visibility/dynamic-instrumentation/worker/index.js
Labels: ci-app, semver-minor

#4861 Use sampling on timeline events
  integration-tests/profiler/profiler.spec.js
  packages/dd-trace/src/profiling/config.js
  packages/dd-trace/src/profiling/profilers/event_plugins/event.js
  packages/dd-trace/src/profiling/profilers/events.js
Labels: profiling, semver-minor

#4804 remove try catch from iast plugin
  packages/dd-trace/src/appsec/iast/iast-plugin.js
  packages/dd-trace/test/appsec/iast/analyzers/vulnerability-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/iast-plugin.spec.js
Labels: semver-patch, asm-iast, appsec

#4967 Explain why keeping query in http end translator
  packages/dd-trace/src/appsec/index.js
Labels: semver-patch, appsec

#4973 fix next esm tests installing wrong version of react
  packages/datadog-plugin-next/test/integration-test/client.spec.js
  scripts/install_plugin_modules.js
Labels: semver-patch, integration-nextjs

#4759 modernize eslint config
  .eslintignore
  .eslintrc.json
  LICENSE-3rdparty.csv
  eslint.config.mjs
  integration-tests/ci-visibility/features-esm/support/steps.mjs
  integration-tests/debugger/snapshot.spec.js
  integration-tests/debugger/target-app/snapshot.js
  integration-tests/esbuild/build-and-test-typescript.mjs
  integration-tests/esbuild/complex-app.mjs
  loader-hook.mjs
  package.json
  packages/datadog-instrumentations/src/pg.js
  packages/datadog-plugin-aws-sdk/test/eventbridge.spec.js
  packages/datadog-plugin-aws-sdk/test/kinesis.spec.js
  packages/datadog-plugin-aws-sdk/test/sns.spec.js
  packages/datadog-plugin-aws-sdk/test/stepfunctions.spec.js
  packages/datadog-plugin-cassandra-driver/test/integration-test/server.mjs
  packages/datadog-plugin-child_process/src/scrub-cmd-params.js
  packages/datadog-plugin-elasticsearch/test/integration-test/server.mjs
  packages/datadog-plugin-google-cloud-pubsub/test/integration-test/server.mjs
  packages/datadog-plugin-graphql/test/integration-test/server.mjs
  packages/datadog-plugin-microgateway-core/test/integration-test/server.mjs
  packages/datadog-plugin-mongodb-core/test/integration-test/server.mjs
  packages/datadog-plugin-mongodb-core/test/integration-test/server2.mjs
  packages/datadog-plugin-net/test/integration-test/server.mjs
  packages/datadog-plugin-openai/test/integration-test/server.mjs
  packages/datadog-plugin-opensearch/test/integration-test/server.mjs
  packages/datadog-plugin-oracledb/test/integration-test/server.mjs
  packages/datadog-plugin-sharedb/test/integration-test/server.mjs
  packages/dd-trace/src/appsec/blocked_templates.js
  packages/dd-trace/src/appsec/iast/analyzers/hardcoded-password-rules.js
  packages/dd-trace/src/appsec/iast/analyzers/hardcoded-secret-rules.js
  packages/dd-trace/src/appsec/iast/analyzers/hardcoded-secrets-rules.js
  packages/dd-trace/src/appsec/iast/vulnerabilities-formatter/evidence-redaction/sensitive-regex.js
  packages/dd-trace/src/appsec/iast/vulnerabilities-formatter/utils.js
  packages/dd-trace/src/azure_metadata.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/debugger/devtools_client/remote_config.js
  packages/dd-trace/src/opentracing/propagation/text_map.js
  packages/dd-trace/test/appsec/iast/analyzers/hardcoded-password-analyzer.spec.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/exporters/common/docker.spec.js
  packages/dd-trace/test/fixtures/esm/esm-hook-test.mjs
  packages/dd-trace/test/opentracing/propagation/text_map.spec.js
  packages/dd-trace/test/telemetry/index.spec.js
  scripts/release/helpers/requirements.js
  yarn.lock
Labels: semver-patch

#4977 fix next test using an incompatible version of react
  scripts/install_plugin_modules.js
Labels: semver-patch

#4979 Bump path-to-regexp from v0.1.10 to v0.1.12
  package.json
  yarn.lock
Labels: semver-patch

#4978 Delete unused benchmark for profiler
  benchmark/profiler/index.js
  benchmark/profiler/server.js
  package.json
Labels: semver-patch

#4974 fix guardrail on node version outside of ssi
  .github/workflows/plugins.yml
  .github/workflows/project.yml
  integration-tests/helpers/index.js
  integration-tests/init.spec.js
  packages/dd-trace/src/guardrails/index.js
Labels: semver-patch

#4972 make sampling rule matching case insensitive
  packages/dd-trace/src/util.js
  packages/dd-trace/test/sampling_rule.spec.js
Labels: semver-patch

#4981 [test optimization] Fix test name extraction in playwright
  integration-tests/ci-visibility/playwright-tests/landing-page-test.js
  integration-tests/playwright/playwright.spec.js
  packages/datadog-instrumentations/src/playwright.js
Labels: ci-app, semver-patch

#4986 Update transitive dependency nanoid to 3.3.8
  yarn.lock
Labels: semver-patch

#4913 Express 5 Instrumentation
  packages/datadog-instrumentations/src/express.js
  packages/datadog-instrumentations/src/helpers/hooks.js
  packages/datadog-instrumentations/src/qs.js
  packages/datadog-instrumentations/src/router.js
  packages/datadog-instrumentations/test/express.spec.js
  packages/datadog-plugin-express/test/index.spec.js
  packages/datadog-plugin-express/test/integration-test/client.spec.js
  packages/datadog-plugin-router/test/index.spec.js
  packages/dd-trace/src/appsec/channels.js
  packages/dd-trace/src/appsec/iast/taint-tracking/plugin.js
  packages/dd-trace/src/appsec/index.js
  packages/dd-trace/test/appsec/attacker-fingerprinting.express.plugin.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/nosql-injection-mongodb-analyzer.express-mongo-sanitize.plugin.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/nosql-injection-mongodb-analyzer.mongoose.plugin.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/nosql-injection-mongodb-analyzer.mquery.plugin.spec.js
  packages/dd-trace/test/appsec/iast/taint-tracking/plugin.spec.js
  packages/dd-trace/test/appsec/iast/taint-tracking/sources/taint-tracking.express.plugin.spec.js
  packages/dd-trace/test/appsec/index.express.plugin.spec.js
  packages/dd-trace/test/appsec/index.spec.js
  packages/dd-trace/test/appsec/rasp/lfi.express.plugin.spec.js
  packages/dd-trace/test/plugins/externals.json
Labels: semver-minor, integration-express

#4990 Update @datadog/native-iast-rewriter to 2.6.0 to support optional chainings
  package.json
  yarn.lock
Labels: semver-minor

#4985 install node22
  benchmark/sirun/Dockerfile
Labels: semver-patch, mergequeue-status: waiting

#4980 Add support for endpoint_counts
  integration-tests/profiler/profiler.spec.js
  packages/dd-trace/src/profiling/exporters/agent.js
  packages/dd-trace/src/profiling/exporters/event_serializer.js
  packages/dd-trace/src/profiling/exporters/file.js
  packages/dd-trace/src/profiling/profiler.js
  packages/dd-trace/src/profiling/profilers/wall.js
  packages/dd-trace/src/profiling/webspan-utils.js
  packages/dd-trace/test/profiling/exporters/file.spec.js
Labels: profiling, semver-minor

#4991 [DI] Handle async errors in mocha tests
  integration-tests/debugger/basic.spec.js
  integration-tests/debugger/snapshot-pruning.spec.js
  integration-tests/debugger/snapshot.spec.js
  integration-tests/helpers/index.js
Labels: semver-patch, dynamic-instrumentation

#4995 Ensure the fake agent in integration tests doesn't swallow exceptions
  integration-tests/debugger/basic.spec.js
  integration-tests/debugger/snapshot-pruning.spec.js
  integration-tests/debugger/snapshot.spec.js
  integration-tests/helpers/fake-agent.js
  integration-tests/helpers/index.js
Labels: semver-patch

#4992 [DI] Improve separation between RC and breakpoint logic
  packages/dd-trace/src/debugger/devtools_client/breakpoints.js
  packages/dd-trace/src/debugger/devtools_client/remote_config.js
Labels: semver-patch, dynamic-instrumentation

#5002 Fix numbers stated in benchmark README.md
  benchmark/sirun/appsec-iast/README.md
  benchmark/sirun/appsec/README.md
  benchmark/sirun/encoding/README.md
  benchmark/sirun/exporting-pipeline/README.md
  benchmark/sirun/log/README.md
  benchmark/sirun/plugin-bluebird/README.md
  benchmark/sirun/plugin-dns/README.md
  benchmark/sirun/plugin-http/README.md
  benchmark/sirun/plugin-net/README.md
  benchmark/sirun/plugin-q/README.md
  benchmark/sirun/spans/README.md
Labels: semver-patch

#5003 Add summary.json to the benchmark .gitignore file
  benchmark/sirun/.gitignore
Labels: semver-patch

#4996 [DI] Improve test setup by allowing breakpoint URL to be dynamic
  integration-tests/debugger/basic.spec.js
  integration-tests/debugger/snapshot-pruning.spec.js
  integration-tests/debugger/target-app/basic.js
  integration-tests/debugger/target-app/snapshot-pruning.js
  integration-tests/debugger/target-app/snapshot.js
  integration-tests/debugger/target-app/unreffed.js
  integration-tests/debugger/unreffed.spec.js
  integration-tests/debugger/utils.js
  packages/dd-trace/test/debugger/devtools_client/utils.js
Labels: semver-patch, dynamic-instrumentation

#4989 Add Support for DD_DOGSTATSD_HOST
  packages/dd-trace/src/config.js
  packages/dd-trace/test/config.spec.js
Labels: semver-minor

#5005 update pyenv
  benchmark/sirun/Dockerfile
Labels: semver-patch

#4998 [DI] Add support for sampling
  integration-tests/debugger/basic.spec.js
  packages/dd-trace/src/debugger/devtools_client/breakpoints.js
  packages/dd-trace/src/debugger/devtools_client/defaults.js
  packages/dd-trace/src/debugger/devtools_client/index.js
Labels: semver-patch, dynamic-instrumentation

#3019 clarify startup benchmark
  benchmark/sirun/startup/README.md
Labels: docs, semver-patch

#4969 remove dependency on msgpack-lite
  LICENSE-3rdparty.csv
  package.json
  packages/dd-trace/src/datastreams/processor.js
  packages/dd-trace/src/datastreams/writer.js
  packages/dd-trace/src/encode/0.4.js
  packages/dd-trace/src/encode/agentless-ci-visibility.js
  packages/dd-trace/src/encode/coverage-ci-visibility.js
  packages/dd-trace/src/encode/span-stats.js
  packages/dd-trace/src/msgpack/chunk.js
  packages/dd-trace/src/msgpack/encoder.js
  packages/dd-trace/src/msgpack/index.js
  packages/dd-trace/test/datastreams/processor.spec.js
  packages/dd-trace/test/encode/agentless-ci-visibility.spec.js
  packages/dd-trace/test/msgpack/encoder.spec.js
Labels: semver-patch

#4633 speed up shimmer by about 50x
  packages/datadog-shimmer/src/shimmer.js
Labels: semver-patch

#5001 telemetry: increment .count when deduping telemetry logs
  packages/dd-trace/src/telemetry/logs/log-collector.js
  packages/dd-trace/src/util.js
  packages/dd-trace/test/telemetry/logs/log-collector.spec.js
Labels: semver-patch

#5009 copy prototypes in shimmer where necessary
  packages/datadog-shimmer/src/shimmer.js
Labels: semver-patch

#5008 [DI] Clean up all logs emitted by the debugger
  packages/dd-trace/src/debugger/devtools_client/breakpoints.js
  packages/dd-trace/src/debugger/devtools_client/config.js
  packages/dd-trace/src/debugger/devtools_client/index.js
  packages/dd-trace/src/debugger/devtools_client/remote_config.js
  packages/dd-trace/src/debugger/devtools_client/status.js
  packages/dd-trace/src/debugger/index.js
Labels: semver-patch, dynamic-instrumentation

#5011 Fix flaky dns and net timeline event tests
  integration-tests/profiler/profiler.spec.js
Labels: dev/testing, profiling, semver-patch

#4999 [DI] Improve sampling tests
  integration-tests/debugger/basic.spec.js
  integration-tests/debugger/target-app/basic.js
  integration-tests/debugger/utils.js
Labels: semver-patch, dynamic-instrumentation

#4975 run benchmarks also on node 20 and 22
  .gitlab/benchmarks.yml
Labels: semver-patch

#4961 use gc observer for gc runtime metrics when available
  packages/dd-trace/src/runtime_metrics.js
Labels: semver-patch

#5013 telemetry: make count logic faster
  packages/dd-trace/src/telemetry/logs/index.js
  packages/dd-trace/src/telemetry/logs/log-collector.js
  packages/dd-trace/test/telemetry/logs/log-collector.spec.js
Labels: semver-patch

#4639 Verify yaml
  .github/workflows/appsec.yml
  .github/workflows/plugins.yml
  .github/workflows/project.yml
  LICENSE-3rdparty.csv
  package.json
  packages/datadog-instrumentations/src/aerospike.js
  packages/datadog-instrumentations/src/next.js
  scripts/verify-ci-config.js
  yarn.lock
Labels: semver-patch

#5017 Test aerospike node 16 with ubuntu-22.04 (#5017)
  .github/workflows/plugins.yml
Labels: semver-patch

#5010 Upgrade iast rewriter version to 2.6.1
  package.json
  yarn.lock
Labels: semver-patch, asm-iast

#4945 Add some checks to avoid runtime errors
  packages/datadog-plugin-avsc/src/schema_iterator.js
  packages/datadog-plugin-grpc/src/client.js
  packages/dd-trace/src/opentracing/propagation/text_map.js
  packages/dd-trace/src/plugins/tracing.js
  packages/dd-trace/src/profiling/profilers/event_plugins/event.js
Labels: semver-patch

#4674 New automatic user event collection
  docs/test.ts
  index.d.ts
  packages/datadog-instrumentations/src/passport-http.js
  packages/datadog-instrumentations/src/passport-local.js
  packages/datadog-instrumentations/src/passport-utils.js
  packages/datadog-instrumentations/test/passport-http.spec.js
  packages/datadog-instrumentations/test/passport-local.spec.js
  packages/datadog-instrumentations/test/passport-utils.spec.js
  packages/dd-trace/src/appsec/addresses.js
  packages/dd-trace/src/appsec/index.js
  packages/dd-trace/src/appsec/passport.js
  packages/dd-trace/src/appsec/remote_config/capabilities.js
  packages/dd-trace/src/appsec/remote_config/index.js
  packages/dd-trace/src/appsec/sdk/track_event.js
  packages/dd-trace/src/appsec/telemetry.js
  packages/dd-trace/src/appsec/user_tracking.js
  packages/dd-trace/src/config.js
  packages/dd-trace/test/appsec/index.spec.js
  packages/dd-trace/test/appsec/passport.spec.js
  packages/dd-trace/test/appsec/remote_config/index.spec.js
  packages/dd-trace/test/appsec/sdk/track_event.spec.js
  packages/dd-trace/test/appsec/telemetry.spec.js
  packages/dd-trace/test/appsec/user_tracking.spec.js
  packages/dd-trace/test/config.spec.js
Labels: asm-waf, semver-minor

#5020 consolidate instances of `loadInst`, so code isn't repeated
  packages/dd-trace/test/setup/helpers/load-inst.js
  packages/dd-trace/test/setup/mocha.js
  scripts/install_plugin_modules.js
  scripts/verify-ci-config.js
Labels: semver-patch

#5023 repo: mandatory issue templates (AIDM-422)
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yaml
Labels: semver-patch

#5022 update native-metrics to 3.1.0
  package.json
  yarn.lock
Labels: semver-patch

#5026 enable crashtracking by default outside of ssi
  package.json
  packages/dd-trace/src/config.js
  packages/dd-trace/test/config.spec.js
  yarn.lock
Labels: semver-minor

#5006 [test optimization] [SDTEST-1332] Fetch `di_enabled` flag
  integration-tests/cucumber/cucumber.spec.js
  integration-tests/jest/jest.spec.js
  integration-tests/mocha/mocha.spec.js
  integration-tests/vitest/vitest.spec.js
  packages/datadog-instrumentations/src/jest.js
  packages/datadog-instrumentations/src/vitest.js
  packages/datadog-plugin-cucumber/src/index.js
  packages/datadog-plugin-jest/src/index.js
  packages/datadog-plugin-mocha/src/index.js
  packages/datadog-plugin-vitest/src/index.js
  packages/dd-trace/src/ci-visibility/exporters/ci-visibility-exporter.js
  packages/dd-trace/src/ci-visibility/requests/get-library-configuration.js
Labels: ci-app, semver-patch

#5035 [DI] Associate probe results with active span
  integration-tests/debugger/basic.spec.js
  packages/dd-trace/src/debugger/devtools_client/index.js
  packages/dd-trace/src/debugger/devtools_client/send.js
Labels: semver-minor, dynamic-instrumentation

#5036 [DI] Improve trace/span-id probe results tests
  integration-tests/debugger/basic.spec.js
  integration-tests/debugger/utils.js
Labels: semver-patch, dynamic-instrumentation

#4904 Support tainted strings coming from database for SQLi, SSTi and Code injection
  docs/test.ts
  index.d.ts
  packages/datadog-instrumentations/src/pg.js
  packages/datadog-instrumentations/src/sequelize.js
  packages/dd-trace/src/appsec/iast/analyzers/code-injection-analyzer.js
  packages/dd-trace/src/appsec/iast/analyzers/injection-analyzer.js
  packages/dd-trace/src/appsec/iast/analyzers/sql-injection-analyzer.js
  packages/dd-trace/src/appsec/iast/analyzers/template-injection-analyzer.js
  packages/dd-trace/src/appsec/iast/iast-plugin.js
  packages/dd-trace/src/appsec/iast/taint-tracking/index.js
  packages/dd-trace/src/appsec/iast/taint-tracking/plugin.js
  packages/dd-trace/src/appsec/iast/taint-tracking/source-types.js
  packages/dd-trace/src/config.js
  packages/dd-trace/test/appsec/iast/analyzers/code-injection-analyzer.express.plugin.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/ldap-injection-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/path-traversal-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/sql-injection-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/template-injection-analyzer.handlebars.plugin.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/template-injection-analyzer.pug.plugin.spec.js
  packages/dd-trace/test/appsec/iast/taint-tracking/plugin.spec.js
  packages/dd-trace/test/appsec/iast/taint-tracking/sources/sql_row.pg.plugin.spec.js
  packages/dd-trace/test/appsec/iast/taint-tracking/sources/sql_row.sequelize.plugin.spec.js
  packages/dd-trace/test/appsec/iast/utils.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/fixtures/telemetry/config_norm_rules.json
  packages/dd-trace/test/plugins/externals.json
Labels: semver-minor

#5029 set node types minimum version to oldest
  package.json
  yarn.lock
Labels: semver-patch

#4912 [serverless] Add DynamoDB Span Pointers
  packages/datadog-plugin-aws-sdk/src/services/dynamodb.js
  packages/datadog-plugin-aws-sdk/src/services/s3.js
  packages/datadog-plugin-aws-sdk/src/util.js
  packages/datadog-plugin-aws-sdk/test/dynamodb.spec.js
  packages/datadog-plugin-aws-sdk/test/util.spec.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/constants.js
  packages/dd-trace/src/util.js
  packages/dd-trace/test/plugins/externals.json
  packages/dd-trace/test/util.spec.js
Labels: semver-minor

#5039 fix runtime metrics test not waiting for gc observer to run
  packages/dd-trace/src/runtime_metrics.js
  packages/dd-trace/test/runtime_metrics.spec.js
Labels: semver-patch

#5027 repo: ask for config details on bug creation
  .github/ISSUE_TEMPLATE/bug_report.yaml
Labels: semver-patch

#5041 update type tests to typescript 4.9.4
  docs/package.json
  docs/yarn.lock
Labels: semver-patch

#5037 [DI] Add test for associating probes with 128 bit span ids
  integration-tests/debugger/basic.spec.js
Labels: semver-patch, dynamic-instrumentation

#4965 Add filesystem events to the timeline
  integration-tests/profiler/fstest.js
  integration-tests/profiler/profiler.spec.js
  packages/datadog-instrumentations/src/fs.js
  packages/dd-trace/src/profiling/profilers/event_plugins/event.js
  packages/dd-trace/src/profiling/profilers/event_plugins/fs.js
  packages/dd-trace/src/profiling/profilers/events.js
Labels: profiling, semver-minor

#5047 fix invalid output for log.trace
  packages/dd-trace/src/log/index.js
  packages/dd-trace/src/log/writer.js
  packages/dd-trace/src/opentracing/span.js
  packages/dd-trace/test/log.spec.js
Labels: semver-patch

#5042 [DI] Attach ddtags to probe results
  integration-tests/debugger/basic.spec.js
  integration-tests/debugger/ddtags.spec.js
  integration-tests/debugger/utils.js
  integration-tests/helpers/fake-agent.js
  packages/dd-trace/src/debugger/devtools_client/send.js
Labels: semver-minor, dynamic-instrumentation

#4960 [MLOB-1942] fix(llmobs): auto-annotations for wrapped functions happen after manual annotations
  packages/dd-trace/src/llmobs/sdk.js
  packages/dd-trace/test/llmobs/sdk/index.spec.js
Labels: semver-patch

#5057 support aerospike 6
  .github/workflows/plugins.yml
  packages/datadog-instrumentations/src/aerospike.js
Labels: semver-minor
