Repository DataDog/dd-trace-js, pull requests merged in 2025-06, with the labels that each got.

#5801 Make get-port wait between retries in tests
  packages/dd-trace/test/setup/core.js
Labels: semver-patch

#5734 chore: remove async storage from rabbitmq integrations
  packages/datadog-instrumentations/src/amqp10.js
  packages/datadog-instrumentations/src/amqplib.js
  packages/datadog-instrumentations/src/rhea.js
  packages/datadog-plugin-amqp10/src/consumer.js
  packages/datadog-plugin-amqp10/src/producer.js
  packages/datadog-plugin-amqplib/src/client.js
  packages/datadog-plugin-amqplib/src/consumer.js
  packages/datadog-plugin-amqplib/src/producer.js
  packages/datadog-plugin-rhea/src/consumer.js
  packages/datadog-plugin-rhea/src/producer.js
  packages/dd-trace/src/plugins/consumer.js
  packages/dd-trace/src/plugins/inbound.js
  packages/dd-trace/src/plugins/producer.js
Labels: semver-minor

#5805 Improve agent.assertFirstTraceSpan to accept an object
  integration-tests/helpers/index.js
  packages/datadog-plugin-aerospike/test/index.spec.js
  packages/datadog-plugin-cassandra-driver/test/index.spec.js
  packages/datadog-plugin-ioredis/test/index.spec.js
  packages/datadog-plugin-memcached/test/index.spec.js
  packages/datadog-plugin-mysql/test/index.spec.js
  packages/datadog-plugin-mysql2/test/index.spec.js
  packages/datadog-plugin-opensearch/test/index.spec.js
  packages/dd-trace/test/plugins/agent.js
Labels: semver-patch

#5808 Test: Ensure yarn.lock doesn't contain duplicates
  .github/workflows/yarn-dedupe.yml
  LICENSE-3rdparty.csv
  package.json
  scripts/verify-ci-config.js
  yarn.lock
Labels: semver-patch

#5809 [test optimization] Fix crash when `error` is empty and failed test replay is enabled
  packages/datadog-plugin-vitest/src/index.js
  packages/dd-trace/src/plugins/ci_plugin.js
Labels: ci-app, semver-patch

#5703 tracing: remove asyncresource from kafka instrumentations
  .github/workflows/appsec.yml
  packages/datadog-instrumentations/src/confluentinc-kafka-javascript.js
  packages/datadog-instrumentations/src/kafkajs.js
  packages/datadog-plugin-confluentinc-kafka-javascript/test/index.spec.js
  packages/datadog-plugin-kafkajs/src/batch-consumer.js
  packages/datadog-plugin-kafkajs/src/consumer.js
  packages/datadog-plugin-kafkajs/src/producer.js
  packages/datadog-plugin-kafkajs/test/index.spec.js
  packages/dd-trace/src/appsec/iast/context/context-plugin.js
  packages/dd-trace/src/appsec/iast/taint-tracking/plugins/kafka.js
  packages/dd-trace/src/plugins/outbound.js
  packages/dd-trace/test/appsec/iast/context/context-plugin.spec.js
Labels: semver-minor

#5796 chore(tracing): remove asyncstorage from google cloud pub/sub
  packages/datadog-instrumentations/src/confluentinc-kafka-javascript.js
  packages/datadog-instrumentations/src/google-cloud-pubsub.js
  packages/datadog-plugin-google-cloud-pubsub/src/client.js
  packages/datadog-plugin-google-cloud-pubsub/src/consumer.js
  packages/datadog-plugin-google-cloud-pubsub/src/producer.js
Labels: semver-minor

#5818 split playwright ci by version
  .github/workflows/test-optimization.yml
  integration-tests/playwright/playwright.spec.js
Labels: semver-patch

#5820 Enable profiles' zstd compression on Node.js <23.8.0
  package.json
  packages/dd-trace/src/profiling/config.js
  packages/dd-trace/src/profiling/profiler.js
  packages/dd-trace/test/profiling/config.spec.js
  packages/dd-trace/test/profiling/profiler.spec.js
  yarn.lock
Labels: profiling, semver-minor

#5821 [DI] Support non-normalized source path names in source maps
  eslint.config.mjs
  integration-tests/debugger/source-map-support.spec.js
  integration-tests/debugger/target-app/source-map-support/bundle.js
  integration-tests/debugger/target-app/source-map-support/bundle.js.map
  integration-tests/debugger/target-app/source-map-support/hello/world.js
  integration-tests/debugger/target-app/source-map-support/hello/world.js.map
  integration-tests/debugger/target-app/source-map-support/hello/world.ts
  integration-tests/debugger/target-app/source-map-support/scripts/build-bundle.sh
  integration-tests/debugger/target-app/source-map-support/scripts/build-typescript.sh
  integration-tests/debugger/target-app/source-map-support/typescript.js
  integration-tests/debugger/target-app/source-map-support/typescript.js.map
  integration-tests/debugger/target-app/source-map-support/typescript.ts
  packages/dd-trace/src/debugger/devtools_client/state.js
  packages/dd-trace/test/debugger/devtools_client/state.spec.js
Labels: semver-patch

#5822 ci(openai): remove flaky configuration test
  packages/datadog-plugin-openai/test/index.spec.js
Labels: semver-patch

#5824 Fix iast overhead controller flaky test
  packages/dd-trace/test/appsec/iast/overhead-controller.spec.js
  packages/dd-trace/test/appsec/iast/utils.js
Labels: semver-patch

#5840 fix remaining mysql/mariadb async resource usage
  packages/datadog-instrumentations/src/mariadb.js
  packages/datadog-instrumentations/src/mysql.js
  packages/datadog-plugin-mysql/src/index.js
Labels: semver-patch

#5811 [test optimization] Remove usage of async resource from jest
  packages/datadog-instrumentations/src/jest.js
Labels: ci-app, semver-patch

#5833 [test optimization] Remove async resource usage from cucumber
  integration-tests/ci-visibility/features/support/steps.js
  integration-tests/cucumber/cucumber.spec.js
  packages/datadog-instrumentations/src/cucumber.js
Labels: ci-app, semver-patch

#5842 Fix startuplog crashing by serializing bigint
  packages/dd-trace/src/sampler.js
  packages/dd-trace/src/startup-log.js
  packages/dd-trace/test/sampler.spec.js
  packages/dd-trace/test/startup-log.spec.js
Labels: semver-patch

#5836 Remove Header Injection vulnerability detection
  packages/dd-trace/src/appsec/iast/analyzers/analyzers.js
  packages/dd-trace/src/appsec/iast/analyzers/header-injection-analyzer.js
  packages/dd-trace/src/appsec/iast/vulnerabilities-formatter/evidence-redaction/sensitive-analyzers/header-sensitive-analyzer.js
  packages/dd-trace/src/appsec/iast/vulnerabilities-formatter/evidence-redaction/sensitive-handler.js
  packages/dd-trace/src/appsec/iast/vulnerabilities.js
  packages/dd-trace/test/appsec/iast/analyzers/header-injection.express.plugin.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/resources/set-header-function.js
  packages/dd-trace/test/appsec/iast/vulnerability-formatter/index.spec.js
Labels: semver-minor, asm-iast

#5844 [test optimization] Fix test optimization tests in v5 release line
  ci/cypress/plugin.js
  ci/cypress/polyfills.js
  integration-tests/ci-visibility/playwright-tests/landing-page-test.js
  integration-tests/playwright/playwright.spec.js
  packages/datadog-plugin-cypress/test/app/cypress/plugins/index.js
  packages/datadog-plugin-cypress/test/index.spec.js
Labels: ci-app, semver-patch

#5815 Baggage update
  packages/dd-trace/src/baggage.js
  packages/dd-trace/src/opentracing/propagation/text_map.js
  packages/dd-trace/test/opentracing/propagation/text_map.spec.js
  packages/dd-trace/test/proxy.spec.js
Labels: semver-patch

#5849 move cypress tests from apm integrations to test optimization
  .github/workflows/apm-integrations.yml
  .github/workflows/test-optimization.yml
Labels: semver-patch

#5853 test: destroy active connections when stopping fake agent
  integration-tests/helpers/fake-agent.js
Labels: semver-patch

#5848 test: reduce usage of get-port dependency
  integration-tests/appsec/data-collection.spec.js
  integration-tests/appsec/data-collection/index.js
  integration-tests/appsec/esm-app/index.mjs
  integration-tests/appsec/esm-security-controls/index.mjs
  integration-tests/appsec/graphql.spec.js
  integration-tests/appsec/iast.esm-security-controls.spec.js
  integration-tests/appsec/iast.esm.spec.js
  integration-tests/appsec/index.spec.js
  integration-tests/debugger/re-evaluation.spec.js
  integration-tests/debugger/source-map-support.spec.js
  integration-tests/debugger/target-app/basic.js
  integration-tests/debugger/target-app/re-evaluation/index.js
  integration-tests/debugger/target-app/re-evaluation/unique-filename.js
  integration-tests/debugger/target-app/redact.js
  integration-tests/debugger/target-app/snapshot-pruning.js
  integration-tests/debugger/target-app/snapshot.js
  integration-tests/debugger/target-app/source-map-support/bundle.js
  integration-tests/debugger/target-app/source-map-support/bundle.js.map
  integration-tests/debugger/target-app/source-map-support/minify.js
  integration-tests/debugger/target-app/source-map-support/minify.min.js
  integration-tests/debugger/target-app/source-map-support/minify.min.js.map
  integration-tests/debugger/target-app/source-map-support/scripts/build-all.sh
  integration-tests/debugger/target-app/source-map-support/typescript.js
  integration-tests/debugger/target-app/source-map-support/typescript.js.map
  integration-tests/debugger/target-app/source-map-support/typescript.ts
  integration-tests/debugger/target-app/template.js
  integration-tests/debugger/target-app/unreffed.js
  integration-tests/debugger/utils.js
  integration-tests/graphql/index.js
  integration-tests/helpers/index.js
  packages/dd-trace/test/appsec/iast/code_injection.integration.spec.js
  packages/dd-trace/test/appsec/iast/overhead-controller.integration.spec.js
  packages/dd-trace/test/appsec/iast/resources/eval.js
  packages/dd-trace/test/appsec/iast/resources/overhead-controller.js
  packages/dd-trace/test/appsec/iast/resources/vm.js
  packages/dd-trace/test/appsec/rasp/command_injection.integration.spec.js
  packages/dd-trace/test/appsec/rasp/lfi.integration.express.plugin.spec.js
  packages/dd-trace/test/appsec/rasp/rasp-metrics.integration.spec.js
  packages/dd-trace/test/appsec/rasp/resources/lfi-app/index.js
  packages/dd-trace/test/appsec/rasp/resources/postgress-app/index.js
  packages/dd-trace/test/appsec/rasp/resources/shi-app/index.js
  packages/dd-trace/test/appsec/rasp/sql_injection.integration.pg.plugin.spec.js
  packages/dd-trace/test/appsec/resources/index.js
  packages/dd-trace/test/appsec/waf-metrics.integration.spec.js
  packages/dd-trace/test/remote_config/rc-client_id.spec.js
  packages/dd-trace/test/remote_config/resources/index.js
Labels: semver-patch

#5847 Fix iast mysql2
  packages/dd-trace/src/appsec/iast/analyzers/sql-injection-analyzer.js
  packages/dd-trace/test/appsec/iast/analyzers/resources/mysql2-vulnerable-method.js
  packages/dd-trace/test/appsec/iast/analyzers/sql-injection-analyzer.mysql2.plugin.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/sql-injection-analyzer.spec.js
Labels: semver-patch

#5857 [test-optimization] [SDTEST-2144] Fix `it.failing` in combination with EFD
  integration-tests/ci-visibility/jest/failing-test.js
  integration-tests/jest/jest.spec.js
  packages/datadog-instrumentations/src/jest.js
Labels: bug, ci-app, semver-patch

#5862 [test-optimization] [SDTEST-303] Unblock CI due to `Jest@30` release
  .github/workflows/test-optimization.yml
  scripts/verify-ci-config.js
Labels: ci-app, semver-patch

#5863 test: speed up DI integration tests
  integration-tests/debugger/basic.spec.js
  integration-tests/debugger/utils.js
Labels: semver-patch

#5839 [SVLS-5649] Add HTTP Context Propagation to Azure Functions
  packages/datadog-plugin-azure-functions/src/index.js
  packages/datadog-plugin-azure-functions/test/integration-test/client.spec.js
  packages/datadog-plugin-azure-functions/test/integration-test/fixtures/src/functions/server.mjs
Labels: semver-patch, serverless

#5874 chore: temporarily restrict yarn audit to prod deps only in CI
  package.json
Labels: semver-patch

#4581 [test-optimization] [SDTEST-303] Fix jest@30 release
  .github/workflows/test-optimization.yml
  integration-tests/ci-visibility/jest-custom-test-sequencer.js
  integration-tests/ci-visibility/run-jest.js
  integration-tests/jest/jest.spec.js
  packages/datadog-instrumentations/src/jest.js
  scripts/verify-ci-config.js
Labels: ci-app, semver-patch

#5877 Fix and improve esbuild and add it to the CI
  .github/workflows/platform.yml
  integration-tests/esbuild/index.spec.js
  integration-tests/esbuild/package.json
  packages/dd-trace/src/exporters/agent/writer.js
  packages/dd-trace/src/profiling/profilers/events.js
Labels: semver-patch

#5878 fix missing octokit dependency for flakiness report workflow
  .github/workflows/flakiness.yml
Labels: semver-patch

#5374 Implement Config Chaining
  integration-tests/startup/index.js
  integration-tests/telemetry.spec.js
  packages/datadog-core/src/utils/src/get.js
  packages/datadog-core/src/utils/src/has.js
  packages/datadog-core/test/utils/src/get.spec.js
  packages/datadog-core/test/utils/src/has.spec.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/telemetry/telemetry.js
  packages/dd-trace/test/telemetry/index.spec.js
Labels: semver-minor

#5880 Reduce false positives when unvalidated redirect vulnerability is detected
  packages/dd-trace/src/appsec/iast/analyzers/unvalidated-redirect-analyzer.js
  packages/dd-trace/src/appsec/iast/taint-tracking/source-types.js
  packages/dd-trace/test/appsec/iast/analyzers/unvalidated-redirect-analyzer.express.plugin.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/vulnerability-analyzer.express.plugin.spec.js
Labels: semver-minor, asm-iast

#5721 chore(ssi): send injection and instrumentation telemetry
  init.js
  integration-tests/helpers/index.js
  integration-tests/init.spec.js
  integration-tests/init/instrument.js
  integration-tests/init/instrument.mjs
  integration-tests/init/trace.js
  integration-tests/package-guardrails.spec.js
  integration-tests/package-guardrails/index.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/constants.js
  packages/dd-trace/src/guardrails/index.js
  packages/dd-trace/src/telemetry/telemetry.js
  packages/dd-trace/test/config.spec.js
Labels: semver-minor

#5892 add explicit main ref when checking out system tests in workflow
  .github/workflows/system-tests.yml
Labels: semver-patch

#5890 Fix router not working with deeply nested middleware
  packages/datadog-instrumentations/src/router.js
  packages/datadog-plugin-router/test/index.spec.js
Labels: semver-patch

#5876 [test-optimization] [SDTEST-2163] Check framework version in capabilities tagging
  integration-tests/playwright/playwright.spec.js
  packages/datadog-instrumentations/src/cucumber.js
  packages/datadog-instrumentations/src/jest.js
  packages/datadog-instrumentations/src/mocha/main.js
  packages/datadog-instrumentations/src/playwright.js
  packages/datadog-instrumentations/src/vitest.js
  packages/datadog-plugin-cypress/src/cypress-plugin.js
  packages/dd-trace/src/plugins/ci_plugin.js
  packages/dd-trace/src/plugins/util/test.js
Labels: ci-app, semver-patch

#5902 Revert "Update to libdatadog-nodejs 0.7.0 (#5896)"
  package.json
  yarn.lock
Labels: semver-patch

#5897 [test optimization] Update test optimization spec
  packages/dd-trace/src/plugins/util/ci.js
  packages/dd-trace/src/plugins/util/tags.js
  packages/dd-trace/src/supported-configurations.json
  packages/dd-trace/test/plugins/util/ci-env/appveyor.json
  packages/dd-trace/test/plugins/util/ci-env/azurepipelines.json
  packages/dd-trace/test/plugins/util/ci-env/bitbucket.json
  packages/dd-trace/test/plugins/util/ci-env/bitrise.json
  packages/dd-trace/test/plugins/util/ci-env/buddy.json
  packages/dd-trace/test/plugins/util/ci-env/buildkite.json
  packages/dd-trace/test/plugins/util/ci-env/circleci.json
  packages/dd-trace/test/plugins/util/ci-env/codefresh.json
  packages/dd-trace/test/plugins/util/ci-env/drone.json
  packages/dd-trace/test/plugins/util/ci-env/github.json
  packages/dd-trace/test/plugins/util/ci-env/gitlab.json
  packages/dd-trace/test/plugins/util/ci-env/jenkins.json
  packages/dd-trace/test/plugins/util/ci-env/teamcity.json
  packages/dd-trace/test/plugins/util/ci-env/travisci.json
  packages/dd-trace/test/plugins/util/ci-env/usersupplied.json
Labels: ci-app, semver-minor

#5898 [test optimization] Improve flakiness of performance overhead test
  .github/workflows/test-optimization.yml
  benchmark/e2e-test-optimization/benchmark-run.js
  package.json
Labels: ci-app, semver-patch

#5899 test: sort config value assertions
  packages/dd-trace/test/config.spec.js
Labels: semver-patch

#5888 Improve support for esbuild + esm with DD_BUILD_ESM env var
  integration-tests/esbuild/build-and-run.esm-patched-const-banner.mjs
  integration-tests/esbuild/build-and-run.esm-patched-global-banner.mjs
  integration-tests/esbuild/build-and-run.esm-relying-in-extension.mjs
  integration-tests/esbuild/build-and-run.esm-relying-in-format.mjs
  integration-tests/esbuild/build-and-run.esm-relying-in-out-extension.mjs
  integration-tests/esbuild/build-and-run.esm-unrelated-js-banner.mjs
  integration-tests/esbuild/build.esm.common-config.js
  integration-tests/esbuild/build.esm.mjs
  integration-tests/esbuild/index.spec.js
  integration-tests/esbuild/package.json
  packages/datadog-esbuild/index.js
Labels: semver-patch

#5907 fix typo
  scripts/flakiness.mjs
Labels: semver-patch

#5894 Support schema extraction in fastify response objects
  packages/datadog-instrumentations/src/fastify.js
  packages/dd-trace/src/appsec/channels.js
  packages/dd-trace/src/appsec/index.js
  packages/dd-trace/test/appsec/index.fastify.plugin.spec.js
Labels: semver-minor, appsec

#5911 wrapCommandQueueClass fix super call
  packages/datadog-instrumentations/src/redis.js
  packages/datadog-plugin-redis/test/client.spec.js
Labels: semver-patch

#5912 fix: Add mongo heartbeatEnabled param to tracer entrypoint
  index.d.ts
Labels: semver-patch, integration-mongodb

#5901 Detect destructuring process.env and use the config-helper instead
  eslint-rules/eslint-process-env.mjs
  packages/dd-trace/src/plugins/util/ci.js
  packages/dd-trace/src/supported-configurations.json
  packages/dd-trace/test/plugins/util/ci-env/azurepipelines.json
  packages/dd-trace/test/plugins/util/ci-env/bitbucket.json
  packages/dd-trace/test/plugins/util/ci-env/bitrise.json
  packages/dd-trace/test/plugins/util/ci-env/buddy.json
  packages/dd-trace/test/plugins/util/ci-env/buildkite.json
  packages/dd-trace/test/plugins/util/ci-env/circleci.json
  packages/dd-trace/test/plugins/util/ci-env/gitlab.json
  packages/dd-trace/test/plugins/util/ci-env/jenkins.json
  packages/dd-trace/test/plugins/util/ci-env/usersupplied.json
  packages/dd-trace/test/plugins/util/test-environment.spec.js
Labels: semver-patch

#5917 Clean up code in Crashtracker class
  packages/dd-trace/src/crashtracking/crashtracker.js
Labels: semver-patch

#5919 ci(langchain): skip latest langchain in ci until mocking is fixed
  packages/datadog-plugin-langchain/test/index.spec.js
  packages/dd-trace/test/llmobs/plugins/langchain/index.spec.js
Labels: semver-patch

#5922 [DI] Improve internal timer performance
  packages/dd-trace/src/debugger/devtools_client/state.js
Labels: semver-patch, dynamic-instrumentation

#5924 Code cleanup: Improve calculation of number of bytes in string
  packages/dd-trace/src/llmobs/writers/spans.js
Labels: semver-patch

#5926 docs: fix bug in docs related to running tests
  CONTRIBUTING.md
Labels: semver-patch

#5605 Support for Prisma client library
  .github/workflows/apm-integrations.yml
  docs/API.md
  docs/add-redirects.sh
  docs/test.ts
  index.d.ts
  packages/datadog-instrumentations/src/helpers/hooks.js
  packages/datadog-instrumentations/src/prisma.js
  packages/datadog-plugin-next/test/next.config.js
  packages/datadog-plugin-prisma/src/client.js
  packages/datadog-plugin-prisma/src/engine.js
  packages/datadog-plugin-prisma/src/index.js
  packages/datadog-plugin-prisma/test/index.spec.js
  packages/datadog-plugin-prisma/test/naming.js
  packages/datadog-plugin-prisma/test/schema.prisma
  packages/dd-trace/src/plugins/index.js
  packages/dd-trace/src/service-naming/schemas/v0/storage.js
  packages/dd-trace/src/service-naming/schemas/v1/storage.js
  packages/dd-trace/src/supported-configurations.json
  packages/dd-trace/test/plugins/externals.json
  scripts/install_plugin_modules.js
Labels: semver-minor

#5859 Enable log injection by default for structured loggers
  integration-tests/automatic-log-submission.spec.js
  integration-tests/pino.spec.js
  integration-tests/telemetry.spec.js
  packages/datadog-plugin-bunyan/src/index.js
  packages/datadog-plugin-bunyan/test/index.spec.js
  packages/datadog-plugin-pino/src/index.js
  packages/datadog-plugin-pino/test/index.spec.js
  packages/datadog-plugin-winston/src/index.js
  packages/datadog-plugin-winston/test/index.spec.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/plugins/log_plugin.js
  packages/dd-trace/src/plugins/structured_log_plugin.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/plugins/log_plugin.spec.js
Labels: semver-minor

#5939 Update one pipeline reference
  .gitlab/one-pipeline.locked.yml
Labels: dev/tooling, semver-patch

#5937 Clear internal timer when manually flushing agent exporter
  packages/dd-trace/src/exporters/agent/index.js
Labels: semver-patch

#5931 Bump the gh-actions-packages group across 6 directories with 6 updates
  .github/actions/install/branch-diff/action.yml
  .github/actions/node/action.yml
  .github/actions/plugins/test-and-upstream/action.yml
  .github/actions/plugins/test/action.yml
  .github/actions/plugins/upstream/action.yml
  .github/workflows/apm-capabilities.yml
  .github/workflows/apm-integrations.yml
  .github/workflows/appsec.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/debugger.yml
  .github/workflows/lambda.yml
  .github/workflows/llmobs.yml
  .github/workflows/platform.yml
  .github/workflows/profiling.yml
  .github/workflows/project.yml
  .github/workflows/release-latest.yml
  .github/workflows/release-proposal.yml
  .github/workflows/test-optimization.yml
Labels: semver-patch

#5935 remove async storage from elasticsearch instrumentation
  packages/datadog-instrumentations/src/elasticsearch.js
  packages/datadog-instrumentations/src/sharedb.js
  packages/datadog-plugin-elasticsearch/src/index.js
  packages/datadog-plugin-sharedb/src/index.js
Labels: semver-patch

#5942 Make profiler integration tests more lenient
  integration-tests/profiler/profiler.spec.js
Labels: dev/testing, profiling, semver-patch

#5936 remove async storage from memcached instrumentation
  packages/datadog-instrumentations/src/memcached.js
  packages/datadog-plugin-memcached/src/index.js
  packages/dd-trace/src/plugins/cache.js
Labels: semver-patch

#5609 add disabled by default integration concept
  packages/datadog-instrumentations/src/confluentinc-kafka-javascript.js
  packages/datadog-instrumentations/src/helpers/register.js
  packages/datadog-instrumentations/test/helpers/register.spec.js
  packages/datadog-plugin-confluentinc-kafka-javascript/src/batch-consumer.js
  packages/datadog-plugin-confluentinc-kafka-javascript/src/consumer.js
  packages/datadog-plugin-confluentinc-kafka-javascript/src/index.js
  packages/datadog-plugin-confluentinc-kafka-javascript/src/producer.js
  packages/datadog-plugin-confluentinc-kafka-javascript/test/index.spec.js
  packages/dd-trace/src/plugin_manager.js
  packages/dd-trace/src/service-naming/schemas/v0/messaging.js
  packages/dd-trace/src/service-naming/schemas/v1/messaging.js
  packages/dd-trace/src/supported-configurations.json
  packages/dd-trace/src/util.js
  packages/dd-trace/test/plugins/plugin-structure.spec.js
Labels: semver-minor

#5950 add documentation note about how to add instrumentation tests to CI [LANGPLAT-352]
  CONTRIBUTING.md
Labels: semver-patch

#5944 [test optimization] Fix playwright tests in v5
  packages/dd-trace/src/plugins/util/test.js
Labels: ci-app, semver-patch

#5903 Remove SSI profiler heuristics telemetry
  integration-tests/profiler/profiler.spec.js
  packages/dd-trace/src/profiler.js
  packages/dd-trace/src/profiling/exporter_cli.js
  packages/dd-trace/src/profiling/ssi-heuristics.js
  packages/dd-trace/src/profiling/ssi-telemetry-mock-profiler.js
  packages/dd-trace/src/proxy.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/profiling/ssi-heuristics.spec.js
Labels: profiling, semver-minor

#5957 reduce output size of flakiness report
  scripts/flakiness.mjs
Labels: semver-patch

#5964 ci(openai): resolve incorrect merge resolution for moderations test
  packages/datadog-plugin-openai/test/index.spec.js
Labels: semver-patch

#5965 ci(openai): resolve further test conflicts from bumping openai support and merging major changes
  packages/datadog-plugin-openai/test/index.spec.js
Labels: semver-patch

#5962 test: load helpers directly instead of using globals
  eslint.config.mjs
  packages/datadog-plugin-aerospike/test/index.spec.js
  packages/datadog-plugin-amqp10/test/index.spec.js
  packages/datadog-plugin-amqplib/test/index.spec.js
  packages/datadog-plugin-apollo/test/index.spec.js
  packages/datadog-plugin-aws-sdk/test/kinesis.spec.js
  packages/datadog-plugin-aws-sdk/test/lambda.spec.js
  packages/datadog-plugin-aws-sdk/test/s3.spec.js
  packages/datadog-plugin-aws-sdk/test/sns.spec.js
  packages/datadog-plugin-aws-sdk/test/sqs.spec.js
  packages/datadog-plugin-cassandra-driver/test/index.spec.js
  packages/datadog-plugin-couchbase/test/index.spec.js
  packages/datadog-plugin-elasticsearch/test/index.spec.js
  packages/datadog-plugin-fastify/test/code_origin.spec.js
  packages/datadog-plugin-fastify/test/tracing.spec.js
  packages/datadog-plugin-fetch/test/index.spec.js
  packages/datadog-plugin-google-cloud-pubsub/test/index.spec.js
  packages/datadog-plugin-graphql/test/index.spec.js
  packages/datadog-plugin-grpc/test/client.spec.js
  packages/datadog-plugin-grpc/test/server.spec.js
  packages/datadog-plugin-http/test/client.spec.js
  packages/datadog-plugin-http/test/server.spec.js
  packages/datadog-plugin-http2/test/client.spec.js
  packages/datadog-plugin-http2/test/server.spec.js
  packages/datadog-plugin-ioredis/test/index.spec.js
  packages/datadog-plugin-iovalkey/test/index.spec.js
  packages/datadog-plugin-kafkajs/test/index.spec.js
  packages/datadog-plugin-mariadb/test/index.spec.js
  packages/datadog-plugin-memcached/test/index.spec.js
  packages/datadog-plugin-moleculer/test/index.spec.js
  packages/datadog-plugin-mongodb-core/test/core.spec.js
  packages/datadog-plugin-mongodb-core/test/mongodb.spec.js
  packages/datadog-plugin-mongoose/test/index.spec.js
  packages/datadog-plugin-mysql/test/index.spec.js
  packages/datadog-plugin-mysql2/test/index.spec.js
  packages/datadog-plugin-net/test/index.spec.js
  packages/datadog-plugin-next/test/index.spec.js
  packages/datadog-plugin-opensearch/test/index.spec.js
  packages/datadog-plugin-oracledb/test/index.spec.js
  packages/datadog-plugin-pg/test/index.spec.js
  packages/datadog-plugin-pino/test/index.spec.js
  packages/datadog-plugin-prisma/test/index.spec.js
  packages/datadog-plugin-redis/test/client.spec.js
  packages/datadog-plugin-redis/test/legacy.spec.js
  packages/datadog-plugin-rhea/test/index.spec.js
  packages/datadog-plugin-tedious/test/index.spec.js
  packages/datadog-plugin-undici/test/index.spec.js
  packages/dd-trace/test/setup/mocha.js
Labels: semver-patch

#5930 Activate weekly dependabot PRs for npm and switch actions to weekly
  .github/dependabot.yml
Labels: semver-patch

#5979 Ensure buffer gets correctly stringified when logged
  packages/dd-trace/src/dogstatsd.js
  packages/dd-trace/src/llmobs/writers/base.js
Labels: semver-patch

#5975 [DI] Use isString helper when asserting string
  packages/dd-trace/src/debugger/devtools_client/condition.js
Labels: semver-patch, dynamic-instrumentation

#5974 [DI] Log even more relevant debug info in case of exceptions
  integration-tests/debugger/basic.spec.js
  packages/dd-trace/src/debugger/devtools_client/breakpoints.js
  packages/dd-trace/test/debugger/devtools_client/breakpoints.spec.js
Labels: semver-patch, dynamic-instrumentation

#5949 remove async storage from cassandra-driver
  packages/datadog-instrumentations/src/cassandra-driver.js
  packages/datadog-plugin-cassandra-driver/src/index.js
  packages/datadog-plugin-moleculer/src/client.js
  packages/dd-trace/src/plugins/outbound.js
Labels: semver-patch

#5913 add event loop and gc configuration for runtime metrics
  docs/test.ts
  index.d.ts
  packages/dd-trace/src/config.js
  packages/dd-trace/src/proxy.js
  packages/dd-trace/src/runtime_metrics/index.js
  packages/dd-trace/src/runtime_metrics/runtime_metrics.js
  packages/dd-trace/src/supported-configurations.json
  packages/dd-trace/src/telemetry/telemetry.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/proxy.spec.js
  packages/dd-trace/test/runtime_metrics.spec.js
Labels: semver-minor

#5929 Add option to append comment to pg queries
  docs/test.ts
  index.d.ts
  packages/datadog-plugin-pg/test/index.spec.js
  packages/dd-trace/src/plugins/database.js
Labels: semver-minor

#5976 test: make sandbox package installation work offline
  CONTRIBUTING.md
  integration-tests/helpers/index.js
Labels: semver-patch
