Repository DataDog/dd-trace-js, pull requests merged in 2025-01, with the labels that each got.

#5050 [DI] Clean up snapshot integration test
  integration-tests/debugger/snapshot.spec.js
  integration-tests/debugger/target-app/snapshot.js
Labels: semver-patch, dynamic-instrumentation

#5065 upgrade mocha@9 to mocha@10
  package.json
  yarn.lock
Labels: semver-patch

#5064 Update native-appsec to 8.4.0
  package.json
  yarn.lock
Labels: semver-minor

#5063 Ignore noop spans
  packages/dd-trace/src/priority_sampler.js
  packages/dd-trace/test/priority_sampler.spec.js
Labels: semver-patch

#5070 Send tags, including git metadata, to RC endpoint
  packages/dd-trace/src/appsec/remote_config/manager.js
  packages/dd-trace/test/appsec/remote_config/manager.spec.js
Labels: semver-patch

#5025 Benchmarks: No need to guard against unhandled promise rejections
  benchmark/sirun/run-all-variants.js
  benchmark/sirun/run-one-variant.js
Labels: semver-patch

#5068 Rename `Tracer` to `NoopProxy` in `noop/proxy.js`
  packages/dd-trace/src/noop/proxy.js
Labels: semver-patch

#5071 add trace level logging when updating config
  packages/dd-trace/src/telemetry/index.js
Labels: semver-patch

#5074 improve logging of spans in trace log level
  packages/datadog-core/src/storage.js
  packages/dd-trace/src/log/index.js
  packages/dd-trace/src/noop/span.js
  packages/dd-trace/src/opentracing/span.js
  packages/dd-trace/src/opentracing/span_context.js
  packages/dd-trace/src/scope.js
  packages/dd-trace/test/log.spec.js
Labels: semver-patch

#5073 Copy config_norm_rules.json from dd-go
  packages/dd-trace/test/fixtures/telemetry/config_norm_rules.json
Labels: semver-patch

#5053 [DI] Implement PII redaction
  integration-tests/debugger/redact.spec.js
  integration-tests/debugger/target-app/redact.js
  packages/dd-trace/src/ci-visibility/dynamic-instrumentation/index.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/debugger/devtools_client/config.js
  packages/dd-trace/src/debugger/devtools_client/snapshot/processor.js
  packages/dd-trace/src/debugger/devtools_client/snapshot/redaction.js
  packages/dd-trace/src/debugger/index.js
  packages/dd-trace/src/proxy.js
  packages/dd-trace/test/ci-visibility/dynamic-instrumentation/target-app/test-visibility-dynamic-instrumentation-script.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/debugger/devtools_client/snapshot/redaction.spec.js
  packages/dd-trace/test/debugger/devtools_client/snapshot/target-code/redaction.js
  packages/dd-trace/test/debugger/devtools_client/snapshot/utils.js
Labels: semver-minor, dynamic-instrumentation

#5024 K8s new scenarios
  .gitlab-ci.yml
Labels: dev/testing, semver-patch

#5086 Log when setting priority on a noop span
  packages/dd-trace/src/priority_sampler.js
Labels: semver-patch

#5077 [DI] Add namespace to all DI related config options
  packages/dd-trace/src/config.js
  packages/dd-trace/src/debugger/devtools_client/config.js
  packages/dd-trace/src/debugger/devtools_client/snapshot/redaction.js
  packages/dd-trace/src/proxy.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/debugger/devtools_client/snapshot/utils.js
  packages/dd-trace/test/fixtures/telemetry/config_norm_rules.json
  packages/dd-trace/test/proxy.spec.js
Labels: semver-patch, dynamic-instrumentation

#5082 Remove config telemetry normalization tests
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/fixtures/telemetry/config_aggregation_list.json
  packages/dd-trace/test/fixtures/telemetry/config_norm_rules.json
  packages/dd-trace/test/fixtures/telemetry/config_prefix_block_list.json
  packages/dd-trace/test/fixtures/telemetry/nodejs_config_rules.json
Labels: semver-patch

#5067 DNS Lookup event hostname is sometimes not a string
  packages/dd-trace/src/profiling/profilers/events.js
Labels: profiling, semver-patch

#5090 [DI] Ensure probes without a 'sampling' property is parsed correctly
  packages/dd-trace/src/debugger/devtools_client/breakpoints.js
  packages/dd-trace/src/debugger/devtools_client/index.js
Labels: semver-patch, dynamic-instrumentation

#5081 [DI] Add a global max snapshot sample rate of 25/second
  integration-tests/debugger/snapshot-global-sample-rate.spec.js
  packages/dd-trace/src/debugger/devtools_client/defaults.js
  packages/dd-trace/src/debugger/devtools_client/index.js
Labels: semver-patch

#5093 Use literals for creating BigInts when possible
  packages/dd-trace/src/datastreams/fnv.js
  packages/dd-trace/src/debugger/devtools_client/index.js
  packages/dd-trace/test/llmobs/span_processor.spec.js
Labels: semver-patch

#5004 [DI] Add Sirun benchmark for Dynamic Instrumentation
  benchmark/sirun/debugger/README.md
  benchmark/sirun/debugger/app.js
  benchmark/sirun/debugger/meta.json
  benchmark/sirun/debugger/start-devtools-client.js
Labels: semver-patch, dynamic-instrumentation

#5100 [DI] Reduce time it takes to run benchmarks
  benchmark/sirun/debugger/app.js
Labels: semver-patch, dynamic-instrumentation

#5099 fix(ci): Balance splits across benchmarking CI jobs according to the number of CPU cores
  benchmark/sirun/runall.sh
Labels: semver-patch

#5102 fix(llmobs): tagger reads propogated mlApp and sessionId from registry tags
  packages/dd-trace/src/llmobs/tagger.js
  packages/dd-trace/test/llmobs/sdk/integration.spec.js
  packages/dd-trace/test/llmobs/tagger.spec.js
Labels: semver-patch

#5072 [test optimization] [SDTEST-1355] Fix DI issues with auto test retries
  integration-tests/cucumber/cucumber.spec.js
  integration-tests/jest/jest.spec.js
  integration-tests/mocha/mocha.spec.js
  integration-tests/vitest/vitest.spec.js
  packages/datadog-instrumentations/src/cucumber.js
  packages/datadog-instrumentations/src/jest.js
  packages/datadog-instrumentations/src/mocha/utils.js
  packages/datadog-instrumentations/src/vitest.js
  packages/datadog-plugin-cucumber/src/index.js
  packages/datadog-plugin-jest/src/index.js
  packages/datadog-plugin-mocha/src/index.js
  packages/datadog-plugin-vitest/src/index.js
  packages/dd-trace/src/ci-visibility/dynamic-instrumentation/index.js
  packages/dd-trace/src/ci-visibility/dynamic-instrumentation/worker/index.js
  packages/dd-trace/src/plugins/ci_plugin.js
  packages/dd-trace/src/plugins/util/test.js
  packages/dd-trace/test/ci-visibility/dynamic-instrumentation/dynamic-instrumentation.spec.js
  packages/dd-trace/test/ci-visibility/dynamic-instrumentation/target-app/test-visibility-dynamic-instrumentation-script.js
Labels: ci-app, semver-patch

#5105 [bench] minor code-cleanup in the benchmarking script
  benchmark/sirun/run-all-variants.js
  benchmark/sirun/run-one-variant.js
  benchmark/sirun/run-util.js
Labels: semver-patch

#5104 [bench] detect number of CPU cores dynamically
  benchmark/sirun/runall.sh
Labels: semver-patch

#5019 otel drop in support for baggage
  packages/dd-trace/src/opentelemetry/context_manager.js
  packages/dd-trace/test/opentelemetry/context_manager.spec.js
Labels: semver-minor

#5108 Fix control case for the profiler benchmark
  benchmark/sirun/profiler/index.js
Labels: dev/testing, semver-patch

#4765 Add parallelism information to profiles
  packages/dd-trace/src/profiling/exporters/event_serializer.js
  packages/dd-trace/test/profiling/exporters/agent.spec.js
Labels: profiling, semver-minor

#5112 [DI] Add missing PII redaction tokens
  packages/dd-trace/src/debugger/devtools_client/snapshot/redaction.js
Labels: semver-patch, dynamic-instrumentation

#5103 [bench] Don't force Node.js 18 for npm/yarn install
  benchmark/sirun/runall.sh
Labels: semver-patch

#4923 [MLOB-1858] feat(llmobs): langchain submits llmobs span events
  .github/workflows/llmobs.yml
  package.json
  packages/datadog-instrumentations/src/openai.js
  packages/datadog-plugin-langchain/src/index.js
  packages/datadog-plugin-langchain/src/tracing.js
  packages/dd-trace/src/llmobs/plugins/base.js
  packages/dd-trace/src/llmobs/plugins/langchain/handlers/chain.js
  packages/dd-trace/src/llmobs/plugins/langchain/handlers/chat_model.js
  packages/dd-trace/src/llmobs/plugins/langchain/handlers/embedding.js
  packages/dd-trace/src/llmobs/plugins/langchain/handlers/index.js
  packages/dd-trace/src/llmobs/plugins/langchain/handlers/llm.js
  packages/dd-trace/src/llmobs/plugins/langchain/index.js
  packages/dd-trace/src/llmobs/plugins/openai.js
  packages/dd-trace/src/llmobs/tagger.js
  packages/dd-trace/src/llmobs/util.js
  packages/dd-trace/test/llmobs/plugins/langchain/index.spec.js
  packages/dd-trace/test/llmobs/sdk/typescript/index.spec.js
  packages/dd-trace/test/llmobs/tagger.spec.js
  packages/dd-trace/test/llmobs/util.js
  packages/dd-trace/test/llmobs/util.spec.js
  packages/dd-trace/test/plugins/externals.json
Labels: semver-minor

#5096 Mark crashes that happen during collecting profiles as `profiler_serializing:1`
  package.json
  packages/dd-trace/src/crashtracking/crashtracker.js
  packages/dd-trace/src/crashtracking/noop.js
  packages/dd-trace/src/profiling/profiler.js
Labels: profiling, semver-minor

#5110 [Test Optimization] Fix DI setup for jest workers
  integration-tests/jest/jest.spec.js
  packages/datadog-instrumentations/src/jest.js
  packages/datadog-plugin-jest/src/index.js
  packages/dd-trace/src/ci-visibility/dynamic-instrumentation/index.js
  packages/dd-trace/src/ci-visibility/exporters/test-worker/index.js
  packages/dd-trace/src/plugins/ci_plugin.js
  packages/dd-trace/src/plugins/util/test.js
Labels: ci-app, semver-patch

#5120 fix startup benchmark
  benchmark/sirun/startup/startup-test.js
Labels: semver-patch

#5062 Untrusted deserialization vulnerability detection
  .github/workflows/appsec.yml
  packages/datadog-instrumentations/src/helpers/hooks.js
  packages/datadog-instrumentations/src/node-serialize.js
  packages/dd-trace/src/appsec/iast/analyzers/analyzers.js
  packages/dd-trace/src/appsec/iast/analyzers/untrusted-deserialization-analyzer.js
  packages/dd-trace/src/appsec/iast/vulnerabilities-formatter/evidence-redaction/sensitive-handler.js
  packages/dd-trace/src/appsec/iast/vulnerabilities.js
  packages/dd-trace/test/appsec/iast/analyzers/untrusted-deserialization-analyzer.node-serialize.plugin.spec.js
  packages/dd-trace/test/appsec/iast/vulnerability-formatter/index.spec.js
  packages/dd-trace/test/appsec/iast/vulnerability-formatter/resources/evidence-redaction-suite.json
Labels: semver-minor, asm-iast

#5080 Instrument vm for code injection vulnerability
  packages/datadog-instrumentations/src/helpers/hooks.js
  packages/datadog-instrumentations/src/vm.js
  packages/dd-trace/src/appsec/iast/analyzers/code-injection-analyzer.js
  packages/dd-trace/test/appsec/iast/analyzers/code-injection-analyzer.express.plugin.spec.js
  packages/dd-trace/test/appsec/iast/code_injection.integration.spec.js
  packages/dd-trace/test/appsec/iast/resources/vm.js
Labels: semver-minor, asm-iast

#5115 fix AppSec SDK not triggering twice in a row
  packages/dd-trace/src/appsec/waf/waf_context_wrapper.js
  packages/dd-trace/test/appsec/sdk/user_blocking.spec.js
Labels: semver-patch, asm-waf

#5128 fix(llmobs): use `config.url` for agent proxy
  packages/dd-trace/src/llmobs/writers/spans/agentProxy.js
  packages/dd-trace/test/llmobs/writers/spans/agentProxy.spec.js
Labels: semver-patch

#5127 inject cloned request headers for signed aws-sdk requests
  packages/datadog-plugin-http/src/client.js
  packages/datadog-plugin-http/test/client.spec.js
Labels: semver-minor

#5134 Ensure yarn.lock matches package.json
  yarn.lock
Labels: semver-patch

#5129 [DI] Fix consistency issue with log messages
  packages/dd-trace/src/debugger/devtools_client/send.js
  packages/dd-trace/src/debugger/devtools_client/status.js
Labels: semver-patch, dynamic-instrumentation

#5133 [DI] Ensure probe EMITTING status is sent correctly
  packages/dd-trace/src/debugger/devtools_client/index.js
  packages/dd-trace/src/debugger/devtools_client/send.js
  packages/dd-trace/test/debugger/devtools_client/send.spec.js
Labels: semver-patch, dynamic-instrumentation

#5123 [test optimization] Fix vitest latest release
  integration-tests/vitest/vitest.spec.js
  packages/datadog-instrumentations/src/vitest.js
  packages/dd-trace/src/ci-visibility/test-api-manual/test-api-manual-plugin.js
  packages/dd-trace/src/plugins/ci_plugin.js
  packages/dd-trace/src/proxy.js
Labels: ci-app, semver-patch

#5136 [test optimization] Fix ATR + DI issues with jest
  integration-tests/ci-visibility/dynamic-instrumentation/is-jest.js
  integration-tests/ci-visibility/dynamic-instrumentation/test-hit-breakpoint.js
  integration-tests/ci-visibility/dynamic-instrumentation/test-not-hit-breakpoint.js
  integration-tests/jest/jest.spec.js
  integration-tests/mocha/mocha.spec.js
  packages/datadog-instrumentations/src/jest.js
  packages/dd-trace/src/plugins/util/test.js
Labels: ci-app, semver-patch

#5106 [bench] clean up temp files even in case of error
  benchmark/sirun/runall.sh
Labels: semver-patch

#5107 [bench] exit if results.ndjson is empty
  benchmark/sirun/strip-unwanted-results.js
Labels: semver-patch

#5130 [DI] Add more debug logs related to queuing and flushing payloads
  packages/dd-trace/src/debugger/devtools_client/send.js
  packages/dd-trace/src/debugger/devtools_client/status.js
Labels: semver-patch, dynamic-instrumentation

#5141 Revert "fix aws-sdk invalid signature exception (#5127)"
  packages/datadog-plugin-http/src/client.js
  packages/datadog-plugin-http/test/client.spec.js
Labels: semver-patch

#5088 add SSI + K8s to version support matrix
  README.md
Labels: semver-patch

#5138 [test optimization] [SDTEST-1272] Detect new tests regardless of Early Flake Detection
  integration-tests/cucumber/cucumber.spec.js
  integration-tests/cypress/cypress.spec.js
  integration-tests/jest/jest.spec.js
  integration-tests/mocha/mocha.spec.js
  integration-tests/playwright/playwright.spec.js
  integration-tests/vitest/vitest.spec.js
  packages/datadog-instrumentations/src/cucumber.js
  packages/datadog-instrumentations/src/jest.js
  packages/datadog-instrumentations/src/mocha/main.js
  packages/datadog-instrumentations/src/mocha/utils.js
  packages/datadog-instrumentations/src/mocha/worker.js
  packages/datadog-instrumentations/src/playwright.js
  packages/datadog-instrumentations/src/vitest.js
  packages/datadog-plugin-cucumber/src/index.js
  packages/datadog-plugin-cypress/src/cypress-plugin.js
  packages/datadog-plugin-cypress/src/support.js
  packages/datadog-plugin-jest/src/index.js
  packages/datadog-plugin-mocha/src/index.js
  packages/datadog-plugin-playwright/src/index.js
  packages/datadog-plugin-vitest/src/index.js
  packages/dd-trace/src/ci-visibility/exporters/ci-visibility-exporter.js
  packages/dd-trace/src/ci-visibility/requests/get-library-configuration.js
  packages/dd-trace/src/plugins/ci_plugin.js
  packages/dd-trace/src/plugins/util/test.js
  packages/dd-trace/test/ci-visibility/exporters/ci-visibility-exporter.spec.js
Labels: ci-app, semver-patch

#5144 inject cloned request headers for http requests
  packages/datadog-plugin-fetch/src/index.js
  packages/datadog-plugin-fetch/test/index.spec.js
  packages/datadog-plugin-http/src/client.js
  packages/datadog-plugin-http/test/client.spec.js
Labels: semver-minor

#5132 Zarir/remove inferred http route
  packages/dd-trace/src/plugins/util/inferred_proxy.js
  packages/dd-trace/test/plugins/util/inferred_proxy.spec.js
Labels: semver-patch

#5137 (chore)APM: Refactor Bedrock Integration
  CODEOWNERS
  packages/datadog-instrumentations/src/aws-sdk.js
  packages/datadog-plugin-aws-sdk/src/services/bedrockruntime/index.js
  packages/datadog-plugin-aws-sdk/src/services/bedrockruntime/tracing.js
  packages/datadog-plugin-aws-sdk/src/services/bedrockruntime/utils.js
  packages/datadog-plugin-aws-sdk/test/bedrockruntime.spec.js
Labels: semver-patch

#5116 (chore)LLMObs: instrument bedrock runtime invoke model
  .github/workflows/llmobs.yml
  packages/datadog-plugin-aws-sdk/src/services/bedrockruntime/index.js
  packages/datadog-plugin-aws-sdk/test/bedrockruntime.spec.js
  packages/datadog-plugin-aws-sdk/test/fixtures/bedrockruntime.js
  packages/dd-trace/src/llmobs/plugins/bedrockruntime.js
  packages/dd-trace/test/llmobs/plugins/aws-sdk/bedrockruntime.spec.js
Labels: semver-patch

#5149 [test optimization] Remove node 16 checks in tests
  integration-tests/automatic-log-submission.spec.js
  integration-tests/cucumber/cucumber.spec.js
  integration-tests/init.spec.js
  integration-tests/selenium/selenium.spec.js
  packages/datadog-plugin-cassandra-driver/test/integration-test/client.spec.js
  packages/datadog-plugin-cucumber/test/index.spec.js
  packages/datadog-plugin-next/test/index.spec.js
  packages/datadog-plugin-next/test/integration-test/client.spec.js
  packages/dd-trace/test/appsec/index.next.plugin.spec.js
Labels: ci-app, semver-patch

#5154 ci(openai): temporarily disable ESM tests
  packages/datadog-plugin-openai/test/integration-test/client.spec.js
Labels: semver-patch

#5142 EOL v4
  README.md
Labels: semver-patch

#5153 Upgrade @datadog/pprof to 5.5.0
  package.json
  yarn.lock
Labels: profiling, semver-minor

#5151 Add more YAML verification
  .github/actions/install/action.yml
  .github/actions/node/14/action.yml
  .github/actions/node/16/action.yml
  .github/actions/node/18/action.yml
  .github/actions/node/20/action.yml
  .github/actions/node/latest/action.yml
  .github/actions/node/oldest/action.yml
  .github/actions/node/setup/action.yml
  .github/actions/plugins/test-and-upstream/action.yml
  .github/actions/plugins/test/action.yml
  .github/actions/plugins/upstream/action.yml
  .github/workflows/actionlint.yml
  .github/workflows/all-green.yml
  .github/workflows/appsec.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/core.yml
  .github/workflows/datadog-static-analysis.yml
  .github/workflows/debugger.yml
  .github/workflows/instrumentations.yml
  .github/workflows/lambda.yml
  .github/workflows/llmobs.yml
  .github/workflows/plugins.yml
  .github/workflows/prepare-release-proposal.yml
  .github/workflows/profiling.yml
  .github/workflows/project.yml
  .github/workflows/release-3.yml
  .github/workflows/release-4.yml
  .github/workflows/release-dev.yml
  .github/workflows/release-latest.yml
  .github/workflows/release-proposal.yml
  .github/workflows/serverless-integration-test.yml
  .github/workflows/system-tests.yml
  .github/workflows/tracing.yml
  packages/datadog-instrumentations/test/check_require_cache.spec.js
  packages/datadog-plugin-find-my-way/test/index.spec.js
  packages/datadog-plugin-fs/test/index.spec.js
  packages/dd-trace/test/plugins/externals.json
  scripts/verify-ci-config.js
Labels: semver-patch

#5150 [DSM] Fix an issue where RabbitMQ producers when producing a message to the default exchange were setting checkpoints that didn't work in DSM
  packages/datadog-plugin-amqplib/src/producer.js
  packages/datadog-plugin-amqplib/test/index.spec.js
Labels: semver-patch

#5109 chore: add some shared llm-type plugin utilities
  packages/datadog-plugin-langchain/src/handlers/default.js
  packages/datadog-plugin-langchain/src/tracing.js
  packages/datadog-plugin-openai/src/tracing.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/plugins/util/llm.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/plugins/util/llm.spec.js
Labels: semver-patch

#5162 chore(tracing): graphql error support
  packages/datadog-plugin-graphql/src/execute.js
  packages/datadog-plugin-graphql/src/utils.js
  packages/datadog-plugin-graphql/src/validate.js
  packages/datadog-plugin-graphql/test/index.spec.js
  packages/dd-trace/src/config.js
  packages/dd-trace/test/plugins/agent.js
Labels: semver-minor

#5135 [CI] Do not allow yarn.lock to be updated in CI
  .github/actions/install/action.yml
Labels: semver-patch

#5174 Fix a crash in the profiler
  package.json
  yarn.lock
Labels: semver-patch

#5172 fix flaky user_tracking test
  packages/dd-trace/test/appsec/user_tracking.spec.js
Labels: semver-patch, asm-waf

#5173 replace msgpack-lite with official library for tests
  LICENSE-3rdparty.csv
  integration-tests/ci-visibility-intake.js
  integration-tests/helpers/fake-agent.js
  package.json
  packages/datadog-plugin-moleculer/test/index.spec.js
  packages/datadog-plugin-net/test/index.spec.js
  packages/dd-trace/src/id.js
  packages/dd-trace/test/datastreams/processor.spec.js
  packages/dd-trace/test/datastreams/writer.spec.js
  packages/dd-trace/test/dd-trace.spec.js
  packages/dd-trace/test/encode/0.4.spec.js
  packages/dd-trace/test/encode/0.5.spec.js
  packages/dd-trace/test/encode/agentless-ci-visibility.spec.js
  packages/dd-trace/test/encode/coverage-ci-visibility.spec.js
  packages/dd-trace/test/encode/span-stats.spec.js
  packages/dd-trace/test/llmobs/util.js
  packages/dd-trace/test/msgpack/encoder.spec.js
  packages/dd-trace/test/plugins/agent.js
  packages/dd-trace/test/plugins/helpers.js
  yarn.lock
Labels: semver-patch

#5163 ci(openai): fix esm tests
  packages/datadog-plugin-openai/test/integration-test/client.spec.js
  packages/datadog-plugin-openai/test/integration-test/server.mjs
Labels: semver-patch

#5044 env var to disable all middleware spans
  packages/datadog-plugin-express/test/integration-test/client.spec.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/plugin_manager.js
  packages/dd-trace/test/config.spec.js
Labels: semver-minor

#5181 remove test-agent plugin logs from test output and save to artifact file instead
  .github/actions/testagent/logs/action.yml
Labels: semver-patch

#5178 retry npm install on error for plugin test suite
  packages/dd-trace/test/plugins/suite.js
Labels: semver-patch

#5166 [DI] Improve path matching algorithm for probe file paths
  packages/dd-trace/src/debugger/devtools_client/state.js
  packages/dd-trace/test/debugger/devtools_client/state.spec.js
Labels: semver-patch, dynamic-instrumentation

#5164 Code injection instrumented metric
  packages/dd-trace/src/appsec/iast/analyzers/code-injection-analyzer.js
  packages/dd-trace/test/appsec/iast/code_injection.integration.spec.js
  packages/dd-trace/test/appsec/iast/resources/eval-methods.js
  packages/dd-trace/test/appsec/iast/resources/eval.js
  packages/dd-trace/test/appsec/rasp/command_injection.integration.spec.js
Labels: semver-minor

#5152 [MLOB-2098] feat(llmobs): record bedrock token counts
  packages/datadog-instrumentations/src/aws-sdk.js
  packages/datadog-plugin-aws-sdk/src/services/bedrockruntime/utils.js
  packages/datadog-plugin-aws-sdk/test/fixtures/bedrockruntime.js
  packages/dd-trace/src/llmobs/plugins/bedrockruntime.js
  packages/dd-trace/test/llmobs/plugins/aws-sdk/bedrockruntime.spec.js
Labels: semver-minor

#5145 Instrument dd-trace-api
  .github/workflows/plugins.yml
  packages/datadog-plugin-dd-trace-api/src/index.js
  packages/datadog-plugin-dd-trace-api/test/index.spec.js
  packages/dd-trace/src/plugin_manager.js
  packages/dd-trace/src/plugins/index.js
Labels: semver-minor
