Repository DataDog/dd-trace-js, pull requests merged in 2025-09, with the labels that each got.

#6361 chore(tracing): fix prisma client tracing for esm and add esm tests
  packages/datadog-instrumentations/src/prisma.js
  packages/datadog-plugin-prisma/test/integration-test/client.spec.js
  packages/datadog-plugin-prisma/test/integration-test/server.mjs
  packages/dd-trace/test/plugins/versions/package.json
Labels: semver-patch

#6376 fix: make sure to bail in shimmer if target is undefined
  packages/datadog-shimmer/src/shimmer.js
  packages/datadog-shimmer/test/shimmer.spec.js
Labels: semver-patch

#6284 feat(llmobs): default `mlApp` to the service name
  packages/dd-trace/src/llmobs/tagger.js
  packages/dd-trace/test/llmobs/sdk/integration.spec.js
  packages/dd-trace/test/llmobs/tagger.spec.js
Labels: semver-minor

#6394 chore: run ESLint in multithreaded mode
  package.json
Labels: semver-patch

#6396 chore: Add Node.js 24 to benchmark matrix
  .gitlab/benchmarks.yml
Labels: semver-patch

#6351 fix ip_extractor algo for Forwarded header
  packages/dd-trace/src/plugins/util/ip_extractor.js
  packages/dd-trace/test/plugins/util/ip_extractor.spec.js
Labels: semver-patch

#6398 test: improve runtime metric tests to be less flaky
  packages/dd-trace/test/runtime_metrics.spec.js
Labels: semver-patch

#6272 Removing hook for express v5 router
  integration-tests/appsec/standalone-asm.spec.js
  packages/datadog-instrumentations/src/express.js
  packages/datadog-plugin-express/src/code_origin.js
  packages/datadog-plugin-express/test/code_origin.spec.js
  packages/datadog-plugin-express/test/index.spec.js
  packages/datadog-plugin-express/test/integration-test/client.spec.js
  packages/dd-trace/src/appsec/channels.js
  packages/dd-trace/src/appsec/rasp/index.js
  packages/dd-trace/test/appsec/rasp/command_injection.express.plugin.spec.js
  packages/dd-trace/test/appsec/rasp/index.spec.js
Labels: semver-patch, integration-express

#6383 fix(llmobs): properly parse "newer" anthropic models, cohere models from bedrock-runtime calls
  docker-compose.yml
  packages/datadog-plugin-aws-sdk/src/services/bedrockruntime/utils.js
  packages/datadog-plugin-aws-sdk/test/bedrockruntime.spec.js
  packages/datadog-plugin-aws-sdk/test/fixtures/bedrockruntime.js
  packages/dd-trace/test/llmobs/cassettes/bedrock-runtime/bedrock-runtime_model_ai21.jamba-1-5-mini-v1_0_invoke_post_94074469.yaml
  packages/dd-trace/test/llmobs/cassettes/bedrock-runtime/bedrock-runtime_model_amazon.titan-text-lite-v1_invoke_post_fd2fbadd.yaml
  packages/dd-trace/test/llmobs/cassettes/bedrock-runtime/bedrock-runtime_model_anthropic.claude-3-5-sonnet-20240620-v1_0_invoke_post_ed137a82.yaml
  packages/dd-trace/test/llmobs/cassettes/bedrock-runtime/bedrock-runtime_model_anthropic.claude-v2_1_invoke_post_a4c60df3.yaml
  packages/dd-trace/test/llmobs/cassettes/bedrock-runtime/bedrock-runtime_model_cohere.command-r-v1_0_invoke_post_700c0483.yaml
  packages/dd-trace/test/llmobs/cassettes/bedrock-runtime/bedrock-runtime_model_meta.llama3-8b-instruct-v1_0_invoke_post_ff948675.yaml
  packages/dd-trace/test/llmobs/cassettes/bedrock-runtime/bedrock-runtime_model_mistral.mistral-7b-instruct-v0_2_invoke_post_2aafa21c.yaml
  packages/dd-trace/test/llmobs/plugins/aws-sdk/bedrockruntime.spec.js
Labels: semver-patch

#6354 fix(tracing): fixes graphql resolver error not returning a then-able result
  packages/datadog-instrumentations/src/graphql.js
  packages/datadog-plugin-graphql/test/index.spec.js
Labels: semver-patch

#6445 bump axios to 1.12.2
  package.json
  yarn.lock
Labels: semver-patch

#6440 [test optimization] Improve cypress flakiness
  integration-tests/cypress/cypress.spec.js
Labels: ci-app, semver-patch

#5743 Use AsyncContextFrame for storing profiler sampling context
  integration-tests/profiler/profiler.spec.js
  packages/dd-trace/src/profiler.js
  packages/dd-trace/src/profiling/config.js
  packages/dd-trace/src/profiling/profilers/wall.js
  packages/dd-trace/src/supported-configurations.json
  packages/dd-trace/test/profiling/profilers/wall.spec.js
Labels: profiling, semver-minor

#6444 [MLOB-3132] add cached metrics for OpenAI
  packages/dd-trace/src/llmobs/constants/tags.js
  packages/dd-trace/src/llmobs/plugins/openai.js
  packages/dd-trace/src/llmobs/tagger.js
  packages/dd-trace/test/llmobs/cassettes/openai/openai_chat_completions_post_5eb44755.yaml
  packages/dd-trace/test/llmobs/cassettes/openai/openai_chat_completions_post_b716cbcd.yaml
  packages/dd-trace/test/llmobs/cassettes/openai/openai_completions_post_96160277.yaml
  packages/dd-trace/test/llmobs/cassettes/openai/openai_completions_post_ece8d3b2.yaml
  packages/dd-trace/test/llmobs/plugins/openai/openaiv4.spec.js
Labels: semver-minor

#6405 feat(aws-sdk, llmobs): support `InvokeModelWithResponseStreamCommand` for bedrock runtime
  packages/datadog-instrumentations/src/aws-sdk.js
  packages/datadog-plugin-aws-sdk/src/services/bedrockruntime/tracing.js
  packages/datadog-plugin-aws-sdk/src/services/bedrockruntime/utils.js
  packages/datadog-plugin-aws-sdk/test/bedrockruntime.spec.js
  packages/datadog-plugin-aws-sdk/test/fixtures/bedrockruntime.js
  packages/dd-trace/src/llmobs/plugins/bedrockruntime.js
  packages/dd-trace/test/llmobs/cassettes/bedrock-runtime/bedrock-runtime_model_ai21.jamba-1-5-mini-v1_0_invoke-with-response-stream_post_5f96d68e.yaml
  packages/dd-trace/test/llmobs/cassettes/bedrock-runtime/bedrock-runtime_model_amazon.titan-text-lite-v1_invoke-with-response-stream_post_bdb7075b.yaml
  packages/dd-trace/test/llmobs/cassettes/bedrock-runtime/bedrock-runtime_model_anthropic.claude-3-5-sonnet-20240620-v1_0_invoke-with-response-stream_post_62cabaec.yaml
  packages/dd-trace/test/llmobs/cassettes/bedrock-runtime/bedrock-runtime_model_anthropic.claude-v2_1_invoke-with-response-stream_post_a5f92858.yaml
  packages/dd-trace/test/llmobs/cassettes/bedrock-runtime/bedrock-runtime_model_cohere.command-r-v1_0_invoke-with-response-stream_post_e8a880e7.yaml
  packages/dd-trace/test/llmobs/cassettes/bedrock-runtime/bedrock-runtime_model_meta.llama3-8b-instruct-v1_0_invoke-with-response-stream_post_8b66d936.yaml
  packages/dd-trace/test/llmobs/cassettes/bedrock-runtime/bedrock-runtime_model_mistral.mistral-7b-instruct-v0_2_invoke-with-response-stream_post_9d0cffc3.yaml
  packages/dd-trace/test/llmobs/plugins/aws-sdk/bedrockruntime.spec.js
  packages/dd-trace/test/llmobs/util.js
Labels: semver-minor

#6446 test,chore: use less globals and improve linting
  .github/workflows/eslint-rules.yml
  .github/workflows/project.yml
  eslint.config.mjs
  integration-tests/appsec/endpoints-collection.spec.js
  integration-tests/ci-visibility/jest/mocked-test.js
  integration-tests/telemetry.spec.js
  packages/datadog-code-origin/test/helpers.js
  packages/datadog-plugin-jest/test/jest-focus.js
  packages/datadog-plugin-jest/test/jest-hook-failure.js
  packages/datadog-plugin-jest/test/jest-test-suite.js
  packages/datadog-plugin-jest/test/jest-test.js
  packages/dd-trace/test/appsec/rasp/rasp_blocking.fastify.plugin.spec.js
  packages/dd-trace/test/setup/core.js
  packages/dd-trace/test/setup/mocha.js
Labels: semver-patch

#6436 fix: ensure default agent hostname is 127.0.0.1 everywhere
  benchmark/sirun/exporting-pipeline/index.js
  benchmark/sirun/statsd.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/config_defaults.js
  packages/dd-trace/src/crashtracking/crashtracker.js
  packages/dd-trace/src/datastreams/writer.js
  packages/dd-trace/src/debugger/devtools_client/config.js
  packages/dd-trace/src/dogstatsd.js
  packages/dd-trace/src/exporters/agent/index.js
  packages/dd-trace/src/exporters/common/agent-info-exporter.js
  packages/dd-trace/src/exporters/span-stats/index.js
  packages/dd-trace/src/profiling/config.js
  packages/dd-trace/src/remote_config/manager.js
  packages/dd-trace/src/startup-log.js
  packages/dd-trace/test/ci-visibility/exporters/agent-proxy/agent-proxy.spec.js
  packages/dd-trace/test/ci-visibility/exporters/ci-visibility-exporter.spec.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/dogstatsd.spec.js
  packages/dd-trace/test/exporters/common/agent-info-exporter.spec.js
  packages/dd-trace/test/profiling/config.spec.js
Labels: semver-patch

#6316 ci(llmobs): resolve some test flakiness
  packages/dd-trace/src/llmobs/plugins/ai/index.js
  packages/dd-trace/test/llmobs/cassettes/azure-openai/azure-openai_chat_completions_post_782ff5d3.yaml
  packages/dd-trace/test/llmobs/cassettes/azure-openai/azure-openai_openai_deployments_gpt-4.1_chat_completions_api-version_2024-05-01-preview_post_e5b3df5e.yaml
  packages/dd-trace/test/llmobs/plugins/ai/index.spec.js
  packages/dd-trace/test/llmobs/plugins/aws-sdk/bedrockruntime.spec.js
  packages/dd-trace/test/llmobs/plugins/openai/openaiv4.spec.js
  packages/dd-trace/test/llmobs/util.js
Labels: semver-patch

#6306 automate dependabot approve and merge for dev deps and actions
  .github/workflows/dependabot-automation.yml
Labels: semver-patch

#6459 ci: add cooldown time of a day to dependabot for regular dependencies
  .github/dependabot.yml
Labels: semver-patch

#6462 test: dry up agent url references
  packages/dd-trace/test/ci-visibility/exporters/agent-proxy/agent-proxy.spec.js
  packages/dd-trace/test/ci-visibility/exporters/ci-visibility-exporter.spec.js
  packages/dd-trace/test/exporters/common/agent-info-exporter.spec.js
Labels: semver-patch

#6470 benchmark: make startup-test more stable by using fixed dep list
  benchmark/sirun/startup/startup-test.js
Labels: semver-patch

#6438 test: update prisma test version and fix esm test
  packages/datadog-plugin-prisma/test/integration-test/client.spec.js
  packages/dd-trace/test/plugins/versions/package.json
Labels: semver-patch

#6458 [test optimization] Support `vitest` programmatic API
  integration-tests/ci-visibility/vitest-tests-programmatic-api/run-programmatic-api.mjs
  integration-tests/ci-visibility/vitest-tests-programmatic-api/test-programmatic-api.mjs
  integration-tests/vitest/vitest.spec.js
  packages/datadog-instrumentations/src/vitest.js
Labels: ci-app, semver-minor

#5803 [test optimization] Improve `vitest` performance
  ci/init.js
  ext/exporters.d.ts
  ext/exporters.js
  integration-tests/ci-visibility/dynamic-instrumentation/parallel-test-hit-breakpoint-1.js
  integration-tests/ci-visibility/dynamic-instrumentation/parallel-test-hit-breakpoint-2.js
  integration-tests/ci-visibility/run-tinypool.mjs
  integration-tests/ci-visibility/tinypool-worker.mjs
  integration-tests/jest/jest.spec.js
  integration-tests/vitest/vitest.spec.js
  packages/datadog-instrumentations/src/helpers/hooks.js
  packages/datadog-instrumentations/src/vitest.js
  packages/datadog-plugin-jest/src/index.js
  packages/datadog-plugin-vitest/src/index.js
  packages/dd-trace/src/ci-visibility/exporters/ci-visibility-exporter.js
  packages/dd-trace/src/ci-visibility/exporters/test-worker/index.js
  packages/dd-trace/src/ci-visibility/exporters/test-worker/writer.js
  packages/dd-trace/src/exporter.js
  packages/dd-trace/src/plugin_manager.js
  packages/dd-trace/src/plugins/ci_plugin.js
  packages/dd-trace/src/plugins/index.js
  packages/dd-trace/src/plugins/util/git.js
  packages/dd-trace/src/plugins/util/test.js
  packages/dd-trace/test/plugins/util/git.spec.js
  packages/dd-trace/test/plugins/versions/package.json
Labels: ci-app, semver-patch

#6489 chore(lint): align ECMA version in ESLint config
  eslint.config.mjs
Labels: semver-patch

#6246 implement pre-release gates
  .gitlab-ci.yml
  .gitlab/benchmarks/bp-runner.fail-on-breach.yml
  .gitlab/macrobenchmarks.yml
Labels: semver-patch

#6506 feat(aws): rename partition tag to aws.partition
  packages/datadog-plugin-aws-sdk/src/base.js
  packages/datadog-plugin-aws-sdk/test/aws-sdk.spec.js
Labels: semver-minor

#6520 benchmark: do not skip failing require calls
  benchmark/sirun/startup/startup-test.js
Labels: semver-patch

#6505 [MLOB-3170] add prompt caching metrics for bedrock
  packages/datadog-plugin-aws-sdk/src/services/bedrockruntime/utils.js
  packages/datadog-plugin-aws-sdk/test/fixtures/bedrockruntime.js
  packages/dd-trace/src/llmobs/constants/tags.js
  packages/dd-trace/src/llmobs/plugins/bedrockruntime.js
  packages/dd-trace/src/llmobs/plugins/openai.js
  packages/dd-trace/src/llmobs/tagger.js
  packages/dd-trace/test/llmobs/cassettes/bedrock-runtime/bedrock-runtime_model_us.anthropic.claude-sonnet-4-20250514-v1_0_invoke-with-response-stream_post_4b5b3e7d.yaml
  packages/dd-trace/test/llmobs/cassettes/bedrock-runtime/bedrock-runtime_model_us.anthropic.claude-sonnet-4-20250514-v1_0_invoke-with-response-stream_post_920fdf6e.yaml
  packages/dd-trace/test/llmobs/cassettes/bedrock-runtime/bedrock-runtime_model_us.anthropic.claude-sonnet-4-20250514-v1_0_invoke_post_0b72aefa.yaml
  packages/dd-trace/test/llmobs/cassettes/bedrock-runtime/bedrock-runtime_model_us.anthropic.claude-sonnet-4-20250514-v1_0_invoke_post_b1cbb572.yaml
  packages/dd-trace/test/llmobs/plugins/aws-sdk/bedrockruntime.spec.js
Labels: semver-minor

#6515 test: use promise based fs functions in integration tests helpers
  integration-tests/helpers/index.js
Labels: semver-patch

#6531 test: fix bug in integration test helper
  integration-tests/helpers/index.js
Labels: semver-patch

#6519 test: simplify vary test helper
  integration-tests/helpers/index.js
  packages/datadog-plugin-amqplib/test/integration-test/client.spec.js
  packages/datadog-plugin-bunyan/test/integration-test/client.spec.js
  packages/datadog-plugin-cassandra-driver/test/integration-test/client.spec.js
  packages/datadog-plugin-connect/test/integration-test/client.spec.js
  packages/datadog-plugin-dns/test/integration-test/client.spec.js
  packages/datadog-plugin-elasticsearch/test/integration-test/client.spec.js
  packages/datadog-plugin-express/test/integration-test/client.spec.js
  packages/datadog-plugin-http2/test/integration-test/client.spec.js
  packages/datadog-plugin-ioredis/test/integration-test/client.spec.js
  packages/datadog-plugin-limitd-client/test/integration-test/client.spec.js
  packages/datadog-plugin-mongodb-core/test/integration-test/client.spec.js
  packages/datadog-plugin-mongoose/test/integration-test/client.spec.js
  packages/datadog-plugin-mysql/test/integration-test/client.spec.js
  packages/datadog-plugin-net/test/integration-test/client.spec.js
  packages/datadog-plugin-next/test/integration-test/client.spec.js
  packages/datadog-plugin-pg/test/integration-test/client.spec.js
  packages/datadog-plugin-pino/test/integration-test/client.spec.js
Labels: semver-patch

#6535 fix: remove duplicate line in config code
  packages/dd-trace/src/config.js
Labels: semver-patch

#6537 chore: improve script for running CI on community PRs
  scripts/run-ci-on-community-pr.sh
Labels: semver-patch

#6516 test: use fs.rm instead of rimraf
  LICENSE-3rdparty.csv
  benchmark/sirun/startup/startup-test.js
  integration-tests/helpers/index.js
  package.json
  packages/datadog-plugin-fs/test/index.spec.js
  yarn.lock
Labels: semver-patch

#6524 fix(ai, llmobs): respect the `functionId` argument for vercel-ai operations
  packages/datadog-plugin-ai/src/tracing.js
  packages/datadog-plugin-ai/test/index.spec.js
  packages/dd-trace/src/llmobs/plugins/ai/index.js
  packages/dd-trace/src/llmobs/plugins/ai/util.js
  packages/dd-trace/test/llmobs/plugins/ai/index.spec.js
Labels: semver-patch

#6538 chore: update sinon to v21
  package.json
  packages/datadog-plugin-openai/test/index.spec.js
  packages/dd-trace/test/appsec/api_security_sampler.spec.js
  packages/dd-trace/test/appsec/iast/telemetry/logs.spec.js
  packages/dd-trace/test/debugger/devtools_client/send.spec.js
  packages/dd-trace/test/debugger/devtools_client/source-maps.spec.js
  packages/dd-trace/test/debugger/devtools_client/status.spec.js
  packages/dd-trace/test/dogstatsd.spec.js
  packages/dd-trace/test/llmobs/sdk/index.spec.js
  packages/dd-trace/test/llmobs/writers/base.spec.js
  packages/dd-trace/test/profiling/profiler.spec.js
  packages/dd-trace/test/rate_limiter.spec.js
  packages/dd-trace/test/remote_config/scheduler.spec.js
  packages/dd-trace/test/runtime_metrics.spec.js
  packages/dd-trace/test/sampling_rule.spec.js
  packages/dd-trace/test/telemetry/index.spec.js
  yarn.lock
Labels: semver-patch

#6552 chore: remove duplicate information in ESLint config
  eslint.config.mjs
Labels: semver-patch

#6543 chore: remove get-port dependency completely
  LICENSE-3rdparty.csv
  benchmark/sirun/startup/startup-test.js
  package.json
  packages/datadog-plugin-grpc/test/integration-test/server.mjs
  packages/datadog-plugin-microgateway-core/test/integration-test/client.spec.js
  packages/datadog-plugin-microgateway-core/test/integration-test/server.mjs
  packages/datadog-plugin-moleculer/test/index.spec.js
  packages/dd-trace/test/plugins/versions/package.json
  yarn.lock
Labels: semver-patch

#6509 [test optimization] Add file system cache for `git` commands
  integration-tests/ci-visibility/git-cache.spec.js
  packages/dd-trace/src/plugins/util/git-cache.js
  packages/dd-trace/src/plugins/util/git.js
  packages/dd-trace/src/supported-configurations.json
  packages/dd-trace/test/plugins/util/git.spec.js
  packages/dd-trace/test/plugins/util/test-environment.spec.js
Labels: ci-app, semver-minor

#6558 test: fix rimraf being required due to merge timing conflict
  integration-tests/ci-visibility/git-cache.spec.js
Labels: semver-patch

#6525 chore(llmobs): add `ml_app` tag to llmobs enabled telemetry metric
  packages/dd-trace/src/llmobs/telemetry.js
Labels: semver-patch

#6546 fix(instrumentation): do not fail accessing oracledb hostName getter
  packages/datadog-instrumentations/src/oracledb.js
Labels: semver-patch

#6556 chore: remove koalas dependency
  LICENSE-3rdparty.csv
  integration-tests/appsec/graphql.spec.js
  package.json
  packages/datadog-plugin-aws-sdk/src/base.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/profiling/config.js
  packages/dd-trace/src/profiling/profilers/events.js
  packages/dd-trace/src/profiling/profilers/space.js
  packages/dd-trace/src/profiling/profilers/wall.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/log.spec.js
  packages/dd-trace/test/plugins/versions/package.json
  yarn.lock
Labels: semver-patch
