Repository DataDog/dd-trace-js, pull requests merged in 2025-02, with the labels that each got.

#5186 [DI] Probe file path matching algo should prefer shorter paths
  packages/dd-trace/src/debugger/devtools_client/state.js
  packages/dd-trace/test/debugger/devtools_client/state.spec.js
Labels: semver-patch, dynamic-instrumentation

#4670 Automatic userID tracking and blocking
  .github/workflows/instrumentations.yml
  packages/datadog-instrumentations/src/helpers/hooks.js
  packages/datadog-instrumentations/src/passport.js
  packages/datadog-instrumentations/test/passport.spec.js
  packages/dd-trace/src/appsec/blocking.js
  packages/dd-trace/src/appsec/channels.js
  packages/dd-trace/src/appsec/iast/analyzers/weak-hash-analyzer.js
  packages/dd-trace/src/appsec/index.js
  packages/dd-trace/src/appsec/sdk/set_user.js
  packages/dd-trace/src/appsec/sdk/user_blocking.js
  packages/dd-trace/src/appsec/telemetry.js
  packages/dd-trace/src/appsec/user_tracking.js
  packages/dd-trace/test/appsec/blocking.spec.js
  packages/dd-trace/test/appsec/index.spec.js
  packages/dd-trace/test/appsec/sdk/set_user.spec.js
  packages/dd-trace/test/appsec/sdk/user_blocking.spec.js
  packages/dd-trace/test/appsec/telemetry.spec.js
  packages/dd-trace/test/appsec/user_tracking.spec.js
  packages/dd-trace/test/plugins/externals.json
Labels: asm-waf, semver-minor

#5188 [DI] Handle different casing in probe file paths
  packages/dd-trace/src/debugger/devtools_client/state.js
  packages/dd-trace/test/debugger/devtools_client/state.spec.js
Labels: semver-patch, dynamic-instrumentation

#5176 [test optimization][SDTEST-1355] Fix ATR + DI
  packages/datadog-instrumentations/src/jest.js
  packages/datadog-plugin-cucumber/src/index.js
  packages/datadog-plugin-jest/src/index.js
  packages/datadog-plugin-mocha/src/index.js
  packages/datadog-plugin-vitest/src/index.js
  packages/dd-trace/src/ci-visibility/dynamic-instrumentation/index.js
  packages/dd-trace/src/ci-visibility/dynamic-instrumentation/worker/index.js
  packages/dd-trace/src/plugins/ci_plugin.js
Labels: ci-app, semver-patch

#5185 [test optimization] Fix `cy.window` for multi origin tests
  integration-tests/cypress-esm-config.mjs
  integration-tests/cypress.config.js
  integration-tests/cypress/cypress.spec.js
  integration-tests/cypress/e2e/multi-origin.js
  packages/datadog-plugin-cypress/src/support.js
Labels: ci-app, semver-patch

#5193 ci: pin github actions by hash and update via dependabot
  .github/dependabot.yml
  .github/workflows/actionlint.yml
  .github/workflows/all-green.yml
  .github/workflows/appsec.yml
  .github/workflows/ci-visibility-performance.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/core.yml
  .github/workflows/datadog-static-analysis.yml
  .github/workflows/debugger.yml
  .github/workflows/instrumentations.yml
  .github/workflows/lambda.yml
  .github/workflows/llmobs.yml
  .github/workflows/package-size.yml
  .github/workflows/plugins.yml
  .github/workflows/pr-labels.yml
  .github/workflows/prepare-release-proposal.yml
  .github/workflows/profiling.yml
  .github/workflows/project.yml
  .github/workflows/rebase-release-proposal.yml
  .github/workflows/release-3.yml
  .github/workflows/release-4.yml
  .github/workflows/release-dev.yml
  .github/workflows/release-latest.yml
  .github/workflows/release-proposal.yml
  .github/workflows/serverless-integration-test.yml
  .github/workflows/system-tests.yml
  .github/workflows/tracing.yml
Labels: semver-patch

#5192 simplify wrap and trace
  index.d.ts
  packages/dd-trace/src/tracer.js
  packages/dd-trace/test/tracer.spec.js
Labels: semver-patch

#5183 add yarnrc with ignore-engines config
  .yarnrc
Labels: semver-patch

#5197 update ci nightly schedules to run 3 times
  .github/workflows/actionlint.yml
  .github/workflows/all-green.yml
  .github/workflows/appsec.yml
  .github/workflows/ci-visibility-performance.yml
  .github/workflows/core.yml
  .github/workflows/datadog-static-analysis.yml
  .github/workflows/debugger.yml
  .github/workflows/instrumentations.yml
  .github/workflows/lambda.yml
  .github/workflows/llmobs.yml
  .github/workflows/package-size.yml
  .github/workflows/plugins.yml
  .github/workflows/profiling.yml
  .github/workflows/project.yml
  .github/workflows/serverless-integration-test.yml
  .github/workflows/system-tests.yml
  .github/workflows/tracing.yml
Labels: semver-patch

#5196 add concurrency group to all-green ci job
  .github/workflows/all-green.yml
Labels: semver-patch

#5012 ESM support for iast
  integration-tests/appsec/esm-app/custom-noop-hooks.mjs
  integration-tests/appsec/esm-app/index.mjs
  integration-tests/appsec/esm-app/more.mjs
  integration-tests/appsec/esm-app/worker-dep.mjs
  integration-tests/appsec/esm-app/worker.mjs
  integration-tests/appsec/iast.esm.spec.js
  package.json
  packages/dd-trace/src/appsec/iast/taint-tracking/constants.js
  packages/dd-trace/src/appsec/iast/taint-tracking/rewriter-esm.mjs
  packages/dd-trace/src/appsec/iast/taint-tracking/rewriter-telemetry.js
  packages/dd-trace/src/appsec/iast/taint-tracking/rewriter.js
  packages/dd-trace/test/appsec/iast/taint-tracking/rewriter-telemetry.spec.js
  packages/dd-trace/test/appsec/iast/taint-tracking/rewriter.spec.js
  yarn.lock
Labels: semver-minor

#5191 [test optimization] [SDTEST-1243] Add tag whenever the test service is provided by the user
  integration-tests/cucumber/cucumber.spec.js
  integration-tests/cypress/cypress.spec.js
  integration-tests/jest/jest.spec.js
  integration-tests/mocha/mocha.spec.js
  integration-tests/playwright/playwright.spec.js
  integration-tests/vitest/vitest.spec.js
  packages/datadog-plugin-cypress/src/cypress-plugin.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/plugin_manager.js
  packages/dd-trace/src/plugins/util/test.js
Labels: ci-app, semver-minor

#5219 Temporarily skip plugin-mongoose test for 8.10.0
  packages/datadog-plugin-mongoose/test/index.spec.js
Labels: semver-patch

#5222 Fix flaky test in rewriter.spec.js
  packages/dd-trace/test/appsec/iast/taint-tracking/rewriter.spec.js
Labels: semver-patch, asm-iast

#5209 remove ability to propagate baggage on its own to avoid app crashes
  packages/dd-trace/src/opentracing/propagation/text_map.js
  packages/dd-trace/test/opentracing/propagation/text_map.spec.js
Labels: semver-patch

#5214 Clean up ESLint config
  benchmark/sirun/appsec-iast/insecure-bank.js
  benchmark/sirun/appsec/insecure-bank.js
  eslint.config.mjs
  integration-tests/.eslintrc.json
  integration-tests/appsec/esm-app/worker.mjs
  package.json
  packages/.eslintrc.json
  packages/dd-trace/test/.eslintrc.json
  packages/dd-trace/test/debugger/devtools_client/state.spec.js
  packages/dd-trace/test/encode/0.5.spec.js
  packages/dd-trace/test/format.spec.js
  packages/dd-trace/test/lambda/fixtures/handler.js
  packages/dd-trace/test/llmobs/sdk/index.spec.js
  packages/dd-trace/test/profiling/.eslintrc.json
  yarn.lock
Labels: semver-patch

#5217 Fix mongoose plugin tests
  packages/datadog-plugin-mongoose/test/index.spec.js
  packages/dd-trace/test/setup/mocha.js
Labels: semver-patch

#5212 chore(graphql): only stringify graphql error extension attributes in span event if not a native type
  packages/datadog-plugin-graphql/src/utils.js
Labels: semver-patch

#5202 [DSM] Add a wait for active stream to the putTestRecords function which was flaking when the stream was inactive
  packages/datadog-plugin-aws-sdk/test/kinesis_helpers.js
Labels: semver-patch

#5240 dd-trace-api: don't proxy objects returned from callbacks
  packages/datadog-plugin-dd-trace-api/src/index.js
  packages/datadog-plugin-dd-trace-api/test/index.spec.js
Labels: semver-patch

#5238 datadog-plugin-mongoose test remove forgotten skip condition for versions >= 8.10.0
  packages/datadog-plugin-mongoose/test/index.spec.js
Labels: semver-patch

#5171 Extended iast location fields
  packages/dd-trace/src/appsec/iast/analyzers/vulnerability-analyzer.js
  packages/dd-trace/src/appsec/iast/vulnerabilities-formatter/index.js
  packages/dd-trace/src/appsec/iast/vulnerability-reporter.js
  packages/dd-trace/test/appsec/iast/analyzers/hsts-header-missing-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/vulnerability-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/xcontenttype-header-missing-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/taint-tracking/sources/sql_row.sequelize.plugin.spec.js
  packages/dd-trace/test/appsec/iast/utils.js
  packages/dd-trace/test/appsec/iast/vulnerability-formatter/index.spec.js
Labels: semver-minor, asm-iast

#5215 Upgrade ESLint from v8 to v9
  eslint.config.mjs
  integration-tests/ci-visibility/dynamic-instrumentation/test-hit-breakpoint.js
  integration-tests/ci-visibility/dynamic-instrumentation/test-not-hit-breakpoint.js
  integration-tests/ci-visibility/jest-flaky/flaky-fails.js
  integration-tests/ci-visibility/jest-flaky/flaky-passes.js
  integration-tests/ci-visibility/jestEnvironmentBadInit.js
  integration-tests/ci-visibility/run-workerpool.js
  integration-tests/ci-visibility/subproject/cypress/support/e2e.js
  integration-tests/ci-visibility/subproject/subproject-test.js
  integration-tests/ci-visibility/test-early-flake-detection/jest-snapshot.js
  integration-tests/cypress-esm-config.mjs
  integration-tests/package-guardrails/index.js
  loader-hook.mjs
  package.json
  packages/datadog-instrumentations/test/generic-pool.spec.js
  packages/datadog-instrumentations/test/mongoose.spec.js
  packages/datadog-instrumentations/test/url.spec.js
  packages/datadog-plugin-aerospike/test/index.spec.js
  packages/datadog-plugin-amqplib/test/index.spec.js
  packages/datadog-plugin-aws-sdk/test/stepfunctions.spec.js
  packages/datadog-plugin-connect/test/index.spec.js
  packages/datadog-plugin-express/test/index.spec.js
  packages/datadog-plugin-fastify/test/tracing.spec.js
  packages/datadog-plugin-fs/test/index.spec.js
  packages/datadog-plugin-http2/test/client.spec.js
  packages/datadog-plugin-mariadb/test/index.spec.js
  packages/datadog-plugin-mysql/test/index.spec.js
  packages/datadog-plugin-mysql2/test/index.spec.js
  packages/datadog-plugin-next/test/server.js
  packages/datadog-plugin-openai/src/tracing.js
  packages/datadog-plugin-router/test/index.spec.js
  packages/dd-trace/src/spanleak.js
  packages/dd-trace/test/appsec/iast/analyzers/resources/fs-async-way-method.js
  packages/dd-trace/test/appsec/iast/resources/eval.js
  packages/dd-trace/test/appsec/next/pages-dir/server.js
  packages/dd-trace/test/ci-visibility/dynamic-instrumentation/target-app/di-dependency.js
  packages/dd-trace/test/custom-metrics.spec.js
  packages/dd-trace/test/exporters/common/request.spec.js
  packages/dd-trace/test/plugins/suite.js
  packages/dd-trace/test/profiling/exporters/agent.spec.js
  scripts/st.js
  yarn.lock
Labels: semver-patch

#5235 change RASP addresses from persistent to ephemeral
  packages/dd-trace/src/appsec/rasp/command_injection.js
  packages/dd-trace/src/appsec/rasp/lfi.js
  packages/dd-trace/src/appsec/rasp/sql_injection.js
  packages/dd-trace/src/appsec/rasp/ssrf.js
  packages/dd-trace/test/appsec/rasp/command_injection.spec.js
  packages/dd-trace/test/appsec/rasp/lfi.spec.js
  packages/dd-trace/test/appsec/rasp/sql_injection.spec.js
  packages/dd-trace/test/appsec/rasp/ssrf.spec.js
Labels: semver-patch, asm-waf

#5248 Temporarily limit koa upstream tests to test against 2.15.3
  packages/datadog-plugin-koa/test/suite.js
Labels: semver-patch

#5249 Revert "Temporarily limit koa upstream tests to test against 2.15.3"
  packages/datadog-plugin-koa/test/suite.js
Labels: semver-patch

#5117 [asm] IAST security controls
  index.d.ts
  integration-tests/appsec/esm-security-controls/index.mjs
  integration-tests/appsec/esm-security-controls/sanitizer-default.mjs
  integration-tests/appsec/esm-security-controls/sanitizer.mjs
  integration-tests/appsec/esm-security-controls/validator.mjs
  integration-tests/appsec/iast.esm-security-controls.spec.js
  package.json
  packages/dd-trace/src/appsec/iast/analyzers/code-injection-analyzer.js
  packages/dd-trace/src/appsec/iast/analyzers/injection-analyzer.js
  packages/dd-trace/src/appsec/iast/analyzers/nosql-injection-mongodb-analyzer.js
  packages/dd-trace/src/appsec/iast/analyzers/sql-injection-analyzer.js
  packages/dd-trace/src/appsec/iast/analyzers/stored-injection-analyzer.js
  packages/dd-trace/src/appsec/iast/analyzers/template-injection-analyzer.js
  packages/dd-trace/src/appsec/iast/analyzers/vulnerability-analyzer.js
  packages/dd-trace/src/appsec/iast/index.js
  packages/dd-trace/src/appsec/iast/security-controls/index.js
  packages/dd-trace/src/appsec/iast/security-controls/parser.js
  packages/dd-trace/src/appsec/iast/taint-tracking/operations.js
  packages/dd-trace/src/appsec/iast/taint-tracking/secure-marks-generator.js
  packages/dd-trace/src/appsec/iast/taint-tracking/secure-marks.js
  packages/dd-trace/src/appsec/iast/telemetry/iast-metric.js
  packages/dd-trace/src/appsec/iast/utils.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/ritm.js
  packages/dd-trace/test/appsec/iast/analyzers/injection-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/nosql-injection-mongodb-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/sql-injection-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/security-controls/index.spec.js
  packages/dd-trace/test/appsec/iast/security-controls/parser.spec.js
  packages/dd-trace/test/appsec/iast/security-controls/resources/custom_input_validator.js
  packages/dd-trace/test/appsec/iast/security-controls/resources/node_modules/anotherlib/node_modules/sanitizer/index.js
  packages/dd-trace/test/appsec/iast/security-controls/resources/node_modules/sanitizer/index.js
  packages/dd-trace/test/appsec/iast/security-controls/resources/sanitizer.js
  packages/dd-trace/test/appsec/iast/security-controls/resources/sanitizer_default.js
  packages/dd-trace/test/appsec/iast/taint-tracking/secure-marks-generator.spec.js
  packages/dd-trace/test/appsec/iast/taint-tracking/secure-marks.spec.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/ritm-tests/module-default.js
  packages/dd-trace/test/ritm.spec.js
  yarn.lock
Labels: semver-minor, asm-iast

#5244 fix(config): keep the lookup value as passed
  packages/dd-trace/src/config.js
  packages/dd-trace/test/config.spec.js
Labels: semver-patch

#5252 prevent usage of semver in code
  eslint.config.mjs
Labels: semver-patch

#5243 [MLOB-2096] feat(llmobs): metadata and metrics annotations update instead of override
  packages/dd-trace/src/llmobs/tagger.js
  packages/dd-trace/test/llmobs/tagger.spec.js
Labels: semver-minor

#5246 dd-trace-api: remove runtime tests that should be test time
  packages/datadog-plugin-dd-trace-api/src/index.js
  packages/datadog-plugin-dd-trace-api/test/index.spec.js
Labels: semver-patch

#5261 ESLint: Disallow warnings in CI
  package.json
  packages/dd-trace/test/config.spec.js
Labels: semver-patch

#5264 change telemetry name for dd-trace-api
  packages/datadog-plugin-dd-trace-api/src/index.js
Labels: semver-patch

#5271 fix(openai): update openai instrumentation for newest release
  packages/datadog-instrumentations/src/openai.js
Labels: semver-patch

#5265 remove span kind from inferred proxy spans
  packages/dd-trace/src/plugins/util/inferred_proxy.js
  packages/dd-trace/test/plugins/util/inferred_proxy.spec.js
Labels: semver-minor

#5230 Inject trace info as comment to MongoDB operation when dbm propagation is enabled.
  docker-compose.yml
  packages/datadog-plugin-mongodb-core/src/index.js
  packages/datadog-plugin-mongodb-core/test/core.spec.js
  packages/datadog-plugin-mongodb-core/test/mongodb.spec.js
  packages/dd-trace/src/plugins/database.js
Labels: semver-minor, integration-mongodb

#5276 fix(openai): apply span char limit truncation to chat completion input tags
  packages/datadog-plugin-openai/src/tracing.js
  packages/datadog-plugin-openai/test/index.spec.js
Labels: semver-patch

#5205 [DI] Add source map support
  eslint.config.mjs
  integration-tests/debugger/basic.spec.js
  integration-tests/debugger/source-map-support.spec.js
  integration-tests/debugger/target-app/source-map-support/index.js
  integration-tests/debugger/target-app/source-map-support/index.js.map
  integration-tests/debugger/target-app/source-map-support/index.ts
  integration-tests/debugger/utils.js
  packages/datadog-plugin-cucumber/src/index.js
  packages/datadog-plugin-mocha/src/index.js
  packages/dd-trace/src/ci-visibility/dynamic-instrumentation/worker/index.js
  packages/dd-trace/src/debugger/devtools_client/breakpoints.js
  packages/dd-trace/src/debugger/devtools_client/source-maps.js
  packages/dd-trace/src/debugger/devtools_client/state.js
  packages/dd-trace/test/debugger/devtools_client/source-maps.spec.js
  packages/dd-trace/test/debugger/devtools_client/state.spec.js
  packages/dd-trace/test/debugger/devtools_client/utils.js
Labels: semver-minor, dynamic-instrumentation

#5273 [test optimization] Fix session fingerprint in playwright
  integration-tests/playwright/playwright.spec.js
  packages/datadog-plugin-playwright/src/index.js
  packages/dd-trace/src/plugins/util/test.js
Labels: ci-app, semver-patch

#5236 [test optimization] [SDTEST-1529] Add quarantined tests logic
  integration-tests/ci-visibility-intake.js
  integration-tests/ci-visibility/features-quarantine/quarantine.feature
  integration-tests/ci-visibility/features-quarantine/support/steps.js
  integration-tests/ci-visibility/playwright-tests-quarantine/quarantine-test.js
  integration-tests/ci-visibility/quarantine/test-quarantine-1.js
  integration-tests/ci-visibility/quarantine/test-quarantine-2.js
  integration-tests/ci-visibility/run-jest.js
  integration-tests/ci-visibility/run-mocha.js
  integration-tests/ci-visibility/vitest-tests/test-quarantine.mjs
  integration-tests/cucumber/cucumber.spec.js
  integration-tests/cypress-esm-config.mjs
  integration-tests/cypress/cypress.spec.js
  integration-tests/cypress/e2e/quarantine.js
  integration-tests/jest/jest.spec.js
  integration-tests/mocha/mocha.spec.js
  integration-tests/playwright/playwright.spec.js
  integration-tests/vitest/vitest.spec.js
  packages/datadog-instrumentations/src/cucumber.js
  packages/datadog-instrumentations/src/jest.js
  packages/datadog-instrumentations/src/mocha/main.js
  packages/datadog-instrumentations/src/mocha/utils.js
  packages/datadog-instrumentations/src/mocha/worker.js
  packages/datadog-instrumentations/src/playwright.js
  packages/datadog-instrumentations/src/vitest.js
  packages/datadog-plugin-cucumber/src/index.js
  packages/datadog-plugin-cypress/src/cypress-plugin.js
  packages/datadog-plugin-jest/src/index.js
  packages/datadog-plugin-mocha/src/index.js
  packages/datadog-plugin-playwright/src/index.js
  packages/datadog-plugin-vitest/src/index.js
  packages/dd-trace/src/ci-visibility/exporters/ci-visibility-exporter.js
  packages/dd-trace/src/ci-visibility/quarantined-tests/get-quarantined-tests.js
  packages/dd-trace/src/ci-visibility/requests/get-library-configuration.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/plugins/ci_plugin.js
  packages/dd-trace/src/plugins/util/test.js
Labels: ci-app, semver-minor

#5279 [DI] Use column number from source maps
  eslint.config.mjs
  integration-tests/debugger/source-map-support.spec.js
  integration-tests/debugger/target-app/source-map-support/index.js.map
  integration-tests/debugger/target-app/source-map-support/minify.js
  integration-tests/debugger/target-app/source-map-support/minify.min.js
  integration-tests/debugger/target-app/source-map-support/minify.min.js.map
  integration-tests/debugger/target-app/source-map-support/scripts/build-minifiy.sh
  integration-tests/debugger/target-app/source-map-support/scripts/build-typescript.sh
  integration-tests/debugger/target-app/source-map-support/typescript.js
  integration-tests/debugger/target-app/source-map-support/typescript.js.map
  integration-tests/debugger/target-app/source-map-support/typescript.ts
  packages/dd-trace/src/ci-visibility/dynamic-instrumentation/worker/index.js
  packages/dd-trace/src/debugger/devtools_client/breakpoints.js
  packages/dd-trace/src/debugger/devtools_client/source-maps.js
  packages/dd-trace/test/debugger/devtools_client/source-maps.spec.js
Labels: semver-patch, dynamic-instrumentation

#5285 Bump esbuild dev-dependency from 0.16.12 to 0.25.0
  package.json
  yarn.lock
Labels: semver-patch

#5283 [test optimization] Change failed test replay to opt out rather than opt in
  integration-tests/cucumber/cucumber.spec.js
  integration-tests/jest/jest.spec.js
  integration-tests/mocha/mocha.spec.js
  integration-tests/vitest/vitest.spec.js
  packages/dd-trace/src/ci-visibility/dynamic-instrumentation/index.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/plugins/ci_plugin.js
  packages/dd-trace/test/config.spec.js
Labels: ci-app, semver-patch

#5286 Increase the benchmark timeout from 15 to 20 minutes
  .gitlab/benchmarks.yml
Labels: semver-patch

#5284 Increase GraphQL benchmark stability
  benchmark/sirun/plugin-graphql/meta.json
  benchmark/sirun/plugin-graphql/schema.js
Labels: semver-patch

#5290 [DI] Workaround bug in AsyncLocalStorage which would otherwise throw
  .github/workflows/system-tests.yml
  packages/dd-trace/src/debugger/devtools_client/breakpoints.js
  packages/dd-trace/src/debugger/devtools_client/source-maps.js
  packages/dd-trace/test/debugger/devtools_client/source-maps.spec.js
Labels: semver-patch, dynamic-instrumentation

#5293 [test optimization] Lighter init in worker thread
  ci/init.js
  packages/dd-trace/src/ci-visibility/dynamic-instrumentation/index.js
Labels: ci-app, semver-patch

#5278 (chore) APM: Fix Bedrock Integration Refactor
  packages/datadog-instrumentations/src/aws-sdk.js
Labels: semver-patch

#5294 tracing: fix http client synchronous errors causing spans to not finish
  packages/datadog-instrumentations/src/http/client.js
  packages/datadog-plugin-http/src/client.js
  packages/datadog-plugin-http/test/client.spec.js
Labels: semver-patch

#5253 [MLOB-2233] feat(openai, llmobs): patch `_thenUnwrap` of chat completion api promise instances
  packages/datadog-instrumentations/src/openai.js
  packages/datadog-plugin-openai/test/index.spec.js
Labels: semver-minor

#5299 Add pipeline to Mongodb query
  packages/datadog-plugin-mongodb-core/src/index.js
  packages/datadog-plugin-mongodb-core/test/mongodb.spec.js
Labels: semver-minor, integration-mongodb

#5021 Enable 128 bit trace id log injection by default
  integration-tests/pino/index.js
  packages/datadog-plugin-bunyan/test/index.spec.js
  packages/datadog-plugin-pino/test/index.spec.js
  packages/datadog-plugin-winston/test/index.spec.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/opentracing/propagation/log.js
  packages/dd-trace/src/telemetry/index.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/opentracing/propagation/log.spec.js
  packages/dd-trace/test/plugins/log_plugin.spec.js
Labels: semver-minor

#5300 Add bot to manage stale PRs
  .github/workflows/stale.yml
  scripts/verify-ci-config.js
Labels: semver-patch

#5223 Make DD_TRACE_128_BIT_TRACEID_GENERATION_ENABLED consistent
  packages/dd-trace/src/opentracing/propagation/text_map.js
  packages/dd-trace/test/opentracing/propagation/text_map.spec.js
Labels: semver-patch

#5232 Make DD_TRACE_SAMPLING_RULES consistent
  packages/dd-trace/src/sampling_rule.js
  packages/dd-trace/src/util.js
Labels: semver-patch

#5291 [test optimization] Configuration parameter to disable git unshallow
  packages/dd-trace/src/ci-visibility/exporters/git/git_metadata.js
  packages/dd-trace/test/ci-visibility/exporters/git/git_metadata.spec.js
Labels: ci-app, semver-patch

#5267 [MLOB-2240] fix(openai, langchain, llmobs): OpenAI and LangChain instrumentation is ESM-compatible
  initialize.mjs
  packages/datadog-instrumentations/src/helpers/hooks.js
  packages/datadog-instrumentations/src/openai.js
  packages/datadog-plugin-langchain/test/integration-test/client.spec.js
  packages/datadog-plugin-langchain/test/integration-test/server.mjs
  packages/datadog-plugin-openai/test/integration-test/client.spec.js
  packages/datadog-plugin-openai/test/integration-test/server.mjs
  register.js
Labels: semver-patch

#5304 [test optimization] Add support for Drone CI
  packages/dd-trace/src/plugins/util/ci.js
  packages/dd-trace/test/plugins/util/ci-env/azurepipelines.json
  packages/dd-trace/test/plugins/util/ci-env/bitbucket.json
  packages/dd-trace/test/plugins/util/ci-env/bitrise.json
  packages/dd-trace/test/plugins/util/ci-env/buddy.json
  packages/dd-trace/test/plugins/util/ci-env/buildkite.json
  packages/dd-trace/test/plugins/util/ci-env/circleci.json
  packages/dd-trace/test/plugins/util/ci-env/drone.json
  packages/dd-trace/test/plugins/util/ci-env/gitlab.json
  packages/dd-trace/test/plugins/util/ci-env/jenkins.json
  packages/dd-trace/test/plugins/util/ci-env/usersupplied.json
Labels: ci-app, semver-patch

#5239 [DSM] Add messaging.destination tag to spans so they show up in queue pages
  packages/datadog-plugin-kafkajs/src/consumer.js
  packages/datadog-plugin-kafkajs/src/producer.js
  packages/datadog-plugin-kafkajs/test/index.spec.js
Labels: semver-minor

#5266 Update span pointer env vars
  packages/datadog-plugin-aws-sdk/src/base.js
  packages/datadog-plugin-aws-sdk/src/services/dynamodb.js
  packages/datadog-plugin-aws-sdk/test/dynamodb.spec.js
  packages/dd-trace/src/config.js
Labels: semver-minor

#5306 Fix MongoDB DBM propagation issue where trace comments are not properly injected into commands
  packages/datadog-plugin-mongodb-core/src/index.js
  packages/datadog-plugin-mongodb-core/test/core.spec.js
  packages/datadog-plugin-mongodb-core/test/mongodb.spec.js
Labels: semver-patch, mergequeue-status: removed

#5260 move otel to datadog context conversion on otel side
  packages/dd-trace/src/opentelemetry/tracer.js
  packages/dd-trace/src/opentracing/propagation/text_map.js
Labels: semver-patch

#5143 fix tracer flare log
  packages/dd-trace/src/flare/index.js
  packages/dd-trace/test/flare.spec.js
Labels: semver-patch

#5061 refactor custom metrics to be self-contained
  packages/dd-trace/src/dogstatsd.js
  packages/dd-trace/src/proxy.js
  packages/dd-trace/test/dogstatsd.spec.js
  packages/dd-trace/test/proxy.spec.js
Labels: semver-patch

#5258 lazy load telemetry entrypoint only when needed
  packages/dd-trace/src/telemetry/index.js
  packages/dd-trace/src/telemetry/telemetry.js
  packages/dd-trace/test/appsec/iast/telemetry/logs.spec.js
  packages/dd-trace/test/telemetry/index.spec.js
Labels: semver-patch

#5250 Add stack id in location as a string
  packages/dd-trace/src/appsec/iast/analyzers/vulnerability-analyzer.js
  packages/dd-trace/src/appsec/iast/iast-context.js
  packages/dd-trace/src/appsec/iast/vulnerabilities-formatter/index.js
  packages/dd-trace/src/appsec/iast/vulnerability-reporter.js
  packages/dd-trace/test/appsec/iast/analyzers/vulnerability-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/vulnerability-formatter/index.spec.js
  packages/dd-trace/test/appsec/iast/vulnerability-reporter.spec.js
Labels: semver-patch, asm-iast, appsec

#5296 [test optimization] Fix wrong `log.error` if quarantined tests are empty
  packages/datadog-instrumentations/src/jest.js
Labels: ci-app, semver-patch

#5302 [DI] Remove source map cache
  packages/dd-trace/src/debugger/devtools_client/source-maps.js
  packages/dd-trace/test/debugger/devtools_client/source-maps.spec.js
Labels: semver-patch, mergequeue-status: removed, dynamic-instrumentation

#5224 add dynamodb payload tagging
  packages/datadog-plugin-aws-sdk/src/services/dynamodb.js
  packages/datadog-plugin-aws-sdk/test/dynamodb.spec.js
  packages/dd-trace/src/payload-tagging/config/aws.json
Labels: semver-minor, integration-aws-sdk, mergequeue-status: removed

#5315 security: fix VULN-9754
  packages/datadog-plugin-azure-functions/test/integration-test/fixtures/yarn.lock
Labels: semver-patch

#5272 only load fetch plugin when fetch is used
  packages/datadog-instrumentations/src/fetch.js
  packages/datadog-instrumentations/src/helpers/fetch.js
  packages/dd-trace/src/plugin_manager.js
Labels: semver-patch

#5227 fix logging when extracting from w3c traceparent
  packages/dd-trace/src/opentracing/propagation/text_map.js
  packages/dd-trace/test/opentracing/propagation/text_map.spec.js
Labels: semver-patch

#5254 lazy load runtime metrics only when needed
  packages/dd-trace/src/runtime_metrics/index.js
  packages/dd-trace/src/runtime_metrics/runtime_metrics.js
  packages/dd-trace/test/runtime_metrics.spec.js
Labels: semver-patch

#5305 lazy load dsm only when needed
  packages/datadog-plugin-amqplib/src/consumer.js
  packages/datadog-plugin-amqplib/src/producer.js
  packages/datadog-plugin-avsc/src/schema_iterator.js
  packages/datadog-plugin-aws-sdk/src/services/kinesis.js
  packages/datadog-plugin-aws-sdk/src/services/sns.js
  packages/datadog-plugin-aws-sdk/src/services/sqs.js
  packages/datadog-plugin-google-cloud-pubsub/src/consumer.js
  packages/datadog-plugin-google-cloud-pubsub/src/producer.js
  packages/datadog-plugin-kafkajs/src/batch-consumer.js
  packages/datadog-plugin-kafkajs/src/consumer.js
  packages/datadog-plugin-kafkajs/src/producer.js
  packages/datadog-plugin-kafkajs/test/index.spec.js
  packages/datadog-plugin-protobufjs/src/schema_iterator.js
  packages/datadog-plugin-rhea/src/consumer.js
  packages/datadog-plugin-rhea/src/producer.js
  packages/dd-trace/src/datastreams/checkpointer.js
  packages/dd-trace/src/datastreams/context.js
  packages/dd-trace/src/datastreams/index.js
  packages/dd-trace/src/datastreams/manager.js
  packages/dd-trace/src/datastreams/processor.js
  packages/dd-trace/src/datastreams/size.js
  packages/dd-trace/src/opentracing/propagation/text_map_dsm.js
  packages/dd-trace/src/tracer.js
Labels: semver-patch

#5259 lazy load span leak detection only when used
  packages/dd-trace/src/opentracing/span.js
  packages/dd-trace/src/proxy.js
Labels: semver-patch

#5309 ESLint: Add yarn lint:inspect command
  package.json
Labels: semver-patch

#5297 ESLint: Add eslint-plugin-unicorn
  LICENSE-3rdparty.csv
  eslint.config.mjs
  package.json
  yarn.lock
Labels: semver-patch

#5319 [DI] Improve code comment
  packages/dd-trace/src/debugger/devtools_client/source-maps.js
Labels: semver-patch, dynamic-instrumentation

#5060 Automated Session Tracking
  .github/workflows/instrumentations.yml
  packages/datadog-instrumentations/src/express-session.js
  packages/datadog-instrumentations/src/helpers/hooks.js
  packages/datadog-instrumentations/test/express-session.spec.js
  packages/dd-trace/src/appsec/addresses.js
  packages/dd-trace/src/appsec/channels.js
  packages/dd-trace/src/appsec/index.js
  packages/dd-trace/src/appsec/sdk/set_user.js
  packages/dd-trace/src/remote_config/capabilities.js
  packages/dd-trace/src/remote_config/index.js
  packages/dd-trace/test/appsec/index.spec.js
  packages/dd-trace/test/appsec/sdk/set_user.spec.js
  packages/dd-trace/test/plugins/externals.json
  packages/dd-trace/test/remote_config/index.spec.js
Labels: asm-waf, semver-minor

#5317 lazy load fetch instrumentation only when needed
  packages/datadog-instrumentations/src/fetch.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/serverless.js
Labels: semver-patch

#5318 only load the naming schema version that is used
  packages/dd-trace/src/service-naming/index.js
  packages/dd-trace/src/service-naming/schemas/index.js
  packages/dd-trace/test/setup/mocha.js
Labels: semver-patch

#5329 fix shimmer double wrapping for non-method functions
  packages/datadog-shimmer/src/shimmer.js
Labels: semver-patch

#5263 ESLint: Require await inside async functions
  benchmark/sirun/get-results.js
  eslint.config.mjs
  packages/datadog-instrumentations/src/apollo-server-core.js
  packages/datadog-instrumentations/src/apollo-server.js
  packages/datadog-instrumentations/src/jest.js
  packages/datadog-instrumentations/src/mocha/main.js
  packages/datadog-instrumentations/src/nyc.js
  packages/datadog-instrumentations/src/vitest.js
  packages/dd-trace/src/debugger/devtools_client/breakpoints.js
  packages/dd-trace/src/debugger/devtools_client/snapshot/collector.js
  packages/dd-trace/src/profiling/profiler.js
Labels: semver-patch

#5303 Split appsec telemetry file into rasp, waf and user
  packages/dd-trace/src/appsec/telemetry.js
  packages/dd-trace/src/appsec/telemetry/common.js
  packages/dd-trace/src/appsec/telemetry/index.js
  packages/dd-trace/src/appsec/telemetry/rasp.js
  packages/dd-trace/src/appsec/telemetry/user.js
  packages/dd-trace/src/appsec/telemetry/waf.js
  packages/dd-trace/test/appsec/telemetry/rasp.spec.js
  packages/dd-trace/test/appsec/telemetry/user.spec.js
  packages/dd-trace/test/appsec/telemetry/waf.spec.js
Labels: semver-patch, appsec

#5327 [test optimization] Lazy load failed test replay logic
  packages/dd-trace/src/ci-visibility/dynamic-instrumentation/index.js
  packages/dd-trace/src/plugins/ci_plugin.js
  packages/dd-trace/src/proxy.js
  packages/dd-trace/test/ci-visibility/dynamic-instrumentation/target-app/test-visibility-dynamic-instrumentation-script.js
Labels: ci-app, semver-patch

#5331 CI: Remove redundant GH Action steps
  .github/workflows/plugins.yml
  .github/workflows/project.yml
  .github/workflows/serverless-integration-test.yml
Labels: semver-patch

#5332 CI: Remove unused GH Actions
  .github/workflows/prepare-release-proposal.yml
  .github/workflows/rebase-release-proposal.yml
  scripts/prepare-release-proposal.js
  scripts/verify-ci-config.js
Labels: semver-patch

#5328 [test optimization] Fix possible crash with known tests
  packages/datadog-instrumentations/src/jest.js
  packages/datadog-instrumentations/src/mocha/main.js
  packages/datadog-instrumentations/src/nyc.js
  packages/datadog-instrumentations/src/vitest.js
Labels: ci-app, semver-patch

#5339 Add TODO comment about appsec code in RC index
  packages/dd-trace/src/remote_config/index.js
Labels: semver-patch, asm-waf

#5330 Add missing decrement method to DogStatsDClient
  index.d.ts
  packages/dd-trace/src/dogstatsd.js
  packages/dd-trace/src/noop/dogstatsd.js
  packages/dd-trace/test/dogstatsd.spec.js
  packages/dd-trace/test/proxy.spec.js
Labels: semver-patch

#5198 Disable APM tracing (standalone billing)
  docs/test.ts
  index.d.ts
  integration-tests/standalone-asm.spec.js
  package.json
  packages/dd-trace/src/appsec/iast/index.js
  packages/dd-trace/src/appsec/iast/vulnerability-reporter.js
  packages/dd-trace/src/appsec/reporter.js
  packages/dd-trace/src/appsec/sdk/track_event.js
  packages/dd-trace/src/appsec/standalone.js
  packages/dd-trace/src/appsec/user_tracking.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/constants.js
  packages/dd-trace/src/exporters/agent/index.js
  packages/dd-trace/src/priority_sampler.js
  packages/dd-trace/src/proxy.js
  packages/dd-trace/src/span_stats.js
  packages/dd-trace/src/standalone/index.js
  packages/dd-trace/src/standalone/product.js
  packages/dd-trace/src/standalone/tracesource.js
  packages/dd-trace/src/standalone/tracesource_priority_sampler.js
  packages/dd-trace/src/tracer.js
  packages/dd-trace/test/appsec/iast/index.spec.js
  packages/dd-trace/test/appsec/iast/vulnerability-reporter.spec.js
  packages/dd-trace/test/appsec/index.spec.js
  packages/dd-trace/test/appsec/reporter.spec.js
  packages/dd-trace/test/appsec/sdk/track_event.spec.js
  packages/dd-trace/test/appsec/user_tracking.spec.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/exporters/agent/exporter.spec.js
  packages/dd-trace/test/priority_sampler.spec.js
  packages/dd-trace/test/proxy.spec.js
  packages/dd-trace/test/span_stats.spec.js
  packages/dd-trace/test/standalone/index.spec.js
  packages/dd-trace/test/standalone/product.spec.js
  packages/dd-trace/test/standalone/tracesource.spec.js
  packages/dd-trace/test/standalone/tracesource_priority_sampler.spec.js
  packages/dd-trace/test/tracer.spec.js
Labels: semver-minor
