Repository DataDog/dd-trace-js, pull requests merged in 2025-04, with the labels that each got.

#4843 [test-optimization] [SDTEST-1163] Playwright active test span
  ci/init.js
  ext/exporters.d.ts
  ext/exporters.js
  integration-tests/ci-visibility/playwright-tests-active-test-span/active-test-span-custom-span-test.js
  integration-tests/ci-visibility/playwright-tests-active-test-span/active-test-span-tags-test.js
  integration-tests/playwright/playwright.spec.js
  packages/datadog-instrumentations/src/playwright.js
  packages/datadog-plugin-playwright/src/index.js
  packages/dd-trace/src/ci-visibility/exporters/test-worker/index.js
  packages/dd-trace/src/ci-visibility/exporters/test-worker/writer.js
  packages/dd-trace/src/exporter.js
  packages/dd-trace/src/plugins/util/test.js
Labels: ci-app, semver-minor

#5507 ci(openai, langchain, llmobs): fix broken tests
  packages/datadog-plugin-langchain/test/index.spec.js
  packages/datadog-plugin-openai/test/index.spec.js
  packages/dd-trace/test/llmobs/plugins/langchain/index.spec.js
  packages/dd-trace/test/llmobs/plugins/openai/openaiv4.spec.js
Labels: semver-patch

#5510 Pin express version to make sure integration tests pass
  integration-tests/appsec/iast.esm-security-controls.spec.js
  integration-tests/opentelemetry.spec.js
Labels: semver-patch

#5504 Always check for the latest Node.js version being installed
  .github/actions/node/action.yml
  .github/workflows/appsec.yml
  .github/workflows/plugins.yml
  .github/workflows/project.yml
  .github/workflows/release-3.yml
  .github/workflows/release-4.yml
  .github/workflows/release-dev.yml
  .github/workflows/release-latest.yml
  .github/workflows/release-proposal.yml
  .github/workflows/serverless-integration-test.yml
Labels: semver-patch

#5419 [Debugger] improve snapshot performance
  integration-tests/debugger/redact.spec.js
  integration-tests/debugger/snapshot-global-sample-rate.spec.js
  integration-tests/debugger/snapshot.spec.js
  integration-tests/helpers/fake-agent.js
  packages/dd-trace/src/debugger/devtools_client/index.js
  packages/dd-trace/src/debugger/devtools_client/snapshot/collector.js
  packages/dd-trace/src/debugger/devtools_client/snapshot/index.js
  packages/dd-trace/src/debugger/devtools_client/snapshot/processor.js
Labels: semver-patch

#5506 increase appsec next test start timeout to 5 minutes
  packages/dd-trace/test/appsec/index.next.plugin.spec.js
Labels: semver-patch

#5488 [DI] Add support for probe condition
  integration-tests/debugger/basic.spec.js
  packages/dd-trace/src/debugger/devtools_client/breakpoints.js
  packages/dd-trace/src/debugger/devtools_client/condition.js
  packages/dd-trace/src/debugger/index.js
  packages/dd-trace/test/debugger/devtools_client/condition-test-cases.js
  packages/dd-trace/test/debugger/devtools_client/condition.spec.js
Labels: semver-minor, dynamic-instrumentation

#5472 Update rewriter to the new renamed wasm-js-rewriter 3.1.0
  LICENSE-3rdparty.csv
  package.json
  packages/dd-trace/src/appsec/iast/taint-tracking/rewriter-esm.mjs
  packages/dd-trace/src/appsec/iast/taint-tracking/rewriter.js
  packages/dd-trace/test/appsec/iast/taint-tracking/rewriter.spec.js
  yarn.lock
Labels: semver-patch

#5517 Update rules to version 1.14.1
  packages/dd-trace/src/appsec/recommended.json
Labels: semver-minor

#5523 Update WAF rules to v1.14.2
  packages/dd-trace/src/appsec/recommended.json
Labels: semver-patch, asm-waf

#5518 Add message to the profiler startup error consistent with one in proxy.js
  packages/dd-trace/src/profiler.js
  packages/dd-trace/src/profiling/profiler.js
Labels: profiling, semver-patch

#5473 add missing shared config for clientIpHeader
  packages/datadog-plugin-koa/test/index.spec.js
  packages/dd-trace/src/plugin_manager.js
  packages/dd-trace/test/plugins/util/web.spec.js
Labels: semver-patch

#5530 Fix CI for mariadb
  packages/datadog-instrumentations/src/mariadb.js
Labels: semver-patch

#5509 [test-optimization] [SDTEST-1784] Co-relate Playwright tests with RUM sessions
  integration-tests/ci-visibility/playwright-tests-rum/active-test-span-rum-test.js
  integration-tests/ci-visibility/web-app-server.js
  integration-tests/playwright/playwright.spec.js
  packages/datadog-instrumentations/src/helpers/hooks.js
  packages/datadog-instrumentations/src/playwright.js
  packages/datadog-plugin-playwright/src/index.js
Labels: ci-app, semver-minor

#5408 Improve iast mongodb nosql detection removing some false positives
  packages/dd-trace/src/appsec/iast/analyzers/nosql-injection-mongodb-analyzer.js
  packages/dd-trace/test/appsec/iast/analyzers/nosql-injection-mongodb-analyzer.express-mongo-sanitize.plugin.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/nosql-injection-mongodb-analyzer.mquery.plugin.spec.js
  packages/dd-trace/test/plugins/externals.json
Labels: semver-minor, asm-iast

#5532 Supporting last mariadb version
  packages/datadog-instrumentations/src/mariadb.js
  packages/dd-trace/test/plugins/externals.json
Labels: semver-minor

#5526 add feature to disable mongo heartbeats spans
  packages/datadog-plugin-mongodb-core/src/index.js
  packages/datadog-plugin-mongodb-core/test/mongodb.spec.js
Labels: semver-minor

#5448 Pin composite actions SHA
  .github/actions/node/action.yml
  .github/actions/plugins/test-and-upstream/action.yml
  .github/actions/plugins/test/action.yml
  .github/actions/plugins/upstream/action.yml
  .github/actions/testagent/logs/action.yml
  .github/actions/testagent/start/action.yml
  .github/dependabot.yml
Labels: dev/tooling, semver-patch

#5520 [DI] Sanitize instanceof class in probe conditions
  packages/dd-trace/src/debugger/devtools_client/condition.js
  packages/dd-trace/test/debugger/devtools_client/condition-test-cases.js
Labels: semver-patch, dynamic-instrumentation

#5540 [DI] Change test name to better highlight what is being tested
  integration-tests/debugger/basic.spec.js
Labels: semver-patch, dynamic-instrumentation

#5539 [DI] Don't rely on logs track to split JSON keys on periods
  integration-tests/debugger/basic.spec.js
  integration-tests/debugger/redact.spec.js
  integration-tests/debugger/snapshot-global-sample-rate.spec.js
  integration-tests/debugger/snapshot-pruning.spec.js
  integration-tests/debugger/snapshot.spec.js
  integration-tests/debugger/source-map-support.spec.js
  packages/dd-trace/src/debugger/devtools_client/send.js
  packages/dd-trace/test/debugger/devtools_client/send.spec.js
Labels: semver-patch, dynamic-instrumentation

#5541 [DI] Conditions: Allow testing of primitives with instanceof
  packages/dd-trace/src/debugger/devtools_client/condition.js
  packages/dd-trace/test/debugger/devtools_client/condition-test-cases.js
  packages/dd-trace/test/debugger/devtools_client/condition.spec.js
Labels: semver-patch, dynamic-instrumentation

#5536 [DI] Reduce size of compiled code when comparing number literals
  packages/dd-trace/src/debugger/devtools_client/condition.js
  packages/dd-trace/test/debugger/devtools_client/condition-test-cases.js
Labels: semver-patch, dynamic-instrumentation

#5493 fix(llmobs): send batches of span events
  packages/dd-trace/src/llmobs/writers/spans/base.js
  packages/dd-trace/test/llmobs/sdk/typescript/index.spec.js
  packages/dd-trace/test/llmobs/writers/spans/base.spec.js
Labels: semver-patch

#5542 [DI] Condtions: Allow using len to count keys in objects
  packages/dd-trace/src/debugger/devtools_client/condition.js
  packages/dd-trace/test/debugger/devtools_client/condition-test-cases.js
Labels: semver-patch, dynamic-instrumentation

#5544 chore: fix loading of instrumentations
  packages/datadog-instrumentations/src/helpers/register.js
Labels: semver-patch

#5527 update the release proposal workflow to create the proposal
  .github/workflows/release-proposal.yml
  scripts/release/proposal.js
Labels: semver-patch

#5545 fix missing dependency for release proposal job
  .github/workflows/release-proposal.yml
Labels: semver-patch

#5524 Start collecting async IDs in profiles
  integration-tests/profiler/codehotspots.js
  integration-tests/profiler/profiler.spec.js
  package.json
  packages/dd-trace/src/profiling/config.js
  packages/dd-trace/src/profiling/profilers/wall.js
  packages/dd-trace/test/profiling/profilers/wall.spec.js
  yarn.lock
Labels: profiling, semver-minor

#5535 [DI] Support multiple probes in the same location
  integration-tests/debugger/basic.spec.js
  packages/dd-trace/src/debugger/devtools_client/breakpoints.js
  packages/dd-trace/src/debugger/devtools_client/index.js
  packages/dd-trace/src/debugger/devtools_client/lock.js
  packages/dd-trace/src/debugger/devtools_client/remote_config.js
  packages/dd-trace/src/debugger/devtools_client/state.js
  packages/dd-trace/test/debugger/devtools_client/breakpoints.spec.js
Labels: semver-minor, dynamic-instrumentation

#5534 Remove appsec distribution metrics
  packages/dd-trace/src/appsec/telemetry/rasp.js
  packages/dd-trace/src/appsec/telemetry/waf.js
  packages/dd-trace/test/appsec/telemetry/rasp.spec.js
  packages/dd-trace/test/appsec/telemetry/waf.spec.js
  packages/dd-trace/test/appsec/waf-metrics.integration.spec.js
Labels: semver-patch, appsec

#5547 remove application-config-path dependency
  .github/workflows/release-proposal.yml
  LICENSE-3rdparty.csv
  package.json
  scripts/release/helpers/requirements.js
  yarn.lock
Labels: semver-patch

#5549 Fix profiler test flakiness
  integration-tests/profiler/codehotspots.js
  integration-tests/profiler/profiler.spec.js
Labels: dev/testing, profiling, semver-patch

#5508 add support for cgroupv2 inode fallback
  packages/dd-trace/src/exporters/common/docker.js
  packages/dd-trace/src/exporters/common/request.js
  packages/dd-trace/src/profiling/exporters/agent.js
  packages/dd-trace/test/exporters/common/docker.spec.js
  packages/dd-trace/test/exporters/common/request.spec.js
  packages/dd-trace/test/profiling/exporters/agent.spec.js
Labels: semver-patch

#5550 [test-optimization] [SDTEST-1830] Add @test.retry_reason to the retries of different frameworks
  integration-tests/cucumber/cucumber.spec.js
  integration-tests/cypress/cypress.spec.js
  integration-tests/jest/jest.spec.js
  integration-tests/mocha/mocha.spec.js
  integration-tests/playwright/playwright.spec.js
  integration-tests/vitest/vitest.spec.js
  packages/datadog-instrumentations/src/cucumber.js
  packages/datadog-instrumentations/src/jest.js
  packages/datadog-instrumentations/src/mocha/main.js
  packages/datadog-instrumentations/src/mocha/utils.js
  packages/datadog-instrumentations/src/playwright.js
  packages/datadog-instrumentations/src/vitest.js
  packages/datadog-plugin-cucumber/src/index.js
  packages/datadog-plugin-cypress/src/cypress-plugin.js
  packages/datadog-plugin-jest/src/index.js
  packages/datadog-plugin-mocha/src/index.js
  packages/datadog-plugin-playwright/src/index.js
  packages/datadog-plugin-vitest/src/index.js
  packages/dd-trace/src/plugins/util/test.js
Labels: ci-app, semver-minor

#5560 Update profiler from 5.7.0 to 5.7.1
  package.json
  yarn.lock
Labels: semver-patch

#5561 Bump Appsec native packages
  package.json
  yarn.lock
Labels: semver-patch, appsec

#5557 fix shimmer slow shim by removing support for unwrap
  integration-tests/package-guardrails/index.js
  packages/datadog-shimmer/src/shimmer.js
  packages/datadog-shimmer/test/shimmer.spec.js
  packages/dd-trace/src/appsec/iast/taint-tracking/rewriter.js
  packages/dd-trace/test/appsec/iast/taint-tracking/rewriter.spec.js
Labels: semver-patch

#5559 Constrain async ID collection to main thread only
  packages/dd-trace/src/profiling/profilers/wall.js
Labels: profiling, semver-patch

#5563 update libdatadog to 0.5.1 and native-metrics to 3.1.1
  package.json
  yarn.lock
Labels: semver-patch

#5566 fix proposal script not checking out new branch
  scripts/release/proposal.js
Labels: semver-patch

#5494 new wasm rewriter w/ orchestrion
  .npmignore
  LICENSE-3rdparty.csv
  benchmark/sirun/runall.sh
  integration-tests/helpers/index.js
  integration-tests/init.spec.js
  package.json
  packages/datadog-instrumentations/orchestrion.yml
  packages/datadog-instrumentations/src/langchain.js
  packages/datadog-instrumentations/src/orchestrion-config/index.js
  packages/datadog-plugin-langchain/src/index.js
  packages/datadog-plugin-langchain/src/tracing.js
  packages/datadog-plugin-langchain/test/index.spec.js
  packages/datadog-plugin-langchain/test/integration-test/client.spec.js
  packages/datadog-plugin-langchain/test/integration-test/server.mjs
  packages/dd-trace/src/appsec/iast/taint-tracking/filter.js
  packages/dd-trace/src/appsec/iast/taint-tracking/index.js
  packages/dd-trace/src/appsec/iast/taint-tracking/rewriter-esm.mjs
  packages/dd-trace/src/appsec/iast/taint-tracking/rewriter-telemetry.js
  packages/dd-trace/src/appsec/iast/taint-tracking/rewriter.js
  packages/dd-trace/src/llmobs/plugins/base.js
  packages/dd-trace/src/llmobs/plugins/langchain/index.js
  packages/dd-trace/src/llmobs/plugins/openai.js
  packages/dd-trace/src/llmobs/plugins/vertexai.js
  packages/dd-trace/src/proxy.js
  packages/dd-trace/test/appsec/iast/analyzers/hardcoded-password-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/hardcoded-secret-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/overhead-controller.spec.js
  packages/dd-trace/test/appsec/iast/taint-tracking/index.spec.js
  packages/dd-trace/test/appsec/iast/taint-tracking/rewriter-telemetry.spec.js
  packages/dd-trace/test/appsec/iast/taint-tracking/rewriter.spec.js
  packages/dd-trace/test/appsec/iast/utils.js
  packages/dd-trace/test/llmobs/plugins/langchain/index.spec.js
  yarn.lock
Labels: semver-minor

#5333 Login events SDK v2
  docs/test.ts
  index.d.ts
  packages/dd-trace/src/appsec/sdk/index.js
  packages/dd-trace/src/appsec/sdk/noop.js
  packages/dd-trace/src/appsec/sdk/set_user.js
  packages/dd-trace/src/appsec/sdk/track_event.js
  packages/dd-trace/src/appsec/sdk/user_blocking.js
  packages/dd-trace/src/appsec/telemetry/index.js
  packages/dd-trace/src/appsec/telemetry/user.js
  packages/dd-trace/test/appsec/sdk/index.spec.js
  packages/dd-trace/test/appsec/sdk/track_event.spec.js
Labels: asm-waf, semver-minor, appsec

#5548 [DI] Process log template
  integration-tests/debugger/basic.spec.js
  integration-tests/debugger/target-app/template.js
  integration-tests/debugger/template.spec.js
  integration-tests/debugger/utils.js
  packages/dd-trace/src/debugger/devtools_client/breakpoints.js
  packages/dd-trace/src/debugger/devtools_client/condition.js
  packages/dd-trace/src/debugger/devtools_client/index.js
  packages/dd-trace/src/debugger/devtools_client/send.js
  packages/dd-trace/test/debugger/devtools_client/condition.spec.js
Labels: semver-minor, dynamic-instrumentation

#5572 [DI] Add debug log when translating breakpoint location using source map
  packages/dd-trace/src/debugger/devtools_client/breakpoints.js
  packages/dd-trace/src/debugger/devtools_client/source-maps.js
Labels: semver-patch, dynamic-instrumentation

#5578 switch from default token to app token for release proposal
  .github/workflows/release-proposal.yml
Labels: semver-patch

#5576 chore: ensure client ip header is converted to lowercase
  packages/datadog-plugin-koa/test/index.spec.js
  packages/dd-trace/src/config.js
Labels: semver-patch

#5584 fix elasticsearch 9 support
  packages/datadog-plugin-elasticsearch/test/index.spec.js
Labels: semver-patch

#5585 Update rewriter to fix stack traces on rewritten files in node 20+
  package.json
  yarn.lock
Labels: semver-patch

#5579 Only activate async_hooks when they're needed for profiler features
  packages/dd-trace/src/profiling/profilers/wall.js
Labels: profiling, semver-patch

#5580 add explicit handling of stack errors in logger
  packages/datadog-plugin-winston/test/index.spec.js
  packages/dd-trace/src/plugins/log_plugin.js
Labels: semver-patch

#5586 inline orchestrion.yml to avoid bundling issues
  packages/datadog-instrumentations/orchestrion.yml
  packages/datadog-instrumentations/src/orchestrion-config/index.js
Labels: semver-patch

#5587 add concurrency and matrix to release proposal
  .github/workflows/release-proposal.yml
  scripts/release/proposal.js
Labels: semver-patch

#5466 feat(llmobs): evaluation metrics can be submitted by agent proxy
  docs/test.ts
  packages/dd-trace/src/config.js
  packages/dd-trace/src/llmobs/constants/writers.js
  packages/dd-trace/src/llmobs/index.js
  packages/dd-trace/src/llmobs/sdk.js
  packages/dd-trace/src/llmobs/writers/base.js
  packages/dd-trace/src/llmobs/writers/evaluations.js
  packages/dd-trace/src/llmobs/writers/spans.js
  packages/dd-trace/src/llmobs/writers/spans/agentProxy.js
  packages/dd-trace/src/llmobs/writers/spans/agentless.js
  packages/dd-trace/src/llmobs/writers/util.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/llmobs/index.spec.js
  packages/dd-trace/test/llmobs/plugins/aws-sdk/bedrockruntime.spec.js
  packages/dd-trace/test/llmobs/plugins/google-cloud-vertexai/index.spec.js
  packages/dd-trace/test/llmobs/plugins/langchain/index.spec.js
  packages/dd-trace/test/llmobs/plugins/openai/openaiv3.spec.js
  packages/dd-trace/test/llmobs/plugins/openai/openaiv4.spec.js
  packages/dd-trace/test/llmobs/sdk/index.spec.js
  packages/dd-trace/test/llmobs/sdk/integration.spec.js
  packages/dd-trace/test/llmobs/sdk/typescript/index.ts
  packages/dd-trace/test/llmobs/writers/base.spec.js
  packages/dd-trace/test/llmobs/writers/evaluations.spec.js
  packages/dd-trace/test/llmobs/writers/spans.spec.js
  packages/dd-trace/test/llmobs/writers/spans/agentProxy.spec.js
  packages/dd-trace/test/llmobs/writers/spans/agentless.spec.js
Labels: semver-minor

#5595 [test-optimization] [SDTEST-1870] Add support for Playwright >= 1.52.0
  packages/datadog-instrumentations/src/playwright.js
Labels: ci-app, semver-patch

#5598 remove safeWrap from shimmer
  packages/datadog-shimmer/src/shimmer.js
  packages/datadog-shimmer/test/shimmer.spec.js
Labels: semver-patch

#5594 [test-optimization] [SDTEST-1871] Fix Playwright bug when redirecting
  packages/datadog-instrumentations/src/playwright.js
Labels: bug, ci-app, semver-patch

#5600 fix release proposal job failing to fetch existing main branch
  .github/workflows/release-proposal.yml
Labels: semver-patch

#5546 Fix span pointers env var & tests
  packages/datadog-plugin-aws-sdk/src/services/dynamodb.js
  packages/datadog-plugin-aws-sdk/test/dynamodb.spec.js
  packages/dd-trace/src/config.js
  packages/dd-trace/test/plugins/agent.js
Labels: semver-patch

#5602 Remove unnecessary dev dependencies
  LICENSE-3rdparty.csv
  package.json
  yarn.lock
Labels: semver-patch

#5597 Add shimmer shimmer benchmarks
  .gitlab/benchmarks.yml
  benchmark/sirun/README.md
  benchmark/sirun/means.js
  benchmark/sirun/shimmer-runtime/README.md
  benchmark/sirun/shimmer-runtime/index.js
  benchmark/sirun/shimmer-runtime/meta.json
  benchmark/sirun/shimmer-startup/README.md
  benchmark/sirun/shimmer-startup/index.js
  benchmark/sirun/shimmer-startup/meta.json
Labels: semver-patch

#5607 [test-optimization] [SDTEST-1871] Add tests for Playwright when redirecting
  integration-tests/ci-visibility/web-app-server-with-redirect.js
  integration-tests/playwright/playwright.spec.js
Labels: ci-app, semver-patch

#5613 cut down shimmer-startup benchmark so it can run in benchmarking platform
  benchmark/sirun/shimmer-startup/index.js
  benchmark/sirun/shimmer-startup/meta.json
Labels: semver-patch

#5611 [DI] Improve integration test failue output
  integration-tests/debugger/utils.js
Labels: semver-patch, dynamic-instrumentation

#5616 Upgrade get-port dev-dependency to v5.1.1
  package.json
  yarn.lock
Labels: semver-patch

#5610 [DI] Improve logging in integration tests
  integration-tests/debugger/target-app/basic.js
  integration-tests/debugger/target-app/redact.js
  integration-tests/debugger/target-app/snapshot-pruning.js
  integration-tests/debugger/target-app/snapshot.js
  integration-tests/debugger/target-app/template.js
Labels: semver-patch, dynamic-instrumentation

#5623 Do not test koa 1.x middleware signature in koa 3.x
  packages/datadog-plugin-koa/test/index.spec.js
Labels: semver-patch

#5622 Ensure correct spelling of Node.js
  README.md
  docs/API.md
  packages/dd-trace/src/appsec/iast/vulnerabilities-formatter/evidence-redaction/sensitive-analyzers/ldap-sensitive-analyzer.js
Labels: semver-patch

#5593 Improve shimmer instrumentation performance
  benchmark/benchmark.js
  benchmark/e2e/README.md
  benchmark/e2e/benchmark-run.js
  benchmark/e2e/express-helloworld-manyroutes/app.js
  benchmark/e2e/fake-agent.js
  benchmark/e2e/preamble.js
  benchmark/stubs/span.js
  docker-compose.yml
  package.json
  packages/datadog-shimmer/src/shimmer.js
  packages/datadog-shimmer/test/shimmer.spec.js
Labels: semver-patch

#5618 handle existing PRs remove inputs and add schedule
  .github/actions/install/branch-diff/action.yml
  .github/workflows/release-proposal.yml
  scripts/release/helpers/terminal.js
  scripts/release/proposal.js
Labels: semver-patch

#5634 Simplify AppSec config
  packages/dd-trace/src/config.js
Labels: semver-patch

#5614 Address cookie vulnerability cardinality
  index.d.ts
  packages/dd-trace/src/appsec/iast/analyzers/cookie-analyzer.js
  packages/dd-trace/src/appsec/iast/iast-plugin.js
  packages/dd-trace/src/config.js
  packages/dd-trace/test/appsec/iast/analyzers/cookie-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/insecure-cookie-analyzer.express.plugin.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/insecure-cookie-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/no-httponly-cookie-analyzer.express.plugin.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/no-httponly-cookie-analyzer.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/no-samesite-cookie-analyzer.express.plugin.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/no-samesite-cookie-analyzer.spec.js
  packages/dd-trace/test/config.spec.js
Labels: semver-minor

#5621 Turn async ID gathering off by default
  integration-tests/profiler/profiler.spec.js
  packages/dd-trace/src/profiling/config.js
  packages/dd-trace/src/profiling/profilers/wall.js
  packages/dd-trace/test/profiling/profilers/wall.spec.js
Labels: profiling, semver-patch

#5630 improve performance of dogstatsd client and ignore non-string name/tags
  packages/dd-trace/src/dogstatsd.js
  packages/dd-trace/test/runtime_metrics.spec.js
Labels: semver-patch

#5626 Link to ESM support documentation
  README.md
Labels: semver-patch
