Repository DataDog/dd-trace-js, pull requests merged in 2025-05, with the labels that each got.

#5642 switch all workflows to use the same datadog api key
  .github/workflows/datadog-static-analysis.yml
  .github/workflows/project.yml
Labels: semver-patch

#5637 remove serverless integration tests
  .github/workflows/serverless-integration-test.yml
  integration-tests/serverless/serverless.spec.js
  integration-tests/serverless/test-gcloud-function.sh
  integration-tests/serverless/test-project/.env.yaml
  integration-tests/serverless/test-project/index.js
  integration-tests/serverless/test-project/package.json
  package.json
Labels: semver-patch

#5638 feat(openai): change span resource names to be consistent between openai v3 and v4
  packages/datadog-plugin-openai/src/tracing.js
  packages/datadog-plugin-openai/test/index.spec.js
Labels: breaking-change, semver-major

#5641 add script to validate no unexpected commits in release proposal
  .github/workflows/release-validate.yml
  scripts/release/helpers/requirements.js
  scripts/release/proposal.js
  scripts/release/validate.js
  scripts/verify-ci-config.js
Labels: semver-patch

#5650 update PR template
  .github/pull_request_template.md
Labels: semver-patch

#5644 prevent exclusion of commit based on the release line
  scripts/release/proposal.js
Labels: semver-patch

#5228 [K9VULN-3470] ci: remove deprecated field in `datadog-static-analyzer-github-action`
  .github/workflows/datadog-static-analysis.yml
Labels: semver-patch

#5170 Avoid false-positives in integrations guardrails
  packages/datadog-instrumentations/src/helpers/register.js
Labels: semver-patch, stale

#5653 [test-optimization] [SDTEST-1954] Check objects before accessing them in Jest
  packages/datadog-instrumentations/src/jest.js
Labels: ci-app, semver-patch

#5608 [test-optimization] [SDTEST-1900] Add custom tags in hooks for Jest
  integration-tests/ci-visibility/test-custom-tags/custom-tags.js
  integration-tests/jest/jest.spec.js
  packages/datadog-instrumentations/src/jest.js
Labels: ci-app, semver-minor

#5651 remove release proposal dont-land-on checks
  scripts/release/proposal.js
Labels: semver-patch

#5661 restore dont-land-on exclusion
  scripts/release/proposal.js
Labels: semver-patch

#5663 fix release proposal not closing patch pr on minor
  scripts/release/proposal.js
Labels: semver-patch

#5671 use a fixed version for latest in node action
  .github/actions/node/action.yml
  .github/workflows/release-proposal.yml
  .github/workflows/release-validate.yml
Labels: semver-patch

#5639 switch to default github token for ci visibility benchmark
  .github/workflows/ci-visibility-performance.yml
  benchmark/e2e-ci/benchmark-run.js
Labels: semver-patch

#5675 revert node action default version
  .github/actions/node/action.yml
  .github/workflows/release-proposal.yml
  .github/workflows/release-validate.yml
Labels: semver-patch

#5631 Improve log safety
  packages/datadog-plugin-winston/test/index.spec.js
  packages/dd-trace/src/plugins/log_plugin.js
Labels: semver-patch

#5668 remove unused packages
  .gitignore
  LICENSE-3rdparty.csv
  package.json
  yarn.lock
Labels: semver-patch

#5679 fix(llmobs): llmobs data can be sent to agent proxy running on uds
  packages/dd-trace/src/llmobs/writers/base.js
  packages/dd-trace/test/llmobs/writers/base.spec.js
  packages/dd-trace/test/llmobs/writers/evaluations.spec.js
  packages/dd-trace/test/llmobs/writers/spans.spec.js
Labels: semver-patch

#5680 tracing: add support for pg cursors / streams
  packages/datadog-instrumentations/src/pg.js
  packages/datadog-plugin-pg/src/index.js
  packages/datadog-plugin-pg/test/index.spec.js
  packages/dd-trace/test/plugins/externals.json
Labels: semver-minor

#5659 fix rasp ssrf flaky test
  packages/dd-trace/test/appsec/rasp/ssrf.express.plugin.spec.js
Labels: semver-patch, appsec

#5681 fix(vitest): fix coverage not being reported when value is zero
  integration-tests/ci-visibility/vitest-tests/coverage-test-zero.mjs
  integration-tests/vitest/vitest.spec.js
  packages/datadog-plugin-vitest/src/index.js
Labels: semver-patch

#5667 Add a fake agent for all profiler integration tests
  integration-tests/profiler/profiler.spec.js
Labels: dev/testing, profiling, semver-patch

#5683 fix: Support for inode when /proc/self/cgroup is a multiline string
  packages/dd-trace/src/exporters/common/docker.js
  packages/dd-trace/test/exporters/common/docker.spec.js
Labels: semver-patch

#5687 Fix Node 24 warning for invoking fs.existsSync with invalid argument type
  packages/dd-trace/src/guardrails/telemetry.js
Labels: semver-patch

#5689 [DI] Fix tests in Node.js 24
  integration-tests/debugger/template.spec.js
Labels: semver-patch, dynamic-instrumentation

#5489 tracing: add support for @confluentinc/kafka-javascript
  .github/workflows/plugins.yml
  .github/workflows/system-tests.yml
  docs/API.md
  docs/add-redirects.sh
  docs/test.ts
  index.d.ts
  packages/datadog-instrumentations/src/confluentinc-kafka-javascript.js
  packages/datadog-instrumentations/src/helpers/hooks.js
  packages/datadog-plugin-confluentinc-kafka-javascript/src/batch-consumer.js
  packages/datadog-plugin-confluentinc-kafka-javascript/src/consumer.js
  packages/datadog-plugin-confluentinc-kafka-javascript/src/index.js
  packages/datadog-plugin-confluentinc-kafka-javascript/src/producer.js
  packages/datadog-plugin-confluentinc-kafka-javascript/test/index.spec.js
  packages/datadog-plugin-confluentinc-kafka-javascript/test/integration-test/client.spec.js
  packages/datadog-plugin-confluentinc-kafka-javascript/test/integration-test/server.mjs
  packages/datadog-plugin-confluentinc-kafka-javascript/test/naming.js
  packages/datadog-plugin-kafkajs/src/batch-consumer.js
  packages/datadog-plugin-kafkajs/src/consumer.js
  packages/datadog-plugin-kafkajs/src/producer.js
  packages/datadog-plugin-kafkajs/src/utils.js
  packages/dd-trace/src/plugins/index.js
  packages/dd-trace/src/service-naming/schemas/v0/messaging.js
  packages/dd-trace/src/service-naming/schemas/v1/messaging.js
  packages/dd-trace/test/plugins/externals.json
  packages/dd-trace/test/plugins/helpers.js
Labels: semver-minor

#5693 Update pprof-nodejs to 5.8.0
  package.json
  yarn.lock
Labels: semver-minor

#5665 re-enable release proposal dont-land-on checks
  scripts/release/proposal.js
  scripts/release/validate.js
Labels: semver-patch

#5695 [DI] Slight improvement to script-matching algorithm
  packages/dd-trace/src/debugger/devtools_client/state.js
Labels: semver-patch, dynamic-instrumentation

#5688 [test-optimization] [SDTEST-1983] Add commit sha to request of Test Management
  integration-tests/cucumber/cucumber.spec.js
  integration-tests/cypress/cypress.spec.js
  integration-tests/jest/jest.spec.js
  integration-tests/mocha/mocha.spec.js
  integration-tests/playwright/playwright.spec.js
  integration-tests/vitest/vitest.spec.js
  packages/dd-trace/src/ci-visibility/test-management/get-test-management-tests.js
  packages/dd-trace/src/plugins/util/test.js
Labels: ci-app, semver-minor

#5694 [DI] Add debug logs when starting/stopping the CDP session
  packages/dd-trace/src/debugger/devtools_client/breakpoints.js
Labels: semver-patch, dynamic-instrumentation

#5701 Bump taint tracking package
  package.json
  yarn.lock
Labels: semver-minor, asm-iast, appsec, node24

#5706 use no async context frame option for now
  .github/workflows/debugger.yml
  packages/dd-trace/test/setup/core.js
Labels: semver-patch

#5590 [LANGPLAT-380] Fix OOM tests flakiness
  integration-tests/profiler/oom.js
  integration-tests/profiler/profiler.spec.js
  packages/dd-trace/src/profiling/exporter_cli.js
Labels: semver-patch

#5713 Pin shared pipeline
  .gitlab-ci.yml
Labels: dev/tooling, semver-patch

#5365 add new baggage APIs which act on currently active baggage
  index.d.ts
  packages/dd-trace/src/baggage.js
  packages/dd-trace/src/noop/proxy.js
  packages/dd-trace/src/opentelemetry/context_manager.js
  packages/dd-trace/src/opentracing/propagation/text_map.js
  packages/dd-trace/src/proxy.js
  packages/dd-trace/test/opentracing/propagation/text_map.spec.js
  packages/dd-trace/test/proxy.spec.js
Labels: semver-minor

#5601 Add minimal fast path for esm being enabled
  packages/datadog-plugin-langchain/src/index.js
  packages/dd-trace/src/appsec/iast/taint-tracking/rewriter.js
Labels: semver-patch

#5722 fix child_process test on node 24
  .github/workflows/plugins.yml
Labels: semver-patch

#5717 simpler adding --no-async-context-frame
  packages/dd-trace/test/setup/core.js
Labels: semver-patch

#5724 docs: add node v24 warning to README
  README.md
Labels: semver-patch

#5714 [DI] Only send probes whos condition is actually met
  integration-tests/debugger/basic.spec.js
  packages/dd-trace/src/debugger/devtools_client/breakpoints.js
  packages/dd-trace/src/debugger/devtools_client/index.js
Labels: bug, semver-patch, dynamic-instrumentation

#5731 [DI] Use custom error property for errors reporting state snapshot
  integration-tests/debugger/snapshot-pruning.spec.js
  packages/dd-trace/src/debugger/devtools_client/send.js
Labels: semver-patch, dynamic-instrumentation

#5636 [DI] Support enabling Dynamic Instrumentation with simple boolean
  index.d.ts
  packages/dd-trace/src/config.js
  packages/dd-trace/test/config.spec.js
Labels: semver-patch, dynamic-instrumentation

#5711 [test-optimization] [SDTEST-1990] Make compatible Test Optimization instrumentations with Node 24
  .github/workflows/project.yml
  packages/datadog-instrumentations/src/cucumber.js
  packages/datadog-instrumentations/src/jest.js
  packages/datadog-instrumentations/src/mocha/main.js
  packages/datadog-instrumentations/src/mocha/utils.js
  packages/datadog-instrumentations/src/playwright.js
  packages/datadog-instrumentations/src/vitest.js
  packages/datadog-plugin-cucumber/src/index.js
  packages/datadog-plugin-jest/src/index.js
  packages/datadog-plugin-mocha/src/index.js
  packages/datadog-plugin-playwright/src/index.js
  packages/datadog-plugin-vitest/src/index.js
Labels: ci-app, semver-patch, node24

#5719 [DI] Improve error handling during snapshot collection
  packages/dd-trace/src/debugger/devtools_client/index.js
  packages/dd-trace/src/debugger/devtools_client/snapshot/index.js
  packages/dd-trace/test/debugger/devtools_client/snapshot/error-handling.spec.js
  packages/dd-trace/test/debugger/devtools_client/snapshot/stub-session.js
  packages/dd-trace/test/debugger/devtools_client/snapshot/utils.js
Labels: semver-patch, dynamic-instrumentation

#5715 [DI] Don't fail to trigger if one of multiple probe conditions throws
  integration-tests/debugger/basic.spec.js
  packages/dd-trace/src/debugger/devtools_client/breakpoints.js
  packages/dd-trace/test/debugger/devtools_client/breakpoints.spec.js
Labels: bug, semver-patch, dynamic-instrumentation

#5655 Report waf results
  packages/dd-trace/src/appsec/graphql.js
  packages/dd-trace/src/appsec/index.js
  packages/dd-trace/src/appsec/rasp/index.js
  packages/dd-trace/src/appsec/rasp/utils.js
  packages/dd-trace/src/appsec/sdk/user_blocking.js
  packages/dd-trace/src/appsec/telemetry/index.js
  packages/dd-trace/src/appsec/telemetry/rasp.js
  packages/dd-trace/src/appsec/waf/waf_context_wrapper.js
  packages/dd-trace/test/appsec/graphql.spec.js
  packages/dd-trace/test/appsec/index.spec.js
  packages/dd-trace/test/appsec/rasp/index.spec.js
  packages/dd-trace/test/appsec/rasp/utils.spec.js
  packages/dd-trace/test/appsec/sdk/user_blocking.spec.js
  packages/dd-trace/test/appsec/telemetry/rasp.spec.js
  packages/dd-trace/test/appsec/waf/index.spec.js
Labels: semver-patch, appsec

#5737 Add an env var for executing integration tests without a sandbox
  integration-tests/helpers/index.js
Labels: dev/testing, semver-patch

#5705 fix(llmobs): span tags update instead correctly
  packages/dd-trace/src/llmobs/tagger.js
  packages/dd-trace/test/llmobs/tagger.spec.js
Labels: semver-patch

#5740 Test profiling sample context propagation through promises
  integration-tests/profiler/codehotspots.js
Labels: dev/testing, profiling, semver-patch

#5739 Update default value for appsec.obfuscatorValueRegex config entry
  packages/dd-trace/src/config.js
  packages/dd-trace/test/config.spec.js
Labels: semver-patch, asm-waf

#5741 Pin shared pipeline with versioned url
  .gitlab-ci.yml
  .gitlab/one-pipeline.locked.yml
Labels: semver-patch

#5698 [DI] Fix race condition when applying probe at app boot
  integration-tests/debugger/re-evaluation.spec.js
  integration-tests/debugger/target-app/re-evaluation/index.js
  integration-tests/debugger/target-app/re-evaluation/package.json
  integration-tests/debugger/target-app/re-evaluation/unique-filename.js
  packages/dd-trace/src/debugger/devtools_client/breakpoints.js
  packages/dd-trace/src/debugger/devtools_client/state.js
  packages/dd-trace/test/debugger/devtools_client/breakpoints.spec.js
  packages/dd-trace/test/debugger/devtools_client/state.spec.js
Labels: bug, semver-patch, dynamic-instrumentation

#5682 Use errorMonitor symbol instead of listening to the error event
  packages/datadog-instrumentations/src/child_process.js
  packages/datadog-instrumentations/src/couchbase.js
  packages/datadog-instrumentations/src/fs.js
  packages/datadog-instrumentations/src/http/client.js
  packages/datadog-instrumentations/src/mysql2.js
  packages/datadog-instrumentations/src/net.js
  packages/datadog-instrumentations/src/pg.js
  packages/datadog-instrumentations/test/child_process.spec.js
  packages/datadog-instrumentations/test/mysql2.spec.js
  packages/datadog-plugin-fs/test/index.spec.js
  packages/datadog-plugin-http/test/client.spec.js
  packages/datadog-plugin-net/test/index.spec.js
  packages/datadog-plugin-pg/test/index.spec.js
Labels: semver-patch

#5745 Ignore appsec startup error in serverless
  packages/dd-trace/src/appsec/index.js
  packages/dd-trace/test/appsec/index.spec.js
Labels: semver-minor

#5632 Safer shimmer implementation
  packages/datadog-instrumentations/src/amqplib.js
  packages/datadog-instrumentations/src/express.js
  packages/datadog-instrumentations/src/helpers/register.js
  packages/datadog-instrumentations/src/jest.js
  packages/datadog-instrumentations/src/next.js
  packages/datadog-instrumentations/src/pg.js
  packages/datadog-instrumentations/src/url.js
  packages/datadog-plugin-next/test/index.spec.js
  packages/datadog-shimmer/src/shimmer.js
  packages/datadog-shimmer/test/shimmer.spec.js
Labels: semver-patch

#5700 [DI] Clear state when last probe is removed
  packages/dd-trace/src/debugger/devtools_client/breakpoints.js
  packages/dd-trace/src/debugger/devtools_client/state.js
  packages/dd-trace/test/debugger/devtools_client/breakpoints.spec.js
  packages/dd-trace/test/debugger/devtools_client/state.spec.js
Labels: bug, semver-patch, dynamic-instrumentation

#5704 tracing: fix kafka header injection error for older kafka brokers
  packages/datadog-instrumentations/src/confluentinc-kafka-javascript.js
  packages/datadog-instrumentations/src/kafkajs.js
  packages/datadog-plugin-confluentinc-kafka-javascript/test/index.spec.js
  packages/datadog-plugin-kafkajs/src/producer.js
  packages/datadog-plugin-kafkajs/test/index.spec.js
Labels: semver-minor, integration-kafkajs

#5753 [test-optimization] [SDTEST-2039] Remove unnecessary channels in Playwright
  packages/datadog-instrumentations/src/playwright.js
  packages/datadog-plugin-playwright/src/index.js
Labels: ci-app, semver-patch

#5751 Deprecate Serverless Mini Agent
  packages/dd-trace/src/proxy.js
  packages/dd-trace/src/serverless.js
  packages/dd-trace/test/serverless.spec.js
Labels: semver-minor, serverless

#5761 remove duplicate line in config.spec.js
  packages/dd-trace/test/config.spec.js
Labels: semver-patch

#5732 chore: fix confluentinc flaky tests
  packages/datadog-plugin-confluentinc-kafka-javascript/test/index.spec.js
Labels: semver-patch

#5397 [test-optimization] Increase minimum supported version of cypress (breaking change)
  .github/workflows/project.yml
  integration-tests/cypress/cypress.spec.js
  packages/datadog-instrumentations/src/cypress.js
  packages/datadog-plugin-cypress/src/plugin.js
  packages/dd-trace/test/plugins/externals.json
Labels: breaking-change, ci-app, semver-patch

#5596 [test-optimization] [SDTEST-1884] Increase minimum supported version of playwright (breaking change)
  integration-tests/playwright/playwright.spec.js
  packages/datadog-instrumentations/src/playwright.js
Labels: breaking-change, ci-app, semver-patch

#5409 [test-optimization] New default value for test session name (breaking change)
  packages/datadog-plugin-cypress/src/cypress-plugin.js
  packages/datadog-plugin-vitest/src/index.js
  packages/dd-trace/src/plugins/ci_plugin.js
  packages/dd-trace/src/plugins/util/test.js
Labels: breaking-change, ci-app, semver-patch

#5728 [DI] Refactor mutex code guarding race condition
  packages/dd-trace/src/debugger/devtools_client/breakpoints.js
  packages/dd-trace/src/debugger/devtools_client/remote_config.js
  packages/dd-trace/test/debugger/devtools_client/breakpoints.spec.js
Labels: semver-patch, dynamic-instrumentation

#5672 Remove code targeting unsupported Node.js versions
  .github/workflows/plugins.yml
  benchmark/sirun/plugin-graphql/index.js
  docs/API.md
  docs/add-redirects.sh
  docs/test.ts
  index.d.ts
  integration-tests/init.spec.js
  integration-tests/opentelemetry.spec.js
  packages/datadog-instrumentations/src/grpc/client.js
  packages/datadog-instrumentations/src/grpc/server.js
  packages/datadog-instrumentations/src/helpers/hooks.js
  packages/datadog-instrumentations/src/helpers/instrument.js
  packages/datadog-instrumentations/src/paperplane.js
  packages/datadog-instrumentations/test/child_process.spec.js
  packages/datadog-instrumentations/test/fs.spec.js
  packages/datadog-instrumentations/test/mongoose.spec.js
  packages/datadog-plugin-child_process/test/index.spec.js
  packages/datadog-plugin-couchbase/test/integration-test/client.spec.js
  packages/datadog-plugin-fastify/test/code_origin.spec.js
  packages/datadog-plugin-fastify/test/integration-test/client.spec.js
  packages/datadog-plugin-fastify/test/tracing.spec.js
  packages/datadog-plugin-fetch/test/index.spec.js
  packages/datadog-plugin-fs/test/index.spec.js
  packages/datadog-plugin-grpc/test/client.spec.js
  packages/datadog-plugin-grpc/test/naming.js
  packages/datadog-plugin-grpc/test/server.spec.js
  packages/datadog-plugin-http/test/client.spec.js
  packages/datadog-plugin-http2/test/client.spec.js
  packages/datadog-plugin-microgateway-core/test/integration-test/client.spec.js
  packages/datadog-plugin-moleculer/test/integration-test/client.spec.js
  packages/datadog-plugin-mongodb-core/test/integration-test/client.spec.js
  packages/datadog-plugin-mongodb-core/test/mongodb.spec.js
  packages/datadog-plugin-mongoose/test/index.spec.js
  packages/datadog-plugin-mongoose/test/integration-test/client.spec.js
  packages/datadog-plugin-mysql/test/integration-test/client.spec.js
  packages/datadog-plugin-mysql2/test/integration-test/client.spec.js
  packages/datadog-plugin-net/test/integration-test/client.spec.js
  packages/datadog-plugin-paperplane/src/index.js
  packages/datadog-plugin-paperplane/src/logger.js
  packages/datadog-plugin-paperplane/src/server.js
  packages/datadog-plugin-paperplane/test/index.spec.js
  packages/datadog-plugin-redis/test/client.spec.js
  packages/datadog-plugin-undici/test/index.spec.js
  packages/dd-trace/src/debugger/devtools_client/source-maps.js
  packages/dd-trace/src/iitm.js
  packages/dd-trace/src/opentracing/span.js
  packages/dd-trace/src/plugins/index.js
  packages/dd-trace/src/service-naming/schemas/v0/web.js
  packages/dd-trace/test/appsec/iast/analyzers/ldap-injection-analyzer.ldapjs.plugin.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/nosql-injection-mongodb-analyzer.express-mongo-sanitize.plugin.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/nosql-injection-mongodb-analyzer.mongoose.plugin.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/nosql-injection-mongodb-analyzer.mquery.plugin.spec.js
  packages/dd-trace/test/appsec/iast/analyzers/sql-injection-analyzer.pg.plugin.spec.js
  packages/dd-trace/test/debugger/devtools_client/source-maps.spec.js
  packages/dd-trace/test/iitm.spec.js
Labels: semver-patch

#5765 Add support for profiler upload compression methods and levels
  packages/dd-trace/src/profiling/config.js
  packages/dd-trace/src/profiling/profiler.js
  packages/dd-trace/src/profiling/profilers/events.js
  packages/dd-trace/src/profiling/profilers/shared.js
  packages/dd-trace/src/profiling/profilers/space.js
  packages/dd-trace/src/profiling/profilers/wall.js
  packages/dd-trace/test/profiling/config.spec.js
  packages/dd-trace/test/profiling/exporters/agent.spec.js
  packages/dd-trace/test/profiling/profiler.spec.js
  packages/dd-trace/test/profiling/profilers/space.spec.js
  packages/dd-trace/test/profiling/profilers/wall.spec.js
Labels: profiling, semver-minor

#5769 [DI] Fix race condition if breakpoint is hit while being removed
  packages/dd-trace/src/debugger/devtools_client/breakpoints.js
  packages/dd-trace/src/debugger/devtools_client/index.js
  packages/dd-trace/test/debugger/devtools_client/index.spec.js
Labels: semver-patch, dynamic-instrumentation

#5770 [test-optimization] [SDTEST-2034] Send tag when there is no branch
  packages/datadog-plugin-cypress/src/cypress-plugin.js
  packages/dd-trace/src/ci-visibility/requests/get-library-configuration.js
  packages/dd-trace/src/plugins/ci_plugin.js
  packages/dd-trace/test/ci-visibility/exporters/ci-visibility-exporter.spec.js
Labels: ci-app, semver-patch

#5766 Configurable NativeSpaceProfiler samplingInterval
  packages/dd-trace/src/profiling/config.js
  packages/dd-trace/src/profiling/profilers/space.js
  packages/dd-trace/test/profiling/profilers/space.spec.js
Labels: profiling, semver-minor

#5776 Bump ESLint dependencies
  LICENSE-3rdparty.csv
  eslint.config.mjs
  integration-tests/debugger/snapshot.spec.js
  integration-tests/debugger/target-app/snapshot.js
  package.json
  packages/datadog-plugin-aws-sdk/test/eventbridge.spec.js
  packages/datadog-plugin-aws-sdk/test/kinesis.spec.js
  packages/datadog-plugin-aws-sdk/test/sns.spec.js
  packages/datadog-plugin-child_process/src/scrub-cmd-params.js
  packages/dd-trace/src/appsec/blocked_templates.js
  packages/dd-trace/src/appsec/iast/analyzers/hardcoded-password-rules.js
  packages/dd-trace/src/appsec/iast/analyzers/hardcoded-secret-rules.js
  packages/dd-trace/src/appsec/iast/analyzers/hardcoded-secrets-rules.js
  packages/dd-trace/src/appsec/iast/vulnerabilities-formatter/evidence-redaction/sensitive-regex.js
  packages/dd-trace/src/appsec/iast/vulnerabilities-formatter/utils.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/debugger/devtools_client/remote_config.js
  packages/dd-trace/test/appsec/iast/analyzers/hardcoded-password-analyzer.spec.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/exporters/common/docker.spec.js
  packages/dd-trace/test/opentracing/propagation/text_map.spec.js
  packages/dd-trace/test/telemetry/index.spec.js
  yarn.lock
Labels: semver-patch

#5775 Make the ddBasePath variable a static string
  packages/dd-trace/src/appsec/iast/path-line.js
  packages/dd-trace/src/appsec/stack_trace.js
  packages/dd-trace/src/telemetry/logs/log-collector.js
  packages/dd-trace/src/util.js
  packages/dd-trace/test/appsec/iast/path-line.spec.js
  packages/dd-trace/test/telemetry/logs/log-collector.spec.js
Labels: semver-patch

#5759 test: remove manual promise handling from test
  packages/datadog-plugin-ioredis/test/index.spec.js
  packages/dd-trace/test/plugins/agent.js
Labels: semver-patch

#5712 feat: add deterministic sampling with knuth based on TraceId
  benchmark/core.js
  packages/datadog-plugin-google-cloud-vertexai/src/tracing.js
  packages/datadog-plugin-langchain/src/handlers/chain.js
  packages/datadog-plugin-langchain/src/handlers/embedding.js
  packages/datadog-plugin-langchain/src/handlers/language_models/chat_model.js
  packages/datadog-plugin-langchain/src/handlers/language_models/llm.js
  packages/datadog-plugin-langchain/src/tracing.js
  packages/datadog-plugin-openai/src/tracing.js
  packages/dd-trace/src/id.js
  packages/dd-trace/src/opentracing/tracer.js
  packages/dd-trace/src/plugins/util/llm.js
  packages/dd-trace/src/priority_sampler.js
  packages/dd-trace/src/random_sampler.js
  packages/dd-trace/src/sampler.js
  packages/dd-trace/src/sampling_rule.js
  packages/dd-trace/src/span_sampler.js
  packages/dd-trace/test/id.spec.js
  packages/dd-trace/test/plugins/util/llm.spec.js
  packages/dd-trace/test/ramdom_sampler.spec.js
  packages/dd-trace/test/sampler.spec.js
  packages/dd-trace/test/sampling_rule.spec.js
Labels: core, semver-minor

#5767 add baggage to span tags
  packages/dd-trace/src/config.js
  packages/dd-trace/src/opentracing/propagation/text_map.js
  packages/dd-trace/test/opentracing/propagation/text_map.spec.js
Labels: semver-minor

#5783 [test optimization] Update automatic log submission tests to include playwright
  integration-tests/automatic-log-submission.spec.js
  integration-tests/ci-visibility/automatic-log-submission-playwright/automatic-log-submission-test.js
  integration-tests/ci-visibility/automatic-log-submission-playwright/logger.js
  integration-tests/ci-visibility/automatic-log-submission-playwright/sum.js
Labels: ci-app, semver-patch

#5786 Activate multiple eslint rules
  eslint.config.mjs
  packages/datadog-instrumentations/src/cassandra-driver.js
  packages/datadog-instrumentations/src/confluentinc-kafka-javascript.js
  packages/datadog-instrumentations/src/couchbase.js
  packages/datadog-instrumentations/src/graphql.js
  packages/datadog-instrumentations/src/helpers/register.js
  packages/datadog-instrumentations/src/jest.js
  packages/datadog-instrumentations/src/kafkajs.js
  packages/datadog-instrumentations/src/mocha/utils.js
  packages/datadog-instrumentations/src/mysql.js
  packages/datadog-instrumentations/src/mysql2.js
  packages/datadog-instrumentations/src/oracledb.js
  packages/datadog-instrumentations/src/playwright.js
  packages/datadog-instrumentations/src/rhea.js
  packages/datadog-instrumentations/src/tedious.js
  packages/datadog-instrumentations/src/vitest.js
  packages/datadog-plugin-aws-sdk/src/services/dynamodb.js
  packages/datadog-plugin-aws-sdk/src/services/eventbridge.js
  packages/datadog-plugin-aws-sdk/src/services/kinesis.js
  packages/datadog-plugin-cypress/src/cypress-plugin.js
  packages/datadog-plugin-jest/src/index.js
  packages/dd-trace/src/appsec/api_security_sampler.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/lambda/handler.js
  packages/dd-trace/src/llmobs/plugins/openai.js
  packages/dd-trace/src/llmobs/sdk.js
  packages/dd-trace/src/llmobs/writers/util.js
  packages/dd-trace/src/opentracing/span.js
  packages/dd-trace/src/plugins/util/test.js
  packages/dd-trace/src/profiling/config.js
  packages/dd-trace/src/startup-log.js
  packages/dd-trace/src/telemetry/send-data.js
Labels: semver-patch

#5793 Pin openai to below v5 in plugin test
  packages/datadog-plugin-openai/test/index.spec.js
  packages/dd-trace/test/llmobs/plugins/openai/openaiv4.spec.js
Labels: semver-patch

#5795 ci(aws-sdk): fix bedrock runtime tests failing
  packages/datadog-plugin-aws-sdk/test/bedrockruntime.spec.js
  packages/dd-trace/test/llmobs/plugins/aws-sdk/bedrockruntime.spec.js
  packages/dd-trace/test/plugins/externals.json
Labels: semver-patch, integration-aws-sdk

#5791 Update dependencies
  package.json
  yarn.lock
Labels: semver-patch

#5799 Fix missing returns
  packages/datadog-instrumentations/src/router.js
Labels: semver-patch
