Repository DataDog/dd-trace-js, pull requests merged in 2025-03, with the labels that each got.

#5351 Bump import-in-the-middle to v1.13.1 (recreates #5350)
  package.json
  yarn.lock
Labels: semver-patch

#5213 Update DD_TAGS Parsing to Meet Spec
  packages/datadog-plugin-express/test/index.spec.js
  packages/datadog-plugin-graphql/src/parse.js
  packages/dd-trace/src/config.js
  packages/dd-trace/src/format.js
  packages/dd-trace/src/plugins/util/git.js
  packages/dd-trace/src/plugins/util/web.js
  packages/dd-trace/src/tagger.js
  packages/dd-trace/test/appsec/iast/code_injection.integration.spec.js
  packages/dd-trace/test/config.spec.js
  packages/dd-trace/test/format.spec.js
  packages/dd-trace/test/plugins/util/git.spec.js
  packages/dd-trace/test/tagger.spec.js
Labels: semver-minor

#5353 Fix bug where MongoDB comment is improperly set to null when dbmPropagationMode is disabled
  packages/datadog-plugin-mongodb-core/src/index.js
  packages/datadog-plugin-mongodb-core/test/core.spec.js
Labels: semver-patch

#5338 Improve release proposal script
  LICENSE-3rdparty.csv
  package.json
  scripts/release/helpers/requirements.js
  scripts/release/helpers/terminal.js
  scripts/release/proposal.js
  yarn.lock
Labels: semver-patch

#5359 [MLOB-2333] chore(llmobs): add telemetry for LLMObs span start
  packages/dd-trace/src/llmobs/plugins/base.js
  packages/dd-trace/src/llmobs/plugins/bedrockruntime.js
  packages/dd-trace/src/llmobs/plugins/langchain/index.js
  packages/dd-trace/src/llmobs/plugins/openai.js
  packages/dd-trace/src/llmobs/sdk.js
  packages/dd-trace/src/llmobs/telemetry.js
Labels: semver-patch

#5347 Custom metrics aggregation
  packages/dd-trace/src/dogstatsd.js
  packages/dd-trace/src/runtime_metrics/runtime_metrics.js
  packages/dd-trace/test/custom-metrics.spec.js
  packages/dd-trace/test/dogstatsd.spec.js
Labels: semver-patch

#5363 reset histogram when a value was never recorded
  packages/dd-trace/src/dogstatsd.js
Labels: semver-patch

#5366 fix fetch not working in serverless environments
  packages/datadog-instrumentations/src/fetch.js
  packages/datadog-plugin-fetch/test/index.spec.js
  packages/dd-trace/src/plugin_manager.js
  packages/dd-trace/src/plugins/index.js
Labels: semver-patch

#5379 [test optimization] Add `auto_injected` telemetry tag
  packages/datadog-plugin-cucumber/src/index.js
  packages/datadog-plugin-cypress/src/cypress-plugin.js
  packages/datadog-plugin-jest/src/index.js
  packages/datadog-plugin-mocha/src/index.js
  packages/datadog-plugin-playwright/src/index.js
  packages/datadog-plugin-vitest/src/index.js
  packages/dd-trace/src/ci-visibility/telemetry.js
Labels: ci-app, semver-patch

#5335 Report general tags and metrics
  package.json
  packages/dd-trace/src/appsec/blocking.js
  packages/dd-trace/src/appsec/graphql.js
  packages/dd-trace/src/appsec/rasp/utils.js
  packages/dd-trace/src/appsec/reporter.js
  packages/dd-trace/src/appsec/sdk/user_blocking.js
  packages/dd-trace/src/appsec/telemetry/index.js
  packages/dd-trace/src/appsec/telemetry/rasp.js
  packages/dd-trace/src/appsec/telemetry/waf.js
  packages/dd-trace/src/appsec/waf/waf_context_wrapper.js
  packages/dd-trace/test/appsec/blocking.spec.js
  packages/dd-trace/test/appsec/graphql.spec.js
  packages/dd-trace/test/appsec/index.body-parser.plugin.spec.js
  packages/dd-trace/test/appsec/index.spec.js
  packages/dd-trace/test/appsec/reporter.spec.js
  packages/dd-trace/test/appsec/sdk/user_blocking.spec.js
  packages/dd-trace/test/appsec/telemetry/rasp.spec.js
  packages/dd-trace/test/appsec/telemetry/waf.spec.js
  packages/dd-trace/test/appsec/waf/waf_context_wrapper.spec.js
  yarn.lock
Labels: semver-minor

#5373 Skip tests on release
  .gitlab-ci.yml
Labels: semver-patch

#5381 feat(llmobs): add support for Azure OpenAI and Deepseek calls made through the OpenAI SDK
  packages/dd-trace/src/llmobs/plugins/openai.js
  packages/dd-trace/test/llmobs/plugins/openai/openaiv3.spec.js
  packages/dd-trace/test/llmobs/plugins/openai/openaiv4.spec.js
Labels: semver-minor

#5355 [test optimization] [SDTEST-1623] Disabled flaky tests implementation
  integration-tests/ci-visibility-intake.js
  integration-tests/ci-visibility/features-quarantine/support/steps.js
  integration-tests/ci-visibility/features-test-management/disabled.feature
  integration-tests/ci-visibility/features-test-management/quarantine.feature
  integration-tests/ci-visibility/features-test-management/support/steps.js
  integration-tests/ci-visibility/playwright-tests-test-management/disabled-test.js
  integration-tests/ci-visibility/playwright-tests-test-management/quarantine-test.js
  integration-tests/ci-visibility/test-management/test-disabled-1.js
  integration-tests/ci-visibility/test-management/test-disabled-2.js
  integration-tests/ci-visibility/test-management/test-quarantine-1.js
  integration-tests/ci-visibility/test-management/test-quarantine-2.js
  integration-tests/ci-visibility/vitest-tests/test-disabled.mjs
  integration-tests/ci-visibility/vitest-tests/test-quarantine.mjs
  integration-tests/cucumber/cucumber.spec.js
  integration-tests/cypress/cypress.spec.js
  integration-tests/cypress/e2e/disable.js
  integration-tests/jest/jest.spec.js
  integration-tests/mocha/mocha.spec.js
  integration-tests/playwright/playwright.spec.js
  integration-tests/vitest/vitest.spec.js
  packages/datadog-instrumentations/src/cucumber.js
  packages/datadog-instrumentations/src/jest.js
  packages/datadog-instrumentations/src/mocha/main.js
  packages/datadog-instrumentations/src/mocha/utils.js
  packages/datadog-instrumentations/src/mocha/worker.js
  packages/datadog-instrumentations/src/playwright.js
  packages/datadog-instrumentations/src/vitest.js
  packages/datadog-plugin-cucumber/src/index.js
  packages/datadog-plugin-cypress/src/cypress-plugin.js
  packages/datadog-plugin-jest/src/index.js
  packages/datadog-plugin-mocha/src/index.js
  packages/datadog-plugin-playwright/src/index.js
  packages/datadog-plugin-vitest/src/index.js
  packages/dd-trace/src/ci-visibility/exporters/ci-visibility-exporter.js
  packages/dd-trace/src/ci-visibility/requests/get-library-configuration.js
  packages/dd-trace/src/ci-visibility/test-management/get-test-management-tests.js
  packages/dd-trace/src/plugins/ci_plugin.js
  packages/dd-trace/src/plugins/util/test.js
Labels: ci-app, semver-minor

#5387 bump axios
  package.json
  packages/dd-trace/test/appsec/attacker-fingerprinting.express.plugin.spec.js
  packages/dd-trace/test/appsec/attacker-fingerprinting.passport-http.plugin.spec.js
  packages/dd-trace/test/appsec/attacker-fingerprinting.passport-local.plugin.spec.js
  packages/dd-trace/test/appsec/attacker-fingerprinting.spec.js
  yarn.lock
Labels: semver-patch

#4970 [MLOB-1954] feat(langchain): generically patch embeddings to enable tracing all embeddings calls
  packages/datadog-instrumentations/src/helpers/hooks.js
  packages/datadog-instrumentations/src/langchain.js
  packages/datadog-plugin-langchain/src/handlers/embedding.js
  packages/datadog-plugin-langchain/test/index.spec.js
  packages/dd-trace/test/plugins/externals.json
Labels: semver-minor

#5383 Fix reporting of profiling_enabled in startup log
  packages/dd-trace/src/startup-log.js
  packages/dd-trace/test/startup-log.spec.js
Labels: semver-patch

#5382 Remove version tag in telemetry metrics
  integration-tests/opentelemetry.spec.js
  packages/dd-trace/src/telemetry/metrics.js
  packages/dd-trace/test/appsec/iast/telemetry/namespaces.spec.js
  packages/dd-trace/test/telemetry/metrics.spec.js
Labels: semver-patch

#5390 [test optimization] Fix git commit message extraction
  packages/dd-trace/src/plugins/util/git.js
  packages/dd-trace/test/plugins/util/git.spec.js
Labels: ci-app, semver-patch

#5400 fix babel helpers regex vulnerability error
  .github/workflows/project.yml
  LICENSE-3rdparty.csv
  package.json
  packages/dd-trace/test/appsec/attacker-fingerprinting.express.plugin.spec.js
  packages/dd-trace/test/appsec/attacker-fingerprinting.passport-http.plugin.spec.js
  packages/dd-trace/test/appsec/attacker-fingerprinting.passport-local.plugin.spec.js
  packages/dd-trace/test/appsec/attacker-fingerprinting.spec.js
  yarn.lock
Labels: semver-patch

#5369 [MLOB-2340] feat(vertexai): add `@google-cloud/vertexai` instrumentation
  .github/workflows/plugins.yml
  CODEOWNERS
  docs/test.ts
  index.d.ts
  packages/datadog-instrumentations/src/google-cloud-vertexai.js
  packages/datadog-instrumentations/src/helpers/hooks.js
  packages/datadog-plugin-google-cloud-vertexai/src/index.js
  packages/datadog-plugin-google-cloud-vertexai/test/index.spec.js
  packages/datadog-plugin-google-cloud-vertexai/test/integration-test/client.spec.js
  packages/datadog-plugin-google-cloud-vertexai/test/integration-test/server.mjs
  packages/datadog-plugin-google-cloud-vertexai/test/resources/generate-content-single-response-with-tools.json
  packages/datadog-plugin-google-cloud-vertexai/test/resources/generate-content-single-response.json
  packages/datadog-plugin-google-cloud-vertexai/test/resources/generate-content-stream-single-response.txt
  packages/datadog-plugin-google-cloud-vertexai/test/resources/malformed-stream.txt
  packages/dd-trace/src/config.js
  packages/dd-trace/src/plugins/index.js
  packages/dd-trace/test/config.spec.js
Labels: semver-minor

#5398 [test optimization] Fix hooks and retries logic in mocha
  integration-tests/ci-visibility/test-nested-hooks/test-nested-hooks.js
  integration-tests/mocha/mocha.spec.js
  packages/datadog-instrumentations/src/mocha/utils.js
Labels: ci-app, semver-patch

#5392 Adds JSDoc types to much of the sampling code
  packages/dd-trace/src/appsec/api_security_sampler.js
  packages/dd-trace/src/opentracing/span.js
  packages/dd-trace/src/priority_sampler.js
  packages/dd-trace/src/sampler.js
  packages/dd-trace/src/standalone/product.js
Labels: semver-patch

#5404 remove fs dependency from lambda hook
  packages/dd-trace/src/lambda/runtime/patch.js
  packages/dd-trace/src/lambda/runtime/ritm.js
Labels: semver-patch

#5412 always disable fs integration in serverless
  packages/datadog-instrumentations/src/helpers/hooks.js
  packages/datadog-instrumentations/src/helpers/register.js
Labels: semver-patch

#5411 [test optimization] Deprecate dd-trace support for cypress <10.2.0
  integration-tests/cypress/cypress.spec.js
  packages/datadog-plugin-cypress/src/plugin.js
Labels: ci-app, semver-patch

#5349 SSI tests gitlab ci
  .gitlab-ci.yml
Labels: semver-patch

#5418 docs(llmobs): fix correct typo in llmobs.AnnotationOptions TypeScript definition comment
  index.d.ts
Labels: semver-patch

#5399 lazy load ip extraction
  packages/dd-trace/src/plugins/util/web.js
  packages/dd-trace/test/plugins/util/web.spec.js
Labels: semver-patch

#5417 CI: Run spec files in datadog-instrumentations sub-dirs
  .github/workflows/instrumentations.yml
  package.json
  packages/datadog-instrumentations/test/helpers/instrument.spec.js
Labels: semver-patch

#5416 Refactor: Move check_require_cache code to helpers folder
  .github/workflows/instrumentations.yml
  packages/datadog-esbuild/index.js
  packages/datadog-instrumentations/src/helpers/check-require-cache.js
  packages/datadog-instrumentations/src/helpers/extract-package-and-module-path.js
  packages/datadog-instrumentations/src/helpers/register.js
  packages/datadog-instrumentations/test/helpers/check-require-cache.spec.js
  packages/datadog-instrumentations/test/helpers/check-require-cache/bad-order.js
  packages/datadog-instrumentations/test/helpers/check-require-cache/good-order.js
  packages/dd-trace/src/tracer.js
Labels: semver-patch

#5427 [test optimization] Fix latest vitest release
  packages/datadog-instrumentations/src/vitest.js
Labels: ci-app, semver-patch

#5424 fix(llmobs): additional options like for manual span instrumentation are properly recognized
  packages/dd-trace/src/llmobs/sdk.js
  packages/dd-trace/test/llmobs/sdk/index.spec.js
Labels: semver-patch

#5414 fix runtime metrics histogram sending invalid data
  packages/dd-trace/src/dogstatsd.js
  packages/dd-trace/src/runtime_metrics/runtime_metrics.js
  packages/dd-trace/test/custom-metrics.spec.js
  packages/dd-trace/test/dogstatsd.spec.js
  packages/dd-trace/test/runtime_metrics.spec.js
Labels: semver-patch

#5229 add span events as a top level field for v0.4 encoding
  packages/dd-trace/src/config.js
  packages/dd-trace/src/encode/0.4.js
  packages/dd-trace/src/encode/0.5.js
  packages/dd-trace/src/exporters/agent/index.js
  packages/dd-trace/src/exporters/agent/writer.js
  packages/dd-trace/src/format.js
  packages/dd-trace/src/log/index.js
  packages/dd-trace/src/log/utils.js
  packages/dd-trace/test/encode/0.4.spec.js
  packages/dd-trace/test/encode/0.5.spec.js
  packages/dd-trace/test/format.spec.js
Labels: semver-minor

#5433 Pin `@opentelemetry/instrumentation-express` testing to `0.47.1`
  integration-tests/opentelemetry.spec.js
Labels: semver-patch

#5380 report truncation metrics
  packages/dd-trace/src/appsec/telemetry/common.js
  packages/dd-trace/src/appsec/telemetry/waf.js
  packages/dd-trace/test/appsec/resources/index.js
  packages/dd-trace/test/appsec/telemetry/rasp.spec.js
  packages/dd-trace/test/appsec/telemetry/waf.spec.js
  packages/dd-trace/test/appsec/waf-metrics.integration.spec.js
Labels: semver-minor, appsec

#5438 [test optimization] Fix playwright e2e tests flakiness
  integration-tests/playwright/playwright.spec.js
Labels: ci-app, semver-patch

#5440 [test optimization] Improve playwright flakiness (this time for real?)
  .github/workflows/project.yml
  integration-tests/ci-visibility/playwright-tests-test-capabilities/passing-test.js
  integration-tests/playwright/playwright.spec.js
Labels: ci-app, semver-patch

#5375 dbm: tedious (sql server) service mode
  packages/datadog-instrumentations/src/tedious.js
  packages/datadog-plugin-tedious/src/index.js
  packages/datadog-plugin-tedious/test/index.spec.js
  packages/dd-trace/src/plugins/database.js
Labels: semver-minor

#5442 increase next.js test timeout to 5 minutes
  packages/datadog-plugin-next/test/index.spec.js
  packages/datadog-plugin-next/test/integration-test/client.spec.js
  packages/dd-trace/test/appsec/index.next.plugin.spec.js
Labels: semver-patch

#5406 lazy load dd-trace-api integration
  packages/datadog-instrumentations/src/dd-trace-api.js
  packages/datadog-instrumentations/src/helpers/hooks.js
  packages/datadog-instrumentations/src/helpers/register.js
  packages/datadog-plugin-dd-trace-api/test/index.spec.js
  packages/dd-trace/src/plugin_manager.js
Labels: semver-patch

#5443 retry test agent start when it fails
  .github/actions/testagent/start/action.yml
Labels: semver-patch

#5436 fix mysql/mysql2/pg dbm trace id tests
  packages/datadog-plugin-mysql/test/index.spec.js
  packages/datadog-plugin-mysql2/test/index.spec.js
  packages/datadog-plugin-pg/test/index.spec.js
Labels: semver-patch

#5445 fix amqplib flaky dsm tests
  packages/datadog-plugin-amqplib/test/index.spec.js
Labels: semver-patch

#5446 fix aws-sdk kinesis flaky dsm test
  packages/datadog-plugin-aws-sdk/test/kinesis.spec.js
Labels: semver-patch

#5449 fix profiling test expecting minimum 2 requests instead of 1
  integration-tests/profiler/profiler.spec.js
Labels: semver-patch

#5451 add matrix strategy to llmobs sdk ci job
  .github/workflows/llmobs.yml
Labels: semver-patch

#5434 retry npm install/view for appsec and plugins tests
  .github/workflows/appsec.yml
  scripts/install_plugin_modules.js
Labels: semver-patch

#5457 set dc-polyfill version to 0.1.6
  package.json
  yarn.lock
Labels: semver-patch

#5465 feat(llmobs): add integration tag to llmobs spans
  packages/dd-trace/src/llmobs/plugins/base.js
  packages/dd-trace/src/llmobs/plugins/bedrockruntime.js
  packages/dd-trace/src/llmobs/span_processor.js
  packages/dd-trace/src/llmobs/tagger.js
  packages/dd-trace/test/llmobs/plugins/aws-sdk/bedrockruntime.spec.js
  packages/dd-trace/test/llmobs/plugins/langchain/index.spec.js
  packages/dd-trace/test/llmobs/plugins/openai/openaiv3.spec.js
  packages/dd-trace/test/llmobs/plugins/openai/openaiv4.spec.js
Labels: semver-minor

#5444 chore(llmobs): add span.finished telemetry metric
  packages/dd-trace/src/llmobs/constants/tags.js
  packages/dd-trace/src/llmobs/noop.js
  packages/dd-trace/src/llmobs/sdk.js
  packages/dd-trace/src/llmobs/span_processor.js
  packages/dd-trace/src/llmobs/tagger.js
  packages/dd-trace/src/llmobs/telemetry.js
Labels: semver-patch

#5368 fix release script esm error on node 20
  package.json
  scripts/release/helpers/requirements.js
  yarn.lock
Labels: semver-patch

#5435 fix connection pool error in mongoose tests
  packages/datadog-plugin-mongoose/test/index.spec.js
Labels: semver-patch

#5464 make cache action unix compatible and update test agent
  .github/actions/install/action.yml
  .github/workflows/plugins.yml
  docker-compose.yml
Labels: semver-patch

#5447 fix wrong test error message when expected span was not received
  packages/dd-trace/test/plugins/helpers.js
Labels: semver-patch

#5463 [test optimization] [SDTEST-1720] Change capabilities tagging to send version number
  integration-tests/cucumber/cucumber.spec.js
  integration-tests/cypress/cypress.spec.js
  integration-tests/jest/jest.spec.js
  integration-tests/mocha/mocha.spec.js
  integration-tests/playwright/playwright.spec.js
  integration-tests/vitest/vitest.spec.js
  packages/datadog-instrumentations/src/vitest.js
  packages/datadog-plugin-cypress/src/cypress-plugin.js
  packages/datadog-plugin-vitest/src/index.js
  packages/dd-trace/src/plugins/ci_plugin.js
  packages/dd-trace/src/plugins/util/test.js
Labels: ci-app, semver-patch

#5480 Fix logging null when debugging and sending data without any error (recreates #5396)
  packages/dd-trace/src/telemetry/send-data.js
Labels: semver-patch

#5413 feat(llmobs): add vertexai plugin
  .github/workflows/llmobs.yml
  packages/datadog-plugin-google-cloud-vertexai/src/index.js
  packages/datadog-plugin-google-cloud-vertexai/src/tracing.js
  packages/datadog-plugin-google-cloud-vertexai/src/utils.js
  packages/dd-trace/src/llmobs/plugins/vertexai.js
  packages/dd-trace/test/llmobs/plugins/google-cloud-vertexai/index.spec.js
Labels: semver-minor

#5384 waf requests telemetry metrics
  packages/dd-trace/src/appsec/blocking.js
  packages/dd-trace/src/appsec/graphql.js
  packages/dd-trace/src/appsec/reporter.js
  packages/dd-trace/src/appsec/telemetry/common.js
  packages/dd-trace/src/appsec/telemetry/index.js
  packages/dd-trace/src/appsec/telemetry/waf.js
  packages/dd-trace/test/appsec/blocking.spec.js
  packages/dd-trace/test/appsec/graphql.spec.js
  packages/dd-trace/test/appsec/reporter.spec.js
  packages/dd-trace/test/appsec/telemetry/rasp.spec.js
  packages/dd-trace/test/appsec/telemetry/waf.spec.js
  packages/dd-trace/test/appsec/waf-metrics.integration.spec.js
Labels: semver-minor, appsec

#5476 fix memory leak in runtime.node.heap.* metrics
  benchmark/sirun/runtime-metrics/README.md
  benchmark/sirun/runtime-metrics/index.js
  benchmark/sirun/runtime-metrics/meta.json
  packages/dd-trace/src/runtime_metrics/runtime_metrics.js
  packages/dd-trace/test/runtime_metrics.spec.js
Labels: semver-patch

#5468 chore(llmobs): add span size telemetry metrics
  packages/dd-trace/src/llmobs/telemetry.js
  packages/dd-trace/src/llmobs/writers/spans/base.js
Labels: semver-minor

#5477 Add a few TODO's
  packages/datadog-instrumentations/src/router.js
  packages/dd-trace/src/plugins/plugin.js
Labels: semver-patch

#5461 chore(langchain): fix test flakiness
  packages/datadog-plugin-langchain/test/index.spec.js
Labels: do-not-merge/WIP, semver-patch

#5475 chore(llmobs): Add llmobs product enabled telemetry metrics
  packages/dd-trace/src/llmobs/index.js
  packages/dd-trace/src/llmobs/telemetry.js
Labels: semver-minor

#5469 chore(llmobs): add telemetry metrics for dropped span/eval payloads
  packages/dd-trace/src/llmobs/telemetry.js
  packages/dd-trace/src/llmobs/writers/base.js
Labels: semver-minor

#5450 add matrix strategy to debugger ci job
  .github/workflows/debugger.yml
Labels: semver-patch

#5462 add sdk.event to communicate a login or custom event
  packages/dd-trace/src/appsec/sdk/track_event.js
  packages/dd-trace/src/appsec/telemetry/index.js
  packages/dd-trace/src/appsec/telemetry/user.js
  packages/dd-trace/test/appsec/sdk/track_event.spec.js
  packages/dd-trace/test/appsec/telemetry/user.spec.js
Labels: semver-minor, appsec

#5467 report rc.client_id tag when rc is enabled
  packages/dd-trace/src/remote_config/manager.js
  packages/dd-trace/test/remote_config/manager.spec.js
  packages/dd-trace/test/remote_config/rc-client_id.spec.js
  packages/dd-trace/test/remote_config/resources/index.js
Labels: semver-minor

#5491 fix duplicate custom metrics when multiple tags are used
  packages/dd-trace/src/dogstatsd.js
  packages/dd-trace/src/histogram.js
  packages/dd-trace/test/dogstatsd.spec.js
  packages/dd-trace/test/runtime_metrics.spec.js
Labels: semver-patch

#5458 Add rasp telemetry metrics
  packages/dd-trace/src/appsec/rasp/command_injection.js
  packages/dd-trace/src/appsec/rasp/index.js
  packages/dd-trace/src/appsec/rasp/lfi.js
  packages/dd-trace/src/appsec/rasp/sql_injection.js
  packages/dd-trace/src/appsec/rasp/ssrf.js
  packages/dd-trace/src/appsec/rasp/utils.js
  packages/dd-trace/src/appsec/reporter.js
  packages/dd-trace/src/appsec/telemetry/index.js
  packages/dd-trace/src/appsec/telemetry/rasp.js
  packages/dd-trace/src/appsec/waf/waf_context_wrapper.js
  packages/dd-trace/test/appsec/rasp/command_injection.spec.js
  packages/dd-trace/test/appsec/rasp/index.spec.js
  packages/dd-trace/test/appsec/rasp/rasp-metrics.integration.spec.js
  packages/dd-trace/test/appsec/rasp/utils.spec.js
  packages/dd-trace/test/appsec/reporter.spec.js
  packages/dd-trace/test/appsec/telemetry/rasp.spec.js
  packages/dd-trace/test/appsec/waf/waf_context_wrapper.spec.js
Labels: semver-minor, appsec

#5497 fix user tracking tests
  packages/dd-trace/test/appsec/blocking.spec.js
  packages/dd-trace/test/appsec/sdk/track_event-integration.spec.js
  packages/dd-trace/test/appsec/sdk/track_event.spec.js
  packages/dd-trace/test/appsec/sdk/user_blocking-integration.spec.js
  packages/dd-trace/test/appsec/sdk/user_blocking.spec.js
  packages/dd-trace/test/appsec/user_tracking.spec.js
Labels: semver-patch, appsec

#5485 chore: add tracing macrobenchmark with runtime metrics enabled
  .gitlab/macrobenchmarks.yml
Labels: semver-patch

#5492 centralize node version numbers for ci workflows
  .github/actions/node/action.yml
  .github/actions/node/active-lts/action.yml
  .github/actions/node/latest/action.yml
  .github/actions/node/newest-maintenance-lts/action.yml
  .github/actions/node/oldest-maintenance-lts/action.yml
  .github/workflows/debugger.yml
  .github/workflows/llmobs.yml
  .github/workflows/project.yml
Labels: semver-patch

#5478 Remove unused code in router instrumentation code
  packages/datadog-instrumentations/src/router.js
Labels: semver-patch

#5500 [DI] Improve integration test error handling
  integration-tests/debugger/utils.js
Labels: semver-patch, dynamic-instrumentation

#5490 Fix span event serialization for array attributes
  packages/dd-trace/src/encode/0.4.js
  packages/dd-trace/test/encode/0.4.spec.js
Labels: semver-minor
